### ISSUE TITLE
Whenever i remove the group "Moderator" from time limits it comes back on restart.

### ISSUE THREAD

**Issue by Harry5573** [BanManagement/BanManager#122]
Whenever i remove the group "Moderator" from time limits it comes back on restart. Example: http://prntscr.com/58nvo4 . @confuser

**Comment by Kakifrucht** [comment]
Not really a big problem for me, but I also have a group "Moderator", so if you could just change the name in the config that would be well. How about ExampleGroup or something?

**Comment by Harry5573** [comment]
This is becoming more of an issue, @confuser could you take a look?
