### ISSUE TITLE
Banned players can connect under certain circumstances

### ISSUE THREAD

**Issue by Kakifrucht** [BanManagement/BanManager#136]
This Bug pretty much existed since always. I'm using a MySQL server hosted on the same machine as the Minecraft server (localhost). I'm on build 30.

When I ban a player via the Server, then unban him to change the ban reason and immediately reban him, the records will show up correctly on the MySQL server and Webinterface, however the player will still be able to connect. Using /bmreload does not help this. A fix is to delete the ban entries manually and then reban him.

**Comment by confuser** [comment]
How quick do you reban them? Do you see the notification message saying that they were unbanned before rebanning?

Most likely due to the fact BanManager uses Bukkit's worker threads for async, rather than a single threaded instance.

**Comment by Kakifrucht** [comment]
Not quickly, 5 seconds delay, no errors or messages. I am able to reproduce this.
Notifications show that everything worked without problems.

**Comment by FourDown** [comment]
I've experienced this issue too. 

We had to instruct our staff to leave a small delay between unbanning and rebanning.

**Comment by confuser** [comment]
I'm able to reproduce this
