### ISSUE TITLE
Bminfo permissions not working.

### ISSUE THREAD

**Issue by tr0nlegacy2012** [BanManagement/BanManager#146]
Hello,

I have Ban Management V5 Snapshot and cannot seem to get bminfo permissions. The command only works when player is opped.

http://prntscr.com/61plsa

**Comment by confuser** [comment]
Check the uuid update guide on bukkit Dev,  it lists the permission changes
to bminfo

**Comment by tr0nlegacy2012** [comment]
I know, those are the permissions I am using.

**Comment by tr0nlegacy2012** [comment]
@confuser 

Bukit says this: http://prntscr.com/61pns1
My permissions: http://prntscr.com/61po0v

**Comment by confuser** [comment]
I'm not familiar with SuperPerms from an owners perspective. I would recommend using a permission plugin like PermissionsEx or GroupManager instead.

However, that being said, can you try the next developer build (probably currently building) and let me know if it fixes your issue? I've explicitly stated the permissions in the plugin file which I believe SuperPerms requires.

**Comment by tr0nlegacy2012** [comment]
I use group Manager as a permissions plugin

**Comment by confuser** [comment]
Interesting, sorry it looked like SuperPerms.

Does the latest build solve your problem?

**Comment by tr0nlegacy2012** [comment]
I am trying the latest build now

**Comment by tr0nlegacy2012** [comment]
It is still not working: 
http://prntscr.com/61pv2k

**Comment by FourDown** [comment]
I seem to be having the same issue.

**Comment by tr0nlegacy2012** [comment]
@confuser Any news?

**Comment by confuser** [comment]
Afraid not, it may be an issue with the permission plugin that you both may be using. I'm not able to replicate it with PermissionsEx.

**Comment by tr0nlegacy2012** [comment]
There are a lot of people with GroupManager, so there's nothing those of us with GroupManager can do??

**Comment by frdmn** [comment]
@tr0nlegacy2012 @FourDown @confuser I just tried to reproduce the issue and _do not_ have any permission issues with the command, once i've given the appropriate permissions:

    [19:16:37 INFO]: The player 'frdmn' has following permissions: bm.command.bminfo.alts, bm.command.bminfo.connection, bm.command.bminfo.ipstats, bm.command.bminfo.playerstats

I'm using GroupManager v2.0 (Phoenix) and Spigot git-Spigot-1649 (pretty old, I know)

Are you guys on outdated versions?

**Comment by FourDown** [comment]
I'm using the latest version of PEX.

@confuser Please provide a copy of the relevant perms from your file?

**Comment by tr0nlegacy2012** [comment]
@confuser @frdmn  @FourDown 
[code] [11:42:54] [Server thread/INFO]: [GroupManager] Loading GroupManager v2.1.11 (Phoenix) [/code]

[code]
 g:util_banmanager_jrmod:

    permissions:
    - bm.command.unban.own

    - bm.command.bminfo.playerstats

    - bm.command.bminfo.ipstats

    - bm.command.bminfo.connection

    - bm.command.bminfo.alts
[/code]

**Comment by frdmn** [comment]
@tr0nlegacy2012 Use `/manucheckp` if the player really has those permissions.

**Comment by tr0nlegacy2012** [comment]
@frdmn http://prntscr.com/6295n5

**Comment by Theepwner** [comment]
@tr0nlegacy2012 the proper permission is bm.bminfo.playerstats

**Comment by FourDown** [comment]
My staff have the 'bm.command.info.playerstats' permission.

**Comment by confuser** [comment]
Ensure they have the bm.command.bminfo permission too

As BanManager doesn't do anything weird that a permissions plugin shouldn't be able to handle, this is therefore an issue with a permissions plugin. Ergo, closed.

**Comment by tr0nlegacy2012** [comment]
@FourDown  Make sure you have these permissions:

  g:util_banmanager_jrmod:
    permissions:
    - bm.command.unban.own
    - bm.command.bminfo
    - bm.command.bminfo.playerstats
    - bm.command.bminfo.ipstats
    - bm.command.bminfo.connection
    - bm.command.bminfo.alts

**Comment by FourDown** [comment]
I don't want them to see all of the modules, only a players current punishments and their history.

**Comment by tr0nlegacy2012** [comment]
They will need to bm.command.bminfo permission along with whichever part of bminfo you want them to see.
