### ISSUE TITLE
Ban Manger

### ISSUE THREAD

**Issue by wmillerruls** [BanManagement/BanManager#147]
Is there a way you can please make me one for me. I can't seem to get FTP clients to work. Please contact me if you can on my website plotnation.enjin.com
I don't care what link its on, and I can setup the admin part.

**Comment by frdmn** [comment]
@wmillerruls What do you mean with "make one for me"? All you need is a MySQL server to store your bans. Then set up the credentials in the `config.yml` and you are good to go.

**Comment by wmillerruls** [comment]
I cant get it to work.

**Comment by frdmn** [comment]
@wmillerruls What's your problem in specific?
