### ISSUE TITLE
Build #54 errors

### ISSUE THREAD

**Issue by prodkid** [BanManagement/BanManager#148]
10:55:58 PM CONSOLE: WARN]: at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
10:55:58 PM CONSOLE: WARN]: at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
10:55:58 PM CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3082)
10:55:58 PM CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2968)
10:55:58 PM CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3516)
10:55:58 PM CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
10:55:58 PM CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
10:55:58 PM CONSOLE: WARN]: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
10:55:58 PM CONSOLE: WARN]: at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
10:55:58 PM CONSOLE: WARN]: at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2273)
10:55:58 PM CONSOLE: WARN]: at me.confuser.banmanager.ormlite.jdbc.JdbcCompiledStatement.runQuery(JdbcCompiledStatement.java:55)
10:55:58 PM CONSOLE: WARN]: at me.confuser.banmanager.ormlite.stmt.SelectIterator.<init>(SelectIterator.java:55)
10:55:58 PM CONSOLE: WARN]: at me.confuser.banmanager.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:247)
10:55:59 PM CONSOLE: WARN]: at me.confuser.banmanager.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:964)
10:55:59 PM CONSOLE: WARN]: ... 11 more
10:55:59 PM CONSOLE: WARN]: Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
10:55:59 PM CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2529)
10:55:59 PM CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2979)
10:55:59 PM CONSOLE: WARN]: ... 22 more
10:55:59 PM CONSOLE: WARN]: java.sql.SQLException: Could not build prepared-query iterator for class me.confuser.banmanager.data.external.ExternalPlayerMuteData
10:55:59 PM CONSOLE: WARN]: at me.confuser.banmanager.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
10:55:59 PM CONSOLE: WARN]: at me.confuser.banmanager.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:968)
10:55:59 PM CONSOLE: WARN]: at me.confuser.banmanager.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:533)
10:55:59 PM CONSOLE: WARN]: at me.confuser.banmanager.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:528)
10:55:59 PM CONSOLE: WARN]: at me.confuser.banmanager.ormlite.stmt.QueryBuilder.iterator(QueryBuilder.java:389)
10:55:59 PM CONSOLE: WARN]: at me.confuser.banmanager.storage.external.ExternalPlayerMuteStorage.findMutes(ExternalPlayerMuteStorage.java:31)
10:55:59 PM CONSOLE: WARN]: at me.confuser.banmanager.runnables.ExternalMuteSync.newMutes(ExternalMuteSync.java:48)
10:55:59 PM CONSOLE: WARN]: at me.confuser.banmanager.runnables.ExternalMuteSync.run(ExternalMuteSync.java:30)
10:55:59 PM CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
10:55:59 PM CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
10:55:59 PM CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
10:55:59 PM CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
10:55:59 PM CONSOLE: WARN]: at java.lang.Thread.run(Unknown Source)
10:55:59 PM CONSOLE: WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
10:55:59 PM CONSOLE: packet successfully received from the server was 118,606 milliseconds ago. The last packet sent successfully to the server was 1 milliseconds ago.
10:55:59 PM CONSOLE: WARN]: at sun.reflect.GeneratedConstructorAccessor321.newInstance(Unknown Source)
10:55:59 PM CONSOLE: WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
10:55:59 PM CONSOLE: WARN]: at java.lang.reflect.Constructor.newInstance(Unknown Source)
10:55:59 PM CONSOLE: WARN]: at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
10:55:59 PM CONSOLE: WARN]: at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
10:55:59 PM CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3082)
10:55:59 PM CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2968)
10:55:59 PM CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3516)
10:55:59 PM CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
10:55:59 PM CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
10:55:59 PM CONSOLE: WARN]: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
10:55:59 PM CONSOLE: WARN]: at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
10:55:59 PM CONSOLE: WARN]: at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2273)
10:55:59 PM CONSOLE: WARN]: at me.confuser.banmanager.ormlite.jdbc.JdbcCompiledStatement.runQuery(JdbcCompiledStatement.java:55)
10:55:59 PM CONSOLE: WARN]: at me.confuser.banmanager.ormlite.stmt.SelectIterator.<init>(SelectIterator.java:55)
10:55:59 PM CONSOLE: WARN]: at me.confuser.banmanager.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:247)
10:55:59 PM CONSOLE: WARN]: at me.confuser.banmanager.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:964)

**Comment by confuser** [comment]
> Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.

Your connection to your database failed. Not much the plugin can do at that point but attempt to reconnect.
