### ISSUE TITLE
Unban/unmute does not transfer to other servers

### ISSUE THREAD

**Issue by Theepwner** [BanManagement/BanManager#149]
Unbanning/unmuting a player will only unban or unmute that player on the server you enter the command.  When the other servers restart, then they will be properly unbanned or unmuted.

In the latest v4 dev build, this issue existed for bans but not mutes.

**Comment by confuser** [comment]
This is occurring on v5 Dev builds? Are you using local or external bans?

**Comment by Theepwner** [comment]
Using version 56 at the moment.  I'm using both local and external bans if you know what I mean.  I have 2 different dedis and the database is on one of the dedis.

So there's more to the issue it seems.  Muting a player on one server on dedi 2, it will only transfer to the other servers that are on dedi 2, not any of the dedi 1 servers.  Unmuting the player will only unmute him on the server you just did it on, so it won't unmute him on the other dedi 2 server(s).  Bans will transfer to both dedi 1 and 2 perfectly, unbanning will only unban on the same dedi.

bmclear works seemlessly.  But here's my different configurations for each dedi, if this matters.
Dedi 1 with database: http://pastebin.com/dgUQixNF
Dedi 2: http://pastebin.com/dgUQixNF

I can look into this more if needed.  Sorry, kinda rushed this.

**Comment by confuser** [comment]
Dedi 1 config has the enabled part of external set to false, hence why it isn't working.

**Comment by Theepwner** [comment]
Just realized I've been using an incorrect BanManager setup.  I always thought External bans was for a database located on a different dedi ._.

So what happens to the players I banned using the external bans?  I just turned that feature off and set it to how it should, but I'm not sure since we meant for global bans.

Thanks.

**Comment by confuser** [comment]
http://dev.bukkit.org/bukkit-plugins/ban-management/#w-global-bans should explain the difference between the two.

Someone else was confused with the names. I might rename it from external to global to avoid future confusion.

**Comment by Theepwner** [comment]
So it appears that I still have an issue.  Banning a player on my OP PvP server on dedi 2 does not transfer the ban to our hub server on dedi 1.

Hub config:  http://pastebin.com/PuWgfR9x
OP PvP config:  http://pastebin.com/wgJmbdV0

They both share the same database too, and the hub server updates only after I restart it.

**Comment by confuser** [comment]
Check your console for any warnings from BanManager on startup regarding time.

**Comment by Theepwner** [comment]
Yeah, got this:
[22:01:08] [Server thread/ERROR]: [BanManager] The time on your server and MySQL database are out by 27 seconds, this may cause syncing issues.

I used NTP to sync both dedis.  All I did was install NTP to both systems and it synced, is that all I have to do? (I didn't configure it)

It fixed the issue, but I'm not sure if this is only a temp fix :/

**Comment by confuser** [comment]
That is indeed the correct fix.

Ensure you have NTP setup to start when your machine boots up.
