### ISSUE TITLE
External database not works

### ISSUE THREAD

**Issue by checkplysgamer** [BanManagement/BanManager#150]
Im put external database true but the plugin tries to connect local, failing
Please help

**Comment by checkplysgamer** [comment]
Im using v4.0 . How to donwload v5?

**Comment by confuser** [comment]
http://ci.frostcast.net for developer builds

Note: Local database is always required, external is optional.

**Comment by checkplysgamer** [comment]
My database is external

**Comment by confuser** [comment]
external is simply a different term to mean global bans.

As I said, the local database connection information is always required, BanManager doesn't care whether or not it is external.

**Comment by checkplysgamer** [comment]
Im put  in local and not works  :-(

**Comment by confuser** [comment]
Please read the FAQ on the plugin page. It'll answer your problem.

**Comment by checkplysgamer** [comment]
Im added % in external database option in host
My bans site: http://bans.txcraftnetwork.tk/
My config:
localDatabase:
  host: mysql.txcraftnetwork.tk
  port: 3306
  database:txcraft_bans
  username: txcraft_dbbans
  password: (my password)
  bansTable: bm_bans
  bansRecordTable: bm_ban_records
  ipBansTable: bm_ip_bans
  ipBansRecordTable: bm_ip_records
  kicksTable: bm_kicks
  mutesTable: bm_mutes
  mutesRecordTable: bm_mutes_records
  playerIpsTable: bm_player_ips
  warningsTable: bm_warnings
  banAppealsTable: bm_ban_appeals
  pinsTable: bm_pins
  staffTable: bm_staff





(this not works)
