### ISSUE TITLE
Own permissions not working properly?

### ISSUE THREAD

**Issue by Kakifrucht** [BanManagement/BanManager#152]
I just tried the latest build with the new .own permissions, but I'm unsure if they work. If I simply hand out the permission bm.command.unban.own, it won't let the player unban, if I add both the .own and the normal one, it will let him unban whoever.

**Comment by confuser** [comment]
bm.command.unban
bm.command.unban.own

Ensure they don't have a bm.exempt.override.ban permission

**Comment by Kakifrucht** [comment]
Yes, thats how I have it.
These are all permissions I gave that specific group:

bm.command.kick
bm.command.ban
bm.command.ban.offline
bm.command.tempban
bm.command.tempban.offline
bm.command.unban
bm.command.unban.own
bm.command.warn
bm.command.warn.offline
bm.command.dwarn
bm.command.tempmute
bm.command.unmute
bm.command.unmute.own
bm.command.bminfo
bm.command.bminfo.playerstats

They can still unban whoever they want.

**Comment by confuser** [comment]
Are you sure they don't have any exempt permissions or are op'd?

**Comment by Kakifrucht** [comment]
No OP and no other permissions, these are the only permissions they have, and some notify permissions inherited from subgroups.

**Comment by confuser** [comment]
Ok thank you for the report. I'll investigate.

**Comment by Kakifrucht** [comment]
After quite some updates the permission node seems to do something, however when Player A bans Player X, A cant unban X, however other player with same permission B can.

**Comment by confuser** [comment]
Thanks for the update @Kakifrucht, I haven't forgotten about this, and I'll try and get this fixed in the next couple of weeks.
