### ISSUE TITLE
Mutes doubling up

### ISSUE THREAD

**Issue by Bestle** [BanManagement/BanManager#153]
I have noticed an issue on my server whereby if a member of staff mutes a player, the muted players mute record shows the following:

- A mute by console
- The same mute by console unmuted by the member of staff
- A new mute by the member of staff

It doesn't seem to happen all of the time and there doesn't seem to be any specific steps to reproduce.

I am using a version of BanManager built from https://github.com/BanManagement/BanManager/commit/e9e23b5c8eea2ea8d073151dca4bf6b8f30b70bb

**Comment by confuser** [comment]
Are they temporary or permanent mutes? Does the issue occur on builds before https://github.com/BanManagement/BanManager/commit/e9e23b5c8eea2ea8d073151dca4bf6b8f30b70bb ?

**Comment by Bestle** [comment]
They are temporary mutes.

I am not sure, I shall give it a try and report back.

**Comment by confuser** [comment]
Did downgrading affect this issue at all?

**Comment by Bestle** [comment]
Haven't had a chance to try yet, sorry.

**Comment by confuser** [comment]
I've not heard any others complaining of this issue. I am also unable to reproduce it. Feel free to open a new issue if this is still a problem.
