### ISSUE TITLE
All commands not working

### ISSUE THREAD

**Issue by MusicReprod** [BanManagement/BanManager#155]
When I ban someone it just keeps repeating /ban <username> <reason>

Same thing for mute. I am using Dev Build #58 on a recent version of Spigot 1.8.

It also seems like Muted people are no longer muted.

Thanks

**Comment by smmalloy** [comment]
Also having a simular issue. Using build 58. When running any command, recevie the following. client side: An error occured whilst attempting to perform that command. Please check the console for the error

console: 
http://pastebin.com/KmzX7p5d

**Comment by confuser** [comment]
@MusicReprod Can you provide the console output for when that occured?

@smmalloy are you running your server in offline mode?

**Comment by smmalloy** [comment]
Server is in Online mode.

**Comment by confuser** [comment]
@smmalloy your error is a separate issue, therefore please open a new one.

@MusicReprod does downgrading to build 57 solve your issue?

http://ci.frostcast.net/job/BanManager/57/

**Comment by confuser** [comment]
Due to lack of response, closing this issue. Feel free to reopen.
