### ISSUE TITLE
Admin name still shows up as a UUID on the web Interface

### ISSUE THREAD

**Issue by T1mTheEnchanter** [BanManagement/BanManager#156]
Hello, I am a staff member on Swag-craft, a.k.a. Imperial Networks. Recently I've noticed an issue regarding the Web Interface. If I select 'IP Address' next to the search box, and click 'Display All', BanManagement will show the UUID of the staff member who banned the player rather than their username. If I go into the detailed ban info of a specific IP Address however, it **will** show me the username of the staff member. An example of what I am trying to say can be found  [here](http://secure.imperialmc.net/bans_v1/index.php?action=searchip&server=2&player=%25).

I'm not sure what the exact version of the web interface we're using, however I do know that we use one of the 5.0 dev builds in-game and for the web interface. The footer does say [this](http://puu.sh/g0Aed.png) - I'm not sure if that would help, but I thought I'd may as well include it anyways.

If this issue has been fixed in a more recent version, then I do apologise for wasting your time.

Regards,
Tim.
https://github.com/BanManagement/BanManager/issues/new#

**Comment by frdmn** [comment]
@T1mTheEnchanter Hey buddy. Thanks for reporting this, but could you please open this in the repository for the web UI? This one (right here) is dedicated for the Java plugin. 

https://github.com/BanManagement/BanManager-WebUI/issues

**Comment by T1mTheEnchanter** [comment]
Alright, sorry about that.

**Comment by frdmn** [comment]
@T1mTheEnchanter No worries.
