### ISSUE TITLE
TempBan for a certain player not working

### ISSUE THREAD

**Issue by xCyanide** [BanManagement/BanManager#158]
I tempbanned a certain player, but that person doesn't get banned. I tested to see if tempban would work for another player and it did. Why does tempban work on everyone else, but doesn't work on one player? I see the player in bans table.

**Comment by XxCoolGamesxX** [comment]
We have some bug of tempbanned.

**Comment by Bestle** [comment]
Have noticed this as well with perm bans. Player banned but still on the server.

**Comment by confuser** [comment]
Are you running in online or offline mode?

**Comment by Bestle** [comment]
Online mode for me.

**Comment by confuser** [comment]
So essentially they aren't being kicked?

The only cause would be if BM doesn't think they're online on the server. This would explain the null pointer exceptions being thrown for a null actor.

However, I can't see a route that would cause this problem, except if the AsyncPlayerPreLoginEvent is not executed, which only occurs on Craftbukkit in offline mode.

**Comment by k3ldon** [comment]
tempban work only with op in offline mode, the node is broken

**Comment by confuser** [comment]
Please try the latest build

http://ci.frostcast.net/job/BanManager/lastSuccessfulBuild/
