### ISSUE TITLE
TempBan'd player causing "Exception in thread"

### ISSUE THREAD

**Issue by seriosbrad** [BanManagement/BanManager#159]
This player was banned for 1 day using the following command:

>/tempban Red_Eagle80 5d Client mods

When he tries to join the server, instead of a ban message sent to his client it throws an error to his client and the console, as well as displays in chat that he has connected but immediately disconnects.

>3:20:25 PM CONSOLE: [INFO] UUID of player Red_Eagle80 is f1331e32-d4ee-49ab-9de4-d9b23bc0ba8b
>3:20:25 PM CONSOLE: Red_Eagle80 has logged in.
>3:20:25 PM CONSOLE: [INFO] Red_Eagle80[/173.19.0.70:42200] logged in with entity id 292132 at ([main] -2635.3947125419168, 35.0, -2468.8617857450454)
>3:20:26 PM CONSOLE: WARN]: Exception in thread "Craft Scheduler Thread - 804"
>3:20:26 PM CONSOLE: WARN]: org.apache.commons.lang.UnhandledException: Plugin BanManager v5.0.0-SNAPSHOT generated an exception while executing task 1268221
>3:20:26 PM CONSOLE: java.lang.StringIndexOutOfBoundsException: String index out of range: -2
>3:20:28 PM CONSOLE: Red_Eagle80 has left.
>3:20:28 PM CONSOLE: [INFO] Red_Eagle80 lost connection: Disconnected
>3:20:28 PM !: Red_Eagle80 has left

BanManager v5.0.0-SNAPSHOT
Spigot-b1e6da1-1092acb

**Comment by seriosbrad** [comment]
Here's an update.  After I unbanned him to reduce his ban to 20 hours, and re-rebanned him, he was able to log into the server and I was unable to ban him until I manually removed him from the database.  Please see the SQL errors in the log:

http://pastebin.com/ha41Gv2w

**Comment by frdmn** [comment]
probably related to #158

**Comment by confuser** [comment]
According to your stack trace you are running an out of date developer build. Please update to the most recent build, it fixes the error in your console.
