### ISSUE TITLE
Kick on ban not always working

### ISSUE THREAD

**Issue by Kakifrucht** [BanManagement/BanManager#161]
I'm not sure if this is any helpful, but I had some instances of players that were tempbanned and didn't get kicked on ban. When manually kicking them they couldn't reconnect and no exceptions were thrown.
I couldn't reproduce this myself though. I'll try to investigate this further.

**Comment by confuser** [comment]
Do you have any other plugins that integrate with BanManager?

**Comment by Kakifrucht** [comment]
No, I'm not using it's API.

**Comment by confuser** [comment]
I'm afraid I've not been able to reproduce this.

If you are able to, please update this issue and I'll reopen it.
