### ISSUE TITLE
Troubles running commands

### ISSUE THREAD

**Issue by smmalloy** [BanManagement/BanManager#162]
Having a issue. Using build 58. When running any command, receive the following. client side: An error occurred whilst attempting to perform that command. Please check the console for the error

console: 
http://pastebin.com/KmzX7p5d

**Comment by confuser** [comment]
For some reason, the actor must be null, which is causing this exception.

Who is running these commands, a player or console? Do you have any NPC like plugins?

**Comment by smmalloy** [comment]
Player, Only plugin on the server.

**Comment by seriosbrad** [comment]
Same thing going on with me here.  No NPC plugins, and the commands are run by players.

https://github.com/BanManagement/BanManager/issues/164

**Comment by smmalloy** [comment]
@confuser Any luck fixing this? Kinda a major issue for me.

**Comment by seriosbrad** [comment]
@smmalloy post your plugin list as well, it'll help pin-point a problem.

**Comment by smmalloy** [comment]
As I previously stated. It is the only plugin on the server.

**Comment by seriosbrad** [comment]
I totally read that yesterday too, my bad!

**Comment by smmalloy** [comment]
haha, soooo Any ideas on a fix?

**Comment by smmalloy** [comment]
@seriosbrad  Any ideas on release of a fix??

**Comment by seriosbrad** [comment]
@smmalloy sorry, nope.  It happens so inconsistently that I haven't been able to figure it out myself. Make sure all your other plugins are up to date, even dev builds.

**Comment by smmalloy** [comment]
No worries, but again, no other plugins running :)

**Comment by seriosbrad** [comment]
I have the memory or a goldfish, apologies hahahaha

**Comment by confuser** [comment]
I'm running BanManager on 9 Frostcast servers, running a mixture between 1.6 - 1.8, and I'm afraid I can't reproduce the issue.

What build of Spigot are you using? Are you behind something like Bungeecord or lilypad?

**Comment by confuser** [comment]
Please try the latest build

http://ci.frostcast.net/job/BanManager/lastSuccessfulBuild/

**Comment by confuser** [comment]
Any luck with the latest developer builds?

Are you /reload'ing the server or using some sort of plugin manager to enable/disable BanManager on the fly without a restart?

**Comment by smmalloy** [comment]
Well, the solution for me, was to use a later build and reset the Db. :)
