### ISSUE TITLE
Update to 1.7.10/1.8.1

### ISSUE THREAD

**Issue by TNTPata** [BanManagement/BanManager#163]
So, on bukkit it seems that the plugin is abandoned, but on GitHub there are recent tickets, it won't work on my server either. So is the plugin updated or is there a really simple way to update it youself that i'm to dumb to understand?

Someone explain to a dumb 14yr old?

**Comment by confuser** [comment]
http://dev.bukkit.org/bukkit-plugins/ban-management/pages/uuid-update/
