### ISSUE TITLE
MySQL errors after server has been running a while

### ISSUE THREAD

**Issue by seriosbrad** [BanManagement/BanManager#164]
I'm running dev build #58, everything runs perfectly - until suddenly, it does not!

Randomly, all of the ban, mute, kick, and temp commands stop working and MySQL errors are produced until I restart the server, then it's back to normal.

Here is a /kick attempt:
http://pastebin.com/KKYqU5Us

Here is a /kick attempt with a reason:
http://pastebin.com/yBAtti2H

And a /mute attempt:
http://pastebin.com/BqfuX75k

I've briefly read some "actor_id" errors being related to the server running in offline mode, but my server is most definitely running in ONLINE mode.  In fact, I am strongly against running in offline mode, for obvious reasons.

**Comment by confuser** [comment]
Can I get a list of your plugins?

**Comment by seriosbrad** [comment]
Sure,

http://pastebin.com/Tz0buxEH

**Comment by Aquazus** [comment]
Got the same error.
Plugins list:

ProtocoLib
Rushland (custom plugin)
RushlandTrails (custom plugin)

**Comment by confuser** [comment]
Please try the latest build

http://ci.frostcast.net/job/BanManager/lastSuccessfulBuild/

**Comment by confuser** [comment]
Any luck with the latest developer builds?

Are you /reload'ing the server or using some sort of plugin manager to enable/disable BanManager on the fly without a restart?

**Comment by confuser** [comment]
I'm going to assume this is fixed due to lack of response.

Please re-comment if still experiencing this issue with the latest developer builds.
