### ISSUE TITLE
SQL Connection error!

### ISSUE THREAD

**Issue by kodlust** [BanManagement/BanManager#167]
Cannot use localhost (i'm on VPS atm).
Has been working flawlessly before (v4).
Using newset ban managment plugin,
Tried both clean run with new db and converted from v4 db.

16:57:08 CONSOLE: WARN]: java.sql.SQLException: Could not build prepared-query iterator for class me.confuser.banmanager.data.IpBanData
16:57:08 CONSOLE: WARN]: at me.confuser.banmanager.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
16:57:08 CONSOLE: WARN]: at me.confuser.banmanager.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:968)
16:57:08 CONSOLE: WARN]: at me.confuser.banmanager.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:533)
16:57:08 CONSOLE: WARN]: at me.confuser.banmanager.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:528)
16:57:08 CONSOLE: WARN]: at me.confuser.banmanager.ormlite.stmt.QueryBuilder.iterator(QueryBuilder.java:389)
16:57:08 CONSOLE: WARN]: at me.confuser.banmanager.storage.IpBanStorage.findBans(IpBanStorage.java:127)
16:57:08 CONSOLE: WARN]: at me.confuser.banmanager.runnables.IpSync.newBans(IpSync.java:43)
16:57:08 CONSOLE: WARN]: at me.confuser.banmanager.runnables.IpSync.run(IpSync.java:25)
16:57:08 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
16:57:08 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
16:57:08 CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
16:57:08 CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
16:57:08 CONSOLE: WARN]: at java.lang.Thread.run(Thread.java:745)
16:57:08 CONSOLE: WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
16:57:08 CONSOLE: packet successfully received from the server was 30,267 milliseconds ago. The last packet sent successfully to the server was 6 milliseconds ago.
16:57:08 CONSOLE: WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
16:57:08 CONSOLE: WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
16:57:08 CONSOLE: WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
16:57:08 CONSOLE: WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
16:57:08 CONSOLE: WARN]: at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
16:57:08 CONSOLE: WARN]: at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
16:57:08 CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3082)
16:57:08 CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2968)
16:57:08 CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3516)
16:57:08 CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
16:57:08 CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
16:57:08 CONSOLE: WARN]: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
16:57:08 CONSOLE: WARN]: at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
16:57:08 CONSOLE: WARN]: at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2273)
16:57:08 CONSOLE: WARN]: at me.confuser.banmanager.ormlite.jdbc.JdbcCompiledStatement.runQuery(JdbcCompiledStatement.java:55)
16:57:08 CONSOLE: WARN]: at me.confuser.banmanager.ormlite.stmt.SelectIterator.<init>(SelectIterator.java:55)
16:57:08 CONSOLE: WARN]: at me.confuser.banmanager.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:247)
16:57:08 CONSOLE: WARN]: at me.confuser.banmanager.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:964)
16:57:08 CONSOLE: WARN]: ... 11 more
16:57:08 CONSOLE: WARN]: Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
16:57:08 CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2529)
16:57:08 CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2979)
16:57:08 CONSOLE: WARN]: ... 22 more
16:57:08 CONSOLE: WARN]: java.sql.SQLException: Could not build prepared-query iterator for class me.confuser.banmanager.data.PlayerBanData
16:57:08 CONSOLE: WARN]: at me.confuser.banmanager.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
16:57:08 CONSOLE: WARN]: at me.confuser.banmanager.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:968)
16:57:08 CONSOLE: WARN]: at me.confuser.banmanager.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:533)
16:57:08 CONSOLE: WARN]: at me.confuser.banmanager.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:528)
16:57:08 CONSOLE: WARN]: at me.confuser.banmanager.ormlite.stmt.QueryBuilder.iterator(QueryBuilder.java:389)
16:57:08 CONSOLE: WARN]: at me.confuser.banmanager.storage.PlayerBanStorage.findBans(PlayerBanStorage.java:135)
16:57:08 CONSOLE: WARN]: at me.confuser.banmanager.runnables.BanSync.newBans(BanSync.java:45)
16:57:08 CONSOLE: WARN]: at me.confuser.banmanager.runnables.BanSync.run(BanSync.java:27)
16:57:08 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
16:57:08 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
16:57:08 CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
16:57:08 CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
16:57:08 CONSOLE: WARN]: at java.lang.Thread.run(Thread.java:745)
16:57:08 CONSOLE: WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
16:57:08 CONSOLE: packet successfully received from the server was 30,268 milliseconds ago. The last packet sent successfully to the server was 7 milliseconds ago.
16:57:08 CONSOLE: WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
16:57:08 CONSOLE: WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
16:57:08 CONSOLE: WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
16:57:08 CONSOLE: WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
16:57:08 CONSOLE: WARN]: at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
16:57:08 CONSOLE: WARN]: at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
16:57:09 CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3082)
16:57:09 CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2968)
16:57:09 CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3516)
16:57:09 CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
16:57:09 CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
16:57:09 CONSOLE: WARN]: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
16:57:09 CONSOLE: WARN]: at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
16:57:09 CONSOLE: WARN]: at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2273)
16:57:09 CONSOLE: WARN]: at me.confuser.banmanager.ormlite.jdbc.JdbcCompiledStatement.runQuery(JdbcCompiledStatement.java:55)
16:57:09 CONSOLE: WARN]: at me.confuser.banmanager.ormlite.stmt.SelectIterator.<init>(SelectIterator.java:55)
16:57:09 CONSOLE: WARN]: at me.confuser.banmanager.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:247)
16:57:09 CONSOLE: WARN]: at me.confuser.banmanager.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:964)
16:57:09 CONSOLE: WARN]: ... 11 more
16:57:09 CONSOLE: WARN]: Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
16:57:09 CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2529)
16:57:09 CONSOLE: WARN]: at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2979)
16:57:09 CONSOLE: WARN]: ... 22 more

**Comment by confuser** [comment]
```
16:57:09 CONSOLE: WARN]: Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
```

Your database service terminated the connection.

**Comment by kodlust** [comment]
If the server is kept online with this issues, the server processor will keep rising until crash...

Had to shutdown during peak hours of players due to 90%+ constant CPU.

**Comment by confuser** [comment]
Then you need to investigate why your mysql server is closing the connection.

I closed this issue as it is a server configuration issue, and not to do with the plugin itself.

**Comment by kodlust** [comment]
No issues with any other plugins using sql. Only banmanager v5 having issues with connection.

**Comment by gaosong2101** [comment]
Same problem, but I solved the problem by using the following method. 
Try editing/adding the following lines on your MySQL config file (my.cnf): 
[mysqld]
wait_timeout=31536000
interactive_timeout=31536000

And then reboot your MySQL server. 

Hope this will be helpful. 
Also sorry for my poor English. 

Ref: http://blog.csdn.net/mqboss/article/details/6659001
