### ISSUE TITLE
WebUI and SQL errors.

### ISSUE THREAD

**Issue by dylanweb2** [BanManagement/BanManager#169]
When I ban someone it shows up on the WEB-UI just fine. but if I try to modify/delete the record from the WEB-UI I get an error saying -1. error record not found - 

Picture might relate to the problem with the unknown characters.

http://puu.sh/gcXg0/c34b377c2e.png

**Comment by frdmn** [comment]
@dylanweb2 Hey! Can you open the issue in the repository for the web UI?

This one right here is actually for the Java plugin only.

You can find the proper repository here:

https://github.com/BanManagement/BanManager-WebUI/issues
