### ISSUE TITLE
warningActions Issue

### ISSUE THREAD

**Issue by EndWar3281** [BanManagement/BanManager#171]
Hello, i just updated to the new Version.
and i got a little problem.
Im using the warningActions with 3 warns = ban well i 'used'.
its not working anymore.
i set it up: 
warningActions:
  enabled: true
  actions:
  '3': ban [name] [reason]

but everytime it is reseting to:
warningActions:
  enabled: true
  actions:
    '10': ban [player] [reason]
  '3': ban [name] [reason]

and/or if i do it like that:
warningActions:
  enabled: true
  actions:
    '3': ban [player] [reason]
  '3': ban [name] [reason]

then its reseting to this:

warningActions:
  enabled: true
  actions:
    '10': ban [player] [reason]
  '3': ban [name] [reason]
  '3': ban [name] [reason]

It would be awesome if i could get fast help.
Thanks

**Comment by Kakifrucht** [comment]
It's not resetting, it's just adding '10': ban [player] [reason] as a default parameter.
There is already a ticket about this. You shouldn't really care about it.

Same thing: #122
