### ISSUE TITLE
Can't delete warning

### ISSUE THREAD

**Issue by Freymuth** [BanManagement/BanManager#172]
Hey,

i installed your plugin without conversion. 

I can't remove this warning. It's a bug?

http://www.youscreen.de/gxuzouxe95.jpg

http://www.youscreen.de/ypyowana94.jpg

Please help me

**Comment by frdmn** [comment]
@Freymuth Wrong repository. This one is for the Java plugin only.

But to answer your question: BanManagement/BanManager-WebUI#15

The admin functions won't work at the moment. Will be back soon.
