### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by GoldPvP** [BanManagement/BanManager#175]
Commands do not work with NCP's

**Comment by confuser** [comment]
Please provide more information. BanManager is designed to work via the Bukkit API and not via NPCs/NMS.

**Comment by GoldPvP** [comment]
That's not what I mean. 
None of the Banmanager commands work if you have the Citizen plugin installed.
Here's an error from it,
http://paste.revo.pw/tolexufima.profile

**Comment by confuser** [comment]
BanManager commands are only designed to be run either by real players or the console, like most other plugins.

**Comment by GoldPvP** [comment]
I know that, I already told you that that is not what I mean.
I said that if you have BanManger installed as [Citizens](http://dev.bukkit.org/bukkit-plugins/citizens/) then when you try to do any banamanger command you get the error which i posted.
