### ISSUE TITLE
API Rate Limit Issue

### ISSUE THREAD

**Issue by MinecraftAdmin** [BanManagement/BanManager#182]
I am running BanManagement 5.x exclusively on a local test machine to convert a remote bans database from an older version of the plugin to the updated UUID version of the database on the local system.

I have over 4800+ bans registered in the old database. The conversion process on the local system stalls as soon as I hit the Mojang API rate limit and after repeated attempts to continue conversion the process only adds 5 to 10 additional bans before stalling again.

Looking at the conversion logs, I noticed it queries Mojangs API for the same usernames every single time it is run. Is there no way for it to skip users already added to the database?

**Comment by confuser** [comment]
The conversion process will look in the database first for the player based on the name. If it can't find it or it finds duplicates, it'll make a request to Mojang.

**Comment by MinecraftAdmin** [comment]
Does it lookup UUID's seperately for Kicks, Bans, Mutes, Tempmutes, and Tempbans?
I noticed a new bm_players  in my database, but since that table was converted completely, I am confused about why it would do that.

**Comment by confuser** [comment]
It should do that for all conversions. Which converter are you seeing this occur with?
