### ISSUE TITLE
Ban import error.

### ISSUE THREAD

**Issue by rippin** [BanManagement/BanManager#183]
http://pastebin.com/bQLGnujw

I tried it on two different servers and on both it imports a couple players then I get this error.

Tried on 5.0.0 and the latest dev version as well.

**Comment by confuser** [comment]
Can you provide your banned-players.json file please

**Comment by rippin** [comment]
Here is a pastebin http://pastebin.com/0Syu2YnU 
If you need the actual file do you know where I can upload it?
