### ISSUE TITLE
Too Many MySQL Connections

### ISSUE THREAD

**Issue by nokoa** [BanManagement/BanManager#184]
It seems as the plugin doesn't close the MySQL connections it opens, which results in too many connection error.

**Comment by Orenthion** [comment]
Do you have an error log?
Can you post the plugin version you are using.

**Comment by nokoa** [comment]
I am using the latest build, on a 1.8 Spigot server. I am using the API and created a Punish menu, I made an option to show punishment records for the players on the menu, but it seems as when the database opens a connection to the database to get the records, it doesn't close those connections. The connections remain open and when I view the records again it opens more, instead of using the ones that are already open. On the plugin config file Max connections is set to default of 10. I will provide an error log later today as for the moment I am not on my computer to get it.

**Comment by confuser** [comment]
Connections are closed on disable.

I've never seen BM opening too many connections to a database before.

What is your connection limit set to in your MySQL configuration?

**Comment by nokoa** [comment]
Due to the problem I get that it opens too many connections I raised the Max_connection on MySQL to 1000, though when it gets to 1000 connections it disconnects the players.  It might be an issue with the API, is there a way for me to close the connection through the APi?

**Comment by confuser** [comment]
By API do you mean the BmAPI class?

**Comment by nokoa** [comment]
Yes

**Comment by nokoa** [comment]
The problem is in my code, I forgot to close the connections

**Comment by confuser** [comment]
BmAPI makes use of CloseableIterator's, ensure you simply call .close() on them

**Comment by z1haze** [comment]
im using banmanager as well, and getting tons of hanging connections in mysql causing too many connections issues... banmanager is obviously not closing connections properly.
