### ISSUE TITLE
Actor is null when looking at records!

### ISSUE THREAD

**Issue by nokoa** [BanManagement/BanManager#186]
Hey there, I have created a Punish Menu using BmAPI, and it seems as when I am trying to display records the actor is null, but when it is displayed for current ban for example, it displays the actor's name just fine. Might it be a bug with your!
 plugin, or am I doing something wrong?
![2015-03-10_16 01 26](https://cloud.githubusercontent.com/assets/7198304/6587281/876859ba-c73f-11e4-9e55-8602eac5863c.png) Records...
"Admin = BmAPI.getMuteRecords(BmAPI.getPlayer(target))
					.moveRelative(id).getActor().getName();"
Current punishment
![2015-03-10_16 01 32](https://cloud.githubusercontent.com/assets/7198304/6587286/934f7344-c73f-11e4-9906-6818fed67383.png)
"Admin = BmAPI.getCurrentMute(target).getActor().getName();"

**Comment by confuser** [comment]
Can you provide the exact code you are using?

I'm not able to reproduce this.

**Comment by HoaxIT** [comment]
same issue here.

```
    public void bans(CallInfo callInfo) throws SQLException {
        String username = callInfo.getArg(0);

        PlayerData player = BmAPI.getPlayer(username);

        List<PlayerBanRecord> playerBanRecords = new ArrayList<PlayerBanRecord>();

        CloseableIterator<PlayerBanRecord> pbr = BmAPI.getBanRecords(player);
        while(pbr.hasNext()){
            playerBanRecords.add(pbr.next());
        }

        Collection<String> messages = null;

        for(PlayerBanRecord p : playerBanRecords){
            message += ChatColor.translateAlternateColorCodes('&', "\n&7- &6" + p.getReason() + ", by &c" + p.getActor().getName() + "&6.");
        }

        callInfo.getPlayer().sendRawMessage(message);
```

**Comment by confuser** [comment]
Please try the latest developer build
