### ISSUE TITLE
Country blocking

### ISSUE THREAD

**Issue by confuser** [BanManagement/BanManager#188]
Via GeoIPTools

http://dev.bukkit.org/bukkit-plugins/geoiptools/pages/developers/

**Comment by EvilOlaf** [comment]
Nice. To improve this it should include two modes: blacklist and whitelist.
In blacklist mode countries on the list will not be allowed to join the server.
In whitelist mode only listed countries will be allowed to join.

For example if you have a German server and problems with bots joining from various locations (even in online mode this could happen) you could explicitly allow users from Germany, Austria and Switzerland only.a
This could be further enhanced by adding a permission node to bypass the whitelist restriction to be able to join from other locations. Useful for players on vacation and stuff.
