### ISSUE TITLE
serverName no longer supported?

### ISSUE THREAD

**Issue by c0wg0d** [BanManagement/BanManager#191]
I'm not sure if this is an issue in the webui or in the plugin itself.  All servers share the same local database, and I set a serverName variable for each in the config.yml.  With v4, I was able to see which server they were banned from, but this doesn't show up anymore.  I tried to put {SERVER} in the "Current Ban HTML Extra" field on the settings setup page, but when I hit save it just disappears.  The settings file is set to chmod 777 but I don't see that being set anywhere.  Is this just not supported anymore or am I doing it wrong?

**Comment by confuser** [comment]
The console name can be changed within console.yml, but as far as serverName for bans etc, it was removed when I re-designed the schema for v5, as for most users, it was an unnecessary column, and info that could quite easily be looked up via a simple grep.

**Comment by c0wg0d** [comment]
Well none of my moderators have ssh access to the server, and it was a really nice thing to know where a player was banned from.  So if I update console.yml to be the server name, is it going to say "Banned by: Server Name" on the web ui now, instead of "Banned by: c0wg0d"?  Or does it go into a different place?

**Comment by confuser** [comment]
Any commands performed by the console, will display the name defined in the console.yml file.

I'm leaving this issue open for considering re-adding this feature back.
