### ISSUE TITLE
Are columns really supposed be binary?

### ISSUE THREAD

**Issue by c0wg0d** [BanManagement/BanManager#192]
I just updated from v4 to v5 and I am very confused at the SQL schema.  Many of the columns are marked as binary fields, so I can't even read the UUIDs in the database.  Is this really how it's supposed to be?

    mysql> select * from player_bans limit 1;
    +----+------------------+------------------------------+------------------+------------+------------+---------+
    | id | player_id        | reason                       | actor_id         | created    | updated    | expires |
    +----+------------------+------------------------------+------------------+------------+------------+---------+
    |  1 | ö±!
              yª@;öÛ¹â=½ | online dating is not allowed | T/V9%N0°[¾ÉBf | 1425149980 | 1426142203 |           0 |
    +----+------------------+------------------------------+------------------+------------+------------+---------+

    mysql> describe player_bans;
    +-----------+--------------+------+-----+---------+----------------+
    | Field     | Type         | Null | Key | Default | Extra          |
    +-----------+--------------+------+-----+---------+----------------+
    | id        | int(11)      | NO   | PRI | NULL    | auto_increment |
    | player_id | binary(16)   | NO   | UNI | NULL    |                |
    | reason    | varchar(255) | NO   |     | NULL    |                |
    | actor_id  | binary(16)   | NO   |     | NULL    |                |
    | created   | int(10)      | NO   | MUL | NULL    |                |
    | updated   | int(10)      | NO   | MUL | NULL    |                |
    | expires   | int(10)      | NO   | MUL | NULL    |                |
    +-----------+--------------+------+-----+---------+----------------+

**Comment by confuser** [comment]
Yes, this is intentional.

It uses less storage space, and it's index based lookups are much faster than varchar.

Use the following query to view it in a common string format

```SELECT HEX(player_id), * FROM player_bans;```
