### ISSUE TITLE
Any way to recreate banned-players.json and banned-ips.json?

### ISSUE THREAD

**Issue by c0wg0d** [BanManagement/BanManager#193]
I just did a migration from v4 to v5 and I'm noticing some discrepancies in the database vs. the fallback banned-players.json file in the server root.  Is there any easy way to generate a new one of these files, or would I be on my own to write a script to do this?

**Comment by confuser** [comment]
v5 no longer modifies the vanilla .json files, as it was causing a lot of problems once the UUID changes were brought into bukkit.

A mocked export command currently does exist, which will eventually export all bans into the .json format. Most likely it'll be within the BanManager folder, and be dated, e.g. banned-players-2015-03-13.json to avoid accidental overriding of the existing banned-players.json and banned-ips.json.

At the moment it's a low priority, and not overly necessary these days, as BanManager keeps all bans in memory, so even if the MySQL database fails, it'll still deny banned players. So for the time being, if your MySQL connection really is that unstable and you want an extra safety net, then feel free to write your own script for the time being, as I have no ETA as to when /bmexport will be available for use.

**Comment by c0wg0d** [comment]
Works great in v5.5.0, thank you so much!
