### ISSUE TITLE
Importing bans from banned-players.json sets all bans to permanent.

### ISSUE THREAD

**Issue by HoaxIT** [BanManagement/BanManager#194]
The following issue occurs when trying to import the following ban from `banned-players.json`
```
  {
    "uuid": "80ce86f9-967a-3c3f-95d6-c3fe0477d758",
    "name": "DavagonV",
    "created": "2015-03-12 16:15:04 +0100",
    "source": "console",
    "expires": "2015-04-05 17:34:35 +0200",
    "reason": "testban"
  },
```

it sets the `expires` column in the database to 0 for the record, which sets the ban to an permanent ban, which should not happen, we're running the latest version from git, and there have been no exceptions in the console while running the import.

**Comment by Orenthion** [comment]
Your uuid and player name do not match (Just an FYI)

**Comment by HoaxIT** [comment]
I've changed those, as they are not relevant to the current issue, the problem lies in the importer, not importing the `expires` string into the `expires` column, which results in permanent bans.

if i had 100 bans, i've could change them manually, but having over 7.000 active bans, it's a pain in the ass to migrate.

**Comment by confuser** [comment]
The exporter will only set it to a permanent ban if expires is equal to "forever".

Can you please provide your banned-players.json file for me to reproduce the issue you are having?

**Comment by HoaxIT** [comment]
I've attached one ban to the ticket, i'll pastebin my banned-players.json in a few.

**Comment by confuser** [comment]
Please try the latest developer build with this fix

http://ci.frostcast.net/job/BanManager/83/
