### ISSUE TITLE
ability to see past bans, kicks, and mutes for an user.

### ISSUE THREAD

**Issue by HoaxIT** [BanManagement/BanManager#198]
correct me if wrong, but there is no command to see the past bans, kicks, and mutes for an user.

**Comment by Orenthion** [comment]
You can view the info using ```/bminfo <player>```
this will only tell you the amount of times.

It will also display any outstanding mutes or bans.

Any info that you would like to see about the specific bans, mutes, kicks, warns can all be viewed from the Web-UI

**Comment by confuser** [comment]
To be handled by #244
