### ISSUE TITLE
startup issue

### ISSUE THREAD

**Issue by theshadyonehd** [BanManagement/BanManager#201]
Getting this error:

http://pastebin.com/3ZfbmPsc

http://pastebin.com/MYXR3yq9

**Comment by confuser** [comment]
Looks like your conversion messed up.

Ensure that your v4 tables are different from v5 tables, as they have a different structure.

Please read the update instructions carefully http://dev.bukkit.org/bukkit-plugins/ban-management/pages/uuid-update/
