### ISSUE TITLE
Can't ban offline players

### ISSUE THREAD

**Issue by c0wg0d** [BanManagement/BanManager#202]
We are unable to ban offline players.  This is a serious issue.  Is this a misconfiguration on our part or does this not work currently?

**Comment by confuser** [comment]
Sounds like a permission issue?

bm.command.ban.offline etc

**Comment by c0wg0d** [comment]
Our moderators have bm.* permissions using PermissionsEx.  This wasn't an issue before the upgrade.  Anything else we should check?

**Comment by confuser** [comment]
What exactly is the problem? Just saying you're unable to ban an offline
player doesn't give me much to go on, in terms of what it could be. What is
the exact response they get when trying?

**Comment by c0wg0d** [comment]
I looked at our whitelist.json and got their UUID.  Looks like they changed their name and looking up via their old name does not return a result anymore.  I guess that means it is working as intended.
