### ISSUE TITLE
Tab-complete acting weird

### ISSUE THREAD

**Issue by Theepwner** [BanManagement/BanManager#204]
Before, tab-complete was auto guess for those who are online. Now it seems like it is going through the database or something.

http://i.imgur.com/zQAUi7j.png
In this image I've done /bminfo a[tab]

This issue is with other BanManager commands as well.

**Comment by confuser** [comment]
It's not acting weird, the behaviour has been changed in the latest developer builds, as per a feature request by others.

The autocomplete functionality now supports offline name lookups as of https://github.com/BanManagement/BanManager/commit/fac09fc1157291172f112816df4c1f9f6c749356

Is this not something you want? If not, I'll make it configurable as to whether or not it is enabled.

**Comment by Theepwner** [comment]
Yes, please make it configurable. It has become a bit more difficult to ban/punish players in-game when we have to type their whole name.
