### ISSUE TITLE
Use for multiserver punish system.

### ISSUE THREAD

**Issue by nokoa** [BanManagement/BanManager#208]
I was planning to use BanManager as a global punish system, though it seems to have some issues. When I punish a player on my network from hub, and the player is currently on a different server, (ie. my SG server), the player is not being kicked at all, also the punishment doesn't seem to exist at that server unless I reload it.

Couple things to add;
Global punishments;
Banning a player in one server will kick them from the other.
The system will constantly recheck and sync it self with the database, so all servers will be synced with the punishments.
Warning a player in one server will show up the warning message in the other server.

**Comment by confuser** [comment]
You've pretty much explained how BanManager already works.

If you're finding the syncing too slow, change it within your schedules.yml file
