### ISSUE TITLE
banned player tries to join notification

### ISSUE THREAD

**Issue by Okane84** [BanManagement/BanManager#209]
it'd be a cool feature to get a notification, to players with an appropriate permission node, when a currently banned player tries to join.

**Comment by confuser** [comment]
What benefit would this have?

**Comment by Okane84** [comment]
for admins and moderators it would be a way to check if some well known griefers, hackers or malicious users who threatened the server are trying to join and eventually send other allied playes to accomplish their objectives. it could prevent group attacks from griefing clans, preparing the server staff team to a possibly malicious players and giving the staff the chance to investigate on them and prevent future damages when staff isn't online.

**Comment by Okane84** [comment]
thank you :)
