### ISSUE TITLE
AutoComplete doesn't work on /unban

### ISSUE THREAD

**Issue by Ahava** [BanManagement/BanManager#210]
When using autocomplete on /unban I get [this](http://pastie.org/private/yx8mynoyxjdzobulgocoq) error. I'm using the latest Spigot 1.8 Release BanManager 5.2.0, PermissionsEx 1.23.1 and MySQL 5.6.

**Comment by EvilOlaf** [comment]
Related to https://github.com/PEXPlugins/PermissionsEx/issues/1956

**Comment by confuser** [comment]
We run PermissionsEx 1.23.1 along with Spigot 1.8 (probably rather outdated now) and BanManager v5.2.0 at Frostcast and do not get this error occurring.

I'll try with a more recent spigot build and see if I can reproduce.

**Comment by EvilOlaf** [comment]
@confuser My version of Spigot 1.8 is outdated too, because the latest 1.8 (not 1.8.3)  build created random crashes so I stepped back to an earlier build which runs fine for me.

**Comment by zml2008** [comment]
Just gotta make sure you don't pass any null permissions strings to us and you should be good. That's what the whole error is about.

**Comment by confuser** [comment]
Command.getPermission is being passed, plugin.yml contains the permission
node. It seems the differing factor causing this is different Spigot builds
as I can't reproduce with the builds we're using in production at
Frostcast. My current assumption is it's a Spigot bug and nothing to do
with pex nor BM but need to confirm.

**Comment by EvilOlaf** [comment]
I hope it doesn't so I don't have to change from my current build to another one :/
(Don't get me wrong in this case.)
Unfortunately distribution of Spigot builds is currently illegal so I can't provide mine for testing.

**Comment by Ahava** [comment]
I've updated to the latest 1.8.3 Build (git-Spigot-dbe012b-63e28b1) and still get the same error on tab complete.

**Comment by mormoon** [comment]
Build #401
[22:56:22 INFO]: This server is running CraftBukkit version git-Spigot-2f787bd-1a1bc08 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)
[22:56:22 INFO]: You are 17 version(s) behind

Just to report/inform, I also have this issue. Also using PEX 123.1 and MYSQL

**Comment by EvilOlaf** [comment]
Confirmed with 1.8.3 too

**Comment by confuser** [comment]
Do you still get the error with Essentials removed?

I'm still unable to reproduce this.

**Comment by mormoon** [comment]
No, can't reproduce this with essentals removed :)

**Comment by confuser** [comment]
Then I can only assume it's Essentials interfering. As its plugin.yml file lacks command permissions, I think it's safe to say that is the cause of the NPE.

Unfortunately there's very little I can do within BM to fix this.
