### ISSUE TITLE
Error "unknown column 'created' in 'where clause'".

### ISSUE THREAD

**Issue by SupaHam** [BanManagement/BanManager#214]
I was on my test server today, which used to be on a pretty old build of BanManager, released over a year ago. I just updated to 5.3.0-SNAPSHOT and get this error. http://paste.ee/p/GSbxp I personally don't care about my existing database since it is a test database, but just thought of bringing this up.

**Comment by confuser** [comment]
The table structure is different in v5, and requires conversion. Please read the update instructions carefully as stated on each download.

http://dev.bukkit.org/bukkit-plugins/ban-management/pages/uuid-update/
