### ISSUE TITLE
Tempmute "which expires in now" bug?

### ISSUE THREAD

**Issue by Theepwner** [BanManagement/BanManager#215]
Temp muting a player will perform as expected, but after the temp mute is over doing /bminfo for that certain player will show the mute is still active and expires now. It will show as "expires now" until the player actually chats after the mute is over.

This isn't a big deal, but I don't think it should say there is still a current mute when the duration is over, regardless if the player finally chatted or not.

**Comment by confuser** [comment]
If this is an issue for you, decrease the mutes check within your scheduler.

**Comment by Theepwner** [comment]
Mutes check within the scheduler?

scheduler:
  expiresCheck: 300
  playerBans: 30
  playerMutes: 30
  ipBans: 30
  externalPlayerBans: 120
  externalPlayerMutes: 120
  externalIpBans: 120
  saveLastChecked: 60
  newMutes: 8
  newBans: 8
  newIPBans: 8
  external: 120
  saveLastRuns: 60

It says these values are in seconds, but this weird "bug" will occur until the player finally chats. Am I missing something?

**Comment by Kakifrucht** [comment]
I have the same thing with tempbans, when doing /bminfo it will show up as still banned, until the player actually connects to the server. The Webinterface got the data right and doesn't show the player banned.
This is nothing major, but I guess the bug is actually valid.

**Comment by confuser** [comment]
Reduce expiresCheck from 300 seconds (5 minutes) to less if you view this as a bug.

The server checks at intervals for expired data, or expires it when required, i.e. when a player joins the server in the case of a ban, or when a player attempts to chat/use commands in the case of mutes.

This is for efficiency.

**Comment by Kakifrucht** [comment]
I understand that, the weird thing is that it's not only 5 minutes the information stays on /bminfo. The tempbanned player I had yesterday should have been unbanned at 23:10, but some hours later he still showed up with the information that the ban expires now. I think what ultimately fixed this was a server restart.

**Comment by Theepwner** [comment]
@confuser Yes, but the problem is that after the 5 minutes it doesn't change, as @Kakifrucht stated.
