### ISSUE TITLE
Punishment Protection

### ISSUE THREAD

**Issue by nokoa** [BanManagement/BanManager#217]
Add the option to protect players from punishments. Add it to the database whoever is on that list cannot be punished.

I would love to see this in future updates!

**Comment by Kakifrucht** [comment]
Why? Functionality like this is already implemented through permissions.

**Comment by nokoa** [comment]
It works while the protected player is online but when the player isn't online the punishment goes through....

**Comment by Kakifrucht** [comment]
That is true, but generally speaking BanManager functionality should only be given out to staff. If your staff bisbehaves there is something seriously broken in your system. I really don't think that an additional column in the database should be added because there is staff that misbehaves.

**Comment by nokoa** [comment]
Yes staff members shall be responsible, but just as a reciprocation, as if a staff members randomly decides to ban the Owner, the Owner shall be protected....

**Comment by Kakifrucht** [comment]
The Owner is protected, he has console access o.O

**Comment by nokoa** [comment]
I know, you know what never mind...........

**Comment by confuser** [comment]
I can see your reasoning behind this @nokoa but if they do these kinds of things, they shouldn't be staff. Like @Kakifrucht said, you should have console access to unban yourself should such a scenario occur.

The problem stems from the fact it's not possible within the Bukkit API to check an offline player's permission.

I will add such a feature, but not in the database, most likely a config file with a list of UUIDs that are exempt from any punishments.

Perhaps a little more configurable, i.e.
```yml
uuidHere:
  mutes: true
  bans: true
  warnings: true
```
