### ISSUE TITLE
User has permission bm.command.ban

### ISSUE THREAD

**Issue by KriticalPvP** [BanManagement/BanManager#218]
bm.command.ban

when player tries to ban someone they get this error::

No Permission... :(

Help? 

Still on v.4

**Comment by Orenthion** [comment]
The permission node for ban in v4 isn't ```bm.command.ban``` it is actually bm.ban

You can view the v4 permission nodes here: [Permissions](http://pastebin.com/wyMCkynB)

**Comment by KriticalPvP** [comment]
Thanks, does V.4 support UUIDs?

**Comment by Kakifrucht** [comment]
No

**Comment by KriticalPvP** [comment]
How do I install V.5 Fresh? and will it work on a 1.7.9/1.8.1 server?

**Comment by confuser** [comment]
Simply use different table names from v4 if you wish to use a completely new installation. If you want to convert from v4 to v5, read the conversion instructions over at http://dev.bukkit.org/bukkit-plugins/ban-management/pages/uuid-update/

It will work on 1.7 and 1.8 servers, even protocol hacks.
