### ISSUE TITLE
Add a max amount of accounts per ip

### ISSUE THREAD

**Issue by Agazed** [BanManagement/BanManager#221]
I have players using alts for unfair advantages. Can you add an option in the config to stop more than a number of accounts per ip address?

**Comment by confuser** [comment]
So a config option like
```maxOnlinePerIp: 2```

which would only allow a maximum of 2 different players joining with the same ip address?

**Comment by Agazed** [comment]
Yes it would limit players from having too many alts for things like power in factions.
