### ISSUE TITLE
Error when banning / muting... ingame but not on console? (after reloading)

### ISSUE THREAD

**Issue by jonas13362** [BanManagement/BanManager#222]
Hello ,

Im getting an internal error if i do /ban name reason ingame but if i do it on console its working properly

Heres the error log if i do it ingame : 
http://pastebin.com/yRJueU0c

Im running 1.8 by the way

Greetings ,
Jonas

**Comment by confuser** [comment]
Did you reload the server or use a plugin manager to install/reload BanManager?

**Comment by jonas13362** [comment]
I reloaded the plugins trought the console.
Im going to restart my server completly now to check if it works , i will edit this post assoon i did

**Comment by jonas13362** [comment]
Seems likely if i do /reload its crashing the plugin.Anyway how to fix it? Also as i said before the edit ban button isnt working good if u wanna save the edit

**Comment by confuser** [comment]
Yes, the fix is, don't use /reload. It creates a lot of memory leaks, and hot swapping code into an already running process is never going to end well in a production environment.
