### ISSUE TITLE
After installation of BanManager, the server will not start.

### ISSUE THREAD

**Issue by minegame30** [BanManagement/BanManager#223]
I just installed Banmanager today, and i have setup all of the configurations as they should be. However, the server gets to the point of loading the BanManager plugin, but then does nothing else.  EG
07.04 18:00:51 [Server] INFO Enabling BanManager v5.2.0
07.04 18:00:51 [Server] INFO Preparing start region for level 2 (Seed: -46345661315635104)
07.04 18:00:50 [Server] INFO Preparing start region for level 1 (Seed: -46345661315635104)
07.04 18:00:50 [Server] INFO Preparing start region for level 0 (Seed: -46345661315635104)

And thats it. Nothing more happens after this. The server is not entirely unresponsive as when I try to connect, it gives me the usual UUID of player (player) is (UUID) but thats it. Nothing else. 
My config can be found here http://pastebin.com/ZNbBGQ1f
Thanks :)

**Comment by confuser** [comment]
It's most likely attempting to connect to the database but failing. BM will eventually timeout, and disable itself.

This is a MySQL database connection issue, and not an issue within BanManager itself.

**Comment by minegame30** [comment]
Just to further the previous reply, turns out my host has had a software issue which was blocking all inbound and outbound traffic for MySQL. 
If you are having this issue, use [This online database connection tester](http://www.rainbowspuppiessunshine.com/tools/dbtest/) to determine if you can connect to your database from outside the localhost (which should give you an idea if plugins can)
