### ISSUE TITLE
Rollback actions

### ISSUE THREAD

**Issue by confuser** [BanManagement/BanManager#224]
If a player with BM perms goes rogue, it would be helpful to have `/bmrollback <player> <timeDiff> [bans/mutes/warnings]` command to silently undo their actions as if they never happened.

This may have syncing problems though, if one server has already synced the ban into memory, but the unban record is never created, how will BM know it should be wiped from memory.

**Comment by EvilOlaf** [comment]
*like*

**Comment by d1One** [comment]
This would have saved my life. You an however just backup your mysql databases once in a wile.
