### ISSUE TITLE
Errors on ban (1.8.3 - offline server)

### ISSUE THREAD

**Issue by kangarko** [BanManagement/BanManager#236]
Hello,

I got database errors when banning a player:
http://pastebin.com/j9kCC8qn

What in the world is wrong with that entry, do you have any idea?
The player is registered correctly in the table "bm_players"

**Comment by confuser** [comment]
What version of BanManager are you running?

**Comment by kangarko** [comment]
Developer build  #110

**Comment by confuser** [comment]
Looks like a player with that UUID already exists in your table, and you have multiple players with the same name. Most likely a case sensitive issue.

Can you do a search for Dionne1999 within your bm_players table and post the results here?

**Comment by kangarko** [comment]
Oh, sorry I did not do a research for that. There were three username with different case.

74d8234bcab53f53b1cf6afb143f9dff 	Dionne1999 	2988974443 	1429885421
ac8b462150983365be1321995ba758a2 	dIONNE1999 	3578900713 	1426950479
4ef6115efac24f07bf009c968c63016a 	Dionne1999 	2130706433 	1429278610

Notice I am running an offline mode server, to which extend is offline mode supported by this plugin?

**Comment by confuser** [comment]
This plugin supports very little in terms of offline mode, only the very basics.

In terms of online mode, it wouldn't be possible to have this situation arise.

For a fix for you, would you consider those 3 names differing in case different people or the same?

**Comment by kangarko** [comment]
I do not really know how the plugin created two usernames with the same name. I can remove all of them since it will be recreated when the player joins.

Thanks for you help. Maybe you can add some check like this for offline-mode servers.

**Comment by confuser** [comment]
So would you consider  Dionne1999 and  dIONNE1999 the same player?

**Comment by kangarko** [comment]
Of course case does not matters.

**Comment by confuser** [comment]
Build 112 should prevent this from occurring again with a fresh dataset.

**Comment by kangarko** [comment]
Thank you so much! One of the best plugins out there for ban management.
