### ISSUE TITLE
Enhancement: List "noted" players

### ISSUE THREAD

**Issue by EvilOlaf** [BanManagement/BanManager#237]
I really like the feature to add notes to players and inform users with the proper permission that users with a note joining the server.

To improve this I suggest to add a feature to list all players with notes which are currently online or maybe add a switch to allow listing all players (offline and online) with notes.

The background is, that if a "noted" player joins staff will be informed, but if a "noted" player is online and a staff member joins after he does not know that there is a player with a note online.

It would also be nice if staff members could delete player notes without the need of the `bm.command.clear` node, because this would allow to clear ALL player records.

Best regards
Olaf

**Comment by confuser** [comment]
- [ ] Separate bm.command.clear into separate permissions for further control
- [ ] Allow /notes to show notes of all online players, `bm.command.notes.online`
