### ISSUE TITLE
BanManager mysql error

### ISSUE THREAD

**Issue by KreWw** [BanManagement/BanManager#238]
Whenever I try to globally ban this error appears!

22.04 09:58:50 [Server] WARN ... 10 more
22.04 09:58:50 [Server] WARN at me.confuser.banmanager.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
22.04 09:58:50 [Server] WARN at me.confuser.banmanager.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:170)
22.04 09:58:50 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
22.04 09:58:50 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
22.04 09:58:50 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
22.04 09:58:50 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
22.04 09:58:50 [Server] WARN at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
22.04 09:58:50 [Server] WARN at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
22.04 09:58:50 [Server] WARN at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
22.04 09:58:50 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
22.04 09:58:50 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
22.04 09:58:50 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
22.04 09:58:50 [Server] WARN at com.mysql.jdbc.Util.getInstance(Util.java:382)
22.04 09:58:50 [Server] WARN at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
22.04 09:58:50 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
22.04 09:58:50 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
22.04 09:58:50 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
22.04 09:58:50 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
22.04 09:58:50 [Server] WARN Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '*L\x1ET\x90rA<\x95jO3\xF1d\x16\xFD' for key 'bm_player_bans_player_idx'
22.04 09:58:50 [Server] WARN at java.lang.Thread.run(Thread.java:745)
22.04 09:58:50 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
22.04 09:58:50 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
22.04 09:58:50 [Server] WARN at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
22.04 09:58:50 [Server] WARN at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
22.04 09:58:50 [Server] WARN at me.confuser.banmanager.runnables.ExternalBanSync.run(ExternalBanSync.java:37)
22.04 09:58:50 [Server] WARN at me.confuser.banmanager.runnables.ExternalBanSync.newBans(ExternalBanSync.java:72)
22.04 09:58:50 [Server] WARN at me.confuser.banmanager.storage.PlayerBanStorage.ban(PlayerBanStorage.java:109)
22.04 09:58:50 [Server] WARN at me.confuser.banmanager.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310)
22.04 09:58:50 [Server] WARN at me.confuser.banmanager.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450)
22.04 09:58:50 [Server] WARN at me.confuser.banmanager.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135)
22.04 09:58:50 [Server] WARN at me.confuser.banmanager.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
22.04 09:58:50 [Server] WARN java.sql.SQLException: Unable to run insert stmt on object me.confuser.banmanager.data.PlayerBanData@282cb13d: INSERT INTO `bm_player_bans` (`player_id` ,`reason` ,`actor_id` ,`created` ,`updated` ,`expires` ) VALUES (?,?,?,?,?,?)

**Comment by confuser** [comment]
Please ensure you are running BanManager v5.3.0
