### ISSUE TITLE
Banall error

### ISSUE THREAD

**Issue by KreWw** [BanManagement/BanManager#241]
Hello when ever I banall it displays this message:(have the latest banmanager on all servers)
26.04 08:00:04 [Server] WARN ... 10 more
26.04 08:00:04 [Server] WARN at me.confuser.banmanager.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
26.04 08:00:04 [Server] WARN at me.confuser.banmanager.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:170)
26.04 08:00:04 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
26.04 08:00:04 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
26.04 08:00:04 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
26.04 08:00:04 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
26.04 08:00:04 [Server] WARN at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
26.04 08:00:04 [Server] WARN at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
26.04 08:00:04 [Server] WARN at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
26.04 08:00:04 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
26.04 08:00:04 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
26.04 08:00:04 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
26.04 08:00:04 [Server] WARN at com.mysql.jdbc.Util.getInstance(Util.java:382)
26.04 08:00:04 [Server] WARN at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
26.04 08:00:04 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
26.04 08:00:04 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
26.04 08:00:04 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
26.04 08:00:04 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
26.04 08:00:04 [Server] WARN Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'Q\x0FIy\xD4\xCCJ\x8D\xB6e\x94cW-0\x99' for key 'bm_player_bans_player_idx'
26.04 08:00:04 [Server] WARN at java.lang.Thread.run(Thread.java:745)
26.04 08:00:04 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
26.04 08:00:04 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
26.04 08:00:04 [Server] WARN at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
26.04 08:00:04 [Server] WARN at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
26.04 08:00:04 [Server] WARN at me.confuser.banmanager.runnables.ExternalBanSync.run(ExternalBanSync.java:37)
26.04 08:00:04 [Server] WARN at me.confuser.banmanager.runnables.ExternalBanSync.newBans(ExternalBanSync.java:72)
26.04 08:00:04 [Server] WARN at me.confuser.banmanager.storage.PlayerBanStorage.ban(PlayerBanStorage.java:109)
26.04 08:00:04 [Server] WARN at me.confuser.banmanager.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310)
26.04 08:00:04 [Server] WARN at me.confuser.banmanager.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450)
26.04 08:00:04 [Server] WARN at me.confuser.banmanager.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135)
26.04 08:00:04 [Server] WARN at me.confuser.banmanager.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
26.04 08:00:04 [Server] WARN java.sql.SQLException: Unable to run insert stmt on object me.confuser.banmanager.data.PlayerBanData@54b7a826: INSERT INTO `bm_player_bans` (`player_id` ,`reason` ,`actor_id` ,`created` ,`updated` ,`expires` ) VALUES (?,?,?,?,?,?)
26.04 08:00:04 [Server] INFO connorcod12 has been permanently banned by KreWw for Dont like it dont play it.

**Comment by EvilOlaf** [comment]
Propably related to https://github.com/BanManagement/BanManager/commit/2f67cd40d0db2d011dc93d8d5bc1cc7bcc3f9ba7

**Comment by confuser** [comment]
Please ensure you are running v5.3.0. If you are, feel free to re-open this issue.
