### ISSUE TITLE
mysql banmanager error

### ISSUE THREAD

**Issue by Eimantux** [BanManagement/BanManager#242]
Hey.
So i'm using v4.0 and triend 5.3 versions of ban manager, and it's always shows me error
http://pastebin.com/ZfYjsVKB
It connected to mysql database becouse it created tables but in 1-2minutes always shows error
I was using older versions, and shows no errors ._.

**Comment by EvilOlaf** [comment]
Make sure you set the privileges for your MySQL user and database properly.
Also it seems like you got timeouts from your database. Check the connection to your database server.
Do you use a fairly recent version of MySQLd like 5.5?

**Comment by Eimantux** [comment]
I set privileges with % symbol. On 3.0v its all okey, but with newer, its shows this error. Also how to check mysql version

**Comment by EvilOlaf** [comment]
Well I don't know on which way you set your privileges but usually you `GRANT ALL` and not `GRAND %` to a user/database. I am not sure if this is the same ^^

You either may ask your provider which version they're using or just use `mysql -v` or similar in command line.

**Comment by Eimantux** [comment]
Version of mysql is 5.5.32

**Comment by confuser** [comment]
Your database connection is timing out. This is not a plugin issue, but rather a server setup issue.

Are you using managed hosting? If so, contact them with regards to your connection problems.

**Comment by Eimantux** [comment]
But the problem is, older version of banmanager is working, newe - no

**Comment by Eimantux** [comment]
Newer*

**Comment by confuser** [comment]
v5+ uses pooled connections. Previous versions used a single connection. You may simply have reached the maximum number of connections your MySQL service allows.

**Comment by Eimantux** [comment]
Ooooooooooooooooooooooh
Thanks
