### ISSUE TITLE
can not ban

### ISSUE THREAD

**Issue by Elioz** [BanManagement/BanManager#243]
Hi,
after banning a player, he still can join,
why is that? (spigot 1.8.3, plugin - the newest version)

thanks

**Comment by EvilOlaf** [comment]
Any console output?

**Comment by Elioz** [comment]
http://pastebin.com/wTG4xc4c

thats an offline-mode server, doesn't it matter?

**Comment by EvilOlaf** [comment]
Does BanManager create new tables in your database each time you restart the server?
Also it is in general important that network services on different machines run the very same time:
`[05:07:45] [Server thread/ERROR]: [BanManager] The time on your server and MySQL database are out by 22 seconds, this may cause syncing issues.`
So either set the server time by yourself with `ntpdate` or blame your provider to do their job properly.

Offline mode COULD be a reason, but this question has to be answered by a developer.

**Comment by confuser** [comment]
If you're running in offline mode, they can simply change their name and re-join.

If you're going to run an offline server, you must be aware of the risks.

**Comment by Elioz** [comment]
thats not the issue, I checked this on real banned player
you see in the logs name is maor2013
after I banned him, I tried to connect with his username and I connected

**Comment by confuser** [comment]
I can tell you for a fact that is the issue. I also do not offer support for offline mode servers. Try using the latest developer build which contains a fix for case differences in names for offline servers.

**Comment by Elioz** [comment]
latest is 5.3.0?

**Comment by confuser** [comment]
The latest is v5.4-0-SNAPSNOT which can be found over at http://ci.frostcast.net/job/BanManager/

Ensure you check the changes, as there are some breaking changes in terms of permissions.

You'll want Build 112 at the very least

http://ci.frostcast.net/job/BanManager/changes

**Comment by Elioz** [comment]
Thank you,
good to know that there is jenkis page to this plugin, soon I will turn off the offline mode
sick tierd from these cracked players, I hope the plugin will work because the banned list on the website is very usefull
