### ISSUE TITLE
Clarification on timeLimits

### ISSUE THREAD

**Issue by c0wg0d** [BanManagement/BanManager#247]
In your config, there's an option for timeLimits via group.  Does this mean that whatever value is set here is the maximum duration they can ban someone?  For example, would this allow groupa to ban a max of 7 days and groupb to ban a max of 1 day?

timeLimits:
  playerBans:
    groupa: 7d
    groupb: 1d

**Comment by confuser** [comment]
Correct. However, to reduce dependencies, it is based on a permission name, rather than the group the player is assigned via another plugin.

In your case to enforce those limits, they would need `bm.timelimit.playerBans.groupa` or `bm.timelimit.playerBans.groupb` permissions
