### ISSUE TITLE
Error retrieving name

### ISSUE THREAD

**Issue by kangarko** [BanManagement/BanManager#249]
Hello,

I am once upon a while getting following error:
http://pastebin.com/ULE6Rijs

this appeared just after the server started on my name, which is premium
PS: Server is in offline mode.

Spigot 1.8.3 and plugin build 126

**Comment by confuser** [comment]
If you're running in offline mode, ensure your `onlineMode` within your conifg.yml is set to false.

**Comment by kangarko** [comment]
I set it to false long time ago, but somehow it was on true. Thanks!

**Comment by kangarko** [comment]
The error is still there :( (I restarted the server and ensured the config is to false)
