### ISSUE TITLE
Beautify default messages

### ISSUE THREAD

**Issue by confuser** [BanManagement/BanManager#251]
Rather ugly, many need changing.

PR/suggestions welcome.

**Comment by EvilOlaf** [comment]
Do you need sugguestions for particular messages or in general?

**Comment by confuser** [comment]
Both really.

**Comment by EvilOlaf** [comment]
I'll take a look into later.

**Comment by EvilOlaf** [comment]
After review I think the default messages doing their job pretty well. The logic is correct and all important information are included. 
Should there be more colours or such stuff?

**Comment by confuser** [comment]
Yes, I think more colours would be nicer. I know of a few staff at Frostcast who aren't fond of the white text.

**Comment by EvilOlaf** [comment]
I see...

**Comment by EvilOlaf** [comment]
So this seems to be done.... For now at least :P
