### ISSUE TITLE
HeroicRebuke/AdminNotes Importer

### ISSUE THREAD

**Issue by LukvonStrom** [BanManagement/BanManager#252]
Hello,
we would like to use your System completely with Warns and Notes but we need a AdminNotes and a HeroicRebuke Importer to keep our Data and import it..

**Comment by Kakifrucht** [comment]
Write one? I'm sorry, but what your asking for seems very specific and if you really want to use it, simply write one.

**Comment by confuser** [comment]
Are you referring to http://dev.bukkit.org/bukkit-plugins/adminnotes/ and http://dev.bukkit.org/bukkit-plugins/heroicrebuke-reloaded/ ?

Can you please provide the data structure for both plugins, similar to how the creator of #254 has done their ticket?

**Comment by LukvonStrom** [comment]
Yes, I reffered to the posted Links With Php MyAdmin I exported the Db structures
HeroicRebuke/Warnings:
http://prntscr.com/71i1dg

AdminNotes:
http://prntscr.com/71i2ii

**Comment by confuser** [comment]
Can you please list out what each field is, some like ack_time are not obviously clear as to what they refer to.

**Comment by LukvonStrom** [comment]
HeroicRebuke:
ack_time = Time when acknowledged
ack= Acknowledged 0/1
code= Acknowledge Code

AdminNotes:
notify= Should the online staff be notified 0/1

**Comment by confuser** [comment]
What does acknowledge code mean? Like I said, please follow the structure of #254, I've never used any of these plugins and have no idea what each of the fields/terms mean. Be explicit in terms of what they would be in BanManager.

**Comment by LukvonStrom** [comment]
With some excel and phpmyadmin magic is everything possible ! :)
