### ISSUE TITLE
Player not found... Again (last I hope)

### ISSUE THREAD

**Issue by JohOply** [BanManagement/BanManager#253]
Hi !

This ticket is following one : #245 
I uploaded BanManager v5.4.0 build 121 on my 1.7.10 Offline Spigot Server.

You said me : "If you are running in true offline mode, ensure your config.yml node onlineMode is set to false.
BanManager will otherwise assume it is in online mode and request names from Mojang"

I understand that, and it was already set to false... but i think there is really a problem on my server... 

During the up from 4.x to 5.4.0, in my config, the option "online" was set to "true". Today, even if the option is set to "false", there is the same problem that i explain in tickets #240 & #245. The mistake during the update can be the problem ? If this is effectivly the problem, how can i fix it ? 

Sorry again for my probably bad english, isn't my native language. I really don't want to do waste of time to anybody, i juste want to fix problems on my server and help you to improve your plugin, in case anybody else has the same bug !

Thanks for reading

**Comment by confuser** [comment]
If you converted from v4 to v5 with onlineMode set to true in the config, your data storage will be incorrect, as it would have attempted to retrieve the UUIDs from Mojang.

To resolve this, re-do the conversion, ensuring `onlineMode` is set to false.
