### ISSUE TITLE
Feature Request - Ban Manager import from GeSuit outdated plugin

### ISSUE THREAD

**Issue by mcraftpete** [BanManagement/BanManager#254]
Hi,
I am really keen to change to ban manager from gesuit which is outdated and relies heavily on bungee which is not a good way for it to function. The only thing stopping me is the import from old files.
The gesuit format is Table name bans
banned_playername    varchar(100)
banned_uuid      varchar(100)
banned_ip     varchar(15)
banned_by    varchar(100)
reason   varchar(255)
type    varchar(100)
banned_on     datetime
banned_until    datetime

This is stored on sql but I could easily create a an excel or tab delaminated text file to import , I am also wondering how it would work with tempbans which are stored in same table ?

I do notice my uuids store as like this 7daf76f5cb0f4669914c14c2b5300c0a
whereas uuid is stored in code type form in yours like squares etc ? ~`��1�M|��(��)

'Type' column can be ban , tempban or unban
Ban is naturally a perm ban , tempban has a time in banned_until 2014-10-08 09:12:08
We also have unban which is when the ban has expired , some players have multiple enties in this table so it shows their history.
Banned_ip is normally null , but an ip ban will show the ip address here.

It would be awesome for you to add this feature as there is bound to be other gesuit owners that want to transfer at some point , my banlist is 9800 ish

I honestly don't mind it being from file and even in a different layout as I can export them to whats required.

I will also donate for this feature as I am very keen to have it :)
I also have Skype : mcraftpete if you need more information or I can check here as often as I can.

**Comment by confuser** [comment]
Thank you for the very detailed request, it'll certainly help.

With regards to time frames, I won't probably be able to get it done until next week at the earliest, plus it'll require a rather large rewrite of the conversion system so I can plug in other converters more easily.

**Comment by mcraftpete** [comment]
ok that would be awesome , thanks for the quick response , I am keen for it as gesuit has started causing memory leaks on more recent bungee builds , being bungee side is always a risky way to do it in my opinion , should never have too many plugins on your mail link to all your servers :)

**Comment by confuser** [comment]
@mcraftpete Can you provide me with an example .sql dump for me to test with please, as well as an example config file from GeSuit that contains the database connection details

**Comment by mcraftpete** [comment]
Sorry I only just see this message  I did reply to private chat but I can add here as well ...

ok so my database layout is ..
CREATE TABLE IF NOT EXISTS `bans` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `banned_playername` varchar(100) DEFAULT NULL,
  `banned_uuid` varchar(100) DEFAULT NULL,
  `banned_ip` varchar(15) DEFAULT NULL,
  `banned_by` varchar(100) DEFAULT NULL,
  `reason` varchar(255) DEFAULT NULL,
  `type` varchar(100) DEFAULT NULL,
  `banned_on` datetime NOT NULL,
  `banned_until` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=22197 ;

and some sample bans are here...
http://pastebin.com/tFbm3cPw

Hope this helps you , my Skype if needed is : mcraftpete 
Thanks fro your help I am keen to get onto BanManager :)

**Comment by confuser** [comment]
Can you please provide the sample data in SQL format (it should contain INSERT INTO queries) please and an example config file from gesuit,

**Comment by confuser** [comment]
Closing due to lack of response/information.
