### ISSUE TITLE
Feature Reuest ./banhistory player

### ISSUE THREAD

**Issue by mcraftpete** [BanManagement/BanManager#255]
Hi,
I liked this feature from another plugin and I can see that you keep history of players bans and don't delete each one , so I was wondering if there was a way to view the players last 10 without doing it from the website ?
/banhistory player
/mutehistory player
/warnhistory player

Thanks :)

**Comment by EvilOlaf** [comment]
Like this? https://github.com/BanManagement/BanManager/issues/244
