### ISSUE TITLE
Plugin Disabled [Red] - Spigot 1.8.3 -R0.1 SNAPSHOT

### ISSUE THREAD

**Issue by DirectGamerHD** [BanManagement/BanManager#257]
Are there any current builds that support the above version of Spigot? I noticed that the latest upload was for a 1.7.10 build, but mentioned that it was also for 1.8.3. 

Is there a misunderstanding? Are there any current builds my version? 

http://i.gyazo.com/9faa1e116b0b1b2a247b49afc76ec752.png

http://i.gyazo.com/43081339b49196de0d7163499b5d5299.png

**Comment by theshadyonehd** [comment]
is there any errors?

**Comment by tr0nlegacy2012** [comment]
are your sql databases properly set up?

**Comment by DirectGamerHD** [comment]
Hm... it seems to require a local database. Why is that? I thought I could use an external if I wanted?

**Comment by confuser** [comment]
Local and external are simply to do with syncing, and not where your database is physically located.

As others have said, check your console, BM will disable itself if it finds any problems.
