### ISSUE TITLE
PlayerLoginEvent

### ISSUE THREAD

**Issue by Agazed** [BanManagement/BanManager#259]
Getting this error when a player joins. Using 5.4.0 and Spigot 1.8.3

http://pastebin.com/11MUupJ3

**Comment by confuser** [comment]
Are you running behind bungeecord?

**Comment by Agazed** [comment]
No I am using Spigot 1.8.3 like I said. I typed /version at the end of this log http://pastebin.com/GCR38mhB

**Comment by Agazed** [comment]
Found the issue. Had to do something with my messages file.
