### ISSUE TITLE
Issues with warning

### ISSUE THREAD

**Issue by Kakifrucht** [BanManagement/BanManager#260]
Hello, I get following stacktrace when trying to warn a player: http://pastebin.com/yFmWnfPk
I'm on latest version from BukkitDev.
Everything else seems to work.

Probably just final String reason = CommandUtils.getReason(2, args); to getReason(1, args);

**Comment by Kakifrucht** [comment]
Temporary fix: /warn Player . Reason, to make sure that array[2] contains the reason.

**Comment by confuser** [comment]
As of v5.3.0 it should be perfectly fine, yes

**Comment by Kakifrucht** [comment]
Worked perfectly, thank you!
