### ISSUE TITLE
Too many mysql connections

### ISSUE THREAD

**Issue by c0wg0d** [BanManagement/BanManager#261]
Mysql has not changed.  I just updated from 5.1.1 to 5.4.0 and got the following:

http://pastebin.com/TVAhXsK8

**Comment by confuser** [comment]
Your MySQL database is saying it has too many connections, and is refusing the connection from the plugin.

This is not a plugin issue, and is a server setup issue.

Please check your MySQL configuration and raise the max connections if necessary. Alternatively, take a look through your plugins to see if you have any others that use MySQL which could be opening too many connections.

**Comment by c0wg0d** [comment]
I downgraded back to 5.1.1 and the issue is resolved.  This was the only change I made, no mysql config changes, no other plugin changes.  The problem appears to be with BanManager.

**Comment by confuser** [comment]
There have been no changes in the way BanManager manages its connections to the database. Lower your maxConnection in the config.

**Comment by c0wg0d** [comment]
I dropped my maxConnections down to 2 and no longer have the issue with the latest version 5.5.0.  You can close this.
