### ISSUE TITLE
Column 'actor_id' cannot be null

### ISSUE THREAD

**Issue by Okane84** [BanManagement/BanManager#263]
Today two moderators of mine were unable to tempban anyone, this is one sample log: http://pastebin.com/myveyVx8

apparently the error was caused by a wrong mysql insert query.
moderators were probably in vanish, using vanishnopacket.

thanks

**Comment by Kakifrucht** [comment]
I'm not completely positive about this, but a chat moderator of mine had the same error. He reconnected and it worked, so I'm not sure.

**Comment by Okane84** [comment]
Mine too but this time reconnect didn't work

**Comment by confuser** [comment]
This only used to happen when the plugin was reloaded, either via /reload or via a plugin manager.

Were either used?

**Comment by Okane84** [comment]
No, i do not use to reload any plugin.

**Comment by confuser** [comment]
Can I get a list of plugins you have running please?

**Comment by Kakifrucht** [comment]
This might be why it happened on my server, it didn't happen again so far.

**Comment by Okane84** [comment]
GroupManager, NetherRoofProtect, WorldEdit, ChatControl, Vault, BlogMOTD, WorldGuard, Reporter, WelcomeTitle, dynmap, CoreProtect-Anti-Xray, Graves, CoreProtect, BukkitSpeak, Parties, BanManager, ClearLag, DeathMessages, ProtocolLib, HolographicDisplays, BlockNotif, SuperTrails, Essentials, NoCheatPlus, EssentialsProtect, VanishNoPacket, NCore, EssentialsAntiBuild, HomeSpawnPlus, NTheEndAgain, Statistics

**Comment by confuser** [comment]
Perhaps it's VanishNoPacket, however, the only way this would occur is if it interfered with the PlayerJoinEvent. I've just taken a quick look at the source code for it, but can't see anything obvious.

**Comment by EvilOlaf** [comment]
Using VNP and BM too and banned a couple of players vanished but works well.

**Comment by Okane84** [comment]
I always use vanishnopacket to performe bans, the problem occurs
occasionally, and usually a rejoin mysteriously seems to solve it :p

**Comment by EvilOlaf** [comment]
Weird. 
Unfortunately we can not ask mbaxter in this case because he refuses to support Spigots version of CraftBukkit and Spigot itself for comprehensible reason.

**Comment by confuser** [comment]
What Spigot version are you running?

**Comment by confuser** [comment]
Should be fixed in latest developer build
