### ISSUE TITLE
Question: Does BanManager have an IRC Channel?

### ISSUE THREAD

**Issue by EvilOlaf** [BanManagement/BanManager#264]
Lots of more ore less known plugins offering an IRC channel (especially on Esper.net) for instant support and various talking.
Does the BanManagement project offer such a channel or do you plan to do so?

**Comment by confuser** [comment]
We don't currently. I'm not overly fond of IRC, but someone can set one up if they wish to. However, I will still be using GitHub Issues for direct support.

**Comment by frdmn** [comment]
I love and actively use IRC als well. I can setup an channel as well as a web IRC client today or later tomorrow!



—

**Comment by EvilOlaf** [comment]
Nice

**Comment by frdmn** [comment]
Channel and a Hubot bot instance is up and running:

* irc.esper.net
* #BanManager

You can also use the Web IRC chat if you dont have a native client:

http://webchat.esper.net
