### ISSUE TITLE
BanAll and UnBanAll error

### ISSUE THREAD

**Issue by KreWw** [BanManagement/BanManager#266]
Before you ask. I am using the latest banmanagement. Freshly downloaded a day ago the 5.4.1 version uploaded it on all servers, configured the config for the external and local on all servers. I even reset the database.

Ok when I ban all this displays:

11.05 12:06:45 [Server] WARN ... 10 more
11.05 12:06:45 [Server] WARN at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
11.05 12:06:45 [Server] WARN at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:170)
11.05 12:06:45 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
11.05 12:06:45 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
11.05 12:06:45 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
11.05 12:06:45 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
11.05 12:06:45 [Server] WARN at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
11.05 12:06:45 [Server] WARN at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
11.05 12:06:45 [Server] WARN at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
11.05 12:06:45 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
11.05 12:06:45 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
11.05 12:06:45 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
11.05 12:06:45 [Server] WARN at com.mysql.jdbc.Util.getInstance(Util.java:382)
11.05 12:06:45 [Server] WARN at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
11.05 12:06:45 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
11.05 12:06:45 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
11.05 12:06:45 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
11.05 12:06:45 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
11.05 12:06:45 [Server] WARN Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '\xD8\xD5\xA9#{ C\xD8\x88;\x11P\x14\x8DiU' for key 'bm_player_bans_player_idx'
11.05 12:06:45 [Server] WARN at java.lang.Thread.run(Thread.java:745)
11.05 12:06:45 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
11.05 12:06:45 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
11.05 12:06:45 [Server] WARN at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
11.05 12:06:45 [Server] WARN at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71)
11.05 12:06:45 [Server] WARN at me.confuser.banmanager.runnables.ExternalBanSync.run(ExternalBanSync.java:37)
11.05 12:06:45 [Server] WARN at me.confuser.banmanager.runnables.ExternalBanSync.newBans(ExternalBanSync.java:72)
11.05 12:06:45 [Server] WARN at me.confuser.banmanager.storage.PlayerBanStorage.ban(PlayerBanStorage.java:110)
11.05 12:06:45 [Server] WARN at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310)
11.05 12:06:45 [Server] WARN at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450)
11.05 12:06:45 [Server] WARN at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135)
11.05 12:06:45 [Server] WARN at me.confuser.banmanager.internal.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
11.05 12:06:45 [Server] WARN java.sql.SQLException: Unable to run insert stmt on object me.confuser.banmanager.data.PlayerBanData@6dec8a4b: INSERT INTO `bm_player_bans` (`player_id` ,`reason` ,`actor_id` ,`created` ,`updated` ,`expires` ) VALUES (?,?,?,?,?,?)
11.05 12:06:45 [Server] INFO Test has been permanently banned by Fanikz for Testing purpose

And when I try to unbanall this appears:

11.05 12:10:04 [Server] INFO ... 15 more
11.05 12:10:04 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
11.05 12:10:04 [Server] INFO at me.confuser.banmanager.commands.external.UnbanAllCommand.onCommand(UnbanAllCommand.java:41) ~[?:?]
11.05 12:10:04 [Server] INFO at me.confuser.banmanager.bukkitutil.Message.set(Message.java:30) ~[?:?]
11.05 12:10:04 [Server] INFO at me.confuser.banmanager.bukkitutil.Message.replace(Message.java:24) ~[?:?]
11.05 12:10:04 [Server] INFO Caused by: java.lang.NullPointerException
11.05 12:10:04 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
11.05 12:10:04 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
11.05 12:10:04 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
11.05 12:10:04 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
11.05 12:10:04 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
11.05 12:10:04 [Server] INFO at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
11.05 12:10:04 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_40]
11.05 12:10:04 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_40]
11.05 12:10:04 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
11.05 12:10:04 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
11.05 12:10:04 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
11.05 12:10:04 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
11.05 12:10:04 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
11.05 12:10:04 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
11.05 12:10:04 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
11.05 12:10:04 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
11.05 12:10:04 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'unbanall' in plugin BanManager v5.4.1
11.05 12:10:04 [Server] ERROR null

**Comment by confuser** [comment]
Strange, this should have been fixed a few versions ago.
