### ISSUE TITLE
Java Crash with Banmanager

### ISSUE THREAD

**Issue by CurePindal** [BanManagement/BanManager#270]
It seems that BanManager caused a Java crash of our server.
Unfortunatly a bit too much mumbo jumbo for me to fully understand. Does anybody else understand what happened?

Full Java Crash log: http://pastebin.com/R4HxmNws

[error occurred during error reporting (printing register info), id 0xb]
Stack: [0x00007f1eabeff000,0x00007f1eac000000],  sp=0x00007f1eabffde60,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
v  ~RuntimeStub::slow_subtype_check Runtime1 stub
j  me.confuser.banmanager.storage.PlayerStorage$1.run()V+4
j  org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run()V+4
j  org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run()V+53
j  java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent

**Comment by confuser** [comment]
This is most likely a hardware issue rather than anything BanManager has done.
