### ISSUE TITLE
Error sending to database?

### ISSUE THREAD

**Issue by minegame30** [BanManagement/BanManager#273]
Hello,
I tried to kick a player today, and I received an error when doing so. I am sure I have all of the configurations setup correctly. See the error below (read from bottom up as that's how my console works).
Thanks :)

15.05 18:11:05 [Server] WARN ... 9 more
15.05 18:11:05 [Server] WARN at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
15.05 18:11:05 [Server] WARN at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:170)
15.05 18:11:05 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
15.05 18:11:05 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
15.05 18:11:05 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
15.05 18:11:05 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
15.05 18:11:05 [Server] WARN at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
15.05 18:11:05 [Server] WARN at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
15.05 18:11:05 [Server] WARN at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
15.05 18:11:05 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
15.05 18:11:05 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
15.05 18:11:05 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
15.05 18:11:05 [Server] WARN at com.mysql.jdbc.Util.getInstance(Util.java:382)
15.05 18:11:05 [Server] WARN at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
15.05 18:11:05 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
15.05 18:11:05 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
15.05 18:11:05 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
15.05 18:11:05 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
15.05 18:11:05 [Server] WARN Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'player_id' cannot be null
15.05 18:11:05 [Server] WARN at java.lang.Thread.run(Thread.java:745)
15.05 18:11:05 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
15.05 18:11:05 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
15.05 18:11:05 [Server] WARN at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
15.05 18:11:05 [Server] WARN at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
15.05 18:11:05 [Server] WARN at me.confuser.banmanager.commands.KickCommand$1.run(KickCommand.java:74)
15.05 18:11:05 [Server] WARN at me.confuser.banmanager.storage.PlayerKickStorage.addKick(PlayerKickStorage.java:26)
15.05 18:11:05 [Server] WARN at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310)
15.05 18:11:05 [Server] WARN at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450)
15.05 18:11:05 [Server] WARN at me.confuser.banmanager.internal.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135)
15.05 18:11:05 [Server] WARN at me.confuser.banmanager.internal.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
15.05 18:11:05 [Server] WARN java.sql.SQLException: Unable to run insert stmt on object me.confuser.banmanager.data.PlayerKickData@d88dcc: INSERT INTO `bm_player_kicks` (`player_id` ,`reason` ,`actor_id` ,`created` ) VALUES (?,?,?,?)
15.05 18:11:05 [Server] INFO An error occured whilst attempting to perform that command. Please check the console for the error
15.05 18:11:05 [Server] INFO Mangle_Girl527 has been kicked by Console for Kicked due to Test Kick

**Comment by confuser** [comment]
What version are you using? Has the server been reloaded or a plugin manager been used to reload banmanager?

**Comment by minegame30** [comment]
Hi, 
Using the latest version (5.4.1) and nope, reload is disabled throughout my entire network. We do not have any plugin managers which could have reloaded them.
Thanks :)

**Comment by confuser** [comment]
This is caused when a player doesn't have their PlayerData pulled into memory on join. Do you have any plugins other than BanManager that deny players from joining?

**Comment by minegame30** [comment]
Nope, not at all.

Well, we use essentials, but I believe the banning system in essentials is disabled when another plugin takes over (IE banmanager).
However, im not sure if this would have an effect...

**Comment by confuser** [comment]
Are you still being affected by this issue?

**Comment by minegame30** [comment]
Yep, still getting this error on a regular basis... :/

Date: Tue, 9 Jun 2015 02:20:47 -0700

**Comment by confuser** [comment]
Should be fixed in latest developer build
