### ISSUE TITLE
Not connection after 10 times timeout

### ISSUE THREAD

**Issue by Pigna** [BanManagement/BanManager#274]
Players unable to join server about once or twice a day.
Getting this in my console (as far as i was able to see it)
http://pastebin.com/bDX0LUek
Something about time out unable to connect after 10 attempts?
Host problem or able to fix codewise?

Way i fix the problem: Restart server. but after a few hours it happens again....

**Comment by confuser** [comment]
First, you need to turn off multicraft rate limiting as it's hiding a lot of the stack trace error.

And yes, it's a problem with your MySQL database dropping the connection.

**Comment by Pigna** [comment]
Suggestions on how to do that? IM with Freaze hosting. Don't know if im able to change things to multicraft itself?
