### ISSUE TITLE
BmAPI Issue

### ISSUE THREAD

**Issue by nokoa** [BanManagement/BanManager#279]
When using BmAPI like this
"CloseableIterator<PlayerBanRecord> b = BmAPI.getBanRecords(BmAPI.getPlayer(target));"

then doing

"b.close()"

The connection seems to remain open, am I doing something wrong, or is it a problem with BmAPI. How would I use it?>

**Comment by confuser** [comment]
By connection, do you mean database connection? BM uses a pool, so it'll open as many connections as the max limit in the config allows.

**Comment by confuser** [comment]
Closed due to lack of response
