### ISSUE TITLE
Enhance warnings

### ISSUE THREAD

**Issue by EvilOlaf** [BanManagement/BanManager#282]
Hey there,

I recently had a small discussion with one of my faithful players about warnings and that made me thinking about how to enhance this.

As it is for now a player keeps his warnings forever if no entitled person uses `/dwarn` or `/bmclear`.

My first idea was to either reverse the logic of dwarn so it will delete the oldest warning instead of the most recent one or enhance the `dwarn` command at all so that a specific warning can be deleted.
Like
`/bminfo -warns` (see https://github.com/BanManagement/BanManager/issues/244)
And then
`/dwarn 3` (for the 3rd warning after the recent one).

Another idea was to create a so called timed warning so there is a new command called `/tempwarn` and basically acts like a `tempban` or `tempmute`.

I am actually not sure how to handle the `warningActions` punishments at timed warnings. Either these could be split up in `permwarningActions` and `timedwarningActions` or use the same punishments for both. Need to think about a little further....assumed you like it :D

**Comment by confuser** [comment]
Well, temp warnings can already be achieved via cleanUp config node, but it's either an all are temporary or none kind of scenario. What sort of scenario would you require a temporary warning?

Perhaps a `-time` flag for /bmclear

I'm not too sure how to handle the deleting of specific records, hence why it's not a part of the plugin, and only within the web interface.

Ideally from my perspective a delete-esque command like `/bmclear warnings 120` where 120 is the id of the warning in the database would be very easy to implement, but not so user friendly as the player would need to know somehow of what the id is.

The problem with your /dwarn 3 idea, is if that player is warned after you've /bminfo'd them, you're going to end up deleting the wrong one.

**Comment by EvilOlaf** [comment]
Well I think it is at the discretion of each individual owner/staff to use a timed warning or not.
You can temporarily warn a player giving offense  but you don't want that the player is marked with this warning forever and also don't want to kick/ban/mute/whatever him. 
It is some kind like in real live. You need to go to the court and suspended sentence that can be basically seen as temporarily warning.

Hm isn't it possible to combine both the `dwarn x` and id in the database? Listing the warnings with `bminfo`will also show the unique id of each warning which can later on be used at `dwarn`.

**Comment by confuser** [comment]
The new `/bminfo` flags output the id of each record.

I'll be adding a new argument to the clear command, e.g. 
`/bmclear [type] [ids]`
`/bmclear banrecords 21 39 102`

**Comment by EvilOlaf** [comment]
Nice.

**Comment by confuser** [comment]
`/bmdelete <type> <ids>` has been added
