### ISSUE TITLE
Can't /bmifno other players

### ISSUE THREAD

**Issue by tr0nlegacy2012** [BanManagement/BanManager#286]
Have the following permissions:
    - bm.command.bminfo
    - bm.command.bminfo.playerstats
    - bm.command.bminfo.connection 
    - bm.command.bminfo.ipstats
    - bm.command.bminfo.alts
    - bm.command.bminfo.players

get "no permission" error when trying /bminfo [name]

**Comment by itismejoey** [comment]
I am also getting this issue. Works fine for OP'd players, but not when you have the permissions.

**Comment by EvilOlaf** [comment]
Add `bm.command.bminfo.others`

**Comment by confuser** [comment]
It's amazing how few people update their plugins blindly without reading the change logs.

**Comment by itismejoey** [comment]
Yes I updated blindly, because as you know from another comment that I had having errors, and might've missed one new perm in a books worth of new perms and change logs. So I will ignore that snarky comment and once again THANK YOU for your quick response and for making an awesome plugin.

**Comment by Kakifrucht** [comment]
You should never just update blindly ANYTHING AT ALL on a production server.

**Comment by itismejoey** [comment]
You don't have to get your panties all up in a wad there @kakifrucht. I tested while our server was down in maintenance mode anyways and only noticed I missed one perm when my mods couldn't look up players. Excuse me for working 50 hours a week plus running a server if I missed ONE PERM!

**Comment by Kakifrucht** [comment]
You are excused, I'm just saying that you shouldn't call what confuser said a snarky comment as I find it completely justified.

**Comment by itismejoey** [comment]
No and that's fine, I apologize for that as I read the comments shortly after waking up. I work in the coding (web) field so I totally understand where he comes from when people don't ready updates.

**Comment by confuser** [comment]
It seems I put .players instead of .others within the change log. Apologies. Thank you for bringing it to my attention. I've now corrected the plugin page on bukkit dev to list the correct permission.
