### ISSUE TITLE
Can't Login to admin panel

### ISSUE THREAD

**Issue by actionforgames** [BanManagement/BanManager#287]
Hi I am using iPage as host. I set Setting.php and Cache to CHMOD 777 and For some reason after I type Correct password and press Sing in it only refresh page. Then I have checked up Cache and I se "0" folder and "search" inside. Nothing else. I have PHP 5.3 (Well iPage is one of most used Hosting Services so It would be strange it something is worng with that one) So I think it have nothing to do with host. I am having 1.5.0 WEB GUI

**Comment by tr0nlegacy2012** [comment]
This is posted in the wrong area. I would advise closing this, and reposting in https://github.com/BanManagement/BanManager-WebUI/issues

**Comment by frdmn** [comment]
What @tr0nlegacy2012 said. This repository is dedicated for the Java plugin only :)

Feel free to reraise the issue in the proper repo:

https://github.com/BanManagement/BanManager-WebUI/issues
