### ISSUE TITLE
Bm import don't work

### ISSUE THREAD

**Issue by Kedarin** [BanManagement/BanManager#288]
I would update my spigot in 1.8.3 ban but manager does not work in 1.8.3.
So I wanted to import bans (/ bm import player) but nothing appears in my banned-players.json.

Would you have a solution for use in Ban manager 1.8.3 or import bans?

thank you,

**Comment by EvilOlaf** [comment]
BanManager works fine with Spigot 1.8.3?
I don't get it.

**Comment by confuser** [comment]
Check your logs.

As previously stated, BanManager works fine with 1.8.3+ of Spigot, and version changes won't affect the import feature, unless Mojang has changed the banned-players.json format.

**Comment by Kedarin** [comment]
It's good I managed to make it work in 1.8,
How to remove BanManager without unban everyone ?
