### ISSUE TITLE
warning actions seems not to work

### ISSUE THREAD

**Issue by Okane84** [BanManagement/BanManager#289]
Hi, i have set the warningActions to true like this:

warningActions:
  enabled: true
  actions:
    '10': tempban [player] 40m [reason]
    '1': kick [player] [reason]
    '2': kick [player] [reason]
    '3': kick [player] [reason]
    '4': tempmute [player] 1m [reason]
    '5': tempmute [player] 1m [reason]
    '6': tempban [player] 2m [reason]
    '7': tempban [player] 5m [reason]
    '8': tempban [player] 10m [reason]
    '9': tempban [player] 20m [reason]
    '11': tempban [player] 1d [reason]
    '12': ban [player] [reason]

no action taken at /warn 
this broke up some updates ago, i always use the last dev build.
no exceptions launched in console, and no errors. just doesn't execute actions.

**Comment by confuser** [comment]
So the player doesn't get kicked when you /warn them?

**Comment by Kakifrucht** [comment]
It's because he didn't update to the new WarningActions style.
Make it look like this:
  actions:
    '4':
    - 'Command'
    '5':
    - 'Command'
    '6':
    - 'Command'
    '7':
    - 'Command'

**Comment by Okane84** [comment]
OK I'll change the config like that and will report if it works. Is it possible to append two or more commands too?

**Comment by Kakifrucht** [comment]
Yes, that is exactly what is the change. You can just add as many commands as you want.

**Comment by EvilOlaf** [comment]
Interesting. Didn't notice too

**Comment by EvilOlaf** [comment]
Confirmed.
New syntax works as expected.
Maybe stupid question but does it support multiple commands this way?

**Comment by Okane84** [comment]
It works ad expected for me too. I gave 3 commands foreach level of warning and no problem at all. I think this is solved and we could close the issue :)

**Comment by EvilOlaf** [comment]
Nice, thanks for the answer.
