### ISSUE TITLE
BungeeCord/Offline mode UUID recognition

### ISSUE THREAD

**Issue by bugfroggy** [BanManagement/BanManager#291]
With Bungeecord and what I would assume is offline mode, this seems to be very buggy. For example, it says "<player> does not exist" when the player is offline, and sometimes on the website it shows as if players don't exist. For example, it'll show a Steve/Alex skin and show no info about the player even though they have a skin and have been punished before. I'd imagine there's other UUID bugs as well.

**Comment by confuser** [comment]
If you're running in offline mode, ensure onlineMode is set to false in the ban manager config.

**Comment by bugfroggy** [comment]
It is, but it still doesn't seem to be working.

**Comment by confuser** [comment]
What exactly do you mean, 'it's not working'? Please note that the offline support was made via a Pull Request. BM doesn't officially support offline mode servers.

**Comment by bugfroggy** [comment]
Whenever I try to ban an offline user, it spits the message that the user doesn't exist at me.
