### ISSUE TITLE
Tabbing online players

### ISSUE THREAD

**Issue by YoloxPanda** [BanManagement/BanManager#293]
you guys need to make that if we do /mute and press [tab] i will show the list to online players. Because it makes it all the people that are offline. This makes it really hard mute someone really fast

Quoted from one of my staff members

**Comment by confuser** [comment]
For anyone else who has this problem, this can be disabled in the config by setting `offlineAutoComplete` to false

**Comment by YoloxPanda** [comment]
yup! :D
