### ISSUE TITLE
Version Issue?

### ISSUE THREAD

**Issue by itismejoey** [BanManagement/BanManager#294]
Was starting to test Ban Manager on my test server with 1.8.6. This error keeps coming up in logs, then the server crashes. I am assuming that it is because of the version, but I wanted to throw it up here anyway. Maybe it can help in future versions.

http://pastebin.com/5Si78NGk

**Comment by confuser** [comment]
This was already fixed.

If you can't wait for the v5.5.0 release, you'll want builds 139 and above

http://ci.frostcast.net
