### ISSUE TITLE
BanManager lag Timings

### ISSUE THREAD

**Issue by Kedarin** [BanManagement/BanManager#296]
Hi,
I don't understand why BanManager get : 

       0.00%	 395.88%	  0.79 s	   197.94 ms	 0.0	       0.0k	    Task: TempBanCommand$1$1(Single)
       0.00%	 512.51%	  0.26 s	   256.26 ms	 0.0	       0.0k	    Task: BanCommand$1$1(Single)

My timings : http://timings.aikar.co/?url=11501230

Server version : version git-Spigot-870264a-0a645a2 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)
BanManager version : 5.4.1

Thank you,

**Comment by EvilOlaf** [comment]
```
Total: 81.331s (Ticks: 3253) - Sample Time: 164.851s  - Spigot Version: 870264a-0a645a2 (MC: 1.8.3)
Average Entities: 543.78 / 1,300.19 (41.82%) - Average Players: 18.08 - Average TPS: 19.73 - Server Load:   39.37%
Minecraft Total: 58.276 s	Pct: 35.35%
   Pct Total	Pct Tick	   Total	      Avg	 PerTick	     Count		Event
      12.15%	  12.31%	 20.03 s	     6.16 ms	 1.0	       3.3k	    Survival - tickEntities
      10.89%	  11.04%	 17.95 s	     5.52 ms	 1.0	       3.3k	    Plugin Scheduler
Learn More

       5.32%	   5.40%	  8.78 s	     2.70 ms	 1.0	       3.3k	    Survival - doTick



       0.00%	   0.01%	  0.00 s	     0.01 ms	 0.0	       0.0k	    CommandListener::onCommand(PlayerCommandPreprocessEvent)
       0.00%	   0.02%	  0.00 s	     0.01 ms	 0.0	       0.0k	    JoinListener::onPlayerLogin(PlayerLoginEvent)
       0.00%	   0.01%	  0.00 s	     0.01 ms	 0.0	       0.0k	    LeaveListener::onLeave(PlayerQuitEvent)
       0.00%	   0.01%	  0.00 s	     0.01 ms	 0.0	       0.0k	    JoinListener::onJoin(PlayerJoinEvent)
```

Strange.

**Comment by Kedarin** [comment]
You can see header information : http://timings.aikar.co/?url=11501230
90-120 users
How long was your measurement? what is ?

**Comment by confuser** [comment]
Your timers are fine @Kedarin, take note that they say "Task" meaning it's the database calls that are causing the increase. This is all done async, so it won't cause lag or affect the server's TPS.
