### ISSUE TITLE
BungeeCord/Offline mode UUID recognition

### ISSUE THREAD

**Issue by bugfroggy** [BanManagement/BanManager#298]
My previous ticket was closed and I'm not sure if it was re-opened when I replied. http://bugg.co/i/410de79de0.png It still doesn't work and I have Online mode as false.

**Comment by EvilOlaf** [comment]
It will not automatically reopen, however all peope watching the repository, maintainer included ;) will get a notification about that.
In some situations it is quite common to keep discussing on closed tickets.
