### ISSUE TITLE
"External" Bans don't register on new servers.

### ISSUE THREAD

**Issue by tr0nlegacy2012** [BanManagement/BanManager#299]
When I ban someone from my network using the banall command, it works great. But as soon as I add a new server and link the external database in the new server config, it doesn't seem to import those bans into the database. 

I'm not an expert when it comes to SQL, I am just a bit confused as to why the /banall bans exist in the banmanager_Network database and the database of the server i ran the command on, but none of the others.

When I do /bminfo on the original server, the ban shows up but on the new server I get a "are you sure that player exists" error message.

Is this intentional, will the banned players still be banned on new servers?

**Comment by confuser** [comment]
External bans will sync to new servers, we use it quite a lot at Frostcast to keep network bans consistent. On your new server, ensure you didn't copy across all the configuration files.

schedules.yml and console.yml should be created from scratch.

**Comment by tr0nlegacy2012** [comment]
If I have existing servers but I am changinc the way my databases are; do I need to delete those files and let them re-generate?

Currently it is setup with "banmanager" as the database with all the tables with different prefixes per server; like this: http://prntscr.com/7cqryt but now I am in the process of converting my database structure to this: http://prntscr.com/7cqsf6

**Comment by confuser** [comment]
Just the schedules.yml and console.yml files that will need regenerating for any new servers. If you're changing table names on existing servers, you don't need to do anything apart from restart.

For network banning to work, the external database info must be the same across all your servers.
