### ISSUE TITLE
Crash on startup (our fault)

### ISSUE THREAD

**Issue by spyproof** [BanManagement/BanManager#300]
So, on staryup we are receiveing the following error:
http://pastebin.com/A8P4jNNG

Let me explain the situation first, all of our servers, except for 1, are all in online mode. 1 server is in offline mode. this created the issue where we had duplicate enteries in the players table. Since this was our fault I went and deleted the offline duplicates. Unfortunatly some bans were linked to the Offline UUID, so if you tried to join the banned UUId with the playerdata that gat removed, it would return null: https://gyazo.com/0dee5fadc6299748b7414a4c4079deb6

I know this is a situation created by our foolness which we did solve. But maybe its worth catching a nullpointer? We managed to fix our issue, I dont expect a fix, but I thought it might be worth mentioning. After all, the fun challange of making a plugin is to make it idiot proof :)

**Comment by confuser** [comment]
If I catch the exception, how would you know there was an integrity issue with your data?
