### ISSUE TITLE
Automatic Updater Suggestion

### ISSUE THREAD

**Issue by minegame30** [BanManagement/BanManager#301]
As the title suggests really.
Perhaps consider integrating an automatic update system, or a command which can be ran ingame to update the plugin. Its very frustrating having to go through and update the plugin on each of our servers manually (we have around 30 servers running the plugin).

Thanks :)

**Comment by EvilOlaf** [comment]
Just add links to all webpages of your plugins to a browser folder and then open them all at once. Then close them one by one if there is no new version. works quite well for me. :P

**Comment by minegame30** [comment]
Haha, good idea! 
Unfortunately I cannot directly link to a folder in the file manager. So I would have to navigate all of the folders as I do now :/

Can I ask what server manager you use? :)

Date: Sat, 6 Jun 2015 23:52:49 -0700

**Comment by confuser** [comment]
The reason I'm not adding an auto update command is because new versions often contain breaking changes, or new tables. Updating blindly wouldn't be a good thing.

You could use a symlink via NFS if you're hosting on dedicated servers.
