### ISSUE TITLE
Feature Request - Kill Banned Players

### ISSUE THREAD

**Issue by FstJosh** [BanManagement/BanManager#304]
Greetings!
I would like to see an option to automatically kill a player before banning them. This would be extremely useful in the case of a PVP server. For example, if the person you're banning stole loot or is hacking, then everything in their inventory would drop to the ground, for anyone to pick up.

**Comment by confuser** [comment]
https://github.com/BanManagement/BanManager/blob/master/src/main/resources/config.yml#L104-L113

this will allow you to kill players on ban
