### ISSUE TITLE
Not working? seems that plugin does not detect player name

### ISSUE THREAD

**Issue by brunyman** [BanManagement/BanManager#307]
I'm using this on a large network, on each network server if I try a command like /ban Blabla Test instead of getting the player banned i get a message back: /ban player reason

No console errors, just does not work, i just updated few day ago to this new uuid compatible version.

I'm using v5.5.0

**Comment by confuser** [comment]
That means the plugin is disabled. Check your logs around start up for more information. It is most likely it failed to connect to the database.
