### ISSUE TITLE
Error rendering server inaccessable

### ISSUE THREAD

**Issue by minegame30** [BanManagement/BanManager#308]
Hi,
as the title says really. At some point today, something happened on our network. Nobody was online, and nobody more could connect. They were simply being timed out when trying to connect. I narrowed the error down to this plugin, and then checked the server log files. I have created a paste with *some* of the errors below. There was a lot more, but they were all just the same as this. This was occuring on all our servers at the same time. Maybe something wrong with mysql? But a connection test showed me that it was online and accepting connections.
http://pastebin.com/fUjCuxLg
I have no idea what caused it. Maybe you can make more sense of it?
Thanks

**Comment by confuser** [comment]
> [16:57:13] [Craft Scheduler Thread - 69/WARN]: Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.

A problem with your MySQL database. Refusing connections.
