### ISSUE TITLE
Warn notice

### ISSUE THREAD

**Issue by GiuseppeGroth** [BanManagement/BanManager#309]
can you add a warn notice like this
http://dev.bukkit.org/media/images/83/969/2015-06-16_17.34.58.png

**Comment by Kakifrucht** [comment]
There is currently no API for titles.

**Comment by EvilOlaf** [comment]
Wow. That would be really awesome.
It is a scientific mystery. Lots of players are able to write (to chat) but are unable to read it....

This way there is almost no chance to NOT see the mssages.

**Comment by confuser** [comment]
This would be 1.8 only and would require use of NMS/packets, as like @Kakifrucht said, there's n API for this.

I'm not going to add this into BanManager itself. If I get time today, I'll create a separate 'extras' plugin for this which listens to BM events.

**Comment by GiuseppeGroth** [comment]
I'll create a separate 'extras' plugin for this which listens to BM events.

Ok this is Verry nice 

can you add too 
Offline Warns

**Comment by Kakifrucht** [comment]
If you want to get this behaviour already, you could use a plugin like TitleManager (which also supports an api) and add the command that displays the titles / actionbar to the warningActions list.

**Comment by EvilOlaf** [comment]
Looking forward to this feature :)

**Comment by confuser** [comment]
https://github.com/BanManagement/BanManager/blob/master/src/main/resources/config.yml#L104-L113

You'll need another plugin implementing some sort of title and actionbar command for this to be achievable, but it is now possible as of the latest developer build.
