### ISSUE TITLE
MySQL Many many many open connections.

### ISSUE THREAD

**Issue by minegame30** [BanManagement/BanManager#311]
Hi,
We are using this on our entire network. Our database host has just suspended our package as there was over 2500 connections to my bans database from our servers' ip addresses. Uh, i think this might be a bug that needs looking into.
Just letting you know :)

**Comment by EvilOlaf** [comment]
There was a similar bug report earlier and this issue had been resolved AFAIR. Which version are you using?

**Comment by minegame30** [comment]
Latest

**Comment by minegame30** [comment]
Ill find the version number

**Comment by minegame30** [comment]
I cant seem to find this issue, could you link me too it? Ill take a look

**Comment by EvilOlaf** [comment]
Hm  couldn't find either. Maybe I was wrong...

**Comment by Kakifrucht** [comment]
How many single BanManager instances does your network run?

**Comment by minegame30** [comment]
Aw, nevermind Olaf :)

Kaki, i'm running 5 instances of the plugin. In the settings, its limited to 10 connections (I believe that is what that setting is for) so theoretically there should be no more than 50 connections at peak, no?

**Comment by confuser** [comment]
Are you using any other plugins that access the database?

The pool is handled by a 3rd party library named ORMLite, if you are
certain it is caused by Ban manager then it is a bug within the library
itself.

**Comment by confuser** [comment]
Closing due to lack of response

**Comment by minegame30** [comment]
My apologies, I thought I had replied already. 
No, no other plugins accessing the database. It has its own database separate from everything else.
