### ISSUE TITLE
BanManagement invalid language

### ISSUE THREAD

**Issue by SrPeterMC** [BanManagement/BanManager#318]
Hi.
Well i tried to translte the plugin to spanish, but when i open 
the servers in changes the name of the .yml to:
messages2015-07-06_21-55-53.yml.invalid
So its stays in english:/

**Comment by EvilOlaf** [comment]
Did you check your console output for further information? Usually some details about why the lang file is invalid will be shown there.

**Comment by SrPeterMC** [comment]
Yep, checked, there are no erros

**Comment by confuser** [comment]
The yml files will only ever be regenerated if it detects a syntax error.

Ensure your file is valid syntax.

There are multiple online tools you can use to check.

**Comment by SrPeterMC** [comment]
I tried http://www.yamllint.com/ and no error:/

**Comment by confuser** [comment]
http://yaml-online-parser.appspot.com/
