### ISSUE TITLE
duplicateIpCheck option is ignored

### ISSUE THREAD

**Issue by Xibalba** [BanManagement/BanManager#320]
Hi ! If have an issue with duplicate ip check : most of the time when a player logs in, this message shows up :

18:34:53 [INFO] [BanManager] Requesting name for 7cf0a82c-188f-358c-9045-52ce7bb5c783
18:34:54 [WARN] [BanManager] Duplicates found for Z3dd7, was unable to contact Mojang for updated names

I have set duplicateIpCheck to false in config and even added thoses ips in bypassDuplicateChecks but the warning is still there.

Thanks for fixing this !

**Comment by confuser** [comment]
> 18:34:53 [INFO] [BanManager] Requesting name for 7cf0a82c-188f-358c-9045-52ce7bb5c783
> 18:34:54 [WARN] [BanManager] Duplicates found for Z3dd7, was unable to contact Mojang for updated names

has nothing to do with ip checks. That warning is merely stating that it found another player in the database named Z3dd7, but with a different UUID.

This is caused when a player changes name, and another player takes their old name 30 days later.

**Comment by Xibalba** [comment]
It's weird because I am the only one who has changed name but only 1 or 2 players are able to connect without this message showing up...

**Comment by confuser** [comment]
Check if you're running in offline mode vs online mode.

**Comment by Xibalba** [comment]
offline mode, then I can't do anything to prevent this message from showing up ?

**Comment by confuser** [comment]
Then set onlineMode to false in your BanManager config file. You'll need to clear your players table.

**Comment by Xibalba** [comment]
Oh sorry I didn't understand that you were talking about the config option ><

onlineMode was set on false

**Comment by confuser** [comment]
If it was set to false, the console message you've quoted would never appear.

**Comment by Lolmaster25** [comment]
On my Onlinemode server, with onlinemode selected in BM config, the options
`duplicateIpCheck: true
bypassDuplicateChecks:
- 0.0.0.0
- 127.0.0.1`

are totally ignored and every time a player joins I get a list of every player that has entered the server as it's a bungeecord and the plugin sees 127.0.0.1 for every player.
