### ISSUE TITLE
"Force Lowercasing offline names" not working

### ISSUE THREAD

**Issue by jessefjxm** [BanManagement/BanManager#322]
Strangely this feature still not working on my side in spigot 1.8, BM v5.4 to 5.6 ... I've already set 'onlinemode' to false, but ban-ed players are still able to login after case changed.

Then I read some part of BM's code, and found that in the onPlayerLogin() event in JoinListener.java ,BM get UUID directly through event.getPlayer().getUniqueId().

And the event in PlayerBanStorage.java, getBan(String playerName) ,which can check BM records with Case-Ignored names, hasn't found been used.

I've post a fork on it, and hope that might work :)

**Comment by confuser** [comment]
OfflinePlayer UUIDs are generated based on the name, which is what is used when banning players when onlineMode is set to false in the config, not the name itself. Therefore using getUniqueId should pose no issue.

**Comment by jessefjxm** [comment]
Yes you're right..... but in BM v.5.4, there's an updating that "Force offline names to lowercase when generating UUIDs. - Fixes case issues for offline servers." , which seemed not working right now, and this is what actually confused me.

The mentioned update was found in:
http://dev.bukkit.org/bukkit-plugins/ban-management/files/59-ban-manager-v5-4-0/

**Comment by confuser** [comment]
That related to #236 and also please note, I don't officially support offline mode, said support was added by others via pull requests.

**Comment by jessefjxm** [comment]
Okay... I'll have it a try. Anyway, thanks for your great plugin :)

**Comment by confuser** [comment]
Sorry. Please don't hesitate to make a PR if you come up with a fix.
