### ISSUE TITLE
Bans table not found

### ISSUE THREAD

**Issue by Retracker** [BanManagement/BanManager#324]
I keep starting the server with the plugin installed in it but in my website when i try to connect using mysql 
it wont let me because this error shows up "Bans table not found" i keep triple checking the mysql info but its the same. Any ideas? im using the latest ban manager file in my 1.8.6 spigot server.

**Comment by EvilOlaf** [comment]
The mysql login credentials are on *nix based systems case sensitive. Make sure that there is no typo.

**Comment by confuser** [comment]
BanManager creates the tables. Type /pl to see if BanManager is red, if it is, it disabled itself on startup, so check your logs.

**Comment by Retracker** [comment]
@EvilOlaf I copied and pasted the details like 3 times its impossible for them to be typed wrong, ;/
@confuser Yes it is disabled i dont really know why, i typed in mysql settings in the ban manager config yml file and in my website by frostcast. ;/ any ideas? Heres the console log of ban manager errors:
http://pastebin.com/zYvJrmwY
dude author if you help me fix this you dont know how much id appreciate it, you'll make my year! :)

**Comment by confuser** [comment]
```
Could not create connection to database server. Attempted reconnect 10 times. Giving up.
```

http://dev.bukkit.org/bukkit-plugins/ban-management/#w-faq

**Comment by Retracker** [comment]
@confuser I'm sorry but i dont know what you mean... This is my first time using MySql with 000webhosting

**Comment by confuser** [comment]
You are attempting to access a MySQL database remotely. By default, MySQL refuses remote connections, this is what is covered in the FAQ. If you do not have the ability to grant new permissions to your database, you will need to contact 000webhosting and ask them to whitelist your minecraft server ip, so it is able to connect remotely.

**Comment by Retracker** [comment]
@confuser ok now i changed my mysql host and got one from freemysqlhosting and now the plugins works on my server its not disabled its not red its in the color green and enabled and working like the commands work but when i use the mysql info on my frostcast web page it wont connect it still says 
"Bans table not found"  but still thanks for your help. Youre the best plugin author out there none have replied to my tickets of having trouble setting up their plugin, you are literally THE best!

**Comment by Retracker** [comment]
http://pastebin.com/YfRd5uiP
thats my console server log all that i found that had to do anything with ban manager. There are noo errors in the console log at all.

**Comment by EvilOlaf** [comment]
`The time on your server and MySQL database are out by 130 seconds, this may cause syncing issues.`
On most network services it is important to have sync your time correctly. Either blame your mysql server host or minecraft server host to do their job properly.

**Comment by Retracker** [comment]
@confuser 
@EvilOlaf 
does the MySQL need to be the same in the ban manager plugin and in my website? Like the same database uername, password, host? Or do  i need to use 1 different mysql and another different mysql account?

**Comment by EvilOlaf** [comment]
Yes, they have to be the same.
The BanManager plugin writes your executed bans, warnings and so on into your database.
The webinterface reads the data from it and parses it into a human understandable way (to say a nice web site :P)

**Comment by Retracker** [comment]
@confuser @EvilOlaf  Thanks guys for both of your help!!! I finally fixed it, the problem was is that i was using the ban manager v5 the latest version and the frostcast website from ban manager v4 so i installed the v4 ban manager in my server and now it works like a charm!

**Comment by Retracker** [comment]
I had to downgrade the ban manager plugin but it was worth it

**Comment by EvilOlaf** [comment]
https://github.com/BanManagement/BanManager-WebUI/releases
Take this Web-UI. Works well with v5.6.0
