### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Phalenex** [BanManagement/BanManager#325]
when attempting to ban or use any command it just spits out the command format

**Comment by EvilOlaf** [comment]
Further investigation not possible.

CB/Spigot version?
BM version?
console output?
commands used?
startup log?

**Comment by Kakifrucht** [comment]
This probably means that the plugin disabled itself. Check the logs on why. In most cases this is due to MySQL misconfiguration.

**Comment by confuser** [comment]
Please look at your logs before raising issues. Console output is there to inform you of the state of your server, it's not there for you to ignore.

**Comment by Phalenex** [comment]
Jesus Christ give me a god damn chance, any ban command would spit out the format in chat and nothing shows in console and clearly I wouldn't make a ticket without trying everything I knew I didn't spend 3 hours with this bullshit for nothing. It hooks into sql fine because the kicks work and warns and they appear in the tables. Console states no errors with version 4.0

**Comment by EvilOlaf** [comment]
4.0? The most current version is 5.6.0?

**Comment by Phalenex** [comment]
i am aware of that but i find 4.0 simpler than 5.6: 5.6 has too much shenans going on

**Comment by EvilOlaf** [comment]
Then my guess is there is pretty much no way to help you any further as version 4 is probably no longer supported.

**Comment by confuser** [comment]
V4 does not support uuids and is no longer supported

**Comment by Kakifrucht** [comment]
What shenans? confuser does a pretty good job at keeping the whole environment modular, if you don't care about some feature, you don't have to use it.
