### ISSUE TITLE
Reasons Issue

### ISSUE THREAD

**Issue by itismejoey** [BanManagement/BanManager#332]
Using ```/ban itismejoey #hacking``` does not display the message that was set in the reasons.yml. Just displays ```itismejoey has been banned for #hacking```

Minecraft: 1.8.6
BanManager: 5.6.0 Build 166

**Comment by Autom3** [comment]
I've added a pull request for a fix for this issue (https://github.com/BanManagement/BanManager/pull/341)

**Comment by confuser** [comment]
Thanks @Autom3 :+1:

**Comment by Autom3** [comment]
You're welcome :)

**Comment by itismejoey** [comment]
Thanks @Autom3!

@confuser - when will this be pushed to be able to download?

**Comment by confuser** [comment]
http://ci.frostcast.net/job/BanManager/ has automatic developer builds, so it was available to download minutes after I merged the PR
