### ISSUE TITLE
reason.yml bug also whats perm to see ban message in chat 

### ISSUE THREAD

**Issue by Twi5TeD** [BanManagement/BanManager#333]
still doesnt work i do hacking: Using a hacked client in the reason file and do /ban playername #hacking and it says banned player for #hacking and not the reason from the reasonfile and does anyone know the perm to see bans in what like if i do /ban name test others can see it?

**Comment by confuser** [comment]
Duplicate of #332

**Comment by confuser** [comment]
Check the bm.nofity permissions at http://dev.bukkit.org/bukkit-plugins/ban-management/pages/commands-permissions/
