### ISSUE TITLE
Plugin don't see some of my players...

### ISSUE THREAD

**Issue by Kixot14** [BanManagement/BanManager#334]
Sometimes this plugin don't see some of my players, and i have error, when try use BM-cmd to somebody - http://pastebin.com/KukY94Jb
At the beginning all is oK, but after 2 or 3 weeks, after created database, plugin send error to console and some banned, muted, etc. players can joined and chating...

And i have a question: When i IpBan someone, that ban IP address and player-nickname or only IP ??

**Comment by EvilOlaf** [comment]
`banip` will ban the players IPv4-address only. So if the player changes his IP-address he will be allowed to join again. This sounds useless but sometimes there are multiple players using the same IP which are all causing trouble.

Not sure about the SQL-error, @confuser will answer this properly. Encoding/charset issue?

**Comment by confuser** [comment]
What version of BanManager are you running?

**Comment by Kixot14** [comment]
Latest - v5.6.0
And version of server is CraftBukkit version git-Spigot-2f787bd-ea28011 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)

**Comment by confuser** [comment]
Note to self, use `createOrUpdate` in `retrieve`

**Comment by Kixot14** [comment]
Where is "createOrUpdate" and what the "retrieve" ?

**Comment by EvilOlaf** [comment]
This information was not for you. Just a note for @confuser himself.

**Comment by Kixot14** [comment]
Lol. Ok, understand! =)

**Comment by RedOreGaming** [comment]
How can I fix it now?

**Comment by confuser** [comment]
@RedOreGaming try the latest developer build 172+

http://ci.frostcast.net/job/BanManager/

**Comment by rocky143** [comment]
Seems like with build 172, we are able to ban the players we weren't able to before but /bminfo says "xyzplayer not found, are you sure they exist?". This is happening specially to those who we not banable before.

**Comment by confuser** [comment]
@rocky143 that will only happen if you have players in your database with duplicate names.
