### ISSUE TITLE
Tempban cancels ban

### ISSUE THREAD

**Issue by EvilOlaf** [BanManagement/BanManager#337]
Following scenario:
Player X gets banned for life for a reason.
A few days later staff members found some waste from player X but did not know that the player was banned earlier and don't take an extra look for.
So player X receives a tempban for a time.
After the time is up both the temporary and the permanent ban are lifted which was not wanted.

I like the idea to have a shorter ban be overridden by a longer one, but in this case the longer or permanent ban gets overridden by a shorter one which is for my case at least not wanted.

This could be solved with a confirmation message for example:
`This player is already banned for [reason] by [actor]. Expires in [expires]. Retype the command to confirm new ban.`

BM5.6.0

**Comment by Agazed** [comment]
I believe this can be solved by not giving a group the bm.command.tempban.override permission.

**Comment by EvilOlaf** [comment]
As I don't think that this particular permission node is true at default this does not fix the issue as none of my groups have this node.
