### ISSUE TITLE
Allow someone to ban only certain groups

### ISSUE THREAD

**Issue by justin2001** [BanManagement/BanManager#339]
So I have five ranks: member, vip, moderator, admin, owner. How do i allow moderator to ban only member and vip, allow admin to ban member, vip and moderator, owner to ban member, vip, moderator and admin? What is the permission node for all these? If this is not a feature then please add this, thanks!!!

**Comment by confuser** [comment]
This isn't a feature, but the problem with this is that it is impossible to look up permissions of offline players within the Bukkit API, meaning that even if I added such a feature, people would still be able to ban them when they're offline.

**Comment by justin2001** [comment]
I think this can be done, by refering the pex config, i am not good at coding but i can explain for you. Thanks!

**Comment by confuser** [comment]
I don't want to have to add every single permission plugin in existence as a soft dependency for such a small feature. If your staff are banning one another, then they shouldn't really be staff.

**Comment by justin2001** [comment]
Please add this, i really need this.

**Comment by Kakifrucht** [comment]
Yeah well, he explained why it can't be done.
If you need something like this, you have bad staff.
