### ISSUE TITLE
Error message when starting 

### ISSUE THREAD

**Issue by Legoman99573** [BanManagement/BanManager#343]

**Comment by EvilOlaf** [comment]
Insufficient information.

Invalid.

**Comment by Legoman99573** [comment]
can u reopen it. pressed enter accidently

**Comment by EvilOlaf** [comment]
Thats better :p 
First of all BuyCraft and BanManager have afaik absolutely nothing to do with each other. How do you think this could cause an issue?


Secondly:
` The time on your server and MySQL database are out by 153 seconds, this may cause syncing issues.`

For most network services it is very important to have a synced time stamp on each side of the connection. So either blame your gameserver host or database host do do their job properly.

**Comment by Legoman99573** [comment]
it is home hosted, but the database is hosted by someone else

**Comment by EvilOlaf** [comment]
Then either blame yourself or the other guy :P

**Comment by confuser** [comment]
Your issue is with Buycraft, and not BanManager, therefore I won't be re-opening this issue.

**Comment by Legoman99573** [comment]
myself is fine, but i blame the other database host. may change host and restart the server.
