### ISSUE TITLE
bm.notify permission problem

### ISSUE THREAD

**Issue by ziutekkk** [BanManagement/BanManager#344]
Hello
I use bm 5.6.0 and pex 1.23.3
When I have permission bm.notify.* ban messages dont show to me. But when I have bm.notify.ban only tempban and unban messages show to me. I think its so weird. For OP's everything works ok but for users with permissions dont. When I had banmanager 4.* I had no problems.
Please look at that.
Thanks

**Comment by confuser** [comment]
We use Pex at Frostcast and I'm not able to reproduce this problem. Can you double check you have the permissions? Rejoin the server and test again as pex doesn't always reload player permissions correctly

**Comment by EvilOlaf** [comment]
> Rejoin the server and test again as pex doesn't always reload player permissions correctly

+1. Especially when using inherits rejoin is practically always needed.

**Comment by confuser** [comment]
Closed due to lack of response and lack of being able to reproduce this problem

**Comment by EvilOlaf** [comment]
@confuser Just little thinking about. Did you try with wildcard permission like stated first or adding various notify notes with their full name?
It just looks like there might be an issue with adding a wildcard permission?
