### ISSUE TITLE
Feature Request - Add MySQLite support

### ISSUE THREAD

**Issue by Legoman99573** [BanManagement/BanManager#347]
I own a server and feel that using MySQLite will work out for users who cannot use MySQL. or add MySQLite as a backup if it fails to connect to server. This could keep the server from pinging the database all the time and if it doesnt see an update, then MySQLite file will remain the same. Also add the option to enable/disable MySQLite for server owners who dont want to use the feature.

**Comment by confuser** [comment]
Sorry but what is MySQLite? Do you mean SQLite? BanManager is a very mature plugin (3 years old) and has used MySQL from the beginning. 

I have no plans to support any other storage options at this time, especially a file based database such as SQLite which would make it absolutely impossible to sync data between servers.

**Comment by EvilOlaf** [comment]
This would be a single server only solution ;)
