### ISSUE TITLE
Not working on bungee

### ISSUE THREAD

**Issue by KevinEssence** [BanManagement/BanManager#350]
So before the whole big uuid update, things were smooth. Recently we notice when we mute or ban a player on a specific server, it doesn't kick or mute them on the other server. When we go on the other server to proceed, it gives us an error when we try to mute or ban them. After some time no matter what server they were punished on they eventually get their punishment, but it's not instant as before on all servers. Using latest build.

**Comment by confuser** [comment]
Please provide more information.

Stack traces, and more information on your setup, i.e. are you using local or external to share the punishments. If the latter, default sync intervals are set to 300 seconds, reduce this in schedules.yml if it is too long.

**Comment by KevinEssence** [comment]
What kind of stack traces sorry.

..and basically we have a bungee network with 9 servers, all connecting bans, ect. to same database through mysql. It's slow on processing information to to other servers. So if you ban someone on one server they can still connect to the other.

**Comment by confuser** [comment]
Right, I'm going to reiterate this once more, as I've already stated this on bukkit dev comments to you, and also within this issue.

Open schedules.yml

https://github.com/BanManagement/BanManager/blob/master/src/main/resources/schedules.yml

edit the numbers under `scheduler`, they are in seconds, so change them to however often you need it to sync bans etc between servers.
