### ISSUE TITLE
[player] not replaced at join denied notification

### ISSUE THREAD

**Issue by EvilOlaf** [BanManagement/BanManager#352]
`[12:08:09 INFO]: Warning: [player] attempted to join the server but was denied due to Fly Hack.`

`[player]` not getting replaced´with the real name ingame as well as in console.

BM5.6.1

Thought I did report this before but couldn't find the report...maybe I was wrong...

**Comment by confuser** [comment]
Are you sure this is the deniedNotify.player message and not .ip? The code does have it as setting the player token

https://github.com/BanManagement/BanManager/blob/master/src/main/java/me/confuser/banmanager/listeners/JoinListener.java#L129

**Comment by EvilOlaf** [comment]
Not sure about that as they sound exactly the same in `messages.yml`.

**Comment by confuser** [comment]
.ip contains [ip] token and .player contains [player]

**Comment by EvilOlaf** [comment]
Then the ip warning contained wrongly `[player]` and not `[ip]`.
So fixed :)
