### ISSUE TITLE
Last version

### ISSUE THREAD

**Issue by Jackiedk100** [BanManagement/BanManager#355]
You said I shall use the last developer build, but on the site, there is standing
Web interface is NOT compatible

So, why shall I use that?... ;(

**Comment by confuser** [comment]
That is no longer relevant and can be ignored

**Comment by frdmn** [comment]
@Jackiedk100 Feel free to post your issues with the web interface in the [BanManagement/BanManager-WebUI|](https://github.com/BanManagement/BanManager-WebUI/issues) repository. I'll do my best to help you out then :)

**Comment by Jackiedk100** [comment]
You can try the site, http://bans.diamondcreeper.dk

Then you will know the fails.. :(

Med venlig hilsen Jackie

**Comment by frdmn** [comment]
Again, please use the [BanManagement/BanManager-WebUI](https://github.com/BanManagement/BanManager-WebUI/issues) repository for further discussion of your problems. This one is dedicated to the Java plugin. Any web related issues have no business in here.
