### ISSUE TITLE
Components of CmdBook have more priority...

### ISSUE THREAD

**Issue by Kixot14** [BanManagement/BanManager#359]
Please say me, what can i do if i have CommandBook and her mute/ban cmd have more priority then BanManager?? I dont wont disabled some thread of cmdBook components, or set Low-Priority-command-registration to true, cause then i lost many useful commands... What can i do yet, if i only wont add more priority to BM mute/ban cmd then have CommandBook?

**Comment by confuser** [comment]
Unfortunately setting the low-priority option is the only thing you can do. Please report this as a bug to CommandBook as there's not much I can do about it.

**Comment by DoctorDark** [comment]
If you don't have any anything blocking it, you should just be able to use /banmanager:<command>
