### ISSUE TITLE
warning message doesnt show playername sometimes

### ISSUE THREAD

**Issue by Twi5TeD** [BanManagement/BanManager#360]
using latest update and getting this still https://gyazo.com/61850d39c738613517e97fc77d1addc2 and sometimes it shows the name https://gyazo.com/888ffec1e7efb370b2a9d3a2402da5b5

**Comment by EvilOlaf** [comment]
Open your `messages.yml`

Search for:
`    ip: '&cWarning: [player] attempted to join the server but was denied due to &4[reason]' `

replace with:
`    ip: '&cWarning: [ip] attempted to join the server but was denied due to &4[reason]'`

**Comment by Twi5TeD** [comment]
but i want it so that their name will show

**Comment by EvilOlaf** [comment]
The name will be shown.

**Comment by Twi5TeD** [comment]
ill try now thanks
