### ISSUE TITLE
Webinterface error

### ISSUE THREAD

**Issue by RedDragonYTHD** [BanManagement/BanManager#363]
Hi, i used the banmanager plugin and i did the webinterface just like it says on the tutorial, But i noticed some mistakes on the interface... First off for example where it says Your server 2015 if i change that, it "rollbacks" to default...
And every time i try to add a server it shows up an error and in the response says nothing....
Just Response:(nothing)
Can some one help me ?

**Comment by EvilOlaf** [comment]
Is your `settings.php` writeable by the webserver?

**Comment by RedDragonYTHD** [comment]
Yup, its everything right

**Comment by RedDragonYTHD** [comment]
I tested like 10 times and i did everything ok

**Comment by frdmn** [comment]
Can you "move" (recreate) this issue in the WebUI repository, please? [BanManagement/BanManager-WebUI](https://github.com/BanManagement/BanManager-WebUI/issues)
