### ISSUE TITLE
Can't remove notes

### ISSUE THREAD

**Issue by Kerrus** [BanManagement/BanManager#365]
There's no command to remove notes, either individually or as an aggregate. You can edit them out of the database, but BMclear doesn't touch them and it'd be really nice if we could just delete them individually.

**Comment by confuser** [comment]
`/bmclear  <player> notes` or use `/bminfo  <player> -n` to find the ids and use `/bmdelete <id>`

**Comment by Kerrus** [comment]
/bm clear <player> notes doesn't do anything. The plugin says 'not a valid command, try [other category]'. 

I'll look at the other stuff though.

**Comment by EvilOlaf** [comment]
The command @confuser provided works as expected. Try bm and clear without space and with player name provided.
