### ISSUE TITLE
/muteip and /tempmuteip

### ISSUE THREAD

**Issue by Agazed** [BanManagement/BanManager#366]
Would be a cool addition as I have some players that like to use alts to bypass mutes.

**Comment by Kakifrucht** [comment]
Seems pointless to me, if they are actually bypassing the rules why not ban them directly.

**Comment by Agazed** [comment]
@Kakifrucht That's my point. I try to avoid banning players because less players, less money, no more server. Especially if the person was just spamming, it doesn't deserve a ban.

Besides, this feature would be hard at all as it would mainly be copy and paste. Heck even I could do it.

**Comment by Kakifrucht** [comment]
Offtopic, but toxic players really should be removed. I guess you need to decide if you want to build a nice and fun community or just generate revenue.

If you check how this project is set up you would notice that individual commands are put into own classes (command pattern), so you would only have to pull request a new class containing your command. Very nice and modular setup.

**Comment by EvilOlaf** [comment]
I agree with @kakifrucht. I like it more to just have a few nice people instead of a server full of idiots.
