### ISSUE TITLE
Error. Player doesn't exist...

### ISSUE THREAD

**Issue by Kixot14** [BanManagement/BanManager#372]
I dont understand what's happen?? Today I given mute to one player, and after that he still can chatting...

When i tried to remute, or check her acc by /bminfo, i had this error http://pastebin.com/qC5AnU5a
And bm notify me about "this player doesn't exist". And only one what i can do with this player - its /banip.

**Comment by Slaand** [comment]
I have almost same issue. We cant punish(/mute /warn etc) some players from server, because "Player doesn't exist" but he is online at the moment.
Error log: http://pastebin.com/RbDSjZrL
Please help! Database remove/clean isn't help at all

**Comment by confuser** [comment]
Update to a developer build, it should already be fixed

http://ci.frostcast.net/job/BanManager/

**Comment by Slaand** [comment]
Now punishments doesn't work at all, im writing a command and players does not getting any punishment.

**Comment by confuser** [comment]
@Slaand please check your logs for any warnings. It sounds like the plugin is disabled for some reason.

**Comment by TemptingMC** [comment]
Same issue for me #373

**Comment by Kixot14** [comment]
After when this player logged in, my server crashes and data of some plugins has been deleted. Whats wrong ?? http://pastebin.com/8A6DPWJs

**Comment by confuser** [comment]
@Kixot14 your issue isn't related to this, the most likely cause is you've ran out of disk space

**Comment by Kixot14** [comment]
Update to a developer build, it should already be fixed ©confuser

With this plugin update i need to update and delete all data from MySQL ??

**Comment by confuser** [comment]
No, just upload the .jar file, nothing else

**Comment by Kixot14** [comment]
Thank for info.

And can you consider my suggestion about dual command?

Example: When need to give mute and warn to player, use /tempmute +tempwarn <player> <timeMuteDiff> <timeWarnDiff> <reason>

And only one notifi in chat for this double action: Moderator [actor] tempmuted [player] for [time] and tempwarned for [time] for [reason]
