### ISSUE TITLE
Conversion Issue

### ISSUE THREAD

**Issue by TemptingMC** [BanManagement/BanManager#373]
Hey, I'm very confused on how to covert. Is it possible for me to pay you $30 to do it for me?

**Comment by confuser** [comment]
I don't do paid bukkit development I'm afraid. The instructions are quite clear. Which part are you having trouble understanding?

**Comment by TemptingMC** [comment]
I'm upgrading from 4.0 to 5.6.1, do the tables need to be converted or does it use the same info. in the tables?

**Comment by TemptingMC** [comment]
@confuser this is my issue:
https://i.gyazo.com/b792bf62cdbf8150a8bc4784f96e752a.png

**Comment by TemptingMC** [comment]
@confuser Please help! I need to get this done today! ^

**Comment by confuser** [comment]
Is your server running in offline or online mode?

**Comment by TemptingMC** [comment]
offline, should I put it on online mode just for the purpose of the conversion?

**Comment by TemptingMC** [comment]
@confuser https://gyazo.com/e6000a1f38a608e5898bf00902936f04
i tried it on online mode.

**Comment by confuser** [comment]
If you're running an offline server, ensure you've set onlineMode to false in your BanManager config.yml

**Comment by TemptingMC** [comment]
I tried running it on online mode.
