### ISSUE TITLE
[Idea] Correct chat blocking

### ISSUE THREAD

**Issue by Slaand** [BanManagement/BanManager#374]
Hello! Plugin doesn't catch and block any messages, which are sended from muted players using any bungee chat plugin (mineversechat, legendchat etc). Same with commands, which are added to config file. @confuser, can you add this feature?
P.S. Im sorry for my english

**Comment by confuser** [comment]
BanManager listens to the chat listener

https://github.com/BanManagement/BanManager/blob/master/src/main/java/me/confuser/banmanager/listeners/ChatListener.java#L15-L16

If any of the plugins you listed are not emitting the event (they're doing it in an unusual way), BanManager will not be able to cancel the messages. It's down to those plugins to cater for this scenario.
