### ISSUE TITLE
Question for confusser

### ISSUE THREAD

**Issue by TemptingMC** [BanManagement/BanManager#377]
Hey, with the latest update, is it possible that when I ban a player, it links there ip with the account so that there ip gets banned as well and when I unban the player, there ip gets unbanned?

**Comment by EvilOlaf** [comment]
You could use the hooks feature for it. Add banip and unbanip ask pre or post event to ban and unban.

**Comment by TemptingMC** [comment]
how do the hooks work? @EvilOlaf I just see "hooks enabled: false"

**Comment by EvilOlaf** [comment]
Set to true and read the manual for the rest :p
