### ISSUE TITLE
Double database profile?

### ISSUE THREAD

**Issue by SubmissiveMC** [BanManagement/BanManager#378]
I have a network with 4 servers which is in beta development right now. Each of these servers has BanManager enabled (Hub, Survival, Creative and WIP). All of these are hooked to the same local database and all of the servers boot fine with no issues in the startup logs. When moving between Hub, Survival and Creative, everything works fine with no issues whatsoever. However, when I log into the WIP server, which has the same config as all of the others, it makes a second user for my name in the bm_players table. When this happens, I can't /bminfo myself or any other player who has joined that server, until I manually delete all of their profiles from the database. I was wondering if someone could help me out with this?

Thanks, SubmissiveMC.

**Comment by confuser** [comment]
Check that they are all running the same version of BanManager.

**Comment by SubmissiveMC** [comment]
Yep they are all running the same version :)

**Comment by confuser** [comment]
Check that they're all in online mode or in offline mode, and not a mix.

Can you please provide any stack traces if there are any?

**Comment by SubmissiveMC** [comment]
All the servers are in offline mode due to bungeecord. Would you mind explaining stack traces to me?
Thanks :)

**Comment by frdmn** [comment]
@SubmissiveMC Any java errors in your server.log/console :)

**Comment by confuser** [comment]
Double check that you don't have one server that isn't set to forward data from bungeecord correctly, otherwise the uuids etc may be wrong.

**Comment by SubmissiveMC** [comment]
There aren't any errors on boot, everything runs smoothly. The configs match up fine where they are meant to I believe, is there any specific options I should be looking for? The only other thing I can think of is that WIP isn't running the same version of Spigot that the others are..

**Comment by confuser** [comment]
>  it makes a second user for my name in the bm_players table. When this happens, I can't /bminfo myself or any other player who has joined that server, until I manually delete all of their profiles from the database.

Any errors when that happens?

**Comment by SubmissiveMC** [comment]
Lemme take a look for you :)

**Comment by SubmissiveMC** [comment]
Okay, going from Fac > WIP > Fac I got this console error

[BanManager] Requesting name for ab3955b8-9f76-336e-95cb-3626c15f152f
[02:59:54 WARN]: [BanManager] Duplicates found for SubmissiveMC, was unable to contact Mojang for updated names
[02:59:54 INFO]: UUID of player SubmissiveMC is 1363d27c-1c2d-4674-bda8-9810d9316f20

**Comment by confuser** [comment]
Your WIP server is saying you have a different UUID than your other servers

WIP UUID: `ab3955b8-9f76-336e-95cb-3626c15f152f`
Your actual online UUID: `1363d27c-1c2d-4674-bda8-9810d9316f20`

WIP isn't forwarding from bungeecord correctly, check your spigot.yml file
