### ISSUE TITLE
Players table not found?

### ISSUE THREAD

**Issue by Steven25309** [BanManagement/BanManager#379]
Hello, I've been trying to fix this problem for about a day now. Everytime I try to add a server to my website I get the error "Players table not found". I double checked my config and all of my MySQL information and everything seems to be working all right. I even contacted my host to see if they could help and they said contact the plugin developer, so here I am.

**Comment by confuser** [comment]
Hi @Steven25309 this repository is for the Bukkit plugin, not webui. Can you open an issue over at https://github.com/BanManagement/BanManager-WebUI please and someone will be able to help you debug the issue.
