### ISSUE TITLE
message error console

### ISSUE THREAD

**Issue by Cydut** [BanManagement/BanManager#380]
Hello,

i have regularly a problem with the plugin

http://pastebin.com/N5vTsSk2

can you help me ?
Spigot : git-Spigot-26dfd01-ad2f806 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)
BanManager 5.0.0-SNAPSHOT 

Thanks by advance

Cydut

**Comment by confuser** [comment]
Why are you running such an old version? Update.

**Comment by Cydut** [comment]
just because we have a huge event for our anniversary and i do not update plugins to be sure that i will not have to manage issues during this Big time. If it runs like that, i prefer to wait after the anniversary.
thanks - Cydut
