### ISSUE TITLE
Information not syncing one way

### ISSUE THREAD

**Issue by darkarrow** [BanManagement/BanManager#381]
Okay so I am currently testing out this plugin on a server I'm starting. My setup is using bungeecord with currently two servers connected to it, the Hub and factions server. I've extensively tested this to try and narrow down exactly what the problem I am having is and I think I've narrowed it down pretty well, now some scenarios!

I ban someone on the Hub server and they connect to the factions server after the ban, the factions server doesn't sync the ban and they are allowed on the server. Note that I have used /bmsync local to try and sync at that moment and the ban still doesn't sync. During this same scenario if I restart the factions server and then attempt to connect the ban is synced. This same thing happens for an unban on the Hub server, it doesn't sync to the factions server unless it is restarted.

New scenario, I ban someone from the factions server and they try to join the Hub server, if not right away eventually the ban is synced and if I don't want to wait for the sync if I use /bmsync local it updates the ban right away and the player is banned. So this way it works just fine

So all syncing works on the Hub server but the factions server only syncs to Hub.

I just installed the plugins and only changed the local database properties to the same on each server, there are no differences in the configs.

If this turns out to just be some stupid thing I did I'm sorry to have wasted your time, but as it stands for syncing bans this is unusable for me. I do really like this plugin though and hope this can get resolved! thanks.

**Comment by confuser** [comment]
Check the times of your server, and ensure they aren't out of sync

run the `date` command via shell (ssh in)

Check your logs on startup to see if BanManager is emitting any sort of warning regarding time differences

**Comment by darkarrow** [comment]
factions: Fri Aug 21 11:04:34 EDT 2015
hub: Fri Aug 21 10:59:45 EDT 2015

[11:01:44] [Server thread/ERROR]: [BanManager] The time on your server and MySQL database are out by 284 seconds, this may cause syncing issues.

It seems that is probably causing it, I have to wait for my VPS provider to answer my ticket because I can't change time on my VPS. If they fix it I'll reply with a definitive answer of if it worked or not. Thank you for the fast response.

**Comment by darkarrow** [comment]
They have now synced the times and the plugin is working perfectly. Thank you very much for the support and your work on the plugin.
