### ISSUE TITLE
Silent actions

### ISSUE THREAD

**Issue by EvilOlaf** [BanManagement/BanManager#382]
From time to time you want to do actions like ban or kick do silently to others. For example you are vanished and want to ban a player without being unhidden by the BM broadcast that player X has been banned by Y.

So my suggestion is to add a `-silent` or `-s` to each command that will suppress any broadcasts to all players. Others will only notice that player X has disconnected or left the server.

**Comment by confuser** [comment]
`-s` is already a feature ;)

**Comment by EvilOlaf** [comment]
Now THAT was fast :grimacing:

**Comment by EvilOlaf** [comment]
Hm does not work with `kick`?
Getting message `[player] is offline` which is btw. also a bug as `[player]` is not being replaced?

My command: `/kick -s playername test`

**Comment by confuser** [comment]
`-s` has to be after the player name, but can be anywhere in the message

e.g.

`/kick confuser testing -s these silent kicks`

**Comment by EvilOlaf** [comment]
`/kick -s playername test` did not work
`/kick playername -s  test`kick the player with the reason `-s test`

Sum ting wong :P
