### ISSUE TITLE
Mysql error

### ISSUE THREAD

**Issue by Nicoelele** [BanManagement/BanManager#387]
Hello. How can I fix this error?

Log:  http://paste.nightsnack.cf/ovayomubiz.avrasm

**Comment by kingpyro** [comment]
Seems like you lost connection to your mySQL database

**Comment by confuser** [comment]
As @kingpyro said, your connection was lost, and BanManager wasn't able to reconnect. Ensure your MySQL database is stable.

**Comment by Nicoelele** [comment]
How to fix this problem and how to do the MySQL database stable?

**Comment by EvilOlaf** [comment]
Ask your host to do their job properly.

**Comment by Nicoelele** [comment]
I fix it!
