### ISSUE TITLE
Name Sensitivity

### ISSUE THREAD

**Issue by kingpyro** [BanManagement/BanManager#389]
Hi,

I am having trouble with players changing their name to a different case to avoid bans.

Ex. I ban player kingpyro but he comes back as KingPyro. Is their anyway to change the lookup to be case insensitive for bans?

If onlineMode: false can we have it use the usernames and not the UUID to determine if someone should be banned or not. Because when someone logs in with a different case, it creates a new UUID for that player.

Thank you - really awesome plugin you have made!

**Comment by Kakifrucht** [comment]
The ban checks UUID's. You shouldn't use onlineMode: false if you are not proxing through BungeeCord, which is the only excuse to use it imo. Think about what you are doing when creating a server for players unwilling to pay 20$ for Minecraft. Not sure where confuserr stands on this topic.

**Comment by Agazed** [comment]
Offline Mode doesn't support UUID checking. You have to ban players by their IP or change your online mode to true.

**Comment by kingpyro** [comment]
I never said this was a bug. I was simply asking for a feature to be added.

**Comment by EvilOlaf** [comment]
I guess not. I might be wrong but if I remember correctly does BanManager not support offline mode. This feature would only help offline mode server so it probably won't be added.

**Comment by confuser** [comment]
Please ensure you're running 5.6.1 (latest release).

I don't support offline mode, but I will accept pull requests to better
support it.
