### ISSUE TITLE
Hooks Question

### ISSUE THREAD

**Issue by TemptingMC** [BanManagement/BanManager#391]
Ok so I have a hook setup which works 100% correctly.

hooks:
  enabled: true
  events:
    ban:
      pre:
      - cmd: banip [player] [reason] (IP Banned)

How do I set an event so whenever i unban a player it unbans the ip?

**Comment by confuser** [comment]
There is currently no hooks for unbans/unmutes

**Comment by TemptingMC** [comment]
Is it possible to add it before Saturday? @confuser

**Comment by confuser** [comment]
Potentially but unlikely

**Comment by TemptingMC** [comment]
Please try too. I appreciate your work.

**Comment by TemptingMC** [comment]
@confuser would this show up on a dev build or on the bukkit builds?

**Comment by EvilOlaf** [comment]
First dev, then maybe Bukkit :P

**Comment by confuser** [comment]
I haven't yet tested this, but it is available as a developer build.

Please note this only adds in support for unban(unmute etc) `post` hooks, and not `pre`.

**Comment by TemptingMC** [comment]
@confuser post just means like after the command is executed?

**Comment by confuser** [comment]
Correct
