### ISSUE TITLE
Banmanager Web interface not updating propperly

### ISSUE THREAD

**Issue by Delliurm** [BanManagement/BanManager#392]
So I setup banmanager on my server, pointed it to my webserver mysql. Created the databases properly, went and setup the website, added my server to the website. Yet when do a test ban, its not showing up on the website? Everything is fine with the plugin, i have access to all the features. I am 100% sure it is using the mysql on my webserver, it found the databases and allowed me to add the server under the admin panel for the banmanager web site. I didnt know if it takes a while to update? The tutorial i watched showed instant update on the website. 

Under past player bans, it shows

Myservername                                                   (the number 2, in red!)

everything else is blank, nothing under recent bans. At first i didnt think it was using my web server data base, because the size never changed, yet now its bigger.

**Comment by frdmn** [comment]
The web interface has its own repository:

https://github.com/BanManagement/BanManager-WebUI/issues

Can you re-raise the issue over there? This repo here is dedicated for the Java plugin :)
