### ISSUE TITLE
PlayerData

### ISSUE THREAD

**Issue by Leblanct** [BanManagement/BanManager#394]
Hey there!

As I try to get the player to be punished, using the API
I use:

Player toPunish = Bukkit.getPlayer(args[0]);

however it tells me it has to be a PlayerData when I try to call the BmAPI.mute();

I then used, 

PlayerData toPunish = (PlayerData) Bukkit.getPlayer(args[0]);

but now it gives me an error on that line when I do /rmute (that's the command I've set)

Any help?

**Comment by Kakifrucht** [comment]
PlayerData toPunish = new PlayerData(Bukkit.getPlayer(args[0]));

**Comment by confuser** [comment]
Or alternatively

```
PlayerData toPunish = BmAPI.getPlayer(args[0]);
```

assuming args[0] is a String and a players name.

**Comment by Leblanct** [comment]
Thanks guys! But I figured it out before this answers, when I realized there is a ''.getPlayer''.

Thanks a lot though.
