### ISSUE TITLE
Unknown Column

### ISSUE THREAD

**Issue by Leblanct** [BanManagement/BanManager#396]
Hey there.

While trying to setup the WebUI, I've added the database, however this error comes up

Uh oh, we've found an error.
Unknown column 'expires' in 'field list'

Any ideas how to fix it?

**Comment by EvilOlaf** [comment]
Please state your issue at the Web-UI repository. This one here is for the java plugin.

https://github.com/BanManagement/BanManager-WebUI

**Comment by frdmn** [comment]
What @EvilOlaf said.

Also I assume the issue is that you run a BM version < 5.6.0. Update your Java plugin and the warning should be gone. :)
