### ISSUE TITLE
Question - Custom Web Tabs

### ISSUE THREAD

**Issue by MrMonkeyPants344** [BanManagement/BanManager#398]
Hello,
Ive just started to use the BanManager on my website and im wondering how to add custom tabs. Like when you enter the page you have the default "Home" and "Statistics" tab but how do I create custom tabs like "Forums" "Help" ect.

Regards
Simon | MrMonkeyPants344

**Comment by frdmn** [comment]
Can you re-open this issue in the proper repository for the web interface: https://github.com/BanManagement/BanManager-WebUI

This repository here is dedicated to the Java part of BanManager :)
