### ISSUE TITLE
Feature Request - Hand over the message to Events

### ISSUE THREAD

**Issue by ferdl9999** [BanManagement/BanManager#399]
Hello,

could you please hand over the final message to the events? I wanna inform all staff members on a bungeecord network when a player was warned or banned for example.

**Comment by confuser** [comment]
Most notification messages are actually created on event listeners as they can be toggled off in the config, as well as the fact they're not really stored, but generated.

If you really need the notification messages, you can very easily replicate them yourself. The performance impact will be negligible as the events are called async.  

https://github.com/BanManagement/BanManager/blob/master/src/main/java/me/confuser/banmanager/listeners/BanListener.java#L23
