### ISSUE TITLE
Allow replacement of "Console" as actor

### ISSUE THREAD

**Issue by EvilOlaf** [BanManagement/BanManager#401]
Hi @confuser ,

as you might know I use the the awesome `warningActions` as well as the `hooks` features.
Especially at the `warningActions` the server will enforce additional punishment like `kick`, `tempban` or `ban`. The enforcing team member is here automatically set as "Console".

My suggestion here is to add more options to customize this behavior. 
The easiest way might be to allow replacing the name "Console" by "Server" or "Automatic".

As always thank you for reading and

Best regards
Olaf

**Comment by confuser** [comment]
This is already possible within the console.yml file

**Comment by EvilOlaf** [comment]
I'm getting old. Thank you for your fast answer and sorry for any inconvenience :).

Best regards
Olaf
