### ISSUE TITLE
Error on start up causing ban manager to only partly load

### ISSUE THREAD

**Issue by voigtman** [BanManagement/BanManager#402]
https://paste.sh/xzoWTNbF#z5Zw956GT1ABcJ1lYxzc6dqO
and then 
https://paste.sh/ZWPP8F2h#fhjrwnLKuq8_aeZEcAvhjQ10

Commands don't appear to work, and neither are punishments..

It had been working fine until the last couple of days.

**Comment by confuser** [comment]
You have a data integrity issue. Update to a developer build, build 175+ which caters for such an issue and will output a warning on startup instead of crashing.

http://ci.frostcast.net/job/BanManager/
