### ISSUE TITLE
Feature Request - Previous usernames

### ISSUE THREAD

**Issue by Aeef** [BanManagement/BanManager#403]
I think it would be cool if you could see a users previous usernames in bminfo. Possibly also the ability to bminfo a users old username, and have it return their current profile.

It could return something like this:
`Previous usernames:
User1, User2`

**Comment by confuser** [comment]
This seems like it would be out of the scope of BanManager and better off in a separate plugin (which is what I've done for Frostcast). If this was implemented I imagine the next feature request would be to punish players via previous names which will just get confusing if people take other people's names after 30 days.
