### ISSUE TITLE
sql error when banning some players. (Unable to run insert stmt on object )

### ISSUE THREAD

**Issue by d1One** [BanManagement/BanManager#405]
I get this error quite often. I try to ban someone that is online currently and get an error saying "Player-name not found, are you sure they exist?"

Log: http://pastebin.com/fPvTZJyv

Im spigot 1.8.8 Using latest release of BM, on a offline server with onlineMode: false

**Comment by confuser** [comment]
> [15:14:34] [Craft Scheduler Thread - 218/INFO]: [BanManager] Requesting UUIDs for legendary12

Are you 100% sure online mode is set to false, as the above message in your log wouldn't display if it was.

Please try a developer build as well.

http://ci.frostcast.net

**Comment by d1One** [comment]
Yes I am. Im trying the latest dev build, it also bugs. I can now ban this specific user but when i use /bminfo it also gives the same error "not found, are you sure they exist"

**Comment by confuser** [comment]
Check your players table. It sounds like you might have multiple uuids for the same player name.

**Comment by d1One** [comment]
I checked the database, and the problem is BanManager ignores name casing even when onlineMode  is set to false. So if a user logs in with the same name but different casing it register 2 times with 2 different UUIS.

**Comment by confuser** [comment]
BanManager doesn't officially support offline mode. That being said, it appears that the UUID generation baked into bukkit are case sensitive in offline mode which is what is causing this problem.

**Comment by d1One** [comment]
Well, all other plugins seem to work fine, they always point commands to the first name registered. But if offline is not supported then i guess this this Issue can be closed.
