### ISSUE TITLE
Kick player notify noreason do not exits.

### ISSUE THREAD

**Issue by voodootje0** [BanManagement/BanManager#409]
Hey BanManager,

Can you please add an option in the config for kicks without any reason (notify)?

![image](https://cloud.githubusercontent.com/assets/6852308/10124308/4eeaff46-6552-11e5-8490-1f90e5b6c177.png)

Thanks for adding it!

- voodootje0

**Comment by Coolaxer** [comment]
I think this is already possible. Just edit your messages.yml and remove - "for [reason]"

**Comment by voodootje0** [comment]
Yeah but if you kick for a reason i cant see the reason, can you make a noReson notify section please?

**Comment by confuser** [comment]
`kick.player.noReason` already exists in both /kick and /nlkick

https://github.com/BanManagement/BanManager/blob/master/src/main/java/me/confuser/banmanager/commands/KickCommand.java#L84-L88

**Comment by voodootje0** [comment]
Yes, the player kick message works but the staff notify doesn't work.
![image](https://cloud.githubusercontent.com/assets/6852308/10167230/eedd8020-66c7-11e5-8b34-b9becb51c61c.png)

**Comment by confuser** [comment]
I'm sorry I don't understand the problem now. All bans require reasons, it's the main premise of this plugin. The reason is only optional for kicking and as of the latest developer builds, unbanning/unmuting.

**Comment by voodootje0** [comment]
When you kick some player with no reason he will get kicked for kick.player.noReason.
But players with the permission `bm.notify.kick` they get 
![image](https://cloud.githubusercontent.com/assets/6852308/10170931/9d76f1f2-66d7-11e5-886d-242ab52347c9.png) and that player is kicked for no reason.

So my question is can you add `kick.notify.noReason` and `kick.notify.reason`
