### ISSUE TITLE
bminfo not working

### ISSUE THREAD

**Issue by Natedanp** [BanManagement/BanManager#411]
Hey, well recently we have decided to start using banmanager. So as I was setting it up and giving out the permission nodes to staff, I noticed /bminfo will not work for people with * or OP. I have added bm.command.bminfo and a few other things for it including bm.command.bminfo.others, but noone seems to be able to do it. We need this command for staff to check players warns as we basically run on warns. So can you tell me if I'm doing anything wrong? Also, Auto tabbing, or TabComplete is having problems. I've noticed auto tabbing does not work for online players but it works for offline players, why is that? Thanks in advance

**Comment by Natedanp** [comment]
I have 2 related posts on the autotabbing thing, and have figured out it could be essentials. Can you confirm that or is there anyway around that?

Posts
[#213](https://github.com/BanManagement/BanManager/issues/213)
[#210](https://github.com/BanManagement/BanManager/issues/210)

**Comment by EvilOlaf** [comment]
You could ask here https://github.com/drtshock/Essentials if this can be fixed at Essentials side. I still have exceptions spaming the console when someone uses tabcomplete at a BM command but I didn't care much as it works anyways.

`bminfo` works fine for me. How do you notice that it "does not work"? Error message? 
Did you try to debug your permissions using PEX debug to check if this is a permission related issue?

**Comment by Natedanp** [comment]
I actually just ended up getting it working. it was due to the staff I was asking not giving me the right message it gave them, so I ended up fixing it by adding the child perms it has so they can actually see each one instead of seeing blank which happens when you only have bm.command.bminfo, well complicated or not that's now working finally, but the tab thing, can you send me the error code you get? We are currently having some issues with our console so there isn't a way for me to look at it right now. Would be appreciated

**Comment by EvilOlaf** [comment]
Well just have a look at the issues you mentioned earlier. :grin:

**Comment by confuser** [comment]
If this is still an issue, please re-open
