### ISSUE TITLE
Feature Request - SoftMute

### ISSUE THREAD

**Issue by Iceee** [BanManagement/BanManager#412]
The idea behind this is to be able to mute or temporarily mute a player without explicitly denying messages.  They should simply not be shown to other players.

**Comment by confuser** [comment]
So the player still sees their messages in chat, but nobody else does?

**Comment by Kakifrucht** [comment]
What would be a use case scenario for this? Basically shadowmuting, right?

**Comment by Iceee** [comment]
Yes, the player would still see their messages but no one else would.  They would have no idea that they were muted.

**Comment by Agazed** [comment]
Clever idea! I use this concept with my anti-spam plugin where spam and advertisement messages are seen by the sender but not the server thus making people not attempt to bypass the filter in some way.

**Comment by confuser** [comment]
How would this work with blacklisted commands whilst muted?

**Comment by Iceee** [comment]
Good question. I'm not sure there's an elegant solution to that. 

It would either have to allow them or cancel the command with no message.

**Comment by EvilOlaf** [comment]
I am not sure if I like the idea of having someone "fake muted".
I more like to have a learning effect when players receive punishment for doing something wrong.

The punished player will just have more frustration (maybe wanted? Don't like.). Also what if other players want to interact with the "soft muted" player? Unnecessary questions will come up why he can't talk. Do a normal mute and everyone will know who and why. No need for questions.


My conclusion is that I would probably not use this feature.


Just my two cents.

**Comment by Iceee** [comment]
It's not meant to replace traditional muting, but the concept has been successfully used on other platforms to deter users who come back on different accounts.

**Comment by Agazed** [comment]
Yes. This isn't meant to replace muting how it currently is and instead be used with a different command. As for blacklisted commands, there should be a separate softmute blacklisted commands list instead where the admin can configure his preferences.

**Comment by EvilOlaf** [comment]
I am aware that this won't replace the usual muting. As said that were just my two cents :wink:

**Comment by confuser** [comment]
Required changes:
- Add comands
```
/smute <player> <reason>
/stempmute <player> <timeDiff> <reason>
```
- Add isSoft to mutes table/data storage
- Add new blacklisted command config option for soft muted commands, which are cancelled with no message
- Add new isSoftMuted method to BmAPI

**Comment by confuser** [comment]
Added in 4f6a661a0f5c0add1426f0d53bb1557e75b6126a

Untested
