### ISSUE TITLE
Internal Error while issuing ban.

### ISSUE THREAD

**Issue by Eternalrealms** [BanManagement/BanManager#413]
When issuing the command ./banall on a player it went trough but they player was still allowed to join the server (Even after he was kicked.) Then I tried to locally ban him and I got these errors http://pastebin.com/KdFSQh96 http://pastebin.com/VgLsbsDm . This happens often on my server is their a fix or is this a bug? 

Using spigot 1.8.8, Using BanManager V 5.7.0

**Comment by Coolaxer** [comment]
The issue is - "Duplicate entry '£¨PÐªO_ˆmc§¿•´' for key 'bm_player_bans_player_idx'"
There are duplicate entries in your mysql database. Since I am using 4.x for 1.6.4, I dont have much experiance with 5.x. But do try to go to the table bm_player_bans_player_idx and check for duplicate entries

**Comment by confuser** [comment]
Are you running in offline mode?

External syncing is set to a 5 minute interval, so it'll take a little while for all servers to contain the ban. If that's too slow, change the timings within the schedules.yml.

**Comment by Eternalrealms** [comment]
Yes, I am using Bungee. Will changing the setting cause performance issues?

**Comment by confuser** [comment]
Potentially, it'll affect how often the plugin will query the database. Most database servers should be able to handle a minute.

Please note that in offline mode, Bukkit considers players with the same name but with different casing to be unique, e.g. confuser is a different player to coNFuser. BanManager is affected by this.
