### ISSUE TITLE
Could not pass event PlayerBanEvent to Ban Manager v5.4.1

### ISSUE THREAD

**Issue by TNTPata** [BanManagement/BanManager#414]
So tried to ban my friend to test, but it only results in an error.
I do not know what this is caused by, i've turned the web upside down.
Pastebin to error log, hopefully someone can make sense of it.
http://pastebin.com/5N7jECCu

Edit: Needs to be read from the bottom up, my host's console is strange.

**Comment by confuser** [comment]
The latest version is v5.6.1, please ensure you are on the latest version before reporting bugs.

**Comment by TNTPata** [comment]
It's says on curse that it only works for CB 1.7.9 An update would be appreciated as it works perfectly on 1.8.x.
But thanks alot, both for the help and making such an awesome plugin

**Comment by EvilOlaf** [comment]
Many plugins are backwards compatible as well as older plugins can also be used on newer cb/spigot builds. Just give it a try... Always :grin:
