### ISSUE TITLE
Sync warns to notify on other servers

### ISSUE THREAD

**Issue by mcraftpete** [BanManagement/BanManager#415]
I have my ban system setup on multiple servers to all share 1 database the local one.

Is it not possible to /kick /warn when player is on a different server to staff ? Well it seems to log the warn but doesn't display anything to player, and doesn't actually kick the player unless you are on the same server as them.
If I set it to log would it make it kick cross server or not ?
Is it something not included or something I am doing wrong ?

**Comment by confuser** [comment]
Cross server kicking is not possible and is out of the scope of this plugin.

Warnings are somewhat cross server, they'll see it next time they join if you've warned them whilst on another server.

**Comment by mcraftpete** [comment]
ok , Well when it tempbans a player on another server it does a routine of kick the player from server ? then registers the ban in database does it ?
If so would this be a possible enhancement request ?

**Comment by confuser** [comment]
On the local setting, each minecraft server will check the database for changes, whether that be bans, unbans, mutes etc periodically, depending on your schedules.yml settings. If it comes across a new ban that it does not have in memory, it will kick the player if they are currently online on that server.

Is your feature request for warns to also sync, so if you warn a player on one server, and they are on another, they will still see it? If so, I'd be happy to implement that.

**Comment by mcraftpete** [comment]
yes it would be great for a players warn to show , sometimes we can warn a player when on another server on the network , ie they could easily be on same server and as you try to warn they move to another before you have type /warn player etc , same as kick , it feels important but we can almost bypass kick by a quick tempban instead so we can workaround , it just feels more normal to /kick is all, but yes being able to warn a player whos elsewhere on network would be great , but I guess it kinda logs it regardless just they don't receive it.
