### ISSUE TITLE
Big problem with banmanager

### ISSUE THREAD

**Issue by Psy2as** [BanManagement/BanManager#419]
Hi, i have a problem... when i start my server it takes 6 minutes loading the plugin
this is the screen: http://i.imgur.com/ycVIiya.png
can you help me plz? i can't wait so much loading the plugin
there is a solution for this or something?

**Comment by Agazed** [comment]
Slow database probably.

**Comment by confuser** [comment]
As @Agazed said, the most likely cause of this is a slow connection to the database. There's nothing that can be done on the plugin end unfortunately. I'd recommend contacting your provider for a solution.
