### ISSUE TITLE
Warn levels

### ISSUE THREAD

**Issue by B1acksheep** [BanManagement/BanManager#420]
Hey,
We have a few ideas / suggestions for the warn function.

1. Possibility of a level in the form of points (0-10).
For example, griefing of blocks is another level as the killing of animals.

2. Add Screenshots (upload from my pc to the web interface) or the direct link (imgur.com/abcde.png), to display this in the interface, as a "Proof" of the warning.
(This feature could also be used for bans.)

**Comment by Agazed** [comment]
#420 kek

**Comment by confuser** [comment]
How would one identify which warning should have what points amount, and how does this differ from the current `warningActions` config option?

**Comment by EvilOlaf** [comment]
My guess is he wants to add an (optional) parameter to the `warn` command to specify how much weight in "warn points" a particular warning should have.
So for example `/warn 2 griefing` would add two warning points (or warnings, depends on solution) to the player. If the player currently has zero warnings and gets a two-point-warning, an action defined at `warningActions` with the minimum of two warnings could be executed.

The Webinterface idea is nice. It should be posted in the proper repositry though. https://github.com/BanManagement/BanManager-WebUI

**Comment by B1acksheep** [comment]
Exactly,
In the current WarningActions every ban is equal. If you have e.g. 10 warnings for spamming you'll be banned and if you have 10 warnings for greifing you'll be banned. 
If you could define a number of total warning points you may have (e.g. 10  points)  and a number for each warning you could get more warnings for minor trespasses like spamming, and you could get less warnings for e.g. griefing. The whole warning system would be more dynamic.
You could define the level for each warning in the command:
e.g. /warn <player> <reason> <points>
The default could be 1 point
