### ISSUE TITLE
Offline mode -> UUID Bug

### ISSUE THREAD

**Issue by HelloItsRien** [BanManagement/BanManager#421]
http://pastebin.com/tcbEWtkh
=+-===========================-+=
Before I start I want to mention that we have
Config > onlineMode: false

We can't (temp)ban/(temp)mute players at our network,
because of the plugin checking on UUID (see the pastebin).

This means that if we ban/mute a player,
the plugin does nothing at all.

The plugin needs to check (if onlineMode: false), on OfflineUUID's.

Hope that we get each other,
thanks in advance.

**Comment by confuser** [comment]
onlineMode is already checked when executing commands, and grabs a case insensitive UUID for the player and assigns it to them.

https://github.com/BanManagement/BanManager/blob/master/src/main/java/me/confuser/banmanager/util/UUIDUtils.java#L150-L154

Please note that I don't officially support offline mode, and this was merely added via a PR from another member of the community.
