### ISSUE TITLE
[FEATURE] Join/quit check

### ISSUE THREAD

**Issue by HelloItsRien** [BanManagement/BanManager#422]
Hiya there!

We would like to see a value in the config for:
checkOnJoin: boolean
checkOnLeave: boolean

Now, the plugin checks on schedulers.yml,
but we want the plugin to check on bans
and mutes e.t.c. everytime a player joins.

Really like to see that implemented,
thanks in advance.

**Comment by confuser** [comment]
I will add `checkOnJoin`, however, please note, that it will send a lot of queries to your database. If you have bots spam joining your server, there is a chance it may overload the database instance.
