### ISSUE TITLE
Timezone Issue

### ISSUE THREAD

**Issue by UntoldFury** [BanManagement/BanManager#425]
Hello!
I was wondering how to change the timezone for my BanManager WebUI. It's set to an EU timezone, and I was wondering how to change it to a US Central timezone. Thanks!

**Comment by frdmn** [comment]
Please resubmit this issue in the appropriate [BanManager-WebUI](https://github.com/BanManagement/BanManager-WebUI) repository. I'll try to help you out over there.

The repo right here is dedicated to the Java plugin.
