### ISSUE TITLE
Can you make it so we can disable commands

### ISSUE THREAD

**Issue by Twi5TeD** [BanManagement/BanManager#427]
i made a plugin thats works better for checking for alts and its overriding my commands for the plugin is there anyway of disabling the command

**Comment by Coolaxer** [comment]
I think you could remove them from the plugin.yml

**Comment by confuser** [comment]
Unfortunately not. You can always use reflection to override it. Your command will always be accessible via /plugin:commandName which was added in 1.7+.

**Comment by DanielProGames** [comment]
@confuser it depends if @Twi5TeD's plugin is a Spigot plugin, because the "/plugin:command" alias is not automatically applied to BungeeCord plugins, unless he expreselly integrates it. I think yes, you can overwrite BanManager' commands using reflection, as @confuser says.
