### ISSUE TITLE
bminfo link size is too big to fit 1 chat line.

### ISSUE THREAD

**Issue by d1One** [BanManagement/BanManager#429]
Hi.
Using /bminfo on a player gives an unnecessarily big link to check the player on our web interface.

http://i.imgur.com/VV0suPL.png
The following link
http://192.99.32.32/banmanager/?action=viewplayer&player=PixelatedPotatos&server=0
Does not fit in one line so Minecraft splits it in two with makes only part of the URL clickable and therefore ends up not working. Would be nice to either have a embedded link shortner or replace some of the tags php uses to something shorter like:
http://192.99.32.32/banmanager/?a=v&p=PixelatedPotatos&s=0 or something... 

Not sure if this should be posted here or on the web interface github since it could be resolved 2 different ways, either by changing the link structure or by adding some kind of shortener.

**Comment by confuser** [comment]
I'm afraid that this is out of the scope of the plugin. You can quite easily solve this via using a domain instead of using an ip address. 

The fact that the link appears to be split when clicking on it sounds like a bug within your craftbukkit build.
