### ISSUE TITLE
Syncing 

### ISSUE THREAD

**Issue by kemit-the-frog** [BanManagement/BanManager#432]
When I try to sync across multiple servers (I'm testing with 2 servers), one server is working normal and i can ban, mute, ect. thru console but the other server just gets put into alarm mode and disables it self. Both configs are the same and I will attach them here. http://pastebin.com/JZs1LV4H (config)
Thanks
Kemit-the-frog

**Comment by confuser** [comment]
Alarm mode?

**Comment by kemit-the-frog** [comment]
when it disables it self.

**Comment by roastnewt** [comment]
You shouldn't use the same database/tables for multiple servers.  If you want to do global bans, you need to have separate local tables, and enable the "external" section of the config for shared tables.

**Comment by kemit-the-frog** [comment]
so each server has to have a separate table on the one database?

Thanks

**Comment by confuser** [comment]
You can certainly have the same database and tables for multiple servers under `local`. BanManager supports syncing all punishments across servers.

What I don't understand is `alarm mode`. Do you have any errors on startup? Can you post the BanManager output from the console?

**Comment by kemit-the-frog** [comment]
Server 1: http://pastebin.com/CpfPpwSm
Server 2: http://pastebin.com/cQtk0fUX

Thanks

**Comment by EvilOlaf** [comment]
Could not create connection to database server. Attempted reconnect 10 times. Giving up.

Check your database credentials.

**Comment by kemit-the-frog** [comment]
All credentials are correct

**Comment by EvilOlaf** [comment]
Does your mysqld listen to localhost only?

**Comment by kemit-the-frog** [comment]
Yes, the problem is that if you ban a player on one server it does not carry over.

**Comment by kemit-the-frog** [comment]
or any other punishment for this

**Comment by kemit-the-frog** [comment]
Could it be a different config file?

**Comment by confuser** [comment]
Your second server cannot connect to the mysql database. That is the
problem.  Read the FAQ on the plugin page. It covers your issue.

**Comment by EvilOlaf** [comment]
Your issue can not be solved by bm. You need to configure your databases properly to allow external access for your secondary server.

**Comment by kemit-the-frog** [comment]
The database should work, I talked to my hosting company and they said "External access SHOULD work, but that is not something that we offer support for. Meaning that we have no intention of blocking it, but if it doesn't work for you then we won't do anything about it since it is not for a service owned through our company." 
Thanks

**Comment by ApfelUser** [comment]
@kemit-the-frog Check your Firewall then. Look at your logs! It has nothing to do with BanManager :smile: 

If you're really sure that this is a problem with BanManager, please send the results of

```
mysql -u <username> -p -h <ip/xxx.xxx.xxx.xxx>
```

**Comment by confuser** [comment]
Closing as not a plugin issue.
