### ISSUE TITLE
Ban doesn't work in  5.7.0 (latest from bukkit)

### ISSUE THREAD

**Issue by JohOply** [BanManagement/BanManager#435]
Hi,

I've found a big problem : when i ban player with /ban or /tempban, they are not kicked, and they could join the server

For a player, i had tempban him. He joined the server. So i ban him. He wasn't kick. I stop the server, and i can't use /bminfo (2 entries for this player in database mysql). I removed one, and i can use /bminfo. I bantemp again. For now, i don't know if he can join.

I use Spigot 1.8.8, and BanManager 5.7.0.

It is a big problem !!

**Comment by EvilOlaf** [comment]
Using the same version and don't have any issues like that.
Check your console output for further information whats wrong.

**Comment by JohOply** [comment]
NB: Banip works perfectly

**Comment by Kakifrucht** [comment]
Double entries in your database? If you always had those you can run a SQL query to remove doubles.

**Comment by confuser** [comment]
By the sounds of it, you are running in offline mode? BanManager doesn't fully support it.

**Comment by JohOply** [comment]
Yes, i running in offline mode... Anybody find it intolerable, but i am in favor of the discovery : myself, at the begining, when i started minecraft, i used a crack version.

**Comment by confuser** [comment]
Bukkit/Spigot/Craftbukkit takes takes player names as case sensitive in offline mode, where as in online it does not. I.e. coNFUSER is the same as confuser in online mode, but they are registered as different players in offline mode, as they generate different UUIDs.

Nothing was changed from 5.6 to 5.7 that affects the way bans are handled.

Offline mode support was added as a community contribution, and I have no plans to officially support it. If anyone wishes to fix this issue, feel free to make a PR, or raise a bug on Spigot.
