### ISSUE TITLE
Webpage Player Info not showing

### ISSUE THREAD

**Issue by dangerORclose** [BanManagement/BanManager#438]
Hey, i have set up all and the ban page is http://www.bans.wafmc.be/index.php But for an unknow reason does it not shows the player bans. And when i search a name i get a error pls go look http://www.bans.wafmc.be/index.php thanks.
U can see in red that there are 5 bans but no names or stuff.
On the 4.0 version was it working but there is no note and stuff so.
I deleted the plugin, the folders.
Deleted the database and recreated one.
I have edited the new databaase ip and password in the php on the webpage.
All what i did works for 4.0 but not for the newest version.
The plugin works perfect only not showing on the webpage pls help thanks

**Comment by confuser** [comment]
Issues for the web interface should be posted over at https://github.com/BanManagement/BanManager-WebUI/issues

However I will provide support to you here.

According to your stats page, you have no currently banned players. If that's the case, this behaviour is expected.

**Comment by dangerORclose** [comment]
No that is the probelm.
I have banned, mited, ipbanned, players.
