### ISSUE TITLE
Incorrect IP Addresses.

### ISSUE THREAD

**Issue by Time6628** [BanManagement/BanManager#439]
BanManager does not appear to get the correct IP addresses from a bungeecord instance and instead displays the bungeecord IP for all users.

**Comment by Kakifrucht** [comment]
Did you set bungeecord to true in spigot.yml?

**Comment by Time6628** [comment]
Yes i did, every other plugin works besides this one(PEX, Essentials, GriefPrevetion,etc).

**Comment by confuser** [comment]
PEX does nothing with ip addresses, so not quite sure why that's mentioned here?

BanManager just pulls the ip address on AsyncPlayerPreLoginEvent. I've not had any other reports of the same issue.

Can anyone else running behind bungeecord confirm if this is an issue?

**Comment by Time6628** [comment]
> PEX does nothing with ip addresses, so not quite sure why that's mentioned here?

BanManager just pulls the ip address on AsyncPlayerPreLoginEvent. I've not had any other reports of the same issue.

Can anyone else running behind bungeecord confirm if this is an issue? > - confuser

I was just listing plugins that were receiving the correct data from the bungeecord instance.

**Comment by confuser** [comment]
Closed due to lack of information and unable to reproduce.

**Comment by tyler2k15** [comment]
This is an issue, on our network we just add the proxy up to ignore duplicate ip check. This is not @confuser fault, it is how bungee is. All connections go through the bungee which then forwards to correct server. So essentially it is the bungee that is connecting to the servers.

**Comment by confuser** [comment]
Setting forward in bungee to true should solve this issue in Bungeecord. At least, that was the case when I used to run it on Frostcast (albeit a couple of years ago, it may have changed since then). The only other time we ever experienced this issue, even with LilyPad, was when our old forward facing appliance (ddos protection) ip was being forwarded and not the players.

**Comment by Time6628** [comment]
The ip is being forwarded, just not to this plugin for some reason.
