### ISSUE TITLE
A way to add "private" comment to ban reason

### ISSUE THREAD

**Issue by columb** [BanManagement/BanManager#44]
Would be nice to have a bit more confidential way to set ban reason.
 i.e. /ban Notch Hacking #Private stats from NoCheatPlus
Where Notch should only know about hacking but not about exact hack which triggered this ban.
OR
/ban jeb_ Abuse #Griefed my house.
It should be possible to view this "comments" (which are actually part of the ban reason) with /bminfo or admin part of the web interface.

**Comment by Iceee** [comment]
Was this implemented?

**Comment by EvilOlaf** [comment]
Not yet ^^
As workaround you could use the `/addnote` feature

**Comment by Iceee** [comment]
I was considering that as well.  I think that's something that should be added to BmAPI.

**Comment by confuser** [comment]
The problem is that # is now used for predefined reasons so another character will need to be used

**Comment by Iceee** [comment]
What about parentheses?

**Comment by confuser** [comment]
Parentheses could work

`/tempban playerName 3d Hacking (uses nodus)`

would temp ban the player and create a note with the message `uses nodus`

**Comment by EvilOlaf** [comment]
Hm I think ( ) would be too common. People could use them already and would be confused if that won't work anymore...

**Comment by confuser** [comment]
I can't imagine people using parentheses in their reasons, but this option will be toggled and disabled by default so it won't cause any problems.
