### ISSUE TITLE
Synchronization Requires /bmsync local

### ISSUE THREAD

**Issue by Iceee** [BanManagement/BanManager#442]
Servers don't seem to synchronize properly without running /bmsync local.  Have you run into this before?

To clarify, this seems to be unbans only.

More info:
I use "local" only since I don't want bans separate for each server.

**Comment by confuser** [comment]
The default syncing is set to every 30 seconds. If that's too slow, feel free to reduce the amount within schedules.yml.

**Comment by Iceee** [comment]
It looks like it's not synchronizing at all unless I force it with /bmsync local.  The schedules.yml file shows that it's synchronizing, but unbans aren't happening with those synchronizations.

**Comment by confuser** [comment]
I'll investigate and see if I can reproduce.

**Comment by confuser** [comment]
Just to confirm, do you get any warnings on startup from BanManager about there being a time difference?

**Comment by confuser** [comment]
Unable to reproduce. Please provide the requested information above if you are still having issues.
