### ISSUE TITLE
banall/muteall no not ban/mute

### ISSUE THREAD

**Issue by Hu5ker** [BanManagement/BanManager#443]
We use the plugin in our server. The previous versions works fine. But with the latest one we have this problem.

When some use /banall name reason, the guy who supposed to be banned is in the server and he not get banned or kicked out of the server. Is the same thing with /muteall.

According to my staff, when they type /ban user reason right after /banall, it say: <i>"An error occured whilst attempting to perform this command. Please check the console for further details"</i>.

What's going on?.

Regards!.

**Comment by EvilOlaf** [comment]
How about checking your console for further details?

**Comment by confuser** [comment]
Closed due to lack of response and information.
