### ISSUE TITLE
uhh

### ISSUE THREAD

**Issue by williamifyy** [BanManagement/BanManager#445]
It connects to the mysql server, then freaks out and no one can join... http://hastebin.com/ozuguqucaq.coffee

**Comment by EvilOlaf** [comment]
User wevans_bandb already has more than 'max_user_connections' active connections

**Comment by tyler2k15** [comment]
@williamifyy Is this the latest version? If so, I had the same issue where it was maxing connections even after increasing max_connections to 500, and then higher to 300. 

'nano /etc/mysql/my.cnf'

After reverting back to 5.3.0, however, it runs fine with no errors. Our current connections is 118 for the entire SQL server

**Comment by williamifyy** [comment]
@tyler2k15 Yeah, newest version

**Comment by confuser** [comment]
@williamifyy do you still get the same issue with v5.3.0?

**Comment by tyler2k15** [comment]
@williamifyy #447 (Not sure if it applies to you, but try version 5.3.0)
Also, are you using Spigot/Bukkit or it a model server using Cauldron? If modded what modpacks/mods/plugins are you running? We may be able to compare to see what is causing the issue.

Plugins: 10.11 14:49:18 [Server] INFO Plugins (56): MySignEdit, Questioner, StaffMonitor, BarAPI, GroupManager, Minetrends, PluginManager, FTBHelper, AutoResponse, Lockette, BanManager, BiomeEdit, BanItem, TekkitCustomizer, WorldEdit, UUIDProvider, OpenInv, Essentials, ClearLag, WorldBorder, HeadsPlus, SimpleAutoAnnouncer, ProtocolLib, PvPControl, AutoSaveWorld, AsyncWorldEdit, EssentialsChat, SimpleHelpTickets, Lottery, Vault, TakeMeHome, BetterEnderChest, KillerMoney, HolographicDisplays, Marriage, WorldGuard, EssentialsProtect, Prism, EssentialsSpawn, Commandspy, Smileychat, Jobs, CommandSigns, WhatIsIt, Citizens, VanishNoPacket, WGRegionEvents, WGCustomFlags, UltraTrader, EnjinMinecraftPlugin, floAuction, WGTimeFlags, WGFlyFlag, Denizen, Towny, TownyChat

Version output: 10.11 14:49:55 [Server] INFO This server is running KCauldron version 1.7.10-1492.150 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

Modpack: HermitCraftModsauce2 (Newest update works fine on all other servers)

**Comment by confuser** [comment]
Closing due to lack of response. Please use #447 if you are still having this problem.
