### ISSUE TITLE
Mysql statement closed

### ISSUE THREAD

**Issue by ModdyLP** [BanManagement/BanManager#446]
Hello today i get this error in my console. I cant see any problems on the server but i want to report befor it come an error.

Log: http://pastebin.com/HB3WRNCR

Best Regards
ModdyLP

**Comment by confuser** [comment]
What version of BanManager are you running?

**Comment by ModdyLP** [comment]
The newest the version 5.7.1

**Comment by confuser** [comment]
I'm hoping this issue was caused by ORMLites inbuilt pool functionality, latest version now uses Hikari instead. Please make a new issue if you come across this again in v5.8.0+
