### ISSUE TITLE
sync keeps breaking

### ISSUE THREAD

**Issue by mcraftpete** [BanManagement/BanManager#448]
Hi,
I keep having my sync breaking , i restart and often this fixes the issue.

I had this error at same time when i went to a diff server to ban a player...
http://pastebin.com/Lk5E6xYU

**Comment by EvilOlaf** [comment]
```
[13:12:11] [Craft Scheduler Thread - 3297/WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'Ã¡Ã‘yÃ«LÅ’Ã™Ã«5ï¿½Ã«Ë†' for key 'bm_player_bans_player_idx'
```

There were a few similar issue reports AFAIR. Check the closed ones for `duplicate entry`.

**Comment by mcraftpete** [comment]
oh ok , has latest upsates fixed it ?

**Comment by confuser** [comment]
If you're running BM using a local setup to sync bans across multiple servers, why are you re-banning on each server manually?

If the amount of time it takes for the bans to sync across all servers is too long, edit your schedules.yml accordingly.
