### ISSUE TITLE
Ban-Broadcast as Globalmessage

### ISSUE THREAD

**Issue by dweSheppard** [BanManagement/BanManager#450]
Hay, I use a global chat plugin, unfortunately, the ban-broadcasts are only displayed in local chat, is there a way to change that?

**Comment by confuser** [comment]
BM doesn't directly hook into Bungeecord nor LilyPad, and I have no plans to do so.

It would be possible for your global chat plugin to integrate with BM's events to make the notifications global, or to create a separate plugin which achieves this.

That being said, I can add an option that on sync, when a new ban/mute/warning etc is detected, it could make a broadcast.

**Comment by tyler2k15** [comment]
Is this necessary if using the "network" database, it will broadcast on all servers anyways

**Comment by confuser** [comment]
It only does this for the external/network, not for those using local across all servers

**Comment by tyler2k15** [comment]
Touche. I'm so used to using separate databases for everything I forget some do that

**Comment by confuser** [comment]
Released as v5.7.2
