### ISSUE TITLE
PlayerMuteRecord INSERT SQLException

### ISSUE THREAD

**Issue by MeMyselfMC** [BanManagement/BanManager#451]
When the plugin is loaded, unloaded, and/or syncs data (local I think, not external), this error is thrown to the console:

http://hastebin.com/ujipewazov.rb

Running the latest Spigot 1.8.8 build & BanManager development build number 208 (currently latest).
I'm behind BungeeCord (latest development build) on CentOS 6.6 x64, Java 8u66, MariaDB.

**Comment by EvilOlaf** [comment]
https://github.com/BanManagement/BanManager/issues/441

**Comment by confuser** [comment]
Solution is in the issue linked above.

Going to leave this issue open to fix it once and for all.

**Comment by confuser** [comment]
Which version did you update from? 5.6?

**Comment by MeMyselfMC** [comment]
Thanks, fixed by running `ALTER TABLE `bm_player_mute_records` ADD COLUMN `soft` TINYINT(1)` manually. And yeah, I updated from 5.6.
