### ISSUE TITLE
Name autocomplete not finding user in specific case.

### ISSUE THREAD

**Issue by mibby** [BanManagement/BanManager#453]
BanManager dev 208

Testing out commands on a user, the autocomplete/find is not finding a user. Essentials banning system doesn't have this problem.

Player name: iMxAndyy

```/kick Andy test```
```[player] is offline```

```/kick iMx test```
```iMxAndyy has been kicked by mibby for test```

**Comment by EvilOlaf** [comment]
Did you check your console if error messages show up on trying this?

**Comment by mibby** [comment]
No errors occurred at all.

**Comment by confuser** [comment]
BM requires using the full name to enact commands and does not support partial name lookups. Solution is to use tab to autocomplete the name. Unless you're saying tab autocomplete is not finding the name?

**Comment by mibby** [comment]
Ban manager does not require the full name if you use the beginning of their name for partial name banning/kicking though. Is there no way to have partial name banning/kicking for any part of their name to be similar to how Essentials handles player involved bans/kicks?

**Comment by confuser** [comment]
BanManager does require the full name for banning and kicking.

Let's say I was on a server, and someone wished to enact a BM command against me.

`/ban conf testing`

Now how is BanManager supposed to know whether that relates to me, i.e. confuser, or someone who has the name `conf`? 

By allowing partial name support, it adds confusion and potential bug reports.

v4 did support partial names, but that was before name changes and UUIDs were implemented. 

As players change their name so often, attempting to execute commands against players via partial names, the likely hood of picking the wrong player is incredibly high.
