### ISSUE TITLE
[Enhancement] /warnall command

### ISSUE THREAD

**Issue by tyler2k15** [BanManagement/BanManager#454]
Hello,

I have a simple request.  I am running a bungee network and we are in the process of switching to a global chat system but we are running into the issue that there is no global warn command so it would not be possible to warn players on other servers unless the staff has console access or is logged into that server. 

Thanks!

**Comment by confuser** [comment]
The problem with /warnall, is it means they'd have the same warning logged in every server, and would see it every time they joined each server.

**Comment by tyler2k15** [comment]
Didn't think about that, although, we have decided against having a global chat plugin so I'll go ahead and close this.
