### ISSUE TITLE
[Feature] Sync to local banned-players.txt

### ISSUE THREAD

**Issue by connection-lost** [BanManagement/BanManager#456]
I think this is a removed feature?
There should be an option that automatically sync bans from BanManager to local banned-players.txt file.
Reason:
1. It provides fallback support. In case the database server is down, BanManager will disable upon start. This kind of incident is not possible to be detected by server admins thus server will keep running in this situation.
2. Plugins such as dynmap will mute banned players' chat on its web interface. Such feature can only rely on ban records on the server.

**Comment by confuser** [comment]
It was removed as it was causing a lot of the lag issues in v4 with the UUID update on Bukkit; and I didn't want to be subjected to any further breaking API changes. 

You can quite easily recreate this either via another plugin listening on the BM events, or setup a cronjob to execute `/bmexport players`, replace the banned players txt file, and reload the vanilla bans in memory.

If your database goes down, I wouldn't exactly expect a standard server to still be running without issues. If you fear it does, then you should be adding redundancy at the database layer, via clustering. A database is as important as the application itself.
