### ISSUE TITLE
Errors in Console

### ISSUE THREAD

**Issue by Dooleylabs** [BanManagement/BanManager#459]
Not sure if this is a dupe of https://github.com/BanManagement/BanManager/issues/455 but the console gets spammed by the following lines on startup:

19.11 08:01:07 [Server] INFO Loaded 0 ip range bans into memory
19.11 08:01:06 [Server] INFO Loaded 0 ip bans into memory
19.11 08:01:06 [Server] WARN ... 14 more
19.11 08:01:06 [Server] WARN at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.executeRawNoArgs(BaseDaoImpl.java:604)
19.11 08:01:06 [Server] WARN at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.executeRawNoArgs(StatementExecutor.java:420)
19.11 08:01:06 [Server] WARN at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseConnection.executeStatement(JdbcDatabaseConnection.java:122)
19.11 08:01:06 [Server] WARN at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:622)
19.11 08:01:06 [Server] WARN at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:779)
19.11 08:01:06 [Server] WARN at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2570)
19.11 08:01:06 [Server] WARN at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
19.11 08:01:06 [Server] WARN at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
19.11 08:01:06 [Server] WARN at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
19.11 08:01:06 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
19.11 08:01:06 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
19.11 08:01:06 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
19.11 08:01:06 [Server] WARN at com.mysql.jdbc.Util.getInstance(Util.java:382)
19.11 08:01:06 [Server] WARN at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
19.11 08:01:06 [Server] WARN at java.lang.reflect.Constructor.newInstance(Unknown Source)
19.11 08:01:06 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
19.11 08:01:06 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
19.11 08:01:06 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
19.11 08:01:06 [Server] WARN Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'createdReason'
19.11 08:01:06 [Server] WARN at java.lang.Thread.run(Unknown Source)
19.11 08:01:06 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
19.11 08:01:06 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
19.11 08:01:06 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
19.11 08:01:06 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
19.11 08:01:06 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
19.11 08:01:06 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
19.11 08:01:06 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
19.11 08:01:06 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
19.11 08:01:06 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
19.11 08:01:06 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
19.11 08:01:06 [Server] WARN at me.confuser.banmanager.BanManager.onEnable(BanManager.java:110)
19.11 08:01:06 [Server] WARN at me.confuser.banmanager.BanManager.setupStorages(BanManager.java:396)
19.11 08:01:06 [Server] WARN at me.confuser.banmanager.storage.PlayerMuteRecordStorage.<init>(PlayerMuteRecordStorage.java:33)
19.11 08:01:06 [Server] WARN at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.executeRawNoArgs(BaseDaoImpl.java:606)
19.11 08:01:06 [Server] WARN at me.confuser.banmanager.internal.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
19.11 08:01:06 [Server] WARN java.sql.SQLException: Could not run raw execute statement ALTER TABLE bm_player_mute_records ADD COLUMN `createdReason` VARCHAR(255),  ADD COLUMN `soft` TINYINT(1), ADD KEY `bm_player_mute_records_soft_idx` (`soft`)
19.11 08:01:05 [Server] INFO Loaded 0 mutes into memory
19.11 08:01:05 [Server] WARN ... 14 more
19.11 08:01:05 [Server] WARN at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.executeRawNoArgs(BaseDaoImpl.java:604)
19.11 08:01:05 [Server] WARN at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.executeRawNoArgs(StatementExecutor.java:420)
19.11 08:01:05 [Server] WARN at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseConnection.executeStatement(JdbcDatabaseConnection.java:122)
19.11 08:01:05 [Server] WARN at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:622)
19.11 08:01:05 [Server] WARN at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:779)
19.11 08:01:05 [Server] WARN at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2570)
19.11 08:01:05 [Server] WARN at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
19.11 08:01:05 [Server] WARN at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
19.11 08:01:05 [Server] WARN at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
19.11 08:01:05 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
19.11 08:01:05 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
19.11 08:01:05 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
19.11 08:01:05 [Server] WARN at com.mysql.jdbc.Util.getInstance(Util.java:382)
19.11 08:01:05 [Server] WARN at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
19.11 08:01:05 [Server] WARN at java.lang.reflect.Constructor.newInstance(Unknown Source)
19.11 08:01:05 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
19.11 08:01:05 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
19.11 08:01:05 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
19.11 08:01:05 [Server] WARN Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'soft'
19.11 08:01:05 [Server] WARN at java.lang.Thread.run(Unknown Source)
19.11 08:01:05 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
19.11 08:01:05 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
19.11 08:01:05 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
19.11 08:01:05 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
19.11 08:01:05 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
19.11 08:01:05 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
19.11 08:01:05 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
19.11 08:01:05 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
19.11 08:01:05 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
19.11 08:01:05 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
19.11 08:01:05 [Server] WARN at me.confuser.banmanager.BanManager.onEnable(BanManager.java:110)
19.11 08:01:05 [Server] WARN at me.confuser.banmanager.BanManager.setupStorages(BanManager.java:395)
19.11 08:01:05 [Server] WARN at me.confuser.banmanager.storage.PlayerMuteStorage.<init>(PlayerMuteStorage.java:42)
19.11 08:01:05 [Server] WARN at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.executeRawNoArgs(BaseDaoImpl.java:606)
19.11 08:01:05 [Server] WARN at me.confuser.banmanager.internal.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
19.11 08:01:05 [Server] WARN java.sql.SQLException: Could not run raw execute statement ALTER TABLE bm_player_mutes ADD COLUMN `soft` TINYINT(1), ADD KEY `bm_player_mutes_soft_idx` (`soft`)
19.11 08:01:05 [Server] INFO Loaded 0 bans into memory
19.11 08:01:03 [Server] INFO Enabling BanManager v5.7.2-SNAPSHOT

I tried emptying the sql database, but after another reboot, the same thing happens. I think it keeps trying to generate pre existing entries.

**Comment by confuser** [comment]
Yep it's a duplicate.

Perfectly safe to ignore, I just re-enabled the stacktrace output on the dev builds to help track down a case where some installations weren't adding the soft column correctly.

**Comment by Dooleylabs** [comment]
What about this? This pops up after the server's been running for a few hours:

19.11 10:04:13 [Server] WARN ... 7 more
19.11 10:04:13 [Server] WARN at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.hasNext(SelectIterator.java:98)
19.11 10:04:13 [Server] WARN at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.hasNextThrow(SelectIterator.java:81)
19.11 10:04:13 [Server] WARN at me.confuser.banmanager.internal.ormlite.jdbc.JdbcDatabaseResults.next(JdbcDatabaseResults.java:64)
19.11 10:04:13 [Server] WARN at com.mysql.jdbc.ResultSetImpl.next(ResultSetImpl.java:7145)
19.11 10:04:13 [Server] WARN at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:794)
19.11 10:04:13 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
19.11 10:04:13 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
19.11 10:04:13 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
19.11 10:04:13 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
19.11 10:04:13 [Server] WARN Caused by: java.sql.SQLException: Operation not allowed after ResultSet closed
19.11 10:04:13 [Server] WARN at java.lang.Thread.run(Unknown Source)
19.11 10:04:13 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
19.11 10:04:13 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
19.11 10:04:13 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
19.11 10:04:13 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
19.11 10:04:13 [Server] WARN at me.confuser.banmanager.runnables.Runner.run(Runner.java:28)
19.11 10:04:13 [Server] WARN at me.confuser.banmanager.runnables.ExpiresSync.run(ExpiresSync.java:72)
19.11 10:04:13 [Server] WARN at me.confuser.banmanager.internal.ormlite.stmt.SelectIterator.hasNext(SelectIterator.java:103)
19.11 10:04:13 [Server] WARN java.lang.IllegalStateException: Errors getting more results of class me.confuser.banmanager.data.PlayerWarnData

**Comment by EvilOlaf** [comment]
This probably belongs here: https://github.com/BanManagement/BanManager/issues/446
