### ISSUE TITLE
Punish players who haven't joined the server

### ISSUE THREAD

**Issue by Aeef** [BanManagement/BanManager#460]
Could you please add an option to toggle off (or just disable completely) the behaviour that prevents punishments being issued to players who have not joined the server. 

Maybe if you wanted to keep this behaviour to prevent mistakes (the only reason I can think of having it), just allow the UUIDs of players to be banned, even if they haven't joined?

Possible uses:
- My personal issue, is that I have a list of UUID's of around 10k cracked alternate accounts, that some players use combined with VPNs/proxies to bypass bans. I can't ban these accounts unless they have connected to the server, which they haven't.

- You have a specific player you don't want to allow onto your server, but they've never joined.

- You get information from other servers of notorious hackers, griefers etc, and want to ban them before they are able to join.

Odd examples I know...

**Comment by Kakifrucht** [comment]
If you have 10k accounts, your best bet would be to directly feed them to the database.

**Comment by confuser** [comment]
How do you propose bypassing Mojang's rate limit when looking up usernames <-> UUIDs? It's the only way if they've never joined the server before.

**Comment by confuser** [comment]
Closing due to lack of response.
