### ISSUE TITLE
Doesnt work /via offine mode

### ISSUE THREAD

**Issue by Legoman99573** [BanManagement/BanManager#461]
My server just got this, then we all cant connect. Can you fix offline support, and for bungee support.

**Comment by confuser** [comment]
If you're behind bungeecord and it's in online mode, BanManager should also be in online mode. Ensure you have bungeecord forwarding enabled in your spigot.yml file.

I have no intentions of fixing offline mode support. Anyone is welcome to PR a fix however.

**Comment by Legoman99573** [comment]
i did, noone (including myself) can connect

**Comment by confuser** [comment]
Then it's not an issue with BanManager as it only refuses player connections if they are banned.

**Comment by Legoman99573** [comment]
Noone is banned

**Comment by Legoman99573** [comment]
Just got plugin

**Comment by Legoman99573** [comment]
Is this why noone can connect:
duplicateIpCheck: true

**Comment by Legoman99573** [comment]
Ill check if a proxy plugin is causing it

**Comment by Legoman99573** [comment]
i did that, but no connection still

**Comment by Legoman99573** [comment]
is there a reason there is no ping response by bungee @confuser

**Comment by Legoman99573** [comment]
Fixed. A plugin hated your plugin. Got rid of it. Thanks for your help, and love improvements. You got me back on this plugin. Please post.
