### ISSUE TITLE
Option to change tab complete

### ISSUE THREAD

**Issue by LaughNgamez** [BanManagement/BanManager#464]
If you have a large amount of players in your ban database tabbing to ban/mute someone can be a pain. It would be ideal to have an option to make it so tab complete just searches through online users.

**Comment by EvilOlaf** [comment]
Yep. Go to your `config.yml`

```
# Set to false to disable offline name completion
offlineAutoComplete: true
```
Set it to `false` and you should be fine.

**Comment by LaughNgamez** [comment]
Oh my mistake, thanks!
