### ISSUE TITLE
Action Time Delay

### ISSUE THREAD

**Issue by GamerSynchro** [BanManagement/BanManager#466]
Hello,

 I'am currently experiencing an issue with BanManager on which I use for Cross-Server punishments. So, there seems to be a delay with me and I don't quite know how to solve it. I'am truly sorry if this issue has been brought up and solved but basically what I'am trying to say is that it takes around 10+ mins for it to actually ban someone such as if I do ' /tempbanall JefferyTheLlama Hacks ' it eventually temp bans them right after 10+ mins

**Comment by EvilOlaf** [comment]
AFAIK you can adjust the delay for syncs at the ´schedules.yml`
However the default values are way lower than ten minutes...

**Comment by GamerSynchro** [comment]
How can I make it so that its instant?

**Comment by confuser** [comment]
Can you provide your schedules.yml contents here please. This is the second report reporting something similar and I'd like as much information as possible.

**Comment by GamerSynchro** [comment]
Sure thing, here it is : http://pastebin.com/NuqvTY7L

**Comment by confuser** [comment]
Some of the timestamps are the same number, meaning they completed within milliseconds of one another. I'll try to debug tomorrow. You can if you like turn on debug mode in your config and you'll see how often each query runs. But, be warned, it'll be very noisy; lots and lots of messages.

**Comment by GamerSynchro** [comment]
Any update about the delay?

**Comment by confuser** [comment]
Not had a chance to look into it yet @GamerSynchro apologies, I'll get to this later today

**Comment by confuser** [comment]
@GamerSynchro Fixed, available as a developer build, 6+ https://ci.frostcast.net/job/BanManager/
