### ISSUE TITLE
[Request] BM info customize.

### ISSUE THREAD

**Issue by theshadyonehd** [BanManagement/BanManager#467]
Hey,
       I would like to customize which ranks can see what information. I dont think it is appropriate for my staff to see players ip's however i still think alot of the other information is very useful. Being about to customize who sees what notes would also be super useful.

Thanks

**Comment by confuser** [comment]
This is already possible via permissions

http://dev.bukkit.org/bukkit-plugins/ban-management/pages/commands-permissions/#w-permissions

**Comment by confuser** [comment]
If there's anything not there, please let me know and I will look into adding it.
