### ISSUE TITLE
[playerId] Not working in latest dev build #10

### ISSUE THREAD

**Issue by Foreme** [BanManagement/BanManager#469]
[playerId] Not working in latest dev build http://ci.frostcast.net/job/BanManager/10/

**Comment by confuser** [comment]
For which messages? I added it to the majority of messages, however there may have been some that were missed

**Comment by Foreme** [comment]
Part where you put the website links in, the ban managers

**Comment by confuser** [comment]
`[playerId]` is available within `info.stats.player` for `/bminfo`

**Comment by Foreme** [comment]
![ss 2015-12-13 at 05 16 22](https://cloud.githubusercontent.com/assets/10572148/11765455/47cf8cca-a1bd-11e5-843a-e73678f1f12a.png)

**Comment by Foreme** [comment]
![6598f392-a26a-11e5-89bf-d86f788c4715](https://cloud.githubusercontent.com/assets/10572148/11798381/3ca0b194-a32f-11e5-96a6-b96b19a79562.png)
