### ISSUE TITLE
TempMute functioning?

### ISSUE THREAD

**Issue by GamerSynchro** [BanManagement/BanManager#470]
Hello, when I attempt to mute a player it shows me this error on console ; http://pastebin.com/r2BaAMmQ

**Comment by EvilOlaf** [comment]
Maybe there is an issue with the syntax you are using. Try `/tempmute Tillamoon 5m Drama` instead of `5min`.

**Comment by confuser** [comment]
Compilation error, which build did you download? v5.7.2 was released yesterday on Bukkit dev.
