### ISSUE TITLE
Question: BanManager max connection timeout

### ISSUE THREAD

**Issue by Dooleylabs** [BanManagement/BanManager#472]
This happens randomly about once a week. I read through roughly 1700 lines of stack trace (which is the same error repeating 10 times xD) and it looks like it can't connect because the maximum number of connections are exceeded. That's not possible; the database is set to 100000 max by default by our host and BanManager is the only plugin using the database. My questions are:

1. Is this BanManager's fault?
2. If not, is this the server host's fault -- and should I use my own instance of mySQL on a private server?
3. How do I fix this if it's a user error?

Error Stack trace:
https://gist.github.com/Dooleylabs/cbce28dc8e31ec85ad15

Config File:
https://gist.github.com/Dooleylabs/abe8df23859d265003f3

If this is a duplicate, I apologize, but this is the only error that ever appears in my console.

**Comment by confuser** [comment]
BanManager only requires 10 connections by default which is suitable for single instance servers with an average of 400 online players. 10 is also sufficient for networks as well. Setting it to 100000 in the config gains absolutely no performance benefits, quite the opposite as it'll flood the database as it attempts to keep alive a lot of unnecessary connections.
