### ISSUE TITLE
max used connections by banmanager

### ISSUE THREAD

**Issue by Posse1** [BanManagement/BanManager#474]
This plugin is causing max used connections to go very high and eventually causes my sql server to stop responding.

when running the command  mysqladmin -u -p extended-status | grep Max_used_connections

i get this result

| Max_used_connections              | 3501          |

when i turn off ban manager the connections go away.

**Comment by confuser** [comment]
What's the maxConnections set to in your config?

**Comment by Posse1** [comment]
they used to be set to 100, i increased them to 3500 thinking it wud help, but it just keeps going higher and higher and eventually causes sql server to stop responding

**Comment by EvilOlaf** [comment]
Does not make sense to raise the max allowed connections in BM unless you are running a server with thousands of players.
See https://github.com/BanManagement/BanManager/issues/472

**Comment by confuser** [comment]
Right, I'm adding a max hardcoded limit as people keep reporting this as a bug with the plugin, but they fail to understand what maxConnections actually does.

**Comment by Posse1** [comment]
Hi, sorry to re-open this. I think I did not clarify the issue properly. I have not touched the maxconnections in BM config file. that is still set to default 10. 

I modified the max_connections from my.cnf for mysql server only when I noticed that it was needing more than 100. I reverted back to default 100 in my.cnf after I noticed no positive results.

My confusion is that howcome BM is reaching 3500+ even though it should not be using more than 10? Where is the fault occurring and how can I check on my side if it is my fault?

**Comment by confuser** [comment]
How many servers do you have running BanManager?

**Comment by Posse1** [comment]
Ban Manager is only running on one server as part of bungee servers. the other servers on the bungee network do not have the plugin. The server is a 100 slot server with player count varying from 15-40 on a daily basis, a lot of people do regularly connect and disconnect from the server if that helps at all.

**Comment by confuser** [comment]
Can we move this to #447 please, as others are also experiencing this issue, but I've as of yet been unable to reproduce it. The connection pool is handled by a 3rd party library, ORMLite.
