### ISSUE TITLE
[playerId] issue

### ISSUE THREAD

**Issue by Foreme** [BanManagement/BanManager#475]
Player ID will only work in BoNeMEAL if there are no dashes
5a8ac98462b3473f9cdf99a5ac49cd86
instead of
5a8ac984-62b3-473f-9cdf-99a5ac49cd86

**Comment by confuser** [comment]
BoNeMEAL is not affiliated officially with BanManager, please raise issues over at https://github.com/ftbastler/BoNeMEAL
