### ISSUE TITLE
Unable to run insert stmt on object

### ISSUE THREAD

**Issue by Llamatic** [BanManagement/BanManager#476]
24.12 02:34:21 [Server] WARN at me.confuser.banmanager.internal.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
24.12 02:34:21 [Server] WARN java.sql.SQLException: Unable to run insert stmt on object me.confuser.banmanager.data.PlayerBanRecord@31e1979b: INSERT INTO `op_bm_player_ban_records` (`player_id` ,`reason` ,`expired` ,`actor_id` ,`pastActor_id` ,`pastCreated` ,`created` ,`createdReason` ) VALUES (?,?,?,?,?,?,?,?)

I have updated the plugin to the latest version and I still get this error. I've also generated the table from new so its empty. I'm using 1.7.10 - 1.8 spigot using offline mode.

**Comment by confuser** [comment]
Can you post the full stacktrace please

**Comment by Llamatic** [comment]
http://pastebin.com/cSVrP9J2

**Comment by confuser** [comment]
```
24.12 10:43:00 [Server] WARN Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'pastActor_id' cannot be null
```
Have you made any changes to your database manually?

**Comment by Llamatic** [comment]
op_bm_player_ban_records was the table it was having problems with so I cleared all the data inside it.

**Comment by Llamatic** [comment]
I have changed the database tables in the config and its working fine now. Sometime must of gone bad down the line lol.
