### ISSUE TITLE
[Bug] Kicking players from console

### ISSUE THREAD

**Issue by xtechgamer735** [BanManagement/BanManager#478]
Hello,

The plugin doesn't like kicking players from console. Its gives me this error when I do so: http://hastebin.com/jamamojuji.vbs

**Comment by confuser** [comment]
That is most odd, did you by any chance clear/delete any rows from the players table whilst the server was running? Or install banmanager via a plugin manager?

Regardless, I'll add better redundancy checks so it doesn't throw an exception in this scenario.

**Comment by xtechgamer735** [comment]
The only thing I have done is delete two records from the 'bm_players_kicks' table while the server was running but the structure of the database has remained the same. I did not use a plugin manager no.
