### ISSUE TITLE
"Player not found, are you sure they exist?"

### ISSUE THREAD

**Issue by Done84** [BanManagement/BanManager#482]
I get this error on a ton of players wile performing any command related to ban manager.
"Player not found, are you sure they exist?"

Im using the latest version altho not the dev one.

**Comment by confuser** [comment]
Commands usually require a player to have joined the server at least once since BanManager has been installed. Otherwise it'll perform a lookup to Mojang to grab their UUID, which is rate limited. In this case when it hits the rate limit it'll simply fail the lookup and say not found.
