### ISSUE TITLE
punishAlts expanded

### ISSUE THREAD

**Issue by Iceee** [BanManagement/BanManager#483]
I'd like to request a feature that expands punishAlts and customizes its behavior.  Instead of banning the alts, I'd like the ability to simply denies login with a message that says something like, "The IP you are joining from is linked to a banned player."

The idea is that we can prevent players from simply rejoining on a new account after being banned, but not necessarily ban any account attempting to join with an IP that matches a banned player.

**Comment by confuser** [comment]
Perhaps `denyAlts` in the config would suffice instead to cover this use case?

**Comment by Iceee** [comment]
That would be great.

**Comment by EvilOlaf** [comment]
Nice :+1:
