### ISSUE TITLE
Breaking With MinecraftMinecart

### ISSUE THREAD

**Issue by rkomonkey2** [BanManagement/BanManager#485]
Added the donation plugin https://www.spigotmc.org/resources/minecraft-market-free-donation-webstore.203/ and banmanager stopped working removed it it worked again...

**Comment by EvilOlaf** [comment]
Without further information like log files very hard to investigate....

**Comment by confuser** [comment]
As stated above, logs required before I can investigate this further.

**Comment by rkomonkey2** [comment]
Loggs in my last post...

**Comment by confuser** [comment]
I'm afraid I don't see any server logs

**Comment by confuser** [comment]
Closing due to lack of information
