### ISSUE TITLE
BanManager clashing with Reporter

### ISSUE THREAD

**Issue by AdamBOD** [BanManagement/BanManager#486]
I use the plugin, BanManager, and I think it's great, it's exactly what I need but I have a small problem. I have another plugin with the functionality of reporting players. Now the command to report a player using that plugin is the same as this plugin and your plugin overrides it. I have tried removing the /report command from the source in your plugin but have been unsuccessful. I have also tried overriding the commands in the commands.yml file but this hasn't worked either. Would be very grateful for any solution. Thanks in advance

**Comment by confuser** [comment]
You should be able to override it via `commands.yml` in your server root

```
aliases:
  report:
  - reporter:report $$1-
```

Unfortunately spigotmc appears to be down right now so I can't see what the command base would be, so I've assumed it's `reporter:commandName`

**Comment by AdamBOD** [comment]
I tried that but it returns nothing when I add the arguments <player> <reason>

**Comment by confuser** [comment]
Can you link to the plugin please?

**Comment by AdamBOD** [comment]
http://dev.bukkit.org/bukkit-plugins/reporter/

**Comment by confuser** [comment]
Try

```
aliases:
  report:
  - rreport $$1-
```

Ensure you are restarting the server when making changes to `commands.yml` and not using `/reload`

**Comment by AdamBOD** [comment]
That worked like a charm. Thank you very much for your assistance I very much appreciate it. <3

**Comment by IhToN** [comment]
Is it possible to do the same for the plugin ReporterGUI?

https://www.spigotmc.org/resources/reportergui.8596/

It seems that uses /report, and I cannot find any reporter:report or anything like that.

**Comment by EvilOlaf** [comment]
Try like above with `/reportergui` as command.

**Comment by IhToN** [comment]
/reportergui command just display the "help" section of the plugin.

**Comment by Arkazium** [comment]
Hello, little bit lost here but where is the commands.yml ? 
I don't find it, he's in the BanManagers or the Report plugin ?

**Comment by EvilOlaf** [comment]
The Commands.Yml is in the same directory as your server jar file.

**Comment by Arkazium** [comment]
Thanks you man :)
