### ISSUE TITLE
SimpleWarnings

### ISSUE THREAD

**Issue by Shizaye** [BanManagement/BanManager#487]
Hi, Is there a method to import the warnings from SimpleWarnings into BanManagers warning system.

SimpleWarnings -> http://dev.bukkit.org/bukkit-plugins/simplewarnings/

**Comment by confuser** [comment]
Can you provide a database dump of the Simple warnings data in your database?

If you don't want it public, you can email it to `support@frostcast.net` or pm me with a download link on Bukkit Dev

**Comment by confuser** [comment]
Just confirming that I received the database dump

**Comment by Shizaye** [comment]
Hi,

Any update?

Thanks.

**Comment by confuser** [comment]
Not yet @Shizaye, I'll try and set some time aside this weekend.

**Comment by confuser** [comment]
`/bmimport simplewarnings`

You can run this as many times as you need to without any duplicates due to UUID lookups which will be rate limited.

**Comment by Shizaye** [comment]
Thanks a million for your support with this! :)
Greatly appreciated.

Cheers,

**Comment by EvilOlaf** [comment]
(Warning, little bit of off-topic might be included in this post)
Even though I do not use SimpleWarnings, I really like the effort you put into this to make an import possible. A few years ago I thought about using SimpleWarnings as it supported warning an offline player. As this has been implemented into BM it became kind a deprecated ;)

Anyways it is really nice to see over all the time BM becoming more and more awesome than it already was.

@confuser Thank you, Sir, for this awesome piece of software you are developing in your free time an keeping it free for all to use.

**Comment by confuser** [comment]
You're welcome @EvilOlaf. Now that Frostcast is shutting down, I'll have slightly more time to make it even better ;)

**Comment by EvilOlaf** [comment]
o_O what happened?
