### ISSUE TITLE
Server Crash! Huge Issue

### ISSUE THREAD

**Issue by GamerSynchro** [BanManagement/BanManager#491]
Hello,

 Currently I've been experiencing an issue with BanManager on which I think is the cause of crashing my Hub server repeatedly. Here's the crash log ; http://pastebin.com/mGatuUZ1 

 The only thing I've done with BanManager on which I haven't done to my other servers is changing the message's. I'am not quite sure why its even causing it to crash just because of that, but here's my messages ; http://pastebin.com/hKsXSmPZ

Would truly be amazing if someone could solve this for me, as I'am extremely clueless on why this is happening and it gets quite annoying.

**Comment by frdmn** [comment]
[...]
    java.lang.OutOfMemoryError: Java heap space
    [...]

You're probably running out of RAM. Either tweak your memory allocation or increase your total RAM.

**Comment by GamerSynchro** [comment]
I have several times, just for some reason it still crashes. It also appears to ONLY happen to my Hub server as thats the only location where I edited the BanManager messages.

**Comment by confuser** [comment]
Editing the messages would not cause your server to run out of memory. You have a lot of plugins installed for a server only allocated with 3GB.
