### ISSUE TITLE
Please Help!

### ISSUE THREAD

**Issue by ArtutoGamerYT** [BanManagement/BanManager#494]
I have an external DataBase and the servers console says this when the plugin is loading:

http://pastebin.com/tZDLvxDE

My config.yml:

http://pastebin.com/HCiie8i2

I know that not is an a BUG or a issue, but i need help.

**Comment by manuelgu** [comment]
Are you sure that the database is accessible with those credentials?
Also, try to disable local as you don't need it.

**Comment by ArtutoGamerYT** [comment]
Yes, is accesible

**Comment by ArtutoGamerYT** [comment]
I tried to disable local, but the plugin disable itself:

[2016-01-07 23:34:14] :  Enabling BanManager v5.8.0
[2016-01-07 23:34:15] :  Local Database is not enabled, disabling plugin
[2016-01-07 23:34:15] :  Disabling BanManager v5.8.0

**Comment by confuser** [comment]
The local database option in the config is always required. From your config it looks like you are attempting to connect to a database over the internet, ensure your database allows connections from your minecraft's server ip address. 

If you're unsure of how to do this, check the FAQs over on the BukkitDev project page.
