### ISSUE TITLE
Mute not really doing anything.

### ISSUE THREAD

**Issue by Done84** [BanManagement/BanManager#495]
Version: Latest non dev. 5.8.0
server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Not only mutes and temp mutes can be assigned multiple times to the same user as it does not actually mute the player.

http://i.imgur.com/f52DXMZ.png

I also tried unloading my chat plugin to see if it was causing the issue but apparently its not (deluxechat)

Config: http://pastebin.com/ZjjFJkFp

**Comment by confuser** [comment]
Any errors in your config?

**Comment by Done84** [comment]
No. Console looks fine:
http://pastebin.com/T5PHU2ay  when i run the command.

**Comment by confuser** [comment]
Are you running in offline mode?

**Comment by Done84** [comment]
Yes.

**Comment by Kakifrucht** [comment]
BanManager does not support offline mode.

**Comment by Done84** [comment]
Well if thats true then having an "onlineMode: false" in the config doesn't make any sense.
If thats the case then i guess this ticket can be closed...
BTW i wouldn't mind dropping 20$+ for ban manager if it was a Premium Spigot plugin with at least "some" offline support.

**Comment by frdmn** [comment]
@Done84 That was a community contribution but is indeed not officially supported by us. Also we don't accept payments for custom work on BanManager.

**Comment by Done84** [comment]
I wasn't offering a personal payment for custom work done. I was saying that if this had some sort of offline support and it would sell many copies in the Spigot Premium (payd) Plugin Section since the only decent ban plugin has stopped being maintained. A 10 dollar plugin sold 300 times adds up pretty quickly, buy your dev, your choice. Have a nice day sir.

**Comment by EvilOlaf** [comment]
Offline mode support could be enhanced by any other developer who has time to do that. As far as I know @confuser would be glad to merge those changes into BanManager but offline mode still won't be supported officially by BM/Frostcast.
