### ISSUE TITLE
update to config.yml wiki

### ISSUE THREAD

**Issue by voigtman** [BanManagement/BanManager#496]
Theres a section in the current config not mentioned in the config info on github

hooks:
  enabled: false
onlineMode: false    <------------

I run spigot with Bungee which means bungee passes through the players uuid to spigot. the spigot server runs in offline mode by necessity - but what about this setting? What should it be set to in this circumstance? Thank you

**Comment by EvilOlaf** [comment]
Has been removed for a reason. Just leave it at online mode.

https://github.com/BanManagement/BanManager/issues/440

**Comment by confuser** [comment]
In your scenario, leave it alone, you should have spigot setup to forward correctly from bungeecord in your spigot.yml file.

BM doesn't support offline mode, and suffers from a bug heavily ingrained into bukkit itself, in which player names are case sensitive in offline mode, i.e. confusER and confuser are considered as 2 different players.

**Comment by voigtman** [comment]
Hi - Thanks for the answer guys - 
when you say "leave it alone" do I leave it as it is 
onlineMode: false <------------
or change it to true?

**Comment by confuser** [comment]
Remove it from your config, or set it to true

**Comment by voigtman** [comment]
thanks very much!
