### ISSUE TITLE
Problem with format year

### ISSUE THREAD

**Issue by Nico180902** [BanManagement/BanManager#498]
!!! This is not a duplicate of !!!
It's not a Problem that is shown 1 second later. The Problem is that the ban Format year dosen't work and that it automatic will changed to days. In the Chat in BM v4.0 it says: "Nico180902 has banned {Player} for 1 year reason..." and now it will Change to days after Update v5.0 "Nico180902 has banned {Player} for 366 days reason..."

I hope you understand me because I'm german and I can't explain it good, but it's not a duplicate of 1 second...

**Comment by confuser** [comment]
Do not spam re-open issues
