### ISSUE TITLE
Handle multiple unbans concurrency without duplicates

### ISSUE THREAD

**Issue by c0wg0d** [BanManagement/BanManager#499]
If a player is banned for one thing, with a single /ban command, it counts at 17 bans, one for each server on the network.  When I look at the player's record on my web panel, it shows each ban as a separate row, with the exact same reason for each.  /bminfo also shows 17 bans.  Is this how it is intended to work or is it a misconfiguration on my part, or a bug?

**Comment by confuser** [comment]
This sounds like a configuration issue, rather than a bug.

Can you explain your setup? It sounds like you're using the external feature to sync bans between servers, but you've mentioned `/ban` rather than `/banall`

**Comment by c0wg0d** [comment]
Sorry, the issue is slightly different than what I reported.  Moderators using /ban are showing up fine, but we are using PwnFilter to autoban, which is running the "bmban" command on the console.  PwnFilter is not a bungee plugin or anything, so I would assume that it is only running that console command on the server where the issue occurred.  Should I be using something other than "bmban"?

I am not using the external feature.  Every server is using the local database and pointing to the MySQL instance.  All configs are using the same table names.

**Comment by confuser** [comment]
They certainly shouldn't be registering the ban more than once. `bmban` is just an alias of `ban`.

Have you got the WebUI running with an example player?

Are you running the latest version, v5.8.0?

**Comment by c0wg0d** [comment]
Yes, I am running 5.8.0 on all servers with BanManager WebUI version GIT-4b9ab47

Is there somewhere I can PM you the link?

**Comment by confuser** [comment]
Sure, email support@frostcast.net

**Comment by confuser** [comment]
Can you check your console to ensure that it's not PwnFilter running the commands multiple times in quick succession?

**Comment by c0wg0d** [comment]
I did a grep in the 2016 log files for "bmban" and there are no duplicates that I see.  I did see a couple duplicates in 2015, but I think that was when we were changing our PwnFilter rules.  Do you need examples of that?  The timestamp for the duplicates is identical down to the second in the log for those.

**Comment by confuser** [comment]
So by the looks of it, it's an issue with unbanning rather than the ban itself. How are the players unbanned?

**Comment by c0wg0d** [comment]
Why does it take someone else to point out the obvious...  Unbans are done via shell script that sends a bmunban to all servers...  Sorry for wasting your time.

**Comment by confuser** [comment]
Regardless, BM should probably take this into account for concurrency sake
