### ISSUE TITLE
Disable Reports?

### ISSUE THREAD

**Issue by FstJosh** [BanManagement/BanManager#501]
Hello. 
I've noticed that there's a new report system built into BanManager, and was curious if an option could be provided to disable it??
I ask this because we use our own custom report system on my own network, and don't quite like the one provided in BanManager. So, unfortunately I will not be upgrading my version of the plugin due to this reason.
Please provide an option to turn it off. It would be much appreciated!

**Comment by EvilOlaf** [comment]
Take a look here: https://github.com/BanManagement/BanManager/issues/486

**Comment by FstJosh** [comment]
Ah, thank you very much! :)
