### ISSUE TITLE
What Next?

### ISSUE THREAD

**Issue by TSGTyson** [BanManagement/BanManager#503]
Sorry I keep bugging you about this plugin. But my ban plugin before crashed and I lost all my memory and I have to reput the bans on my server quick.

I think I found a new jump.
I restart/reload the server and it is still saying the same old "Could not connect to data base tried 10 times giving up" thing.
I went into the MySQL thing and I found this: https://gyazo.com/f9cc286f05e66202be63dfcd150d311d
Which leads me to believe that this is some sort of glitch because it is doing the same exact thing, not loading commands. I checked before when I was supposedly doing it wrong and nothing was there. I contacted the Server Hosts and I believe I did everything correctly when connecting to the database now, when I checked I saw all the banmanager files inside of it but the commands still don't work. Is this a glitch or am I still not connected to the database?

**Comment by confuser** [comment]
If the tables have been created, then BM was able to connect. Please refrain from re-opening duplicate issues.

If you're still having connection issues, please contact your host. This is not a "glitch" with the plugin. BM requires a stable database connection.
