### ISSUE TITLE
Request: Store all IP's players conenct from

### ISSUE THREAD

**Issue by FrozenBeard** [BanManagement/BanManager#508]
Keep a full history of IP's players connect from, not just the last IP.
To help diagnose alts mostly, the "im round a friends house" or "that alt is my brothers" is impossible to diagnose without a history of existing IP's, its not hard to change an IP either, which they can hide an alt account on.
Most of these kids are not smart and will at one point join the server from their main home IP, this is key information that needs to be retained to improve alt account checking.

This could be saved as an array in the current IP column in the database.

**Comment by EvilOlaf** [comment]
:+1:
Could be togglable though.

**Comment by EvilOlaf** [comment]
This would also be useful if `denyAlts` is set to `true`.

**Comment by EvilOlaf** [comment]
Was just curious if it would be possible to use `bminfo` in combination with an ip address to list players  assigned with a particular IP address. As for now BM saves the last known IP address of each player in the database so querying for this should be pretty simple?

**Comment by confuser** [comment]
@EvilOlaf `/alts <ip>` should suffice for that

**Comment by EvilOlaf** [comment]
Uh did not know that. Nice.

**Comment by confuser** [comment]
@FrozenBeard how would you view this in game? A flag as part of `/bminfo`?

**Comment by FrozenBeard** [comment]
@confuser Yep, where it currently is, except comer separated, if you wanted to get smart, you could do it in json format,so that you could click the IP's to search for other accounts on that IP.

**Comment by confuser** [comment]
It'll be too large to fit under the existing connection details for people that use a variety of ip addresses.

What about `/bminfo -i <player>` instead? I can add pagination as well then. I'd like to add in join/leave time as well, so you have more information.
