### ISSUE TITLE
Request: Un-ban reason

### ISSUE THREAD

**Issue by FrozenBeard** [BanManagement/BanManager#509]
"Why did we unban that player from 6 months ago?" Is something my staff are always talking about in out chat, nobody can remember when you have 1000 bans, having an optional un-ban reason/text will let us understand why a player was unbanned and/or link to external resources to back up their unban (Like linking to a forum post)

**Comment by EvilOlaf** [comment]
AFAIR this has been already suggested a while ago, hasn't it?

**Comment by confuser** [comment]
`/unban <player> [reason]` was implemented quite some time ago

**Comment by FrozenBeard** [comment]
Oh FANTASTIC! I chalk this up to the docs not being updated then ;p All this work and people don't know about it! 
Looks like this needs an update
http://dev.bukkit.org/bukkit-plugins/ban-management/pages/commands-permissions/

**Comment by confuser** [comment]
Apologies, I've updated the documentation on Bukkit Dev to reflect this discrepancy
