### ISSUE TITLE
/kick and /ban not working.

### ISSUE THREAD

**Issue by DeadlyForest** [BanManagement/BanManager#510]
When I try to use /kick or /ban it is not working. This is what I do:
/kick skullcandy15 You smell
Then it says in chat: /kick <player> <reason>

Am I just doing this wrong?

**Comment by EvilOlaf** [comment]
BanManager is probably not enabled correctly. Check your startup log for errors.

**Comment by DeadlyForest** [comment]
If I do /plugins the name is green though so I think that it is.

**Comment by DeadlyForest** [comment]
Here is thae startup log, I don't see anything wrong:
26.01 18:54:36 [Server] INFO Loading default resource pack
26.01 18:53:39 [Server] INFO No new version available
26.01 18:53:39 [Server] INFO Checking for Updates ... 
26.01 18:53:39 [Server] INFO Loaded 0 NPCs.
26.01 18:53:39 [Server] INFO Loaded 0 queued votes
26.01 18:53:39 [Server] INFO Loading queued votes
26.01 18:53:39 [Server] INFO Connection established!
26.01 18:53:39 [Server] Startup Done (11.542s)! For help, type "help" or "?"
26.01 18:53:39 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
26.01 18:53:39 [Server] INFO GAListener v1.3.1 Enabled
26.01 18:53:39 [Server] INFO Enabling GAListener v1.3.1
26.01 18:53:39 [Server] INFO [==================================================================================================]
26.01 18:53:39 [Server] INFO the buy signs and also use the sub commands feature for the crate loot!
26.01 18:53:39 [Server] INFO You have Vault installed this will allow ArchonCrates to use the Economy system for
26.01 18:53:39 [Server] INFO Vault API:
26.01 18:53:39 [Server] INFO You are running the newest version of ArchonCrates! (17.3)
26.01 18:53:39 [Multicraft] Skipped 19 lines due to rate limit (30/s)
26.01 18:53:38 [Server] INFO (world_the_end) TNT ignition is PERMITTED.
26.01 18:53:38 [Server] INFO Loaded configuration for world 'world_nether'
26.01 18:53:38 [Server] INFO (world_nether) Fire spread is UNRESTRICTED.
26.01 18:53:38 [Server] INFO (world_nether) Lava fire is blocked.
26.01 18:53:38 [Server] INFO (world_nether) Lighters are PERMITTED.
26.01 18:53:38 [Server] INFO (world_nether) TNT ignition is PERMITTED.
26.01 18:53:38 [Server] INFO Loaded configuration for world 'world'
26.01 18:53:38 [Server] INFO (world) Fire spread is UNRESTRICTED.
26.01 18:53:38 [Server] INFO (world) Lava fire is blocked.
26.01 18:53:38 [Server] INFO (world) Lighters are PERMITTED.
26.01 18:53:38 [Server] INFO (world) TNT ignition is PERMITTED.
26.01 18:53:38 [Server] INFO Loaded configuration for world 'Towny_the_end'
26.01 18:53:38 [Server] INFO (Towny_the_end) Fire spread is UNRESTRICTED.
26.01 18:53:38 [Server] INFO (Towny_the_end) Lava fire is blocked.
26.01 18:53:38 [Server] INFO (Towny_the_end) Lighters are PERMITTED.
26.01 18:53:38 [Server] INFO (Towny_the_end) TNT ignition is PERMITTED.
26.01 18:53:38 [Server] INFO Default configuration file written: /plugins/WorldGuard/worlds/Towny_the_end/blacklist.txt
26.01 18:53:38 [Server] INFO Default configuration file written: /plugins/WorldGuard/worlds/Towny_the_end/config.yml
26.01 18:53:38 [Server] INFO Loaded configuration for world 'Towny_nether'
26.01 18:53:38 [Server] INFO (Towny_nether) Fire spread is UNRESTRICTED.
26.01 18:53:38 [Server] INFO (Towny_nether) Lava fire is blocked.
26.01 18:53:38 [Server] INFO (Towny_nether) Lighters are PERMITTED.
26.01 18:53:38 [Server] INFO (Towny_nether) TNT ignition is PERMITTED.
26.01 18:53:38 [Server] INFO Default configuration file written: /plugins/WorldGuard/worlds/Towny_nether/blacklist.txt
26.01 18:53:38 [Server] INFO Default configuration file written: /plugins/WorldGuard/worlds/Towny_nether/config.yml
26.01 18:53:38 [Server] INFO Loaded configuration for world 'Towny'
26.01 18:53:38 [Server] INFO (Towny) Fire spread is UNRESTRICTED.
26.01 18:53:38 [Server] INFO (Towny) Lava fire is blocked.
26.01 18:53:38 [Server] INFO (Towny) Lighters are PERMITTED.
26.01 18:53:38 [Server] INFO (Towny) TNT ignition is PERMITTED.
26.01 18:53:38 [Multicraft] Skipped 52 lines due to rate limit (30/s)
26.01 18:53:37 [Server] INFO Arrow Despawn Rate: 1200
26.01 18:53:37 [Server] INFO Item Merge Radius: 2.5
26.01 18:53:37 [Server] INFO Item Despawn Rate: 6000
26.01 18:53:37 [Server] INFO Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
26.01 18:53:37 [Server] INFO Max TNT Explosions: 100
26.01 18:53:37 [Server] INFO Custom Map Seeds:  Village: 10387312 Feature: 14357617
26.01 18:53:37 [Server] INFO Max Entity Collisions: 8
26.01 18:53:37 [Server] INFO Sending up to 10 chunks per packet
26.01 18:53:37 [Server] INFO Structure Info Saving: true
26.01 18:53:37 [Server] INFO Random Lighting Updates: false
26.01 18:53:37 [Server] INFO Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
26.01 18:53:37 [Server] INFO Nerfing mobs spawned from spawners: false
26.01 18:53:37 [Server] INFO Replace Blocks: [1, 5]
26.01 18:53:37 [Server] INFO Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
26.01 18:53:37 [Server] INFO Engine Mode: 1
26.01 18:53:37 [Server] INFO Anti X-Ray: true

**Comment by EvilOlaf** [comment]
This is just a small part of your startup log.

**Comment by DeadlyForest** [comment]
Well here is a full log.
[2016-01-24-1.log.gz](https://github.com/BanManagement/BanManager/files/107619/2016-01-24-1.log.gz)

**Comment by confuser** [comment]
> [18:41:59] [Server thread/INFO]: [BanManager] Enabling BanManager v5.0.0
[18:41:59] [Server thread/WARN]: [BanManager] Local Database is not enabled, disabling plugin
[18:41:59] [Server thread/INFO]: [BanManager] Disabling BanManager v5.0.0

You're running a very old version of BanManager, the latest stable release is v5.8.0

You have also not setup the config correctly. 

It's interesting that even though the plugin has disabled itself, you mention it still shows up as green in /plugins, perhaps that is a spigot bug and the cause of #502

**Comment by DeadlyForest** [comment]
Is there an updated tutorial on how to enable it correctly?

**Comment by DeadlyForest** [comment]
Also, Is this plugin just not for 1.8? In the case that it is, what is a similar plugin that I can I use as a replacement for a 1.8 server?

**Comment by EvilOlaf** [comment]
Actually there is no need for a tutorial. You put the plugin to the `plugins/` folder, enter your database credentials at the `local database` settings (BanManager ALWAYS needs a local database, which btw. does not mean that it has to be sit on localhost...)  in your `config.yml` and done.

It is for 1.8. We are using BM for years now through a couple of servers and for course today on 1.8 ;)

**Comment by DeadlyForest** [comment]
All of this info is already filled out, same problem. Unless the port is not the server port, in that situation, idk where to get the port from. (I am using bisecthosting, which uses multicraft.)

**Comment by EvilOlaf** [comment]
At `port` you have to enter the port of your database server. In most cases this is `3306`. Otherwise ask your host for those details.

**Comment by DeadlyForest** [comment]
You can close this topic, I figured out what was wrong. It was indeed an info problem thank you, have an nice day!
