### ISSUE TITLE
Maxconnections in config

### ISSUE THREAD

**Issue by Nico180902** [BanManagement/BanManager#511]
Yesterday I was looking around in the config.yml and I saw "maxconnetions:10". Now I want to know what that means:

Does it mean that only 10 people can connect on the server?
Or can I only save 10 bans?

Please answer my question

**Comment by confuser** [comment]
It defines the maximum number of active MySQL connections the plugin will open.

**Comment by Nico180902** [comment]
And what is that rate ok for many bans? because often the plugin strikes and I saw in the console:
You have reached the maxconnections:10 shutting down plugin.. So as I saw that I have put that to 100.. Is this option ok?

**Comment by EvilOlaf** [comment]
Even for a  big server 10 is way enough, so try setting to 5 for example.

**Comment by Nico180902** [comment]
What happen If I put there to many connections?

**Comment by confuser** [comment]
Your MySQL database may either start having performance problems, and/or you'll reach the maximum connection limit it allows, anything else interacting with your database may start to fail.

**Comment by Nico180902** [comment]
Ok. And the Performance depents of the GB RAM that the server has got?

**Comment by EvilOlaf** [comment]
This get's a little side-tracked ^^ Such question you may better ask at Spigot or Sponge forums, depending on your  Minecraft server software.
