### ISSUE TITLE
No way of monitoring what muted players say

### ISSUE THREAD

**Issue by AdamBOD** [BanManagement/BanManager#512]
I realized the other day that messages sent to global chat can't be monitored at all. They neither show up in console nor can they be monitored by staff. I feel that this is very important as you the uglier side of players is really show when they're being punished. If this can't be implemented that's fine otherwise I think it would be a  useful addition

**Comment by confuser** [comment]
Well, I can solve both of these issues, by logging any messages BM cancels to the console, as well as broadcasting them to players with a particular permission node.

**Comment by confuser** [comment]
Permissions `bm.notify.muted` `bm.notify.mutedip`
