### ISSUE TITLE
Issue with reloading and reasons.yml

### ISSUE THREAD

**Issue by EvilOlaf** [BanManagement/BanManager#513]
I recently played around with the `reasons.yml` and discovered that after removing one or more earlier defined reasons from the file and using `/bmreload` those are being re-added to the `reasons.yml` file.

Using 5.7.2, I know not the most current version. However there has probably nothing be changed in the code for the reasons stuff since then.

**Comment by confuser** [comment]
So running /bmreload is physically causing old removed reasons from the file to be re-inserted into the file?

**Comment by EvilOlaf** [comment]
Yes, Sir.

**Comment by confuser** [comment]
This is affecting all config files, looks like perhaps an underlying bug either within my BukkitPluginUtil dependency or within Bukkit's YAML library itself.

**Comment by Kakifrucht** [comment]
In a similar manner, you can only add players to the exemptions.yml while the server is not running. Adding/removing them and reloading will just recover the state before you added them in the first place.
