### ISSUE TITLE
Tables Not Generating [Ban Management 4.0]

### ISSUE THREAD

**Issue by ACA30** [BanManagement/BanManager#516]
The tables on my Ban Management plugin are not generating, so I cannot put them on my bans website. The website is: http://ghostmcbans.16mb.com/
I have the config hooked up to my MySQL database (http://www.freemysqlhosting.net/)
Please let me know if there is anything else I need to include.

**Thanks!**
_ACA30_

**Comment by confuser** [comment]
BanManager v4 is no longer supported. Please update to v5.

**Comment by ACA30** [comment]
But, does BanManager v5 still upload to a website?

**Comment by Kakifrucht** [comment]
"upload to a website" wut

**Comment by ACA30** [comment]
Like upload to http://ghostmcbans.16mb.com/ @Kakifrucht

**Comment by ACA30** [comment]
Like it uploads to the MySQL database and that gets put on my bans website

**Comment by Kakifrucht** [comment]
BanManager is still MySQL supported, if you want to display that information on your website you can find links to do so on the BanManager documentation.

**Comment by ACA30** [comment]
Lel I'm a failure can u send me the link to the BanManager documentation! xD @Kakifrucht

**Comment by EvilOlaf** [comment]
@ACA30 Take a look here: http://dev.bukkit.org/bukkit-plugins/ban-management/
There you will find some frequently asked questions answered as well as a link to explanations for the configuration files.

**Comment by ACA30** [comment]
@EvilOlaf Thanks! lel! xD
