### ISSUE TITLE
Tempbanip - Timeformat doesen't work

### ISSUE THREAD

**Issue by Nico180902** [BanManagement/BanManager#517]
Hey, I have a Problem with the tempbanip:
If I ban someone with the tempbanip* then the plugin doesen't know what "[expires] is**.
For better explaining, some Pictures:

# * ![screenshot_14](https://cloud.githubusercontent.com/assets/16621651/12701685/5e38770e-c811-11e5-88ba-42414fd798e6.png)
# **![screenshot_15](https://cloud.githubusercontent.com/assets/16621651/12701688/728a81a2-c811-11e5-9e81-247ee7b23c53.png)

**Comment by EvilOlaf** [comment]
Which version are you using?

**Comment by Nico180902** [comment]
His Snapshotversion (BanManger 5.9.0)

**Comment by Nico180902** [comment]
With BanManager 5.8.0 it doesen't work too.

**Comment by EvilOlaf** [comment]
Did you  try to use the default `messages.yml`?

**Comment by Nico180902** [comment]
Yes I did. It's the same too

**Comment by Nico180902** [comment]
Why do you think that's the fault of the Messages?

**Comment by EvilOlaf** [comment]
Actually just guessing. @confuser might investigate this further.

**Comment by Nico180902** [comment]
Yes, I hope

**Comment by confuser** [comment]
Strange, the `expires` token is definitely being set

https://github.com/BanManagement/BanManager/blob/master/src/main/java/me/confuser/banmanager/listeners/JoinListener.java#L115

I'll try and reproduce this

**Comment by confuser** [comment]
I'm afraid I can't reproduce this. Expires is set correctly. Are there any errors in your console?

**Comment by Nico180902** [comment]
Im 100% Sure that there are no Errors in CONSOLE!
