### ISSUE TITLE
Web Interface

### ISSUE THREAD

**Issue by termanator1128** [BanManagement/BanManager#528]
Hi with the web interface when i try to change the same of the server where it says © Your Server 2016 and i try to change the Your Server and then save it it doesnt save and it doesnt change anywhere using the latest version
Thanks
-term

**Comment by frdmn** [comment]
Hey! This is the wrong repository. There is a dedicated one for the web interface. Would you mind closing this one and raising it in the proper repo: 

https://github.com/BanManagement/BanManager-WebUI

Thanks!
