### ISSUE TITLE
Allow half points to be issued for warnings

### ISSUE THREAD

**Issue by StealthBravo** [BanManagement/BanManager#529]
This may sound silly, but allowing half points to be used in warnings would be useful. This does have a valid usage scenario, like below:

We have a point hierarchy that we'd like to implement:

2 points - kick from server
3 points - 15 min mute
4 points - temp ban for 12 hours
5 points: temp ban for 24 hours
6 points - temp ban for 2 days
7 points - temp ban for 4 days
8 points - temp ban for 8 days
9 points - temp ban for 16 days + 6 hour mute
10 points - permanent ban

We'd like to issue temporary warnings for 7 days with a point value of 0.5 for minor chat offenses, since they're really not worth a full point. Everything else, we want to temporarily warn for 20 days for with a point value of one. The plugin currently does not accept 0.5 as a point value.

Sure, we could inflate point values to get around this, but it seems and looks silly to do so. This is a pretty simple feature with a valid usage scenario, so I believe it should be implemented in the next release. 

Thoughts? Thanks!

**Comment by Kakifrucht** [comment]
How about simply messaging the player for his minor offences?

**Comment by StealthBravo** [comment]
@Kakifrucht the point of warnings is to have a formal record of the offense as well as to progressively punish for repeated rule violations. Messaging the player defeats both of those purposes because there is no record and no punishment hierarchy with that.

**Comment by EvilOlaf** [comment]
Double up the warning points and use the gabs for your minor stuff :D 
Also you are able to give a specific weight of warning points to a warn. But not sure if this has been officially released yet.

**Comment by StealthBravo** [comment]
@EvilOlaf No weight feature as far as I'm concerned. I considered doubling up the points as you suggested, but it really makes no sense in this case and the hierarchy would be inflated quite a bit, to the point where it seems silly.

**Comment by EvilOlaf** [comment]
There you go:
https://github.com/BanManagement/BanManager/commit/f822991aeb14bc0c630e60a3edb6dfe1ee51e83e

**Comment by StealthBravo** [comment]
@EvilOlaf Ah, misunderstood what you meant by weight. Yes, I'm aware that you can assign X amount of points with a warning, hence me knowing that 0.5 doesn't work. The plugin's doesn't even handle it properly, it just throws an internal error.

**Comment by EvilOlaf** [comment]
I am not sure if it is a good idea to add support for `float` instead of `int` in this case....

**Comment by confuser** [comment]
Please note the experimental tag in the commit
