### ISSUE TITLE
Delay for recent BM actions

### ISSUE THREAD

**Issue by EvilOlaf** [BanManagement/BanManager#530]
BM notices when a player has been warned very recently and prevents double warnings.

I wish there would be a feature to detect any BM action taken on a player and basically does the same as descriped above for  - whatever - five or ten seconds.

As an example: Three team mates which don't know what they do think they need to take action. So a user gets a warn, a kick and a tempban within one or two seconds.

**Comment by confuser** [comment]
I think it'd be best implemented as a permission, similar to the time limits. If it's implemented like double warnings, for every command, it could cause unexpected behaviour when running commands automatically through other plugins.

**Comment by EvilOlaf** [comment]
Good thinking :+1:
