### ISSUE TITLE
Question. Database cleanup.

### ISSUE THREAD

**Issue by Done84** [BanManagement/BanManager#534]
Is there any way to clear the database's alternate acount info without reseting the bans?

I've been noticing that since my database is quite old a lot of people get flagged for having alternate accounts that arent really alts, this happens cause sometimes players share they're accounts or try/tried to hack someones account a long time ago, VPN's also cause this and sometimes even dinamic IP's.

Im wondering where this info is stored and if i can delete that part of the database and start over without reseeting the bans and ipbans.

**Comment by confuser** [comment]
The ip addresses are stored within the players table. However, you can't simply wipe that table, as your bans etc all depend on it.

You have a couple of options:
- Update the `bypassDuplicateChecks` config option and add in the ip addresses you wish to ignore
- Change the stored ip address for affected players
- Change the stored ip address for players that haven't joined the server in quite some time (unix timestamp within the players table) to something that's in your `bypassDuplicateChecks` option, like `127.0.0.1`
