### ISSUE TITLE
Enhance denyAlts

### ISSUE THREAD

**Issue by EvilOlaf** [BanManagement/BanManager#535]
The idea to deny users from the same IP to prevent users with multiple accounts is nice but has an issue. If the users simple changes his IP address (depending on your ISP you'll get a new IP after disconnecting from the internet) he can join with his other account(s). 

So my suggestion is if player X with the IP-address 1.2.3.4 has been banned for reason and another player (lets call him Y) trying to join from 1.2.3.4 he may get the predefined message about being linked to a banned account.
Meanwhile the same ban with the same reason (maybe with a predefined prefix/suffix like `multiacc`) and same expiration date (if temporarily) will be automatically applied to Y. This way changing the IP-address will not help.

**Comment by confuser** [comment]
How does this differ from `punishAlts`?

https://github.com/BanManagement/BanManager/blob/master/src/main/resources/config.yml#L129

**Comment by EvilOlaf** [comment]
Uhm...pretty loud question :P 
Did not notice that this was already there. My bad, sorry.
