### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Agazed** [BanManagement/BanManager#536]
http://pastebin.com/R5NNeBa5

**Comment by EvilOlaf** [comment]
https://github.com/BanManagement/BanManager/issues/493

**Comment by confuser** [comment]
Did you change the system time? Has your time zone changed (daylight savings etc)?

**Comment by Agazed** [comment]
No, happened randomly.

**Comment by confuser** [comment]
Strange, as you're the second person to have reported this in a very similar time frame. Are you 100% certain your servers weren't affected by DST?

This issue occurs because of HikariCP, but as BM uses time explicitly for syncing data between multiple servers, it's quite important that the server's time doesn't change randomly.

**Comment by Agazed** [comment]
Not entirely sure, but it hasn't happened again. I haven't modified the system clock configuration at all besides when I first setup the machine.

**Comment by confuser** [comment]
If it happens again, let me know @Agazed and I'll revisit this.

**Comment by confuser** [comment]
Was your server lagging by any chance? TPS issues may cause this as well.

https://github.com/brettwooldridge/HikariCP/issues/559

I'll bump HikariCP to 2.4.4 in the next update

**Comment by Agazed** [comment]
I couldn't tell you as I don't store old timings data. However it makes sense and seems like that would be the probable cause. Server does tend to lag a bit when more players join. Thanks for investigating!

**Comment by EvilOlaf** [comment]
> Server does tend to lag a bit when more players join. 
Having the same issue, but had no problem with date and time yet.
Well, still on 5.7.2 which might be the reason.
