### ISSUE TITLE
Console id could not be found in players table

### ISSUE THREAD

**Issue by Tjdriver** [BanManagement/BanManager#537]
Hey there! I am currently trying to set up my WebUI with MySQL. I have correctly made all the tables and inserted the console ID in the bottom section but when I press "Save" I get this error:
"Error
Console id could not be found in players table"
Do you have the fix for this? It would be appreciated. 
Thanks,
Tjdriver.

**Comment by EvilOlaf** [comment]
It seems like you are reporting an issue with the Web-UI. In this case state your report at the proper repository as this one here is for the java plugin only.

https://github.com/BanManagement/BanManager-WebUI

**Comment by Tjdriver** [comment]
Okay, sorry about that! I have re-posted it on there.
