### ISSUE TITLE
MVN Install failing goals

### ISSUE THREAD

**Issue by Tigatok** [BanManagement/BanManager#542]
After running sudo mvn install -e

 Failed to execute goal on project BanManager: Could not resolve dependencies for project me.confuser:BanManager:jar:5.9.0-SNAPSHOT: Failed to collect dependencies for [org.bukkit:bukkit:jar:1.7.10-R0.1-SNAPSHOT (provided), com.sk89q:guavabackport:jar:1.1 (compile), com.j256.ormlite:ormlite-core:jar:4.48 (compile), com.j256.ormlite:ormlite-jdbc:jar:4.48 (compile), com.zaxxer:HikariCP:jar:2.4.3 (compile), org.slf4j:slf4j-simple:jar:1.6.4 (compile), org.mcstats.bukkit:metrics-lite:jar:R8-SNAPSHOT (compile), me.confuser:BukkitPluginUtil:jar:1.5.3 (compile), com.googlecode.concurrent-trees:concurrent-trees:jar:2.4.0 (compile), org.projectlombok:lombok:jar:1.14.2 (provided), net.gravitydevelopment.updater:updater:jar:2.3 (compile), com.google.code.gson:gson:jar:2.3.1 (compile), commons-net:commons-net:jar:3.3 (compile), com.github.spullara.cli-parser:cli-parser:jar:1.1.2 (compile), com.maxmind.geoip2:geoip2:jar:2.2.0 (compile)]: Failed to read artifact descriptor for me.confuser:BukkitPluginUtil:jar:1.5.3: Could not transfer artifact me.confuser:BukkitPluginUtil:pom:1.5.3 from/to confuser-repo (http://ci.frostcast.net/plugin/repository/everything): Failed to transfer file: http://ci.frostcast.net/plugin/repository/everything/me/confuser/BukkitPluginUtil/1.5.3/BukkitPluginUtil-1.5.3.pom. Return code is: 522 , ReasonPhrase:Origin Connection Time-out. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project BanManager: Could not resolve dependencies for project me.confuser:BanManager:jar:5.9.0-SNAPSHOT: Failed to collect dependencies for [org.bukkit:bukkit:jar:1.7.10-R0.1-SNAPSHOT (provided), com.sk89q:guavabackport:jar:1.1 (compile), com.j256.ormlite:ormlite-core:jar:4.48 (compile), com.j256.ormlite:ormlite-jdbc:jar:4.48 (compile), com.zaxxer:HikariCP:jar:2.4.3 (compile), org.slf4j:slf4j-simple:jar:1.6.4 (compile), org.mcstats.bukkit:metrics-lite:jar:R8-SNAPSHOT (compile), me.confuser:BukkitPluginUtil:jar:1.5.3 (compile), com.googlecode.concurrent-trees:concurrent-trees:jar:2.4.0 (compile), org.projectlombok:lombok:jar:1.14.2 (provided), net.gravitydevelopment.updater:updater:jar:2.3 (compile), com.google.code.gson:gson:jar:2.3.1 (compile), commons-net:commons-net:jar:3.3 (compile), com.github.spullara.cli-parser:cli-parser:jar:1.1.2 (compile), com.maxmind.geoip2:geoip2:jar:2.2.0 (compile)]

**Comment by Mrtenz** [comment]
This happens because the ci.frostcast.net repo is still not working.

**Comment by confuser** [comment]
Fixed

**Comment by Tigatok** [comment]
Not sure if I am doing something wrong on my end, but the output of 
sudo mvn install 

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.110s
[INFO] Finished at: Mon Mar 07 10:20:56 PST 2016
[INFO] Final Memory: 8M/147M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project BanManager: Could not resolve dependencies for project me.confuser:BanManager:jar:5.9.0-SNAPSHOT: Failed to collect dependencies for [org.bukkit:bukkit:jar:1.7.10-R0.1-SNAPSHOT (provided), com.sk89q:guavabackport:jar:1.1 (compile), com.j256.ormlite:ormlite-core:jar:4.48 (compile), com.j256.ormlite:ormlite-jdbc:jar:4.48 (compile), com.zaxxer:HikariCP:jar:2.4.4 (compile), org.slf4j:slf4j-simple:jar:1.6.4 (compile), org.mcstats.bukkit:metrics-lite:jar:R8-SNAPSHOT (compile), me.confuser:BukkitPluginUtil:jar:1.5.3 (compile), com.googlecode.concurrent-trees:concurrent-trees:jar:2.4.0 (compile), org.projectlombok:lombok:jar:1.14.2 (provided), net.gravitydevelopment.updater:updater:jar:2.3 (compile), com.google.code.gson:gson:jar:2.3.1 (compile), commons-net:commons-net:jar:3.3 (compile), com.github.spullara.cli-parser:cli-parser:jar:1.1.2 (compile), com.maxmind.geoip2:geoip2:jar:2.2.0 (compile)]: Failed to read artifact descriptor for me.confuser:BukkitPluginUtil:jar:1.5.3: Could not transfer artifact me.confuser:BukkitPluginUtil:pom:1.5.3 from/to confuser-repo (http://ci.frostcast.net/plugin/repository/everything): peer not authenticated -> [Help 1]

**Comment by confuser** [comment]
That's odd. Can you try editing the pom.xml and changing `http://ci.frostcast.net/plugin/repository/everything` to `https://ci.frostcast.net/plugin/repository/everything`?

**Comment by frdmn** [comment]
@confuser I just tried to check using `curl` and found out that there are a bunch of redirects going on:

1. The first one redirects from `http://ci.frostcast.net/plugin/repository/everything` to `https://ci.frostcast.net/plugin/repository/everything` which looks quite fine.
2. The second one however, redirects again to `http://ci.frostcast.net:443/plugin/repository/everything/` which seems very odd. Trying to talk HTTP via the default HTTPS port doesn't end up well, thus the ...
3. ... `400 Bad Request` response

**Comment by confuser** [comment]
I've temporarily disabled forcing all HTTP traffic over HTTPS until I can sort out the redirects properly.
