### ISSUE TITLE
Would it be possible to upload a 1.9 version elsewhere while the site is down?

### ISSUE THREAD

**Issue by zombachu** [BanManagement/BanManager#543]
Hopefully you guys get the VPS situation sorted out soon, but in the meantime can you upload the 1.9 build somewhere? Awesome plugin, by the way.

**Comment by zombachu** [comment]
Just tried the fix mentioned in #540 and it works great. An official build would still be nice to have, though. Sorry for wasting your time with this issue.

**Comment by confuser** [comment]
Build 47+ https://ci.frostcast.net/job/BanManager/
