### ISSUE TITLE
The convert section of the config

### ISSUE THREAD

**Issue by KCQuetzal** [BanManagement/BanManager#544]
I will be switching hosts here soon.  Is there a way to export to a flatfile before the switch and then import back to MySQL once I get that set up with the new host?  Is that what the convert section would provide the ability for?  Any assistance greatly appreciated!

**Comment by confuser** [comment]
No, convert is for converting from the old v4 player name based version over to v5 for UUIDs. It'll be removed in v5.9.

If you're switching hosts, backup and restore your MySQL database.

**Comment by KCQuetzal** [comment]
Ok thank you for the advice!
