### ISSUE TITLE
I've tried everything, but bminfo is only working for OP's

### ISSUE THREAD

**Issue by mickcoyne** [BanManagement/BanManager#550]
You can see that I have given the correct permission node, i have also tried replacing the '*' with things like "others" but nothing works. All of the other punishments work :(

http://pastebin.com/MMdbc9FZ

**Comment by confuser** [comment]
You'll need `bm.command.bminfo` permission as well as `bm.command.bminfo.*`

**Comment by mickcoyne** [comment]
I added The other perm...still doesn't work. Don't hate me XD I wouldn't come here if i hadn't of tried everything

**Comment by confuser** [comment]
What permissions plugin are you using @mickcoyne ?

**Comment by mickcoyne** [comment]
GroupManager @confuser I gave bm.command.* as a temp fix, but I don't want to continue that risk.

**Comment by confuser** [comment]
I'm not familiar with that permissions plugin I'm afraid. With PermissionsEx, players had to rejoin the server in order for their permissions to be updated. Can you post what your perms look like now? It is just with bminfo that you're having problems with, no other command permissions correct?

**Comment by mickcoyne** [comment]
It is just with bminfo that you're having problems with, no other command permissions correct? Yes

`  Acolyte:
    default: false
    permissions:
    - bm.command.activity
    - bm.command.addnote
    - bm.command.alts
    - bm.command.bminfo
    - bm.command.bminfo.*
    - bm.command.kick
    - bm.command.mute
    - bm.command.nlkick
    - bm.command.notes
    - bm.command.notes.online
    - bm.command.tempmute
    - bm.command.tempwarn
    - bm.command.unmute
    - bm.command.unmuteip
    - bm.command.warn
    - bm.notify.ban
    - brewery.mod
    - essentials.ban.notify
    - essentials.chat.ignoreexempt
    - essentials.cooldown.bypass
    - essentials.helpop.receive
    - essentials.kick
    - essentials.mute
    - essentials.mute.notify
    - essentials.mute.offline
    - essentials.timer.bypass
    - essentials.togglejail
    - essentials.togglejail.offline
    - prism.alerts
    - signlogger.notify
    - towny.chat.mod
    inheritance:
    - member`

**Comment by mickcoyne** [comment]
http://pastebin.com/qGTiuXcP

better permissions copy--easy to read

**Comment by confuser** [comment]
I've just added `bm.command.bminfo.*` to the plugin file. Can you try build 56+ please?

http://ci.frostcast.net/job/BanManager/56/

**Comment by mickcoyne** [comment]
It is fixed now! you are great!
