### ISSUE TITLE
Essentials override

### ISSUE THREAD

**Issue by iyordiii** [BanManagement/BanManager#551]
Hi,

I contacted you with the mail, but you said to do it here so:

Can you do: that ban management override essentials, if i do /ban or /mute it says 2 times what I need to do. One of Ban manager and one of essentials.

I use the last version of essentials for 1.8.*

Thanks

Regards,
Yordi

**Comment by confuser** [comment]
Which Essentials? Spigot's fork, the original, or EssentialsX? Can you list your plugins please?

**Comment by iyordiii** [comment]
I use this: 
-	Essentials-2.x-SNAPSHOT.jar
-	EssentialsChat-2.x-SNAPSHOT
-	EssentialsSpawn-2.x-SNAPSHOT

Version: TeamCity
Authors: Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally

~ Yordi

**Comment by iyordiii** [comment]
Here a link : http://dev.bukkit.org/bukkit-plugins/essentials/

**Comment by confuser** [comment]
Essentials on BukkitDev isn't fully compatible with 1.8+ servers. Please try with either Spigot's Essentials (https://hub.spigotmc.org/jenkins/job/Spigot-Essentials/) or EssentialsX https://github.com/drtshock/Essentials/

**Comment by iyordiii** [comment]
Ok, thanks.

I gonna try it.

**Comment by iyordiii** [comment]
Nice spigot doesn't work, so i use EssentialsX
And now it works. Thank you for your fast support !!
