### ISSUE TITLE
Mute Broadcast Notify

### ISSUE THREAD

**Issue by LaughNgamez** [BanManagement/BanManager#560]
Hi there, it may be my ignorance but it seems right now there is no way to disable the [Muted] <msg> that an operator sees when a muted player tries to speak.

I want to see messages from when a muted player tries to speak and removing the message just makes it a blank line. Help with this would be appreciated.

**Comment by EvilOlaf** [comment]
So you want to disable the broadcast, but on the same time you want to see it?

Anyway. There are permission nodes to control who can read messages from muted players. 
```
bm.notify.muted: true
bm.notify.mutedip: true
```

**Comment by LaughNgamez** [comment]
Sorry, should have made that more clear.

I want to see the messages IE: X was muted for Y for 15 minutes
I do not want to see: [Muted] chat message

I'll try those nodes thanks.

**Comment by EvilOlaf** [comment]
So you want to receive reminder that every time this particular player tries to chat that he was muted till X but not the message itself?
If so this is not possible AFAIK. But you can disable receiving these messages at all using the nodes above.

**Comment by LaughNgamez** [comment]
No, sorry for not being more clear haha. 
I just want to see the initial x was muted for reason. Nothing to do with when they try to chat, I want that option completely off.

**Comment by EvilOlaf** [comment]
This should be achievable by negating those nodes ;)
