### ISSUE TITLE
Essentials taking over

### ISSUE THREAD

**Issue by timothydavidhart** [BanManagement/BanManager#561]
Essentials seems to be taking over my bans,kicks and mutes and not following the priority system message back for more details.

**Comment by EvilOlaf** [comment]
So where are your details

**Comment by timothydavidhart** [comment]
What do you want to have is what im asking

**Comment by confuser** [comment]
Either use EssentialsX or use Spigot's fork

**Comment by timothydavidhart** [comment]
confuser could I have a link please?

**Comment by EvilOlaf** [comment]
I highly recommend using EssentialsX as it is actively maintained while Spigots Essentials just have been updated to run somehow on 1.8 and/or 1.9. 

Grab it here:
https://ci.drtshock.net/job/EssentialsX/

Also note that there are a few changes compared to Essentials. Check their wiki on github.

**Comment by timothydavidhart** [comment]
I am already using the latest version of exxentialsx

**Comment by confuser** [comment]
@timothydavidhart can you raise a bug with them please then? I know Essentials does some wrapping around other plugin commands, and it should give other plugins priority. I'm not aware of any compatibility issues I can fix on my side, but it'd be good to know if there are.

**Comment by timothydavidhart** [comment]
https://github.com/drtshock/Essentials/issues/530

**Comment by drtshock** [comment]
rip undetailed reports.
