### ISSUE TITLE
Show reports on login

### ISSUE THREAD

**Issue by xILukasIx** [BanManagement/BanManager#562]
I'm not sure how far you are with completing the implementation of /report, but could you add getting notified of new (or just all existing) reports when you log in + a perm node for it?

Right now, there's no way of finding out if any user on the server got reported other than checking the WebUI. A message on login would be great:
[player] got reported by [actor] for [reason] on [created].

This could also show up when the reported [player] logs in to people with the right permission:
-bm.notify.report.join

-bm.notify.report doesn't exist yet, but will probably be used for notifying online players when a new report JUST got created (unless it exists already)?

Another possibility would be to just display "There are open reports!" when you join the server and adding the reports to /bminfo AND implementing a new command /reports that shows existing reports.
I'm not sure if the reports have an ID yet which you can see.

**Comment by confuser** [comment]
Most of these are on my list (currently using this as a base line with some modifications) https://github.com/EvilOlaf/BanManager/wiki/BM-Reports

Keep an eye on #557 for progress.

**Comment by EvilOlaf** [comment]
I'll add this to the page mentioned above
