### ISSUE TITLE
Implement a jail system

### ISSUE THREAD

**Issue by JohOply** [BanManagement/BanManager#563]
Hi

Is it possible to implement a jail system? Some features : 
- Jail online and offline players
- Prevent escaping
- Command to know for what reason and how many time player is jail
- Block all commands and have a whitelist commands
- Food control
- Automute during jail
- Many other possibilities

Thank you for reading :)

**Comment by confuser** [comment]
Sorry, jailing is something I'm going to implement. It was originally under a "To Don't" on the main page, looks like I removed it when I redid everything.

http://dev.bukkit.org/bukkit-plugins/ban-management/pages/main/r94/#w-to-dont
