### ISSUE TITLE
DeniedNotify

### ISSUE THREAD

**Issue by iyordiii** [BanManagement/BanManager#564]
Is it possible to disable the DeniedNotify ?

~ Yordi

**Comment by EvilOlaf** [comment]
Yes
Set these permissions to false:
```
      bm.notify.denied.player: true
      bm.notify.denied.ip: true
```

**Comment by iyordiii** [comment]
And for OPS ?

**Comment by EvilOlaf** [comment]
I can find most things I need using google. But I guess that's not the point.

List of commands an permissions: http://dev.bukkit.org/bukkit-plugins/ban-management/pages/commands-permissions/

If you have trouble setting permission nodes with your permission system, ask the respective developer for help.
