### ISSUE TITLE
Essentials Staff Commands and ban Manager commands are conflicting 

### ISSUE THREAD

**Issue by Danielh90** [BanManagement/BanManager#565]
How do I fix this issue? https://gyazo.com/ca585784a926099536a5d9e553a6b523 I know about disable the ban, /kick and /mute in the essentials but that does not seem to work for me? Can BanManager Fix this issue? I have never seen this issue before It just poped up yesterday.

**Comment by confuser** [comment]
Please see https://github.com/drtshock/Essentials/issues/530

This is most likely an issue with Essentials.
