### ISSUE TITLE
Disable muted player message broadcastion from config.

### ISSUE THREAD

**Issue by Ghostlyr** [BanManagement/BanManager#573]
Hello. Found a nasty thing after upgrade from 4 version - broadcasting muted player messages. All plugins, involved to logging chat messages are logged and these "cancelled" messages. I did not need it absolutely. Could you add a configuration ability to completely turn off this new feature?

**Comment by confuser** [comment]
Negate `bm.notify.muted` and `bm.notify.mutedip` permissions

**Comment by Ghostlyr** [comment]
Oh, you misunderstood me. =(
Permissions already installed so negative. I mean, plugins, leading logging chat, writes a message rejected by banmanament. And it console i can see theese messages too. But i dont want it, because they are misleading moderators.

![456456](https://cloud.githubusercontent.com/assets/8511068/14232253/7b31256e-f9c5-11e5-849b-aeec05bd6a46.png)

(tested on last 1.7.10 coreprotect)

**Comment by confuser** [comment]
Sorry but I don't quite follow. Are you saying CoreProtect is logging the message even though BM has cancelled the event? If so, then that sounds like a bug with CoreProtect.

**Comment by Ghostlyr** [comment]
Hmm, maybe. It seems CP hooks the message before it is canceled by other plugins...
Sorry for trouble you =)
