### ISSUE TITLE
Error, database.

### ISSUE THREAD

**Issue by bingoberra** [BanManagement/BanManager#578]
05.04 04:27:30 [Server] WARN at java.lang.Thread.run(Unknown Source)
05.04 04:27:30 [Server] WARN at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527)
05.04 04:27:30 [Server] WARN at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269)
05.04 04:27:30 [Server] WARN at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331)
05.04 04:27:30 [Server] WARN at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376)
05.04 04:27:30 [Server] WARN at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411)
05.04 04:27:30 [Server] WARN at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321)
05.04 04:27:30 [Server] WARN at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361)
05.04 04:27:30 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
05.04 04:27:30 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
05.04 04:27:30 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
05.04 04:27:30 [Server] WARN at me.confuser.banmanager.BanManager.onEnable(BanManager.java:116)
05.04 04:27:30 [Server] WARN at me.confuser.banmanager.BanManager.setupStorages(BanManager.java:310)
05.04 04:27:30 [Server] WARN at me.confuser.banmanager.storage.PlayerBanStorage.<init>(PlayerBanStorage.java:46)
05.04 04:27:30 [Server] WARN at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:475)
05.04 04:27:30 [Server] WARN at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:484)
05.04 04:27:30 [Server] WARN at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:954)
05.04 04:27:30 [Server] WARN at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:217)
05.04 04:27:30 [Server] WARN at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:243)
05.04 04:27:30 [Server] WARN at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadOnlyConnection(DataSourceConnectionSource.java:102)
05.04 04:27:30 [Server] WARN at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadWriteConnection(DataSourceConnectionSource.java:120)
05.04 04:27:30 [Server] WARN java.lang.Exception: Apparent connection leak detected
05.04 04:27:30 [Server] WARN 6583 [HikariPool-0 housekeeper] WARN me.confuser.banmanager.internal.hikari.pool.ProxyLeakTask - Connection leak detection triggered for com.mysql.jdbc.JDBC4Connection@51139b20, stack trace follows
05.04 04:27:24 [Server] WARN 74 [Server thread] INFO me.confuser.banmanager.internal.hikari.HikariDataSource - HikariPool-0 - Started.

**Comment by confuser** [comment]
Your connection to the database is slow.
