### ISSUE TITLE
DeluxeChat Support

### ISSUE THREAD

**Issue by edyyy** [BanManagement/BanManager#580]
The new feature that allows staff members to see muted users messages caused some issues with DeluxeChat. Users are still able to talk in chat even if they are muted. 

I am pretty sure this is because DeluxeChat has a higher priority over BanManager and is able to bypass it. This didn't happen in older versions of BanManager.

**Comment by confuser** [comment]
Can you check to see if your players have the `bm.notify.muted` permission node at all? Only those with that permission should be able to see the muted messages.

**Comment by edyyy** [comment]
I have tested this with and without the permission nodes. The negative permission does disable the messages with prefix [Muted], however normal chat messages still show up as if user wasn't muted at all.

**Comment by confuser** [comment]
Issue resolved remotely.

Required setting `hooks.banmanager` to true in the chat plugin's config file.
