### ISSUE TITLE
BanManager error

### ISSUE THREAD

**Issue by BlackRavenMC** [BanManagement/BanManager#581]
Getting this error every minute:

http://pastebin.com/pyLBfDiG
Using banmanger 5.9

**Comment by EvilOlaf** [comment]
There are multiple issue reports with a similar exception, did you have a look at those?
https://github.com/BanManagement/BanManager/search?q=Unable+to+run+insert+stmt+on+object+&type=Issues&utf8=%E2%9C%93

**Comment by BlackRavenMC** [comment]
@EvilOlaf  Yeah, almost all of them have 'Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column soft in field list' error, but I have 'Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column player_id cannot be null' error.

**Comment by confuser** [comment]
Are you running in offline mode? Have you modified any data in your database manually?

**Comment by BlackRavenMC** [comment]
I'm running server in offline mode and modified some data, because there where multiple same names that i couldn't ban.

**Comment by confuser** [comment]
I'm afraid BM doesn't officially support offline mode. Due to the way Bukkit handles offline names, different name cases are treated as separate players in offline mode. E.g. confuser != Confuser

**Comment by rautamiekka** [comment]
^ Just use case-insensitive checking in both database and plugin, and we're golden. There's no point in universally considering different casing different person.

Or at least add it as an option.

**Comment by confuser** [comment]
The issue is with uuid generation on the Player object. It'd require a lot
of refactoring. Happy to accept PRs
