### ISSUE TITLE
Towny Support for /mute

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [BanManagement/BanManager#583]
I am using TownyChat and everytime I use /mute or /tempmute, players bypass it because there is no support for TownyChat or DeluxeChat

**Comment by confuser** [comment]
DeluxeChat is supported. Please enable the banmanager hook within the deluxechat config.

I can't speak for towny. BmAPI does offer a way to check if a player is muted, which most popular plugins do integrate with.
