### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by termanator1128** [BanManagement/BanManager#584]
Hi i have a feature to request. I would like to see a GUI system in it.

**Comment by confuser** [comment]
GUI is planned. Already have a library to handle this as well.

Happy to hear peoples suggestions on how it should look/function.

Not going to be working on it until reports lands in master.

**Comment by termanator1128** [comment]
ok cool ill try to think of ways it should look

**Comment by Kakifrucht** [comment]
@confuser which lib do you plan on working with?

**Comment by confuser** [comment]
Alternatives exist which cover this
