### ISSUE TITLE
Update HikariCP to 2.4.5

### ISSUE THREAD

**Issue by c0wg0d** [BanManagement/BanManager#585]
I just updated to 5.9.0 from 5.8.0 and I am seeing this in the start up.  Is there a problem with my configuration?

`[02:58:30 WARN]: 52 [Server thread] WARN me.confuser.banmanager.internal.hikari.pool.PoolBase - HikariPool-0 - Failed to get/set network timeout for connection. (com.mysql.jdbc.JDBC4Connection.getNetworkTimeout()I)`

Using a local database with maxConnections: 2.

**Comment by EvilOlaf** [comment]
See here: https://github.com/BanManagement/BanManager/issues/548
Can be safely ignored.

**Comment by confuser** [comment]
Looks like it's been fixed in HikariCP 2.4.5
