### ISSUE TITLE
DateUtils wrong output

### ISSUE THREAD

**Issue by sigmaroot** [BanManagement/BanManager#587]
When using /tempban player 10d Reason, it's showing _banned for 1 week_ instead of _banned for 1 week 3 days_

Will commit a workaround soon....

**Comment by sigmaroot** [comment]
Workaround with configurable setting is #588

**Comment by confuser** [comment]
Interesting. I wasn't aware of this being a problem. This should be the default, behaviour, i.e. not configurable. @sigmaroot Can you update your PR please and remove the config option?

**Comment by sigmaroot** [comment]
Done.

**Comment by confuser** [comment]
Thanks @sigmaroot, much appreciated
