### ISSUE TITLE
TAB COMPLETE

### ISSUE THREAD

**Issue by floflo180** [BanManagement/BanManager#592]
You closed 2 other tickets without solving the problem. I will elaborate on my problem although I have no idea what their issue is. I'm assuming it is the same thing as mine.

Server version: 1.7.10
Java: 8
Problem: A player has logged into the server, they are on the server, I type /ban floflo then I click tab and it doesn't auto complete the tab. The player is ONLINE. That is the issue.

**Comment by confuser** [comment]
Again, duplicate of #590. If there is a bug, I will reopen the original issue. Just because an issue is closed, doesn't mean the discussion is closed. Please stop opening new issues.
