### ISSUE TITLE
error on start up 

### ISSUE THREAD

**Issue by kemit-the-frog** [BanManagement/BanManager#593]
[14:11:47] [Server thread/INFO]: [BanManager] Enabling BanManager v5.9.0
[14:11:48] [Server thread/WARN]: 49 [Server thread] INFO me.confuser.banmanager.internal.hikari.HikariDataSource - HikariPool-1 - Started.

I keep getting this error when i try to start the server, all i did was install the plugin and give it mysql login. What does it mean?

**Comment by EvilOlaf** [comment]
This is not an error but INFO.

**Comment by kemit-the-frog** [comment]
what does it mean?

**Comment by EvilOlaf** [comment]
Hikari is the library that is used to create a bridge between BM and your MySQL server. The message itself is purely informational and means that the connection pool to the MySQL server has started.

**Comment by confuser** [comment]
Duplicate of #585.
