### ISSUE TITLE
1.7.10

### ISSUE THREAD

**Issue by vursanity** [BanManagement/BanManager#594]
I am using the latest public version (not dev version) of the plugin and the tab complete doesn't work.
I am using java 8, server version 1.7.10, centos. Please help!

**Comment by confuser** [comment]
Again, duplicate of #590. Stop opening a separate issue.

**Comment by vursanity** [comment]
Sir, you are not even attempting to answer the question

**Comment by confuser** [comment]
@vursanity The 'problem' has already been reported by another user, and you can subscribe/participate within that very same issue. I will not waste time having to handle the exact same reported issue multiple times, which is what you are currently doing.
