### ISSUE TITLE
Hello , I have a question about how UUIDs work with this plugin and probably an issue with it.

### ISSUE THREAD

**Issue by Nev3rGiveUp** [BanManagement/BanManager#595]
I'm a server admin and I LOVE this plugin , I didn't used it in 1.8.8 ,because it was kinda buggy and yeah... Now I saw that on 13 of march the plugin has been updated and I was happy as hell!!!!!! I installed everything back from version 1.7 - banlists , mysql database , just everything and when I tested it it just don't work properly with my OFFLINE server. And here is the problem - if player is old and he is known , bans work properly , if this player never joined the server the plugin will notice the ban ,but whenever the player wants to join ... here is the problem HE JOINS. When the player is new: the plugin again notice in the chat about the ban ,but didn't kick the player... even when the player logout then he can login without being stopped from the plugin. How UUIDs work with this plugin now? And how can I configure it to work with my server? I'm running 1.9.2 latest version of spigot. I really LOVE this plugin ,because of its capability to just fit my server perfectly. I really NEED help! :(

**Comment by Agazed** [comment]
How about you set online mode to true and stop pirating the game :))

**Comment by EvilOlaf** [comment]
Offline mode is not officially supported by BM. If you run offline and run into trouble you are on your own.

However PRs to enhance offline support will be accepted.

**Comment by rautamiekka** [comment]
@Agazed: for first I bought the game to avoid someone stealing my name.

For second offline mode is used to enable using undercover accounts.

For third we can easily login as one of our Players if necessary.

**Comment by Nev3rGiveUp** [comment]
@Agazed  > How about you set online mode to true and stop pirating the game :))

Firstly in our country 75% of the players are cracked , so if I set online mode to true I will need to close my server. Now I have aroung 20-30 players and I'm -10 dolars every month... I'm sorry for spamming the issue tab :)
