### ISSUE TITLE
Invalid Response

### ISSUE THREAD

**Issue by CarlosRpenguin** [BanManagement/BanManager#596]
Im having problems adding a server to the web end. The plugin is giving me no errors and im running version 4.0 of the plugin on minecraft 1.2.5 but its just giving me this.
http://prnt.sc/av889k

**Comment by EvilOlaf** [comment]
My guess is such an old version is not supported anymore.

**Comment by confuser** [comment]
Unfortunately v4 is no longer supported. Are the database and the website hosted on the same server? Try `127.0.0.1` instead of `localhost`. Also, I wouldn't use root with MySQL, it's a security concern.

**Comment by CarlosRpenguin** [comment]
Yes, They are on the same computer, I have tried 127.0.0.1, localhost, and my public ip. Also yes I know not to use root I was just using for testing.

**Comment by confuser** [comment]
What does the web page display when you attempt to add a server? Your original screenshot doesn't show any messages, just the form.

**Comment by CarlosRpenguin** [comment]
http://imgur.com/9xPecpC < this is all it does.

**Comment by confuser** [comment]
Can you open your browser network console? Right click the page, click "Inspect" in Chrome, or "Inspect Element" in Firefox. Click the "Network tab. Try adding the server again. You should see a request go through. Click on it, and paste the response here.

**Comment by CarlosRpenguin** [comment]
HTTP/1.0 500 Internal Server Error
Date: Fri, 22 Apr 2016 11:24:56 GMT
Server: Apache
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
X-Frame-Options: SAMEORIGIN
Content-Length: 0
Connection: close
Content-Type: text/html; charset=UTF-8

**Comment by confuser** [comment]
Can you paste the content of response tab too please?

**Comment by CarlosRpenguin** [comment]
http://imgur.com/mvjhxYz Im guessing this is what u mean?

**Comment by confuser** [comment]
Yes. In that case, take a look at your webserver logs. It should give some indication as to what the problem is.

**Comment by CarlosRpenguin** [comment]
I dont see anything in the access and error logs about it.

**Comment by confuser** [comment]
Try enabling PHP errors, either set display_errors to 1 in your php.ini file, or add the following to the top of index.php

```
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
```

**Comment by CarlosRpenguin** [comment]
Okay i set "display_errors" to On, now what would you like me to do?

**Comment by confuser** [comment]
Restart your webserver. Try adding a server again. Check the output in your browser console, and check your server logs.

**Comment by CarlosRpenguin** [comment]
Nope nothing, its not throwing errors, its not giving me a response. And it doesn't tell me whats wrong

**Comment by CarlosRpenguin** [comment]
Okay, so I have manged to connect the sql to a external web server and it added it fine. But I just test banned someone and its not updating on the site.

**Comment by EvilOlaf** [comment]
updates do not happen immediately. just wait a few minutes to let the system update itself.

**Comment by CarlosRpenguin** [comment]
Thats not it, I just restarted the server and did /bminfo and now it doesnt even say he is banned on the server...

**Comment by CarlosRpenguin** [comment]
Switched to external SQL server, but its not making the tables i need. What Do I put into the warnings and kicks slots on the website?

**Comment by confuser** [comment]
@CarlosRpenguin It'll be the table names for kicks and warnings.
