### ISSUE TITLE
Paperspigot console spam

### ISSUE THREAD

**Issue by ziutekkk** [BanManagement/BanManager#597]
Hello
i use newest build of paper spigot and Banmanager 5.9.0
I get spammed with this error in console:
http://pastebin.com/Ha4iwXmM
Any possible fixes?
Thanks

**Comment by confuser** [comment]
Very similar to #577. I'm not familiar with paper unfortunately, so I don't quite know it's differences. However, as per the other issue, this looks like it's being caused by `sendMessage`, which as far as I was aware, was supposed to be thread safe.

Can you open an issue with Paper please?

**Comment by confuser** [comment]
Can you try dev build 62+ please?

http://ci.frostcast.net/job/BanManager/

**Comment by ziutekkk** [comment]
Sure, I will write info after testing.

**Comment by ziutekkk** [comment]
OK, no errors now
Thanks
