### ISSUE TITLE
Disable Messages

### ISSUE THREAD

**Issue by Henaminator** [BanManagement/BanManager#598]
Helllo, is it possible to disable messages in the message config?

For example:
  mute:
    player:
      blocked: '&cYou may not use the [command] command whilst muted!'
      disallowed: '&6You have been permanently muted for &4[reason] &6by [actor]'
     > broadcast: '' <
I wanted to disable that but won't work, it keeps sending me empty messages for the Operators when a muted player tries to send a chat message.

I also want to disable:
  deniedNotify:
    player: '&cWarning: [player] attempted to join the server but was denied due to
      &4[reason]'
Same problem there, if I remove what's in the ''.

Anyway to fix this? I don't want the message to be shown at all and no empty messages.

**Comment by confuser** [comment]
You can negate the permission nodes, however, setting the message to empty would probably be a good idea as well.

Perms to negate:
`bm.notify.muted`
`bm.notify.denied.player`
`bm.notify.denied.ip`

**Comment by Henaminator** [comment]
Thanks man, worked! :+1: 
All I did with pex was to add the perm to a rank like this -bm.notify.muted

Keep up the great work :)
