### ISSUE TITLE
/unbaniprange throws an error when executing it.

### ISSUE THREAD

**Issue by StarDan90** [BanManagement/BanManager#601]
Steps to reproduce the problem:
1. IP-ban an IP range with /baniprange
2. Unban the same range with /unbaniprange

This is the error that it shows: (the IP shown there is totally random and not associated to a player)
http://storage2.static.itmages.com/i/16/0502/h_1462211472_8323317_caaba8cd5d.png

The command actually unbans the IP range despite the error. It happens even on the latest dev version of the plugin.

**Comment by confuser** [comment]
Typo in the notification broadcast. Should be fixed in builds 63+
