### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by tehrenderr** [BanManagement/BanManager#603]
Anyway you can make it configurable so we can use the old /bminfo display. It looked so much nicer and cleaner than the newer one. By older I mean pre v5.0.

**Comment by EvilOlaf** [comment]
Bminfo is configurable AFAIK. Just edit the message file till it fits your needs.

**Comment by confuser** [comment]
Subjective. As stated by @EvilOlaf you can customise it to your liking within the messages.yml file. If there's anything that's preventing you from doing that, such as missing tokens etc, let me know.

**Comment by tehrenderr** [comment]
Well one thing that changed is before my staff were able to see how much time was left on someone's ban when they did bminfo but I don't believe thats possible anymore and if it is, it shows player connection info such as IP addressed which I don't want my staff to see.

**Comment by confuser** [comment]
So in my refactor, we (Frostcast) needed to be able to refine what staff saw. Permissions are all listed at http://dev.bukkit.org/bukkit-plugins/ban-management/pages/commands-permissions/#w-permissions

bm.command.bminfo were separated out. Seeing current bans is possible with the existing bm.command.bminfo permission. If you don't want them to see connection details, do not give them the `bm.command.bminfo.connection` permission. They're all listed.
