### ISSUE TITLE
Ban Manager leak crashed my server?

### ISSUE THREAD

**Issue by tehrenderr** [BanManagement/BanManager#604]
http://pastebin.com/L5Ed6fEE

**Comment by EvilOlaf** [comment]
Seems like the  connection to your database is unstable. I think this could lead into freeze in rare circumstances.  Though this is not BMs fault. Not entirely at least.

**Comment by tehrenderr** [comment]
So how can I prevent this?

**Comment by confuser** [comment]
You need a stable database connection. Your provider will need to solve it for you if you're not self managed
