### ISSUE TITLE
Issues on Bungeecord servers

### ISSUE THREAD

**Issue by BrandonT800** [BanManagement/BanManager#606]
Hi there, when I try using the BanManager plugin on my server, I have issues with the plugin. When I type the command in, it will either, say a notification that the player has been banned/muted/warned, or nothing will happen. When it shows this ban notification, it does not ban the player. Any ideas? Also, the servers are in "offline mode" which is a MUST with bungeecord.
Thanks!
-Brandon

**Comment by confuser** [comment]
Is bungeecord itself in online mode?

**Comment by BrandonT800** [comment]
Yes, it is.

**Comment by confuser** [comment]
Any errors in your console?

**Comment by BrandonT800** [comment]
No. One second, let me record a video of what is happening.

**Comment by BrandonT800** [comment]
https://www.youtube.com/watch?v=tzj0oOxmJfY&feature=youtu.be

**Comment by confuser** [comment]
You have a lot of errors in your console

**Comment by BrandonT800** [comment]
BM works perfectly fine, when in online mode. just unsure of what's going on when in offline mode. I believe the errors are with other plugins.

**Comment by confuser** [comment]
Have you enabled the bungeecord settings in your spigot.yml file, so UUIDs etc are forwarded correctly?
