### ISSUE TITLE
Problem whit geoip.yml file disappears when enable block country

### ISSUE THREAD

**Issue by pjorun** [BanManagement/BanManager#607]
When i add this plugin and start the server :

Folder BanManager ( before geoip enable ) http://i68.tinypic.com/34dq6q9.jpg

i have all file on this plugin, but when i enable geoip and add country to blocking and start the server file geoip.yml is disappears

Folder BanManager ( after enable geoip ) http://i63.tinypic.com/2wr2rn9.jpg geoip file disappears

**Comment by confuser** [comment]
I'm not quite sure what's causing this, but I'll try to replicate it.

**Comment by pjorun** [comment]
I checked the previous versions of the plugin , but the problem persists

**Comment by confuser** [comment]
http://ci.frostcast.net/job/BanManager/ Build 71+
