### ISSUE TITLE
Player not found?

### ISSUE THREAD

**Issue by Henaminator** [BanManagement/BanManager#608]
Hello, I have a bungeecord server and I use MySQL, all the servers are conntected to the same mysql server, but whenever I try to use /bminfo or /ban a player, I get this message: https://gyazo.com/fbcba18f9f70ff2214b9a10fc85356df.png

I also found this error in the console:
17.05 14:27:42 [Server] WARN 58 [Server thread] WARN me.confuser.banmanager.internal.hikari.pool.PoolBase - HikariPool-1 - Failed to get/set network timeout for connection. (com.mysql.jdbc.JDBC4Connection.getNetworkTimeout()I)
17.05 14:27:42 [Server] WARN 42 [Server thread] INFO me.confuser.banmanager.internal.hikari.HikariDataSource - HikariPool-1 - Started.
17.05 14:27:42 [Server] INFO Enabling BanManager v5.9.0

**Comment by EvilOlaf** [comment]
The warning is informational. Lots of servers get these at startup. No worries here.

Do you run your slaves in offline mode? Is bungee mode enabled there? Is BungeeCord running in online mode?
These might look like self-evident things but sometimes basic things can cause an issue ;)


Can you provide your `config.yml` files? You may remove your MySQL credentials before.

**Comment by Henaminator** [comment]
Yes, all in offline mode and bungee in online.

# 
# Aliases will be found and blocked automatically, e.g. msg will block tell
debug: false
databases:
  local:
    enabled: true
    host: IP
    port: PORT
    name: DATABASE
    user: USERNAME
    password: PASSWORD
    maxConnections: 102410
    tables:
      players: bm_players
      playerBans: bm_player_bans
      playerBanRecords: bm_player_ban_records
      playerMutes: bm_player_mutes
      playerMuteRecords: bm_player_mute_records
      playerKicks: bm_player_kicks
      playerNotes: bm_player_notes
      playerReports: bm_player_reports
      playerReportLocations: bm_player_report_locations
      playerWarnings: bm_player_warnings
      ipBans: bm_ip_bans
      ipBanRecords: bm_ip_ban_records
      ipMutes: bm_ip_mutes
      ipMuteRecords: bm_ip_mute_records
      ipRangeBans: bm_ip_range_bans
      ipRangeBanRecords: bm_ip_range_ban_records
  external:
    enabled: false
    host: 127.0.0.1
    port: 3306
    name: external_bans
    user: root
    password: ''
    maxConnections: 10
    tables:
      playerBans: bm_player_ban_all
      playerUnbans: bm_player_unban_all
      playerMutes: bm_player_mute_all
      playerUnmutes: bm_player_unmute_all
      playerNotes: bm_player_note_all
      ipBans: bm_ip_ban_all
      ipUnbans: bm_ip_unban_all
mutedCommandBlacklist:
- msg
softMutedCommandBlacklist:
- msg
duplicateIpCheck: true
bypassDuplicateChecks:
- 0.0.0.0
- 127.0.0.1
logKicks: false
displayNotifications: true
broadcastOnSync: false
timeLimits: {}
reportCooldown: 10
warningCooldown: 10
warningActions:
  enabled: false
hooks:
  enabled: false
checkForUpdates: true
offlineAutoComplete: true
punishAlts: false
denyAlts: false
cleanUp:
  kicks: 30
  banRecords: 0
  ipBanRecords: 0
  ipMuteRecords: 0
  muteRecords: 0
  readWarnings: 0
  unreadWarnings: 0
maxOnlinePerIp: 0
checkOnJoin: false
createNoteReasons: false

**Comment by confuser** [comment]
>  maxConnections: 102410

Your max connections is far too high, 5 - 10 will suffice. Have you enabled bungeecord forwarding within your spigot.yml file?

**Comment by Henaminator** [comment]
Yes

**Comment by confuser** [comment]
The common cause of this is due to offline mode, and bungeecord forwarding not being enabled correctly. Please ensure this is enabled on all your servers and that you have restarted them after enabling it.

If you're 100% certain that this isn't the case, please take a look at your bm_players table within your database, and see if you can find your player within there.

**Comment by Henaminator** [comment]
I found the problem, it says that my player doesn't exist when there is 2 of me in the table like this: https://gyazo.com/bcb9b443c0cd5765b37758e60c06facc.png, I tried to delete the fake one and it worked. But when I relogged the fake one came back.

**Comment by confuser** [comment]
The 'fake' one is caused by offline mode.

**Comment by Henaminator** [comment]
But all the servers on my bungee network have to be in offline mode, apart from the proxy server.

**Comment by confuser** [comment]
Yes, and you must ensure all servers have bungeecord forwarding enabled in each of their spigot.yml files which has been stated numerous times now.

**Comment by Henaminator** [comment]
There is no bungee forwarding..

# This is the main configuration file for Spigot.
# As you can see, there's tons to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
# For a reference for any variable inside this file, check out the Spigot wiki at
# http://www.spigotmc.org/wiki/spigot-configuration/
# 
# If you need help with the configuration or have any questions related to Spigot,
# join us at the IRC or drop by our forums and leave a post.
# 
# IRC: #spigot @ irc.spi.gt ( http://www.spigotmc.org/pages/irc/ )
# Forums: http://www.spigotmc.org/

config-version: 8
messages:
  whitelist: You are not whitelisted on this server!
  unknown-command: Unknown command. Type "/help" for help.
  server-full: The server is full!
  outdated-client: Outdated client! Please use {0}
  outdated-server: Outdated server! I'm still on {0}
  restart: Server is restarting
settings:
  save-user-cache-on-stop-only: false
  sample-count: 12
  player-shuffle: 0
  filter-creative-items: true
  bungeecord: true
  late-bind: false
  user-cache-size: 1000
  int-cache-limit: 1024
  moved-wrongly-threshold: 0.0625
  moved-too-quickly-threshold: 100.0
  timeout-time: 60
  restart-on-crash: true
  restart-script: ./start.sh
  netty-threads: 4
  attribute:
    maxHealth:
      max: 2048.0
    movementSpeed:
      max: 2048.0
    attackDamage:
      max: 2048.0
  debug: false
commands:
  tab-complete: 0
  spam-exclusions:
  - /skill
  silent-commandblock-console: false
  replace-commands:
  - setblock
  - summon
  - testforblock
  - tellraw
  log: true
stats:
  disable-saving: false
  forced-stats: {}
world-settings:
  default:
    verbose: true
    anti-xray:
      enabled: true
      engine-mode: 1
      hide-blocks:
      - 14
      - 15
      - 16
      - 21
      - 48
      - 49
      - 54
      - 56
      - 73
      - 74
      - 82
      - 129
      - 130
      replace-blocks:
      - 1
      - 5
    nerf-spawner-mobs: false
    growth:
      cactus-modifier: 100
      cane-modifier: 100
      melon-modifier: 100
      mushroom-modifier: 100
      pumpkin-modifier: 100
      sapling-modifier: 100
      wheat-modifier: 100
      netherwart-modifier: 100
    mob-spawn-range: 4
    entity-activation-range:
      animals: 32
      monsters: 32
      misc: 16
    entity-tracking-range:
      players: 48
      animals: 48
      monsters: 48
      misc: 32
      other: 64
    ticks-per:
      hopper-transfer: 8
      hopper-check: 8
    hopper-amount: 1
    random-light-updates: false
    save-structure-info: true
    max-bulk-chunks: 10
    max-entity-collisions: 8
    dragon-death-sound-radius: 0
    seed-village: 10387312
    seed-feature: 14357617
    hunger:
      walk-exhaustion: 0.2
      sprint-exhaustion: 0.8
      combat-exhaustion: 0.3
      regen-exhaustion: 3.0
    max-tnt-per-tick: 100
    max-tick-time:
      tile: 50
      entity: 50
    item-despawn-rate: 6000
    merge-radius:
      item: 2.5
      exp: 3.0
    arrow-despawn-rate: 1200
    enable-zombie-pigmen-portal-spawns: true
    wither-spawn-sound-radius: 0
    view-distance: 10
    hanging-tick-frequency: 100
    zombie-aggressive-towards-villager: true
    chunks-per-tick: 650
    clear-tick-list: false

**Comment by confuser** [comment]
Then ensure you have `ip_forward` set to true within your bungeecord config file

**Comment by Henaminator** [comment]
Yes, I have.

**Comment by Henaminator** [comment]
So yeah, what now?

**Comment by confuser** [comment]
You've restarted all servers, including bungeecord and double checked that bungeecord is set to true in all your servers spigot.yml files?

**Comment by Henaminator** [comment]
Yes

**Comment by Henaminator** [comment]
Should the mysql database for banmanager be in the same place as the proxy server is?

**Comment by EvilOlaf** [comment]
It does not matter on which machine the MySQLd is running as long as it is reachable for all servers and you can ensure that the connection is stable.

**Comment by confuser** [comment]
Then please make a thread on the spigot forums, as this sounds like a bungeecord/spigot issue, rather than a BM specific one.

**Comment by Henaminator** [comment]
I realised something, if I put _ip_forwardin_g to false, and goto for example my survival server and set bungeecord to false there, everything seems to work fine. But the problem about that is that, my survival server won't be bungee then, so I won't be able to use any bungee commands like /hub and /server.

**Comment by Henaminator** [comment]
Solved!

**Comment by confuser** [comment]
@Henaminator it would be helpful if you posted what the issue/solution was for others who come across this problem
