### ISSUE TITLE
About Offline mode

### ISSUE THREAD

**Issue by Nev3rGiveUp** [BanManagement/BanManager#610]
Is there any version of this plugin that I can use in 1.9 offline mode server? I know the new version doesn't support offline mode ,but like a year ago , the previous developer of my server used this plugin for ban system. How can I use it now again?

**Comment by EvilOlaf** [comment]
BM never officially supported offline mode. It supports offline mode partially. However if you run into trouble you are on your own.
PRs to enhance offline mode would be accepted though.

**Comment by Nev3rGiveUp** [comment]
http://prntscr.com/b71jfz
If my server can work with this , tell me please.

**Comment by EvilOlaf** [comment]
As I do not have a second sight about what your server is all about, your configuration and whatever I can not tell if it will run flawlessly. It probably will.
As stated above you are on your own when running offline mode.

**Comment by Nev3rGiveUp** [comment]
Ok thanks for you fast answers

**Comment by confuser** [comment]
The basic support that was added via a contribution has problems with usernames of different cases
