### ISSUE TITLE
SQL table issue

### ISSUE THREAD

**Issue by mitcus** [BanManagement/BanManager#611]
Hello, I have a short question.
After player banned, new record in sql table created.
For exapmle, I've banned player **ytrewq**, new record in bm_player_ban_records created.
But I see that nicknames shown incorrect. 
[https://yadi.sk/i/bNIYV9BvruCox](https://yadi.sk/i/bNIYV9BvruCox)

I have 
spigot 1.8.8
BanManager 5.9.0
UUID 2.8.4

database: MariaDB

I have no other issues - players banned normal.

**Comment by confuser** [comment]
Player named are stored in `bm_players`.

`bm_player_ban_records` references the player's uuid (`player_id`) which can be used to look up a name.

Hope that clears up the confusion.

**Comment by mitcus** [comment]
Oh, thanks and sorry for maybe noob request!
