### ISSUE TITLE
Can't ban/mute Ghost Client

### ISSUE THREAD

**Issue by Tristiisch74** [BanManagement/BanManager#613]
Hi, in my server, I have offline mode to true and I have some hacker who come with Ghost (like Huzuni) and I can use ./bminfo or /ban or other with this player (juste ./seen to get the IP and i can /ban IP), It create an error in database with this name and if this same name come with vanilla version, I can't use ./bminfo or other. I want to ban or just block Ghost Client to come to my server, can you help me ?

I'm sorry for my bad english, I'm not english :/

![image](https://cloud.githubusercontent.com/assets/19597873/15589413/03e4d148-2393-11e6-9799-64bcec7e1204.png)

**Comment by EvilOlaf** [comment]
Offline mode is not officially supported. If you run into trouble you are on your own.

The "error" might be interesting though. Where is it?
Check your console output.

**Comment by Tristiisch74** [comment]
I don't have error with ./bminfo just don't find the pseudo.

**Comment by EvilOlaf** [comment]
As stated at https://github.com/BanManagement/BanManager/issues/610 offline mode support has known flaws with case sensitivity. Though it was a contribution and will not be enhanced by BM itself. Feel free to enhance offline mode support by yourself and provide a PR.
