### ISSUE TITLE
Command BMinfo stopped working

### ISSUE THREAD

**Issue by jensm04** [BanManagement/BanManager#615]
/bminfo playername command stopped working, user exists in database but /bminfo returns with: **playername not found, are you sure they exist?**

**Comment by confuser** [comment]
Are you running in offline mode?

**Comment by jensm04** [comment]
That could be it, probably a misconfiguration of mine.

**Comment by confuser** [comment]
If you are using bungeecord, ensure you have it set in online mode, and ensure you have bungeecord forwarding enabled within each of your minecraft servers

**Comment by jensm04** [comment]
Are the servers supposed to be in online mode, or only the bungee server

**Comment by confuser** [comment]
If you're behind bungeecord, bungeecord itself must be in online mode. All of your servers must be in offline mode, but have bungeecord forwarding enabled within the spigot.yml file

**Comment by jensm04** [comment]
Fixed, thanks.
