### ISSUE TITLE
When kicking player without reason, player with shortest name will be kicked

### ISSUE THREAD

**Issue by Kakifrucht** [BanManagement/BanManager#621]
Just doing /kick Notch without a reason will always kick the player with shortest name apparently.

**Comment by confuser** [comment]
Is it always the shortest name, regardless of if that name matches at all?

**Comment by Kakifrucht** [comment]
Difficult to test honestly, don't want to kick players who shouldn't be.
But it sure seems that way. No matter which name you type, once I connect with account name "DDR", he gets kicked.

**Comment by confuser** [comment]
Are you on Spigot 1.9 or 1.10?

**Comment by Kakifrucht** [comment]
1.9

**Comment by confuser** [comment]
I was able to reproduce this. Something to do with `getPlayer(String)`. I don't recall it behaving like that.
