### ISSUE TITLE
Add 1.10 Support, Server Crashes

### ISSUE THREAD

**Issue by GershonR** [BanManagement/BanManager#623]
Not sure if its connected to BanManager or not but according to my staff everytime someone is banned/muted it crashes the server.

Here is some logs:
http://pastebin.com/jHe5WUjB

**Comment by confuser** [comment]
This appears to be a hacked client attempting to fly? They're kicked multiple times by the looks of it. This then causes the main thread to lockup. I'd suggest updating ProtocolLib and checking the Spigot forums to see if anyone else has reported this. I'll leave this open for now, for feedback, but based on the logs it doesn't appear to be directly caused by BM.

**Comment by GershonR** [comment]
I think i'm using either 4.0.1 or 4.0.2
Using:
https://www.spigotmc.org/resources/protocollib.1997/

I can't access the 4.0.2 build from Jenkins because that site is down
I'm not sure how to check its version in-game

**Comment by confuser** [comment]
What other plugins are you using that kick players? 1.10 is still relatively new, expect instabilities and crashing. Please ensure you're running the latest spigot build too.

**Comment by GershonR** [comment]
I run always the latest Spigot, update every couple of hours and nothing else other than EssentialsX but I think BanManager overrides

**Comment by confuser** [comment]
I meant other plugins which cause players to be kicked, e.g. NoCheatPlus etc. BM is just using a bukkit method to perform the kick. If there is a new incompatibility, then I'll fix it, however as far as I can tell, it works perfectly fine under 1.10

**Comment by GershonR** [comment]
A staff did /tempmute and it locked up the server just like that so I think its a banmanager issue

**Comment by confuser** [comment]
What errors occurred in your console/server log? According to stats, there are over a 100 servers running 1.10, and this is the first I've heard of this. So I'd like to get to the bottom of this.

**Comment by GershonR** [comment]
Here you go its similiar to the one above:
http://pastebin.com/QzcytQiD

**Comment by confuser** [comment]
Have you tried the latest developer build?

**Comment by GershonR** [comment]
I tried it but the commands don't do anything

I tried temp-muting, muting, temp-banning, banning a player but they can still talk/play
I only get a message saying they have been muted etc

**Comment by confuser** [comment]
What did the logs show with the latest developer build?

**Comment by GershonR** [comment]
Nothing appeared on the console when I was testing it, it was acting like it was properly working

**Comment by confuser** [comment]
Sorry, misunderstood your previous message. Great. I'll make a release this weekend then.

**Comment by GershonR** [comment]
Still happens:
http://pastebin.com/i0V7QpCh

**Comment by confuser** [comment]
Can you post the full crash log? It doesn't appear to be BM based on what you've pasted. Please be aware that spigot 1.10 is still unstable.

**Comment by GershonR** [comment]
It doesn't generate one, and it happened when /mute was used
