### ISSUE TITLE
bm.command.bmactivity not working for /bmactivity

### ISSUE THREAD

**Issue by runelynx** [BanManagement/BanManager#625]
Hi,
I've just updated to the latest version of BM - 5.10.0, and have newest spigot as of 5 mins ago. I have given a player the perm bm.command.bmactivity but when they try to /bmactivity <name> 200d ...  it says no permission.
The command works for me as op. When I sudo the player with the same command I'm entering, they get a permissions error.

**Comment by confuser** [comment]
Apologies for the confusion. The permission is `bm.command.activity`. I've updated the documentation. That being said, it should really be `bm.command.bmactivity` for consistency. I'll keep this open as a bug.
