### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by ArtutoGamerYT** [BanManagement/BanManager#627]
It kicks me from the game and spams this in the console:

> 19:46:33 CONSOLE: WARN]: at me.confuser.banmanager.internal.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
19:46:33 CONSOLE: WARN]: at me.confuser.banmanager.internal.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
19:46:33 CONSOLE: WARN]: at me.confuser.banmanager.internal.hikari.HikariDataSource.getConnection(HikariDataSource.java:99)
19:46:33 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadWriteConnection(DataSourceConnectionSource.java:120)
19:46:33 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadOnlyConnection(DataSourceConnectionSource.java:102)
19:46:33 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:243)
19:46:33 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:964)
19:46:33 CONSOLE: WARN]: ... 12 more
19:46:33 CONSOLE: WARN]: java.sql.SQLException: Could not build prepared-query iterator for class me.confuser.banmanager.data.PlayerMuteData
19:46:33 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
19:46:33 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:968)
19:46:33 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:533)
19:46:33 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:528)
19:46:33 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.stmt.QueryBuilder.iterator(QueryBuilder.java:389)
19:46:33 CONSOLE: WARN]: at me.confuser.banmanager.storage.PlayerMuteStorage.findMutes(PlayerMuteStorage.java:172)
19:46:33 CONSOLE: WARN]: at me.confuser.banmanager.runnables.MuteSync.newMutes(MuteSync.java:30)
19:46:33 CONSOLE: WARN]: at me.confuser.banmanager.runnables.MuteSync.run(MuteSync.java:22)
19:46:33 CONSOLE: WARN]: at me.confuser.banmanager.runnables.Runner.run(Runner.java:28)
19:46:33 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
19:46:33 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
19:46:33 CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
19:46:33 CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
19:46:33 CONSOLE: WARN]: at java.lang.Thread.run(Thread.java:745)
19:46:33 CONSOLE: WARN]: Caused by: java.sql.SQLTransientConnectionException: HikariPool-4 - Connection is not available, request timed out after 30000ms.
19:46:33 CONSOLE: WARN]: at me.confuser.banmanager.internal.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
19:46:33 CONSOLE: WARN]: at me.confuser.banmanager.internal.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
19:46:33 CONSOLE: WARN]: at me.confuser.banmanager.internal.hikari.HikariDataSource.getConnection(HikariDataSource.java:99)
19:46:33 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadWriteConnection(DataSourceConnectionSource.java:120)
19:46:33 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadOnlyConnection(DataSourceConnectionSource.java:102)
19:46:33 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:243)
19:46:33 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:964)
19:46:33 CONSOLE: WARN]: ... 12 more
19:46:33 CONSOLE: WARN]: java.sql.SQLException: Could not build prepared-query iterator for class me.confuser.banmanager.data.PlayerMuteData
19:46:33 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
19:46:34 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:968)
19:46:34 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:533)
19:46:34 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:528)
19:46:34 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.stmt.QueryBuilder.iterator(QueryBuilder.java:389)
19:46:34 CONSOLE: WARN]: at me.confuser.banmanager.storage.PlayerMuteStorage.findMutes(PlayerMuteStorage.java:172)
19:46:34 CONSOLE: WARN]: at me.confuser.banmanager.runnables.MuteSync.newMutes(MuteSync.java:30)
19:46:34 CONSOLE: WARN]: at me.confuser.banmanager.runnables.MuteSync.run(MuteSync.java:22)
19:46:34 CONSOLE: WARN]: at me.confuser.banmanager.runnables.Runner.run(Runner.java:28)
19:46:34 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
19:46:34 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
19:46:34 CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
19:46:34 CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
19:46:34 CONSOLE: WARN]: at java.lang.Thread.run(Thread.java:745)
19:46:34 CONSOLE: WARN]: Caused by: java.sql.SQLTransientConnectionException: HikariPool-4 - Connection is not available, request timed out after 30000ms.
19:46:34 CONSOLE: WARN]: at me.confuser.banmanager.internal.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
19:46:34 CONSOLE: WARN]: at me.confuser.banmanager.internal.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
19:46:34 CONSOLE: WARN]: at me.confuser.banmanager.internal.hikari.HikariDataSource.getConnection(HikariDataSource.java:99)
19:46:34 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadWriteConnection(DataSourceConnectionSource.java:120)
19:46:34 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadOnlyConnection(DataSourceConnectionSource.java:102)
19:46:34 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:243)
19:46:34 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:964)
19:46:34 CONSOLE: WARN]: ... 12 more
19:46:34 CONSOLE: WARN]: java.sql.SQLException: Could not build prepared-query iterator for class me.confuser.banmanager.data.PlayerMuteRecord
19:46:34 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
19:46:34 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:968)
19:46:34 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:533)
19:46:34 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:528)
19:46:34 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.stmt.QueryBuilder.iterator(QueryBuilder.java:389)
19:46:34 CONSOLE: WARN]: at me.confuser.banmanager.storage.PlayerMuteRecordStorage.findUnmutes(PlayerMuteRecordStorage.java:57)
19:46:34 CONSOLE: WARN]: at me.confuser.banmanager.runnables.MuteSync.newUnmutes(MuteSync.java:54)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.runnables.MuteSync.run(MuteSync.java:22)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.runnables.Runner.run(Runner.java:28)
19:46:41 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
19:46:41 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
19:46:41 CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
19:46:41 CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
19:46:41 CONSOLE: WARN]: at java.lang.Thread.run(Thread.java:745)
19:46:41 CONSOLE: WARN]: Caused by: java.sql.SQLTransientConnectionException: HikariPool-4 - Connection is not available, request timed out after 30000ms.
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.hikari.HikariDataSource.getConnection(HikariDataSource.java:99)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadWriteConnection(DataSourceConnectionSource.java:120)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadOnlyConnection(DataSourceConnectionSource.java:102)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:243)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:964)
19:46:41 CONSOLE: WARN]: ... 12 more
19:46:41 CONSOLE: WARN]: java.sql.SQLException: Could not build prepared-query iterator for class me.confuser.banmanager.data.PlayerMuteRecord
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:968)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:533)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:528)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.stmt.QueryBuilder.iterator(QueryBuilder.java:389)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.storage.PlayerMuteRecordStorage.findUnmutes(PlayerMuteRecordStorage.java:57)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.runnables.MuteSync.newUnmutes(MuteSync.java:54)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.runnables.MuteSync.run(MuteSync.java:23)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.runnables.Runner.run(Runner.java:28)
19:46:41 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
19:46:41 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
19:46:41 CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
19:46:41 CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
19:46:41 CONSOLE: WARN]: at java.lang.Thread.run(Thread.java:745)
19:46:41 CONSOLE: WARN]: Caused by: java.sql.SQLTransientConnectionException: HikariPool-4 - Connection is not available, request timed out after 30000ms.
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.hikari.HikariDataSource.getConnection(HikariDataSource.java:99)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadWriteConnection(DataSourceConnectionSource.java:120)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadOnlyConnection(DataSourceConnectionSource.java:102)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:243)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:964)
19:46:41 CONSOLE: WARN]: ... 12 more
19:46:41 CONSOLE: WARN]: java.sql.SQLException: Could not build prepared-query iterator for class me.confuser.banmanager.data.PlayerMuteData
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:968)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:533)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.iterator(BaseDaoImpl.java:528)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.stmt.QueryBuilder.iterator(QueryBuilder.java:389)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.storage.PlayerMuteStorage.findMutes(PlayerMuteStorage.java:172)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.runnables.MuteSync.newMutes(MuteSync.java:30)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.runnables.MuteSync.run(MuteSync.java:22)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.runnables.Runner.run(Runner.java:28)
19:46:41 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
19:46:41 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
19:46:41 CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
19:46:41 CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
19:46:41 CONSOLE: WARN]: at java.lang.Thread.run(Thread.java:745)
19:46:41 CONSOLE: WARN]: Caused by: java.sql.SQLTransientConnectionException: HikariPool-4 - Connection is not available, request timed out after 30000ms.
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.hikari.pool.HikariPool.getConnection(HikariPool.java:196)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.hikari.HikariDataSource.getConnection(HikariDataSource.java:99)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadWriteConnection(DataSourceConnectionSource.java:120)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadOnlyConnection(DataSourceConnectionSource.java:102)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:243)
19:46:41 CONSOLE: WARN]: at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.createIterator(BaseDaoImpl.java:964)
19:46:41 CONSOLE: WARN]: ... 12 more

Im using the latest version of BanManger in 1.8.8 spigot

**Comment by confuser** [comment]
> 19:46:33 CONSOLE: WARN]: Caused by: java.sql.SQLTransientConnectionException: HikariPool-4 - Connection is not available, request timed out after 30000ms.

Your MySQL connection dropped and couldn't be re-established. This isn't a bug with BanManager itself. Please ensure you have a stable connection.

**Comment by ArtutoGamerYT** [comment]
The MySQL is good... It works 4 other plugins when banmanager doesnt

**Comment by confuser** [comment]
BM needs a constant stable database connection. Any instabilities will cause issues. There's nothing I can do within the plugin to fix issues with your database.

**Comment by ArtutoGamerYT** [comment]
The database is stable.. When i updated to the latest version of BM this
error appears...

**Comment by ArtutoGamerYT** [comment]
Plugin Uninstalled.
