### ISSUE TITLE
Constant memory leaks

### ISSUE THREAD

**Issue by MattVibes** [BanManagement/BanManager#629]
Hello,
I find this plugin very useful and use it on my server. I use a local database for a bungeecord server. However once in a while (quite often), my entire dedicated server starts lagging, the cause for this is this plugin which causes huge memory leaks for some strange reason. 
Thanks for reading this,
Have a nice day.

**Comment by confuser** [comment]
What leads you to believe it's this plugin causing the memory leak?

**Comment by MattVibes** [comment]
The plugin throws lots of errors in the console.

**Comment by confuser** [comment]
It would help if you posted some of them

**Comment by confuser** [comment]
Closing due to lack of reply
