### ISSUE TITLE
Setting Specific Temp Times

### ISSUE THREAD

**Issue by UntoldFury** [BanManagement/BanManager#631]
Hello!

I was wondering if there was a way to set a permission so a certain group can only tempmute/ban up to a certain point. (Such as 5 hours). I can't seem to find any way to do this.

Thanks for your help!
UntoldFury

**Comment by confuser** [comment]
Please see the timeLimits config option: https://github.com/BanManagement/BanManager/blob/master/src/main/resources/config.yml#L86-L98
