### ISSUE TITLE
[Q] Is there any option to disable UUID feature?

### ISSUE THREAD

**Issue by UnioDex** [BanManagement/BanManager#632]
I am running an offline mode server and i dont need UUID. I still using BanManager 4.0. Is there any option to disable UUID feature in latest version?

**Comment by EvilOlaf** [comment]
If your server is running in offline mode BM will generate random UUIDs (based on the name afaik). This can not be disabled.

The offline mode support of BM was contributed by the community and this behavior is not officially supported. If you run into trouble when using offline mode you are on your own.

You can enhance offline mode support by yourself and if you like share your code by issuing a PR.

**Comment by confuser** [comment]
See #582, I've just pushed a possible fix for it which may offer support in a developer build. However, conversion from v4 -> v5 was removed in the recent v5 versions, you'll need to use an older v5 build. NOTE: I can't recall if the converter supported offline mode or not, if it didn't, then I'm afraid you'll need to perform the conversion yourself.
