### ISSUE TITLE
Memory leaks once in a while

### ISSUE THREAD

**Issue by MattVibes** [BanManagement/BanManager#633]
Once in a while I will get this:

`29.06 12:08:26 [Server] WARN 38881928 [HikariPool-1 housekeeper] WARN me.confuser.banmanager.internal.hikari.pool.ProxyLeakTask - Connection leak detection triggered for com.mysql.jdbc.JDBC4Connection@211b0527, stack trace follows
29.06 12:08:26 [Server] WARN java.lang.Exception: Apparent connection leak detected
29.06 12:08:26 [Server] WARN at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadWriteConnection(DataSourceConnectionSource.java:120)
29.06 12:08:26 [Server] WARN at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:308)
29.06 12:08:26 [Server] WARN at me.confuser.banmanager.listeners.LeaveListener$1.run(LeaveListener.java:35)
29.06 12:08:26 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
29.06 12:08:26 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
29.06 12:08:26 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
29.06 12:08:26 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
29.06 12:08:26 [Server] WARN at java.lang.Thread.run(Thread.java:745)
29.06 12:10:51 [Server] WARN Exception in thread "Craft Scheduler Thread - 510" 
29.06 12:10:51 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin CommunityBridge v2.6.0.000 generated an exception while executing task 34
29.06 12:10:51 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
29.06 12:10:51 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
29.06 12:10:51 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
29.06 12:10:51 [Server] INFO at java.lang.Thread.run(Thread.java:745)
29.06 12:10:51 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
29.06 12:10:51 [Server] INFO at org.communitybridge.main.CBMetrics.postPlugin(CBMetrics.java:350)
29.06 12:10:51 [Server] INFO at org.communitybridge.main.CBMetrics.access$4(CBMetrics.java:343)
29.06 12:10:51 [Server] INFO at org.communitybridge.main.CBMetrics$1.run(CBMetrics.java:229)
29.06 12:10:51 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
29.06 12:10:51 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
29.06 12:10:51 [Server] INFO ... 3 more`

**Comment by confuser** [comment]
That is not a memory leak. It's a warning informing you that a query took too long. If your database connection is slow, you can disable leak detection in your config by setting it to 0.

As for your other error, you have an outdated plugin CommunityBridge.
