### ISSUE TITLE
Current spigot.

### ISSUE THREAD

**Issue by keyman1986** [BanManagement/BanManager#636]
INFO [BanManager] Enabling BanManager v5.10.1 03.07 20:34:53 [Server] WARN 108 [Server thread] INFO me.confuser.banmanager.internal.hikari.HikariDataSource - HikariPool-1 - Started. 03.07 20:35:11 [Server] WARN 18434 [Server thread] INFO me.confuser.banmanager.internal.hikari.pool.HikariPool - HikariPool-1 - Close initiated... 03.07 20:35:11 [Server] WARN 18438 [Server thread] INFO me.confuser.banmanager.internal.hikari.pool.HikariPool - HikariPool-1 - Closed. 03.07 20:35:11 [Server] ERROR Error occurred while enabling BanManager v5.10.1 (Is it up to date?) 03.07 20:35:11 [Server] INFO me.confuser.banmanager.internal.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 10 times. Giving up. 03.07 20:35:11 [Server] INFO at me.confuser.banmanager.internal.hikari.pool.HikariPool.checkFailFast(HikariPool.java:528) ~[?:?] 03.07 20:35:11 [Server] INFO at me.confuser.banmanager.internal.hikari.pool.HikariPool.<init>(HikariPool.java:118) ~[?:?] 03.07 20:35:11 [Server] INFO at me.confuser.banmanager.internal.hikari.HikariDataSource.getConnection(HikariDataSource.java:94) ~[?:?] 03.07 20:35:11 [Server] INFO at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadWriteConnection(DataSourceConnectionSource.java:120) ~[?:?] 03.07 20:35:11 [Server] INFO at me.confuser.banmanager.internal.ormlite.jdbc.DataSourceConnectionSource.getReadOnlyConnection(DataSourceConnectionSource.java:102) ~[?:?] 03.07 20:35:11 [Server] INFO at me.confuser.banmanager.internal.ormlite.dao.BaseDaoImpl.isTableExists(BaseDaoImpl.java:689) ~[?:?] 03.07 20:35:11 [Server] INFO at me.confuser.banmanager.storage.PlayerStorage.<init>(PlayerStorage.java:40) ~[?:?] 03.07 20:35:11 [Server] INFO at me.confuser.banmanager.BanManager.setupStorages(BanManager.java:326) ~[?:?] 03.07 20:35:11 [Server] INFO at me.confuser.banmanager.BanManager.onEnable(BanManager.java:124) ~[?:?] 03.07 20:35:11 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.10.jar:git-Spigot-c3e4052-1953f52] 03.07 20:35:11 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52] 03.07 20:35:11 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52] 03.07 20:35:11 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52] 03.07 20:35:11 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52] 03.07 20:35:11 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:416) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52] 03.07 20:35:11 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:381) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52] 03.07 20:35:11 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:336) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52] 03.07 20:35:11 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:270) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52] 03.07 20:35:11 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52] 03.07 20:35:11 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_65] 03.07 20:35:11 [Server] INFO Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 10 times. Giving up. 03.07 20:35:11 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_65] 03.07 20:35:11 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_65] 03.07 20:35:11 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_65]

**Comment by EvilOlaf** [comment]
First of all please use proper formatting. Reading this is kind a pain in the butt.
Secondly make sure your mysql credentials are correct and if not hosted on `localhost` make sure your database is externally reachable.
`[Server] INFO me.confuser.banmanager.internal.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not create connection to database server. Attempted reconnect 10 times. Giving up.`
