### ISSUE TITLE
Duplicated IDs per player

### ISSUE THREAD

**Issue by Arkazium** [BanManagement/BanManager#637]
Hello,

I know my problem is known but I have some player who have duplicated id, i think it's possible with a hacked client, look this:
`[BanManager] Requesting name for 9f263204-402a-3223-a85f-aa71eb1afa20`
`[BanManager] Duplicates found for Xanty694, was unable to contact Mojang for updated names`
`[BanManager] Requesting name for 4563f9bb-aa4e-4a8a-9e27-d01599d88cc9`
`UUID of player Xanty694 is 41a0c8e2-45c1-303c-b5e0-cee604f9c65f`

The problem is: I can't ban these people (impossible), and there is a solution to remove the fake id ?

Thanks for help !

**Comment by confuser** [comment]
This is due to player name changes. You have a new player that has taken the name of another player. BM then tries to contact Mojang servers to find out what the new player name is to update it's database with.

**Comment by Arkazium** [comment]
So I can only ban the uuid ?

**Comment by confuser** [comment]
In this case, yes. All action commands, i.e. ban, mute, warn etc all accept a UUID or a player name.

Alternatively you can do a manual lookup of the name via the UUID to find out what they should really be and update the relevant rows in the players table. Or you can just delete the duplicates from the players table.

Does your server not allow external connections? The only reasons the lookup would fail, is if there's networking problems, or you've reached Mojangs rate limiting for its API.

**Comment by Arkazium** [comment]
Ok, i just don't find the command for /ban an UUID.

How i can remove duplicates from the players in table ? I'm on table: bm_players in sql,  I don't find.
Now i thinks my server doesn't allow external connections.

**Comment by confuser** [comment]
Are you running in online mode or offline mode? It must allow external connections if it's online mode.

`/ban 9f263204-402a-3223-a85f-aa71eb1afa20 Test` should work

**Comment by Arkazium** [comment]
Sorry, my server running in offline mode for the moment, and there is a solution to remove duplicates from the players in table ?

**Comment by confuser** [comment]
Please update to a developer build, builds 92+

http://ci.frostcast.net/job/BanManager/

Set onlineMode to false in plugins/BanManager/config.yml and restart the server

**Comment by Arkazium** [comment]
Ok I do it, but now what's happening ? it will fix the problem ? :)

**Comment by confuser** [comment]
Yes, however none of the existing UUIDs will be correct. Setting onlineMode to false will now ensure any new players joining have a correct case-insensitive offline UUID. This means unfortunately you'll need to wipe all BanManager data in your database and start over.

**Comment by Arkazium** [comment]
Ok I will try, thank you very much for this option.
I close :)
