### ISSUE TITLE
Question, help

### ISSUE THREAD

**Issue by mixa46rus** [BanManagement/BanManager#638]
How to make it show who banned the player, instead of "banned by Server"?

![2016-07-05_21-29-23](https://cloud.githubusercontent.com/assets/20305705/16595408/92ae82ce-42f7-11e6-88da-8800606ae9c6.png)

**Comment by confuser** [comment]
Bans issued via the console will state they've been banned by the console (or some other name depending on what it's been configured to; I imagine `Server` in your case? 

Any bans issued by a player in game will display their name as having performed the ban. I hope that answers your question.
