### ISSUE TITLE
/report comes up with a error

### ISSUE THREAD

**Issue by starwarsfreak219** [BanManagement/BanManager#639]
Whenever a player on my server does /report <player> <reason> it will come up with an error(http://hastebin.com/uyirulebec.coffee), from what I can tell, it says that something is null in the player_reports, I did reset the report files in my database but it still came up with this error, I did restart the server to see if that would help, but it still came up with the error. This is on the latest Spigot 1.10.2 build and the plugin version is 5.10.1... Do you think you can help determine the issue? This is the only issue I am currently having with the plugin atm. Thanks! ☺

**Comment by starwarsfreak219** [comment]
Just tested the latest Development build, it still comes up with the same error...

**Comment by starwarsfreak219** [comment]
So, I just created a fresh new server to see if I can test it on a different scale, I also created a new database, this seems to be a issue on the plugins end for as I fresh generated it... along with fresh generated the database, this is on the Development build so I would think that it would be in the actual build as well since I had the same issue on both of these builds... it seems to be only affecting the player reports, but it only does it when a player does /report <player> <reason>, if the user is unreportable, or not allowed to be reported, then it will say that they are not allowed to be reported, and not give an error, only when they are allowed to be reported it runs into the error.

**Comment by starwarsfreak219** [comment]
I went all the way back and tested on earlier versions of spigot, I went back to 1.9, resetting my database on the test database, and it worked just fine on the 1.9 version(yes, I used the 1.9 version of this plugin for this test, looks like the latest version breaks in 1.10), still came up with errors on 1.10, and it was the same exact error I am experiencing, yes, updating to the 1.10.2 server, I did reset the database, but the issue still remained, looks like something is empty in your guys' coding part...

**Comment by confuser** [comment]
Thank you for your investigative report. This error is a little odd. It's caused by `assignee_id` within your `bm_player_reports` not allowing null values. I've double checked the schema defined in the plugin, and it's definitely set to allow null values. I also can't find anything in the commit history that had this problem which made it to a developer build either. Can you check your bm_player_reports table please?

**Comment by starwarsfreak219** [comment]
I took a screenshot of my tables, here it is:
http://imgur.com/GrMeO6v

**Comment by confuser** [comment]
As expected, asingee_id in your database does not allow null values. Please click "Change" for that column and allow null. With a fresh install I cannot reproduce this issue unfortunately.

**Comment by starwarsfreak219** [comment]
Looks like it is fixed now! Thanks! ☺
