### ISSUE TITLE
disable the mute broadcast

### ISSUE THREAD

**Issue by MrLazio101** [BanManagement/BanManager#642]
Idk if this is implemented yet or not, but can u disable the mute broadcast. even when i have the  message in the messages.yml to empty quotes it still shows a empty space in the chat and it looks really weird and annoying #

**Comment by EvilOlaf** [comment]
There is permission node for the broadcast AFAIK. Negate it for yourself and you're good to go.

**Comment by confuser** [comment]
Negate `bm.notify.mute` and `bm.notify.tempmute`
