### ISSUE TITLE
A way to remove /report messages by doing /report remove <id> so it will automatically clear up closed reports

### ISSUE THREAD

**Issue by starwarsfreak219** [BanManagement/BanManager#645]
I think this enhancement would make /report a lot better, it gets annoying since I have to reset my player reports file even if I remove it manually from my Database, it will make the next one go to page 2 and say the <id> of it, for instance, I report 1 person and that is on one page, then I make a second report, remove it in my Database, make another report after that, makes the id 3 and goes to a new page, I believe that there should be a way to remove reports, the reports area can get spammed, and sometimes cases are still open when they were closed, I believe this would help server owners save space and time when dealing with removing reports that some users may spam, or make a false report. Hope this enhancement gets added.

**Comment by confuser** [comment]
I'm not quite sure I follow. Id's are sequential, even if a report is removed, it'll never be reset back to 1. The idea is for reports to be kept as part of a record. Similar to a player's ban history. You can choose which states to search with via `/report list [page] [state]`, i.e. to list all open reports `/report list 1 Open`

**Comment by starwarsfreak219** [comment]
So then it would be harder to remove unnecessary reports that can occur(false reports). Which can get in the way, but then again, I could put them into the closed reports. But it might confuse some staff and cause issues. I will have to tell staff to let me deal with reports and if they are assigned to the report then they have to deal with it. I think that would be the best bet.

**Comment by confuser** [comment]
Would a new state `Invalid` be of any help in those cases?
