### ISSUE TITLE
WebUI: Error: Invalid response from server, try again.

### ISSUE THREAD

**Issue by Legoooo** [BanManagement/BanManager#649]
Hello,

I have setup the WEBUI correctly with details and Console UUID, is there a way to fix this? 

(Sorry if I did upload this in the wrong section, I am new to Github.)

![](https://i.gyazo.com/3c0dc3e75e5b60308d0527a261f143a8.png)

![](https://i.gyazo.com/27af8e5573502c810d56c74a6ddd950b.png)

**Comment by EvilOlaf** [comment]
Actually it is in the wrong section as this repository here is about the java plugin. Put your report here: https://github.com/BanManagement/BanManager-WebUI
