### ISSUE TITLE
Null Pointer?

### ISSUE THREAD

**Issue by ryans1230** [BanManagement/BanManager#651]
I know a may be a few builds behind but shouldn't be getting this right? 
http://hastebin.com/huxijomaqa.avrasm

**Comment by confuser** [comment]
I would highly recommend trying the latest developer build. See #646 for more info.

**Comment by ryans1230** [comment]
Ah okay. We did just move our servers over to a HDD due to storage issues, and all our databases are still on the SSD

Side note: you wouldn't happen to know of any ways to split the debug messages from the rest on the normal console out? We are using log4j, but I haven't found anything on it yet

**Comment by confuser** [comment]
You can use grep if you're on linux, or you can use a custom log4j config with custom pattern matching, e.g. http://stackoverflow.com/a/731106 requires starting up the server with the following flag `-Dlog4j.configurationFile=LocationOfYourConfigFileHere`
