### ISSUE TITLE
BanManager commands not working in 5.11.0

### ISSUE THREAD

**Issue by StarDan90** [BanManagement/BanManager#655]
I'm trying to ban, kick, warn... a player, but nothing happens. No errors. I'm using the default config for the plugin. I can't use any BanManager commands when OnlineMode is set to false. My server is an offline server.

**Comment by EvilOlaf** [comment]
Did you check your console for additional information?

**Comment by StarDan90** [comment]
Yes, but it doesn't show anything

**Comment by StarDan90** [comment]
The banmanager commands work fine from console, but not from player

**Comment by confuser** [comment]
Were there any warnings or errors on start up?

**Comment by StarDan90** [comment]
Nope, no errors or warnings at all

**Comment by confuser** [comment]
This may have been related to #661 

Please try builds 110+ https://ci.frostcast.net/job/BanManager/
