### ISSUE TITLE
Spigot server crash

### ISSUE THREAD

**Issue by wesley27** [BanManagement/BanManager#656]
This happened on the latest version and the previous version, I've no idea what's causing it. I believe it's a BM issue because the dump says so - Here's the log: http://pastebin.com/mYKUKx4J

The server just randomly crashes with this error. Not often, but no crashes are really desired.

Thanks!

**Comment by confuser** [comment]
Possibly caused by a corrupted chunk. Take a look at the error at the very
end.

**Comment by wesley27** [comment]
That's possible, scanning now. Why would that dump a BM error though?

**Comment by confuser** [comment]
There isn't a bm error, it's merely a warning.
