### ISSUE TITLE
SQL Error on player report

### ISSUE THREAD

**Issue by miguel456** [BanManagement/BanManager#657]
So today when I tried to report myself through the console for testing the messages I got a stacktrace that displayed an SQL error.
Stacktrace: http://hastebin.com/heqakemaxu.coffee

I'm running Spigot 1.10 and I downloaded the appropriate version (v5.10.1) from Bukkit.
The stacktrace says that the column 'asignee_id' on table 'bm_player_reports' cannot be null. So ironically I made it null by running the following SQL Query:
```
ALTER TABLE bm_player_reports
CHANGE assignee_idassignee_id` binary(16) NULL AFTER state_id;
```
And next time I tried reporting it went trough without a hassle. Fixed it by making the column null.
So my question is: Is this a bug or a confusion with my version and my head?

**Comment by confuser** [comment]
Most certainly a bug. Someone else reported this a while ago. I've just found what's causing it. Thanks for bringing it up.
