### ISSUE TITLE
How to delete reports? And a lot of report suggestions. 

### ISSUE THREAD

**Issue by FrozenBeard** [BanManagement/BanManager#658]
There isn't that much documentation on how to manage reports, I figured out from the permissions there is a /report close, a /report list /report assign /assign teleport, but there is no delete? Multiple efforts just create new tickets with that word as the report! Its a mess, players create a mess, they screw up and submit multiple reports.

I really dont like, if you misspell any of the report commands then its added as a new report, this also stops players from using those key words at the begging of their report.  what would be a better option would be to create a /reports (WIth an S at the end) This then lists automatically, You could then do /reports teleport, /reports assign, it would also make sense to have comer separated ID's so you could assign multiple reports to a single player. 

/bmdelete report ID would make sense to be included, with its own permission. 

Limited messages, the messages for reports are tiny, a better option would be to allow an extended report to be made by allow the reporter to hold a book they have written with an extended report, this has multiple pages and is easy to read.

**Comment by EvilOlaf** [comment]
My guess is the documentation will be added as soon as the whole report thing is complete. 

As for now maybe it helps when you take a look at the wiki of my BanManager fork. There is a page with all the ideas I wrote together for the report feature. 

I like the idea to manage the reports with another command than creating new reports. Have to admit I never thought that would be a problem but makes perfect sense.

**Comment by confuser** [comment]
Most of these changes are reasonable.

The typos opening reports is most certainly a bug. The reports feature will become more manageable within the new web ui. Feedback during development on it is most certainly welcome.

**Comment by confuser** [comment]
- [ ] Migrate report sub commands to `/reports`
- [ ] `/report <player>` should not make a callout to Mojang if the player doesn't exist in the database
- [ ] Add `/bmdelete` support for reports
- [ ] Add PlayerReportDeletedEvent for ReportsLogger to remove associated references
- [ ] Add support to assign multiple reports to a single player, i.e. `/reports assign 1,2,3 confuser`
- [ ] Add sub commands to documentation

**Comment by confuser** [comment]
Would it be preferable to always open a book when reporting a player? Optionally could open a book if no reason specified, but that may cause confusion for players.

**Comment by confuser** [comment]
`/bmdelete reports <ids>` already exists, however it doesn't remove any associated data, i.e. locations. I've raised a separate bug for that in #659

**Comment by confuser** [comment]
Almost all of this is now in the latest developer build. I've opened #668 for using a book.
