### ISSUE TITLE
Spigot server crash (new error with more bm references)

### ISSUE THREAD

**Issue by wesley27** [BanManagement/BanManager#660]
Sorry to bother with a new error, my server has been crashing randomly all day with this stack: http://pastebin.com/C07quygw

There's a lot of BM refereneces in the dump, as opposed to the single warning I got in the dump from #656

**Comment by confuser** [comment]
What version of BM are you running? How much memory is your server using?

**Comment by wesley27** [comment]
@confuser Using BM v5.11.0. Server is config'd to use a max of 8GB, it allocates around 4GB on average, and uses 2-3GB on average.

**Comment by confuser** [comment]
I'm not sure this is caused by BM. Is there anything in the logs before the crash?

**Comment by wesley27** [comment]
@confuser there's nothing in the logs before the crash, it's apparently random. I actually don't think it's a BM issue anymore, my server is randomly crashing and the stack is different every time, the first one just happened to reference BM. I think it's being caused by dynmap updating tiles to sql frequently.

Thanks!
