### ISSUE TITLE
One specific player can't execute any banmanager commands

### ISSUE THREAD

**Issue by HashtagOliver** [BanManagement/BanManager#662]
So to the best of my knowledge I have set up the plugin completely fine, there are no errors on startup or when executing any commands yet one specific account (username is Hashtag) cannot execute anything, when typing a command such as /warn, the plugin shows "/warn <player> <reason> in chat but when it is filled out - for example - /warn test123 test nothing comes up in chat or console: 

Pictures:
[Hashtag pic 1](https://i.gyazo.com/e679ef158387ead07af73fb0854c731b.png)
[Hashtag pic 2](https://i.gyazo.com/6362ed07450a9205ba180786f0b29f91.gif)
[Console receiving commands](https://i.gyazo.com/40c2d31d4cad49d16daf1e9e73d9d557.png)

Tests repeated on a second account:
[Working on second account](https://i.gyazo.com/e1e5054d5bb297eb0973d49fd6919c6e.png)
[Console receiving commands](https://i.gyazo.com/7d07d4cf069afaac951ef0aa09b87d54.png)

All players have no conflicting permissions or inheritances - commands do not work with/without op or specific banmanager permissions:
[permissions](https://i.gyazo.com/7a0b04fe6ca4a3fa86f680ea91d3d86c.png) - (bm.* was added as a test)

I have also wiped my config and tested without editing any of the files (except connecting to mySQL database) which does not fix the problem either.

**Comment by frdmn** [comment]
@HashtagOliver Could you try to setup an secondary development server using Spigot/Bukkit and **just** BanManager? Then give yourself OP permissions and retry. If it works there, something is interfering with BM on your prod server.

**Comment by HashtagOliver** [comment]
Doesn't fix the problem on an empty Spigot server with only BanManager, also would it really be another plugin interfering with just _one_ player being able to use the commands? They work fine for everyone else.

**Comment by confuser** [comment]
Are you running in online or offline mode?

**Comment by HashtagOliver** [comment]
I own the premium account Hashtag & I have ran the test server in both online and offline mode which both have the same problem.

**Comment by confuser** [comment]
Did you wipe the tables when switching between online and offline mode? Can you check in the `bm_players` table, that the user exists? `SELECT HEX(id), name, lastSeen FROM bm_players WHERE name = 'Hashtag'`

**Comment by HashtagOliver** [comment]
Yes, I've also tried it on a completely different MySQL server to make sure it wasn't my one and it is giving me the same issue.

**Comment by confuser** [comment]
Is it just warnings that fail, or other commands as well?

I've just ran this locally without problems via the console

```
>warn Hashtag test
[11:09:45 INFO]: [BanManager] Requesting UUIDs for Hashtag
[11:09:45 INFO]: Hashtag has been warned by Console for test
>warn Hashtag test1
[11:09:50 INFO]: This player was warned too recently, try again later
>tempban Hashtag 5m test
[11:10:03 INFO]: Hashtag has been temporarily banned for 5 minutes by Console for test
```

**Comment by HashtagOliver** [comment]
All punishment commands, so excluding /bminfo and the like which do not enforce any bans, kicks or mutes do not work when _executed_ by the account "Hashtag", it can be punished just fine by other accounts.

**Comment by HashtagOliver** [comment]
I'll also mention I've used this plugin on other servers before with the account Hashtag and had not had this problem.

**Comment by confuser** [comment]
Did you check that the user was in your bm_players table?

**Comment by HashtagOliver** [comment]
[on the brand new empty database](https://i.gyazo.com/c4bbbb532aee7c9966de47dc90604f38.png)

**Comment by TrexMX** [comment]
I have the same issue. When i execute a command from the console it works, but if a player execute a command it doesn't works.

**Comment by HashtagOliver** [comment]
I can sudo hashtag from the console and it works but the actual account cant

**Comment by confuser** [comment]
@TrexMX Please try the latest developer build. That issue should already be fixed for offline servers.


I'm not entirely sure what the issue is @HashtagOliver in your case, as you state it occurs in online mode, and without any additional plugins installed. Are you using a plugin manager by any chance?

**Comment by HashtagOliver** [comment]
Nope, only Spigot is on the server.

**Comment by confuser** [comment]
Are you still having this issue @HashtagOliver ?
