### ISSUE TITLE
Missing actor ip ban NPE

### ISSUE THREAD

**Issue by gibbswe** [BanManagement/BanManager#666]
http://pastebin.com/rECr7E31

Running on Spigot 1.10.2 and debug enabled.

**Comment by confuser** [comment]
You have an ip ban that was executed by a player that doesn't exist in the database.

Note: Ip loadAll should gracefully handle this, similar to player bans/mutes.

**Comment by gibbswe** [comment]
Is there a way for me to find the player/IP-ban or what should I do? Remove IP-bans?

**Comment by confuser** [comment]
You could try the following query:

```
SELECT i.id, INET_NTOA(i.ip) AS ip
FROM bm_ip_bans i 
        LEFT JOIN bm_players a 
            ON a.id = i.actor_id
WHERE a.id IS NULL;
```

This will tell you which ip ban is affected. You can delete it for now.

**Comment by gibbswe** [comment]
Thanks; solved it by setting the console as actor_id. Although, when trying to update 1 row at a time the binary-value cot corrupted and I noticed there was another row with the corrupted ID already.

But now it works, thanks (:
