### ISSUE TITLE
Report player reason with book

### ISSUE THREAD

**Issue by confuser** [BanManagement/BanManager#668]
If no reason specified, open a book to allow the player to type a more detailed report

**Comment by EvilOlaf** [comment]
Another solution for the character limit would be allowing to use multiple lines. All chat messages of a player will be catched until he writes a word or command to exit this mode. 

For example like this: 
"you are now in report mode. Please write all needed details to the chat. You can use multiple lines. When you're done use the command /report done to exit report mode."

**Comment by confuser** [comment]
That would work much better in terms of cross-compatibility. Opening a book server side requires using packets/Protocol Lib. My only concern is if someone makes a mistake and wishes to edit a line.

**Comment by EvilOlaf** [comment]
If a report would allow the character limit of Minecraft only it would not be possible to edit the report afterwards as well.

**Comment by confuser** [comment]
Not the report as a whole, but on a line by line basis it would be possible.

**Comment by EvilOlaf** [comment]
I meant to say that I think that people will not care about typos.

**Comment by confuser** [comment]
Perhaps, but I can imagine scenarios where people would, such as mentioning the wrong player names etc as that would affect the report itself. In those cases, it would be beneficial to offer a way to change a line whilst in 'report mode'.

**Comment by EvilOlaf** [comment]
I see....hm what about JSON'ing the chat?
Imagine this: You enter the first line of your report in report mode. 
When sent to server with `return` the line you entered will be shown in chat and in theory you are now able to write the next line.

BUT. The text of the first line (or whatever line you just entered or show all lines) is not normal text. When moving the mouse over the text a box shows up with something like `click to remove this line`. And when you do, well, the line will be removed from the report ^^.

**Comment by confuser** [comment]
What if there were two options at the end of each line? One an edit, the other delete. Clicking edit puts the text in the command line, prefixed with `#lineNumberHere textHere`.

**Comment by EvilOlaf** [comment]
I did not know that it is possible to activate and feed a players chat line server side. That would be awesome.

**Comment by confuser** [comment]
It's not server side, it'd be done using JSON chat, which can prefill the required message.

**Comment by EvilOlaf** [comment]
Interesting to know anyways :P.

**Comment by xH3LLRAIZ3Rx** [comment]
In 1.11 they just increased the character limit from 100 to 256 characters
