### ISSUE TITLE
Mute on warn case sensitive

### ISSUE THREAD

**Issue by Kakifrucht** [BanManagement/BanManager#669]
Right now the function checks the case of the input, could you remove make it case insensitive please?

**Comment by confuser** [comment]
I'm afraid I don't quite follow. It's UUID based.

**Comment by Kakifrucht** [comment]
Oh sorry, I wasn't being very clear. I'm talking about the prompt to input the warn reason after a player has been warned. If I warn him for "InSuLtInG OtHeR PlAyerS" he has to type the exact same case, "insulting other players" should work too though.
