### ISSUE TITLE
Can't ban players

### ISSUE THREAD

**Issue by StarDan90** [BanManagement/BanManager#678]
I have been trying to tempban myself from Console. It doesn't work (it shows the notification that I was banned, but I'm still connected to the server. My server is in offline mode and my bungeecord is also in offline mode. And it doesn't matter whether I set onlinemode to true or false in BanManager config. The command /kick works fine, but doing it without arguments randomly kicks someone.
I'm using PaperSpigot 1.10.2 and latest BanManager snapshot. This happened in PaperSpigot 1.9.4 as well.

**Comment by EvilOlaf** [comment]
Offline mode is not officially supported by BanManager.
Offline mode support was originally a contribution from the community.
So if you run your server in offline mode (unless you have a online mode bungee proxy before) you are on your own.

**Comment by confuser** [comment]
Odd. I'll see if I can reproduce this.

**Comment by Arkazium** [comment]
Same problem, there is a fix now ?

**Comment by confuser** [comment]
I've not been able to reproduce this unfortunately. Fresh install of BM and Spigot, server set to offline mode, as well as BM set to offline mode. Bans work as expected.

**Comment by confuser** [comment]
Scratch that, found the issue
