### ISSUE TITLE
Question: extract player bans via CLI

### ISSUE THREAD

**Issue by EvilOlaf** [BanManagement/BanManager#679]
Hey there,

is it possible to extract a list of all players (including UUID and last known name) which are currently permanently banned via MySQL cli?
Actually I am quite sure this is possible, otherwise stuff like the WebUI would not work. Unfortunately I am not very deep in MySQL so I have no clue how I would have to set up the command to get the proper output.

Thanks for reading

**Comment by confuser** [comment]
```sql
SELECT HEX(p.id), p.name, b.reason, b.expires 
  FROM bm_players p 
  RIGHT JOIN bm_player_bans b ON b.player_id = p.id
```
