### ISSUE TITLE
Permissions not working ?

### ISSUE THREAD

**Issue by denireilly** [BanManagement/BanManager#685]
Hello,

so i recently installed BM for my network and everything is setup and working apart from when giving my
staff team permissions to use the plugin it still says they dont have permission 

Using version BanManager v3.13

**Comment by confuser** [comment]
What permission plugin are you using?

**Comment by denireilly** [comment]
Group manager

**Comment by confuser** [comment]
Were you able to resolve this @denireilly? Sounds like a setup issue rather than an issue with the plugin itself.

What permission nodes are you giving your staff?

**Comment by denireilly** [comment]
Hello,

i am still not able to if i give them the Bm.* they can use the commands but anything else is not working 
i am using the permission node found here https://dev.bukkit.org/bukkit-plugins/ban-management/pages/commands-permissions/

**Comment by confuser** [comment]
So the `bm.command.ban` permission is not working for you?

**Comment by denireilly** [comment]
thats correct yeh

**Comment by confuser** [comment]
This isn't an issue with BM itself. I'm not overly familiar with group manager, but can you post your group manager config?

**Comment by denireilly** [comment]
its group manager were using , here is a copy of the perms http://prntscr.com/cx5pgx

**Comment by denireilly** [comment]
Please let me know asap if you could think of anything ?

**Comment by denireilly** [comment]
Also think there is a small bug where it displays the recent bans , http://prntscr.com/cxgckc it seems to display weird link to site http://s3.thecraftingdead.com/banmanagement/index.php

**Comment by confuser** [comment]
I can't see anything obvious from your screenshot. From the plugin perspective, the command is correctly associated with the bm.command.ban permission

**Comment by denireilly** [comment]
its a bungee network i dont know if anything will effect it that way ?

**Comment by denireilly** [comment]
anything ?

**Comment by confuser** [comment]
There's nothing in BM that could cause this. Please raise a bug with GroupManager to investigate further. In fact, is GM even still supported?
