### ISSUE TITLE
Lower priority on AyncChatEvent?

### ISSUE THREAD

**Issue by Kakifrucht** [BanManagement/BanManager#686]
Players are still able to write, for example, in faction chat. Setting event priority to LOWEST would fix this issue.
[Reference](https://github.com/BanManagement/BanManager/blob/master/src/main/java/me/confuser/banmanager/listeners/ChatListener.java#L21)

**Comment by confuser** [comment]
Lowering it could cause unknown conflicts with other chat plugins. Perhaps it needs to be configurable instead.

**Comment by Kakifrucht** [comment]
Should /bmreload also reload the priority? I'm unsure of it working properly yet. You should probably also not put monitor there, since events shouldn't be cancelled at that level.

**Comment by confuser** [comment]
/bmreload does not reload the priority. It will add additional complexity. As for 'monitor', it's up to the user. Reloading via a plugin manager such as PlugMan should suffice.

**Comment by Kakifrucht** [comment]
Works perfectly then!
