### ISSUE TITLE
Enhancement: Allow action by player name, not UUID

### ISSUE THREAD

**Issue by EvilOlaf** [BanManagement/BanManager#687]
Hey there,

usually all punishments are assigned to player UUID which makes perfect sense. However there is a situation where it could be useful to do actions especially on a players' name rather than its UUID.

As an example I have a player that has an offensive nickname. I want to force him to either play on another server or change his name. As I am lazy and hate responding to unban applications I would like to see an option to allow to ban a specific nick name so that the player can rejoin after changing his nick without having to ask for an unban.

Thanks for reading.

**Comment by confuser** [comment]
Config based, or does it need to be synced between servers?

**Comment by rautamiekka** [comment]
^ If it was me, syncing across Servers would always be best. It shouldn't complicate the plugin too much, and the Db Server is up to the Owner.

**Comment by EvilOlaf** [comment]
Awesome
