### ISSUE TITLE
Staff logins ?

### ISSUE THREAD

**Issue by denireilly** [BanManagement/BanManager#698]
Hello,

Is there anyway we could add or unless there is already a way , to add like staff logins, instead of just the one admin login

**Comment by confuser** [comment]
Being covered in https://github.com/BanManagement/BanManager-WebUI/issues/27#issuecomment-234732693 but it's not yet ready

**Comment by denireilly** [comment]
Hello,

Would there be a way to Have or implement the new web GUI into older versions ?

**Comment by confuser** [comment]
The new WebUI will be fully compatible with BanManager v5+

**Comment by denireilly** [comment]
What version if ban manager is in 1.6.4 ? as thats the version i am currently stuck in

**Comment by confuser** [comment]
That'll be v4, which is no longer supported, and the new UI certainly won't be supporting it I'm afraid.

**Comment by denireilly** [comment]
ah :/ is there anyway for it to be edited to work on that versions ?

**Comment by confuser** [comment]
Not easily, no. v4 is name based, v5+ is entirely UUID based.

**Comment by CasperYT** [comment]
confuser fix the shit with essentials
