### ISSUE TITLE
Doesn't work with essentials

### ISSUE THREAD

**Issue by CasperYT** [BanManagement/BanManager#700]
# Alright this doesn't work with essentials. that really annoys me so please fix this

> U might Want to Fix That
_**Regard's Casper**_

**Comment by CasperYT** [comment]
What?

**Comment by CasperYT** [comment]
invalid? Seriously. Many People can't use this with essentials. not even me

**Comment by confuser** [comment]
You haven't given any details. I'd recommend opening a new issue and giving more information.

**Comment by CasperYT** [comment]
kk ill link a forum post :-1:
