### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by CasperYT** [BanManagement/BanManager#701]
https://www.reddit.com/r/admincraft/comments/241pd0/banmanagement_and_essentials_not_compatible/
https://www.tapatalk.com/topic/108393-68411
And mroe shit

**Comment by Kakifrucht** [comment]
Yeah, not helping at all.
The reddit post is over 2 years old. You have misconfigured your server if you have issues.
This is not the way to get help.
Please say what YOUR problem is and we can try to help you. 
Both plugins are perfectly compatible.
