### ISSUE TITLE
"Duplicate" messages being sent to the 'suspect'

### ISSUE THREAD

**Issue by groovybluedog** [BanManagement/BanManager#703]
Let's say I warn someone. They get sent this message:

You have been warned by X for X
X has been warned by X for X

Same goes for anything else...

X has been temporarily muted for 10 seconds by X for X
You have been temporarily muted for X by X which expired in X seconds

This message that explains the same thing simply is not necessary and has the possibility of confusing users.

I would love to see it so the public version that the server sees goes to everyone except for the suspect, which would only see their "You have been" message.

**Comment by groovybluedog** [comment]
And on another note this needs UUID support!

**Comment by groovybluedog** [comment]
On top of this, how come there is a report functionality but no functionality to actually view the report other than the date, time and reported person? Like if I report someone with a reason, I can't see any functionality to open report 1 and see the reason... I can only assign, delete or teleport to it...

**Comment by EvilOlaf** [comment]
1st. Fix your permissions. The upper message is intended to be shown to the warned player. The other one is for other team mates.
2nd. BM has UUID support since version 5.x
3rd. The report feature is still WIP.

**Comment by confuser** [comment]
As said above, the notification is an issue with permissions. I'd like to understand the use case of giving all players notification message permissions.

v5 supports UUID, and has done for almost 2 years.

Use `/report info <id>` to see the reason and other information about the report.

**Comment by groovybluedog** [comment]
1) Most plugins can work right off the bat without any permissions setup. It's odd that this isn't the case here, but I'll take a look at it at some point.
2) I cannot search for UUID's on the Ban Management web interface :(
3) Thanks - that should be made clearer in the documentation. Also for the reference of others, it is /reports not /report for the report management command

Thanks for the replies
