### ISSUE TITLE
Connection Not being closed

### ISSUE THREAD

**Issue by Qballl** [BanManagement/BanManager#706]
# Issue report

**Tell us about your environment**

* **Server Software: Spigot 
* **Server Version: 1.10.2
* **BanManager Version: 5.12

* **Online/Offline mode**: offline
* **Bungeecoord online/offline mode (if applicable)**: 

**BanManager config.yml**:

Here is a hastebin of my config http://paste.md-5.net/navorenawo.sm

There is a message about a leak. Here is the error http://paste.md-5.net/kecomoratu.avrasm

**Comment by confuser** [comment]
Your database connection is running quite slow. If this is expected, feel free to disable `leakDetection` in your config by setting it to 0

**Comment by Qballl** [comment]
It is not I've never seen that error before

**Comment by EvilOlaf** [comment]
Maybe your database host had a bad day?

**Comment by Qballl** [comment]
Maybe
