### ISSUE TITLE
BungeeMSG support

### ISSUE THREAD

**Issue by t0mmyxbl** [BanManagement/BanManager#708]
Wondering if you can add support for bungeeMSG. Trying to add a mute/softmute command blacklist for messaging users although due to bungeeMSG it still allows the users to use all the messaging commands.

**Comment by confuser** [comment]
I'm not familiar with `BungeeMSG`. Is it a Bukkit or Bungeecord plugin?

**Comment by t0mmyxbl** [comment]
It's a bungeecord plugin allowing users to send messages across multiple servers

**Comment by confuser** [comment]
I'm not sure if it's possible to cancel chat events on Bukkit, being sent via Bungeecord. An issue was raised in #680, @ryans1230 found a work around. If there's a need, I can investigate creating a separate Bungee plugin to handle mutes/offer an API.

**Comment by ryans1230** [comment]
My solution is quite inelegant. When a player logs in I called the API. If it returns a mute, I publish it to redis, which is that interpreted by my Bungee plugin (basically stored as a UUID and long if applicable). Then after that I just listen to the BM events and pass the information over redis.

**Comment by t0mmyxbl** [comment]
The developer of BungeeMSG has another plugin called spigotbridge which essentially links spigot plugins to work with bungeemsg. I asked on his spigot page if he could provide ban manager support and he replied saying he'll work on it. Hopefully this will be a solution.

**Comment by confuser** [comment]
Thanks for the update @t0mmyxbl, can you let us know once they've added support? I'd be interested to see how they've achieved it.

**Comment by FadiDev** [comment]
Hello, I am thr developer of BungeeMSG. I just happend to find this issue on here. I was busy last week due to school, I will be working on that feature this week.

**Comment by FadiDev** [comment]
*Typos;)

**Comment by Ghostlyr** [comment]
@confuser, would really like to see the implementation through separate bungee-proxy plugin. Other ways looks like quirk, because to implement support with all kinds of bridges for a bunch of other bungee-chat plugins - extremely problematic.
