### ISSUE TITLE
Permission bm.command.delete does not allow /bmdelete notes note#

### ISSUE THREAD

**Issue by runelynx** [BanManagement/BanManager#709]
# Issue report

**Tell us about your environment**
**Spigot 1.11.2-R0.1-SNAPSHOT**

* **Server Software:**
* **Server Version:**
* **BanManager Version:**
**Ban Manager 5.13.0-SNAPSHOT**

* **Online/Offline mode**: 
* **Bungeecoord online/offline mode (if applicable)**: 
**online**

**BanManager config.yml**:

```yaml



```

**Describe your issue:** 

Everything works great!  Except. I have given my staff bm.command.delete as per your commands/permissions page.  They find note # 184 using /bminfo -n <player>. They type /bmdelete notes 184. They are told no permission.  Please check that your commands page is correct?

**Comment by confuser** [comment]
Like /bmclear, it's separated into different permissions. It looks like quite a lot of the pages/links on BukkitDev are broken from Curse's platform update. I'll leave this open until they're in a better state.

```
bm.command.delete
bm.command.delete.banrecords
bm.command.delete.kicks
bm.command.delete.muterecords
bm.command.delete.notes
bm.command.delete.reports
bm.command.delete.warnings
```
