### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by Puckon** [BanManagement/BanManager#711]
# Issue report

**Tell us about your environment**

* **Server Software:**
* **Server Version:** This server is running CraftBukkit version git-Spigot-7d78b81-d5e7885 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

* **BanManager Version:** 5.13.0

* **Online/Offline mode**: offline
* **Bungeecoord online/offline mode (if applicable)**: online

**BanManager config.yml**:

```yaml

Ensure you mask/remove any MySQL credentials!

```

**Describe your issue:** 

Server outputs following error on startup of server every time. See link
**How to replicate:** 

 
**Further information:**

 https://hastebin.com/ikoviropoh.css

**Comment by confuser** [comment]
Fixed in v5.13.1, waiting approval on BukkitDev, or download from the CI server at http://ci.frostcast.net/job/BanManager/143/
