### ISSUE TITLE
Expirecheck Unmuting

### ISSUE THREAD

**Issue by t0mmyxbl** [BanManagement/BanManager#714]
BM Version: 5.13.1 (did have version 5.12.0 and was doing the same)
Spigot 1.9.4
Online Mode: true
Bungeecord

When tempmuting a player, for some reason after the expirecheck (in the schedules.yml) is ran it is unmuting them if the player is online at the time. This is no good if a player has been muted any time longer than the expirecheck has left (which is every 5 minutes).

**Comment by confuser** [comment]
Are there any warnings from BM on startup about there being a time difference between your MC server and MySQL database?

**Comment by t0mmyxbl** [comment]
no warnings at all

**Comment by t0mmyxbl** [comment]
After further testing for some reason tempmuting any time less than 15minutes gives this effect. Muting for 30m seems to work ok

**Comment by confuser** [comment]
Based on previous comments, you are using the local database option across multiple servers correct? It could be caused by time differences. E.g. one server is 15 minutes ahead of others, therefore the expiry check runs too soon. I'd recommend checking the differences between the servers, and MySQL. Timezone differences won't matter, but minute differences will.

**Comment by t0mmyxbl** [comment]
could I potentially stop all the servers, set the schedules.yml lastchecked all to 0, then start them all back up again so they are definitely in sync?

**Comment by confuser** [comment]
Yes (but back up first), however if the servers' clocks have drifted, the issue will occur again.

**Comment by t0mmyxbl** [comment]
the servers clock is fine, just checked

**Comment by confuser** [comment]
Are you running everything on the same server?

**Comment by t0mmyxbl** [comment]
essentially yes, 2 different boxes with allocations and with bungeecord, but both have the same time

**Comment by t0mmyxbl** [comment]
It looks as if everything is ok now. Thanks for the support!
