### ISSUE TITLE
Ban Manager Web Interface Semi-Blank after setup

### ISSUE THREAD

**Issue by dafuq360** [BanManagement/BanManager#715]
After setting up the Ban Management Web Interface on my mac, I launched localhost/banmanager, as in banmanager is the folder with banmanager's web interface. However, I am very confused. Can tell me why this happens and how to fix it:
http://prntscr.com/dzyktb

Thank you!

**Comment by dafuq360** [comment]
sorry that i put this in the wrong area - meant to post this issue in the web ui version

**Comment by confuser** [comment]
As GitHub doesn't allow moving issues between projects, it's fine for now.

Based on the screenshot, it looks like the CSS failed to load. Can you open the dev console in your browser, and head to the Network tab? In Chrome, Right Click -> Inspect Element -> Network tab.

**Comment by dafuq360** [comment]
And take a screenshot of that too?

**Comment by confuser** [comment]
Yes please

**Comment by dafuq360** [comment]
I opened the network tab - seems to look empty:
http://prntscr.com/e08ygd

**Comment by dafuq360** [comment]
oh sorry i think i had to reload the page:
http://prntscr.com/e090dn

**Comment by dafuq360** [comment]
I also have an issue with the plugin itself. I don't seem to be getting any errors in my console, but when I type /ban, the player name, and the reason, nothing happens. Also when I type /addnote, and the player name, and the note, it gives me an error

**Comment by confuser** [comment]
Your webserver is responding with 403 Forbidden for the static resources (CSS, JS).

As for your other issue, with the plugin itself. Check your server logs. It sounds like the plugin disabled itself at startup.

**Comment by dafuq360** [comment]
I don't think it disabled itself because I am able to run commands like - when I run just /ban it says the correct sytax. But otherwise it doesn't work. I will send you the error for /add note

**Comment by dafuq360** [comment]
http://pastebin.com/VtpfXsuH
^^#1
http://pastebin.com/0NJFcZsk
^^#2

**Comment by confuser** [comment]
I would recommend updating to the latest version, v5.13.1
