### ISSUE TITLE
Remove Metrics

### ISSUE THREAD

**Issue by confuser** [BanManagement/BanManager#716]
Looks like the maven repo is down causing fresh compilations to fail.

 http://mcstats.org/ is also down

**Comment by confuser** [comment]
Website is back online (albeit slow), but the repo is still down, causing compilations to fail.

- [ ] Setup a mirror on CI

**Comment by 7rory768** [comment]
I recommend http://bstats.org/ that's what I've moved to: https://bstats.org/plugin/bukkit/SimpleFreeze
