### ISSUE TITLE
/kick  does not work correctly

### ISSUE THREAD

**Issue by EpiGame** [BanManagement/BanManager#719]
When my helpers use /kick (i have the bm.exempt.kick permission), I'm kicked from the server...

And when I write /kick + enter, it kick someone at random... 
Is this normal?

Thank you very much

**Comment by EpiGame** [comment]
And when I type /bmreport <player>, all of commands that my helpers did, is replaced by 'console have muted x player' 

Is this normal ?

**Comment by EvilOlaf** [comment]
Hard to track down without further information. Please fill out the issue template properly.

**Comment by EpiGame** [comment]
In fact, I have all the permissions of my server ('*'), so I have bm.exempt.kick too.
And when a moderator type /kick EpiGame (my username), I am kicked of my server... And the moderator haven't the overide permission !

And when I type /kick whithout any argument, this kick players in alphabetical order...


Can you help me solve this problem please ?

Thank you very much !

**Comment by confuser** [comment]
Are your moderators /op'd?

**Comment by EpiGame** [comment]
No, I am the only one :/

**Comment by confuser** [comment]
Do your moderators have the `bm.exempt.override.kick` permission? Please repeat the process via `/bmkick`. It may be another plugin overriding `/kick`

**Comment by EpiGame** [comment]
Oh sorry, I'm so stupid, they had the 'bm.exempt.*' because i was thinking that with this perm, they will not have other permissions that the exempt permission :/
I'm really sorry

**Comment by EpiGame** [comment]
But there still an other problem...
When I type /kick without any argument, this kick players in alphabetical order...

**Comment by confuser** [comment]
That shouldn't be happening. I'll investigate. Could be a bug with the command parser.

**Comment by EpiGame** [comment]
The problem is when I type '/kick' without any argument, it kick a random player... But I have never had this problem with any other command. When I type '/ban' without any argument, it works perfectly, and send me '/ban <player> <reason>'

**Comment by confuser** [comment]
@EpiGame Does `/bmkick` behave in the same way?

**Comment by EpiGame** [comment]
yes
