### ISSUE TITLE
I cant connect the plugin with the DB

### ISSUE THREAD

**Issue by AltijdSander** [BanManagement/BanManager#723]
Hey there!

I can't connect the plugin with the DB, its wil say "Could not create connection to database server. Attempted reconnect 10 times. Giving up."

I get stuck with setting the config. I have tried everything. Can someone help me with the config?

**Comment by Fuechschen** [comment]
It's a bit hard to help you without knowing what you tried and how you config looks. You maybe want to paste your config here, but do not forget to remove passwords
