### ISSUE TITLE
[enhancement] Allowing for the [id] message varaible for notes and reports

### ISSUE THREAD

**Issue by FrozenBeard** [BanManagement/BanManager#733]
Cant delete a note without knowing its ID, i want to display the note ID with each time its posted in-game.

People need to have their "report" ticket Id to reference in forum posts etc, cant do that as [id] tag dousn't work in the messages.yml for reports. It needs to show them their ticket ID as soon as they post one.

**Comment by confuser** [comment]
Sure, `/notes` is missing an id variable. Where for a report is this missing? `/reports` does support an `[id]` variable.

**Comment by FrozenBeard** [comment]
When the user creates the report; it needs to tell them the ID of it in the creation message, so then they can reference it.
Are players able to list the reports they have created?
