### ISSUE TITLE
Add support for MySQL 5.7 w/ SSL 

### ISSUE THREAD

**Issue by runelynx** [BanManagement/BanManager#738]
# Issue report

* **Server Software:**
Spigot
* **Server Version:**
1.12
* **BanManager Version:**
5.15.0-SNAPSHOT

* **Online/Offline mode**: 
* **Bungeecoord online/offline mode (if applicable)**: 
Bungee Online, servers offline

**BanManager config.yml**:

```yaml

Config here
https://pastebin.com/VBtpeqHF
```

**Describe your issue:** 

See error here on plugin load
https://pastebin.com/GnrqBZVC

The problem is that new versions of MySQL require SSL to be used, and if not it spams the console on every single DB connection. So my DB requires SSl... but most plugins I can get around this by appending parameters to the DB name so they get inserted into the connection string. That doesn't seem to work for Ban Manager.

Please take a look?

**Comment by confuser** [comment]
Does the useSSL property set to true suffice? Or do you require any other options?

**Comment by runelynx** [comment]
This is what I use as the DB name in other plugins - both of these parameters would be nice :) 

database: rpgame?**verifyServerCertificate**=false&**useSSL**=true
