### ISSUE TITLE
Cannot find com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()

### ISSUE THREAD

**Issue by jessefjxm** [BanManagement/BanManager#740]
# Issue report

**Tell us about your environment**

* **Server Software:**
OS: Ubuntu 16.04.2 LTS
Java: java version "1.8.0_121"
* **Server Version:**
Server: spigot-1.12-R0.1-SNAPSHOT-b1344.jar
* **BanManager Version:**
Plugin: BanManager v5.14.0

* **Online/Offline mode**: Offline
* **Bungeecoord online/offline mode (if applicable)**:  Offline

**BanManager config.yml**:  

```yaml 

https://pastebin.com/a0QCgWgh

```

**Describe your issue:** 

A java.lang.NoSuchMethodError will be throw out every startup, and stop BanManager from working.
Method signature: com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()
Console log: https://pastebin.com/dJjDe6Kz

**How to replicate:** 

Happens every time I runs my 1.12 server. on 2 different machines. Haven't seen such error on any other plugins. But I'm not sure if it happens on others' servers :(
 
**Further information:**

**Comment by confuser** [comment]
You'll need to use a developer build for 1.12 compatibility. https://ci.frostcast.net/job/BanManager build 8+
