### ISSUE TITLE
BanManager refuses to work on 1.12

### ISSUE THREAD

**Issue by Skizzy77** [BanManagement/BanManager#743]
# Issue report
Hello there! We host off of a dedicated OVH server, running phpMyAdmin, along with a variety of other services. We were previously running Spigot 1.11.2 on our server and BanManager was working great. We updated to 1.12, and BanManager refused to load into the server. Our error is below.

* **Server Software:** Spigot
* **Server Version:** MC-1.12
* **BanManager Version:** 5.14.0

* **Online/Offline mode**: 
* **Bungeecoord online/offline mode (if applicable)**: 
BungeeCord is in Online mode.

**BanManager config.yml**:
# 
# Aliases will be found and blocked automatically, e.g. msg will block tell
debug: false
databases:
  local:
    enabled: true
    host: 127.0.0.1
    port: 3306
    name: punishments
    user: 
    password: 
    maxConnections: 10
    leakDetection: 3000
    tables:
      players: bm_players
      playerBans: bm_player_bans
      playerBanRecords: bm_player_ban_records
      playerMutes: bm_player_mutes
      playerMuteRecords: bm_player_mute_records
      playerKicks: bm_player_kicks
      playerNotes: bm_player_notes
      playerHistory: bm_player_history
      playerReports: bm_player_reports
      playerReportLocations: bm_player_report_locations
      playerReportStates: bm_player_report_states
      playerReportCommands: bm_player_report_commands
      playerReportComments: bm_player_report_comments
      playerWarnings: bm_player_warnings
      ipBans: bm_ip_bans
      ipBanRecords: bm_ip_ban_records
      ipMutes: bm_ip_mutes
      ipMuteRecords: bm_ip_mute_records
      ipRangeBans: bm_ip_range_bans
      ipRangeBanRecords: bm_ip_range_ban_records
      rollbacks: bm_rollbacks
      nameBans: bm_name_bans
      nameBanRecords: bm_name_ban_records
  global:
    enabled: false
    host: 107.180.50.238
    port: 3306
    name: punish-database
    user: 
    password: 
    maxConnections: 10
    leakDetection: 3000
    tables:
      playerBans: bm_player_ban_all
      playerUnbans: bm_player_unban_all
      playerMutes: bm_player_mute_all
      playerUnmutes: bm_player_unmute_all
      playerNotes: bm_player_note_all
      ipBans: bm_ip_ban_all
      ipUnbans: bm_ip_unban_all
mutedCommandBlacklist:
- msg
softMutedCommandBlacklist:
- msg
duplicateIpCheck: true
bypassDuplicateChecks:
- 0.0.0.0
- 127.0.0.1
logKicks: false
logIps: true
displayNotifications: true
broadcastOnSync: false
timeLimits: {}
reportCooldown: 10
warningCooldown: 10
warningActions:
  enabled: false
warningMute: false
hooks:
  enabled: false
checkForUpdates: true
offlineAutoComplete: true
punishAlts: false
denyAlts: false
cleanUp:
  kicks: 30
  banRecords: 0
  ipBanRecords: 0
  ipMuteRecords: 0
  muteRecords: 0
  readWarnings: 0
  unreadWarnings: 0
maxOnlinePerIp: 0
checkOnJoin: false
createNoteReasons: false
onlineMode: true
chatPriority: normal
```yaml

Ensure you mask/remove any MySQL credentials!

```

**Describe your issue:**
I expect the plugin to function properly, but it does not like the 1.12 version we are now running.

13.07 01:33:04 [Server] ERROR Error occurred while enabling BanManager v5.14.0 (Is it up to date?)
13.07 01:33:04 [Server] INFO java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()Lcom/google/common/util/concurrent/ListeningExecutorService;
13.07 01:33:04 [Server] INFO at me.confuser.banmanager.internal.guava.cache.LocalCache.<clinit>(LocalCache.java:77) ~[?:?]
13.07 01:33:04 [Server] INFO at me.confuser.banmanager.internal.guava.cache.LocalCache$LocalManualCache.<init>(LocalCache.java:4702) ~[?:?]
13.07 01:33:04 [Server] INFO at me.confuser.banmanager.internal.guava.cache.CacheBuilder.build(CacheBuilder.java:811) ~[?:?]
13.07 01:33:04 [Server] INFO at me.confuser.banmanager.storage.PlayerWarnStorage.<init>(PlayerWarnStorage.java:34) ~[?:?]
13.07 01:33:04 [Server] INFO at me.confuser.banmanager.BanManager.setupStorages(BanManager.java:343) ~[?:?]
13.07 01:33:04 [Server] INFO at me.confuser.banmanager.BanManager.onEnable(BanManager.java:135) ~[?:?]
13.07 01:33:04 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.jar:git-Spigot-7228328-50b75cd]
13.07 01:33:04 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
13.07 01:33:04 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
13.07 01:33:04 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
13.07 01:33:04 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
13.07 01:33:04 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:748) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
```log here```

**How to replicate:** 

Not applicable
 
**Further information:**

Not applicable

**Comment by EvilOlaf** [comment]
Grab latest dev build and try again.

**Comment by Castiella** [comment]
Where can we find the newest dev build? I'm using 

BanManager v5.14.0
 and i'm having the same error.

**Comment by EvilOlaf** [comment]
There you go: https://ci.frostcast.net/job/BanManager/

**Comment by Castiella** [comment]
Thank you!

**Comment by DrFallen** [comment]
Hi I'm getting the same issue I'm using 5.15 when I try /ban -s confuser test in your example it just keeps coming up with ban <player> <reason>
