### ISSUE TITLE
(question/request) SQL-lite

### ISSUE THREAD

**Issue by FatalBlade** [BanManagement/BanManager#744]
Hi, I do apologize for asking this here but didn't see anywhere else to do so. Is it possible to run this with an SQL-lite type set up so that the Database is on my own system rather than having it hosted somewhere else? I would love to use this plugin on my server but I don't want to pay somewhere just to host the DB.

**Comment by rautamiekka** [comment]
You could host MySQL yourself ...

**Comment by confuser** [comment]
I'm afraid the plugin only supports MySQL. A lot of the features including the syncing and the web UI are dependent on the database being available from other servers; which is not possible with SQLite, at least, not without setting up NFS, but that also carries concurrency risks.

**Comment by FatalBlade** [comment]
Ahh okay, thank you. :/
