### ISSUE TITLE
Banning issues.

### ISSUE THREAD

**Issue by Castiella** [BanManagement/BanManager#746]
Using the most recent dev build.

Two issues.

Can't see if a player is banned with /seen - is this something that can be rectified?

also, I can't auto-tab fill in names for bans ect.

**Comment by EvilOlaf** [comment]
`/seen` is a command that is provided by Essentials(X). Therefore Essentials cannot know if a player is banned.
Does tabcomplete work for other commands that need player names as argument?

**Comment by Castiella** [comment]
Ah i see, and no, the only time tab complete works is if you have done the command on the player before, weirdly

**Comment by confuser** [comment]
BM has it's own store of players. Offline completion will only be available if a player has joined the server at least once since BM has been installed.

**Comment by Castiella** [comment]
No, you don't understand what I was saying.

Its not offline players, its ONLINE players

If i was to ban or kick someone with essentials - you can autofill their name if theyre online.

You can't do that with ban manager. Is it something you can implement?

**Comment by Castiella** [comment]
Also, it doesn't autofill when a player joins at all - if thats what its supposed to do.

Ive had several players join since it was added and their names don't autofill.

**Comment by confuser** [comment]
You can. Check what plugins you have installed, it sounds like something is conflicting.
