### ISSUE TITLE
Exception launched when tab complete for offline users

### ISSUE THREAD

**Issue by afroman84** [BanManagement/BanManager#748]
Hello, 
i'm using latest dev build 15 from BanManager. The offlineAutoComplete: true option is set, and when i 
press tab key this exception is launched: https://hastebin.com/nidijudoxi.vbs
the tab complete works for every command supporting name completion, not for BM commands. 
If i set offlineAutoComplete: false, for the bm commands the tab works only with online players.
It worked past ago, now there's something that's changed that makes it not work.
Thank you

**Comment by confuser** [comment]
When modifying the offlineAutoComplete, please ensure you restart the server.

**Comment by afroman84** [comment]
thank you i will provide
