### ISSUE TITLE
Wont enable?

### ISSUE THREAD

**Issue by Alethars** [BanManagement/BanManager#749]
# Issue report

**Tell us about your environment**

* **Server Software:**   x2 Xeon E5-2670v2, DDR4 ECC RAM, And 1Gbps Connection
* **Server Version:** Craftbukkit version git-Spigot-596221b-2c5c611 (Latest release possible)
* **BanManager Version:** 5.15.0-SNAPSHOT

* **Online/Offline mode**:  online
* **Bungeecoord online/offline mode (if applicable)**: 

**BanManager config.yml**:

```yaml

Ensure you mask/remove any MySQL credentials!

```
https://pastebin.com/tXgrg5t0

**Describe your issue:** Wont enable, what  have I done wrong?
 

**Console Log:** https://pastebin.com/9QMTWe5b

**Comment by EvilOlaf** [comment]
mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 10 times. Giving up.

Either your database is not reachable or your mysql credentials are wrong.
