### ISSUE TITLE
How to get onBan event ?

### ISSUE THREAD

**Issue by fede1132** [BanManagement/BanManager#750]
Hi, i want get onBan event(When staffer ban other player event), how to do that ?

**Comment by EvilOlaf** [comment]
Not sure if this helps: https://github.com/BanManagement/BanManager/blob/master/src/main/java/me/confuser/banmanager/events/PlayerBanEvent.java

**Comment by fede1132** [comment]
> Very thanks, now work. You are the best !

**Comment by fede1132** [comment]
Last question: When i use event.getBan().getExpires() give me the expire date in ticks/second how to get example: 14d or 2 weeks ?

**Comment by EvilOlaf** [comment]
You should get the unix timestamp when the ban expires. 
https://github.com/BanManagement/BanManager/blob/master/src/main/java/me/confuser/banmanager/BmAPI.java
From that point forward you have to calculate the date on your own. Should be an easy one.
```
Date date = new Date ();
date.setTime((long)unix_time*1000);
```

**Comment by fede1132** [comment]
What is the variable unix_time ?

**Comment by confuser** [comment]
```
Date date = new Date();
date.setTime(event.getBan().getExpires() * 1000L);
```
