### ISSUE TITLE
Request: exempt from showing alts

### ISSUE THREAD

**Issue by FrozenBeard** [BanManagement/BanManager#752]
Requesting permission as well as an IP for admins. IP's change, What if an admin wants to use an alt to go undercover on their server? Need to keep top secrecy! can you please add a exempt permission for OPs/Admins so it dousnt show their alts on the same IP.

I know theres an IP section, but that isn't helpful to have to check your IP, EVERY time you connect and update the config.

Thanks.

**Comment by confuser** [comment]
It's not possible to check the permission of offline players via Bukkit unfortunately. However, what I can add in is the following:

1. On player join, players with `bm.exempt.alts` do not cause deny alts, punish alts or broadcast alts
2. Add an `alts` section to the exemptions config to prevent the player name showing when running the `/findalts` command or `/bminfo`

**Comment by FrozenBeard** [comment]
That sounds good.
