### ISSUE TITLE
ISE and NPE after closed result set

### ISSUE THREAD

**Issue by sigmaroot** [BanManagement/BanManager#753]
# Issue report

**Tell us about your environment**

* **Server Software: Paper Spigot**
* **Server Version: 1.12.1 build 1201**
* **BanManager Version: 1.1 b16 from Jenkins**

* **Online/Offline mode: online**
* **Bungeecoord online/offline mode (if applicable): No BungeCoord** 

**BanManager config.yml**:
https://pastebin.com/4m8grq78

**Describe your issue:**
First:
https://pastebin.com/98vRm1dT
Next:
https://pastebin.com/30PTFr6i

**How to replicate:** 
I dunno...
 
**Further information:**
It appears after a server is started (few seconds later)...

**Comment by confuser** [comment]
I notice you're using paper spigot? I'm afraid I'm out of the loop these days as to what forks are available. Does it occur with normal spigot?

**Comment by sigmaroot** [comment]
I'm not able to test it with spigot, because this doen't happen all the time and I have to use it with paper due to all other players, sorry.

It happend yesterday, but no error today (nightly restarts).

I guess it is the best to have an eye on this issue and if it does occur some more times I will report it here 😄

**Comment by confuser** [comment]
No worries. As I don't run a network any more, it's quite difficult for me to reproduce these types of issues. Please let me know if you see it again and if you notice any kind of pattern.

**Comment by sigmaroot** [comment]
Ok, one time more: https://pastebin.com/p34dqPNK

This time it wasn't after a (re)start of the server. I guess this is a very rar error.

Seems that another query cannot be send after the result set is closed (by sql server or plugin).

As long as there are no more informations about the occurence it's hard to tell what's causing it... This can also be an issue within ormlite... I dunno...

I think it's a minor bug...
