### ISSUE TITLE
Sponge support

### ISSUE THREAD

**Issue by darkarrow** [BanManagement/BanManager#754]
Hello! I use this plugin quite often when setting up server networks. Recently I started setting up a network and some of the servers are going to be spongeforge servers. So now I am wondering if there are any plans to have this on sponge as well? Or perhaps there already is a sponge version and I just couldn't find it?

**Comment by confuser** [comment]
I've been asked this through a variety of channels, but never here! Whilst I would love to develop a sponge version, unfortunately I don't have much time these days to take on such a task. Would certainly need to be a community effort. I'm happy to step in and help where needed.

**Comment by vertex101** [comment]
well i will take a look through some things and see what i can come up with

**Comment by clienthax** [comment]
Any updates on this?, Was looking at porting this myself.

**Comment by confuser** [comment]
Nothing yet, I was considering starting to abstract some of the logic out into non-Bukkit specific classes but not had time yet. Open to a collaborative effort on this though.

**Comment by clienthax** [comment]
I havn't touched bukkit in a long while plugin wise, but I need to port this over to use my existing ban db's anyway, so I will make a decent attempt at it :)

Any good ways to multistack this for sponge/bukkit as far as compiling goes?

I see you are using maven, which i have hardly and experience in, I generally use gradle.

**Comment by clienthax** [comment]
Seems luckperms is multistacked, could be used as a base buildsystem wise, https://github.com/lucko/LuckPerms

**Comment by confuser** [comment]
@clienthax I don't work with Java on a daily basis so a little out of touch with best practises. Open to migrating to gradle, LuckPerms looks like a good way to refactor the project out.

**Comment by clienthax** [comment]
@confuser Making some decent progress on this, https://github.com/clienthax/BanManager

**Comment by confuser** [comment]
@clienthax awesome 🙌

**Comment by clienthax** [comment]
@confuser what are the jsonmessage things? I'm guessing it's for pagnation?

**Comment by clienthax** [comment]
@confuser Can you add me on discord, clienthax#1337

**Comment by confuser** [comment]
@clienthax mostly for better ux e.g. clicking links etc. I'm not on there very often but it's jamesm#6409

**Comment by confuser** [comment]
Just an update on this. I'm currently using #788 as a baseline to implement this. It's in progress but no ETA as of yet.

**Comment by confuser** [comment]
Sponge build available over in #795, not available on CI yet

**Comment by confuser** [comment]
Alpha builds available at https://ci.frostcast.net/job/BanManager/

**Comment by mike88898** [comment]
> Alpha builds available at https://ci.frostcast.net/job/BanManager/

What version of sponge does this support? Currently running 7.1.0, tried it out with no luck.

**Comment by confuser** [comment]
@mike88898 working with the latest stable build `spongevanilla-1.12.2-7.1.6.jar` however there is an issue #807 which I'm working on fixing, is it the same one you're having?
