### ISSUE TITLE
1.12 support?

### ISSUE THREAD

**Issue by redstonedesigner** [BanManagement/BanManager#755]
When will 1.12 support be activated?

I would like to use this but it seems that it is not supported by 1.12.
This is a problem.

Please fix ASAP.

**Comment by confuser** [comment]
1) This is a free open source project, making demands will not bode well.
2) 1.12 has been supported for quite some time via a developer build https://ci.frostcast.net/job/BanManager/ which is linked to on the main plugin page on BukkitDev and Spigot. 
3) You would have found this had you spent a small amount of time looking at other open issues e.g. #743
