### ISSUE TITLE
Tempwarnings expiring and being deleted, unlike tempmute/tempban?

### ISSUE THREAD

**Issue by MrEminent42** [BanManagement/BanManager#758]
Hello! I have an addition that I think would be very useful to BanManager.

Tempwarns currently are deleted after they expire, unlike tempmutes and tempbans. Adding 'records' like are currently implemented with tempmutes and tempbans could be very beneficial to server owners as they could still keep a record of previous warns that a player had.

Currently, if staff uses /warn to warn a player, then that warning accumulates and never 'expires'. If we use /tempwarn, when the warning expires, there is absolutely no record of that warning ever occurring. 

Having temporary warnings 'expire' but still kept in the database and able to be seen (with an 'expired' tag) would let staff be able to see the previous history of a player, without the player having to worry about a few warnings that they got months ago pushing them closer and closer to the 'limit' (when other punishment commands are executed). 

Furthermore, warns could be added permanently to the player's warning 'count' but the warning 'points' would expire after a certain time. This meaning that when a staff member (or the player themselves) performs /bminfo, they will see a total warn count with the [warns] variable, and [points] will only be the number of points of warnings that haven't expired yet.

Also, I do have a separate question about the 'points' system for warnings. If I set a 'warning action' in the config for '10', does that mean 10 total warns, or 10 total points? Say, a player is warned two times each with five points. Would that trigger the '10' warning actions?

Thanks!

**Comment by confuser** [comment]
I'm on the fence with this. Warnings themselves are supposed to be the record. If they're not meant to be used against the player, then surely they should be deleted? In this scenario, if staff are using their warning history regardless of whether it has expired or not as a basis to punish a player, the player should in fact worry about a few warnings they had a few months ago.

>Also, I do have a separate question about the 'points' system for warnings. If I set a 'warning action' in the config for '10', does that mean 10 total warns, or 10 total points? Say, a player is warned two times each with five points. Would that trigger the '10' warning actions?
Yes, warning actions are triggered on points. By default, a warning is worth 1 point. Therefore, 10 warnings would equal '10' warning action triggers. However, 2 warnings at 5 points each will also trigger the 10 warning action triggers.

**Comment by MrEminent42** [comment]
Thanks for your reply!

You make a good point. Yeah if the staff is using the previous warnings as a basis to issue punishments, then the record should be kept and referenced to when issuing new punishments.

In my mind, though, if a player goes a few months or half a year or more without any warnings or punishments, that player has earned a fresh start. However, I would still like to keep the records of those warnings since I might look at them when a user is applying for staff, etc.

As I read this I know I'm contradicting myself a bit. My main point is that it would be nice to have an archive of users' previous (temp)warns, without them having to worry about a warning they got months and months or years ago. 

Also, one more question, is there a way to define the amount warning points a certain predefined reason has? For example, #hacking could have five warning points while #cursing could have two.

Cheers!
