### ISSUE TITLE
Enhance /alts

### ISSUE THREAD

**Issue by EvilOlaf** [BanManagement/BanManager#759]
My idea is to JSONify the output of `/alts` in two ways.
As for now it just outputs a list of all known alts seperated by comma.

Firstly depending on the current ban status of each alt the displayed color could be altered. For example 
- non-banned accounts in green
- accounts with expired or lifted bans in yellow
- temporarly banned players in gold and
- currently permanent banned accounts in red

As second idea I would like to see the ability to simply click on one of these names to execute the `bminfo` command for that specific player.

As always thanks for reading.

**Comment by MrEminent42** [comment]
+1

I think the JSON-ifying to allow us to click the name when using /alts is an awesome idea!

**Comment by EvilOlaf** [comment]
Uh yeah...man, cant wait to see this in action. :+1:
