### ISSUE TITLE
2 suggestions

### ISSUE THREAD

**Issue by ABeekhub** [BanManagement/BanManager#761]
Hi there, 

Would it be possible to mention that the database itself should be created manually? The instructions say "You do not have to create the tables, the plugin will do that for you.". I found this is a little confusing because I assumed it would also create the database itself. Just to make the installation process clearer/easier. 

Would it be possible to write to the log the IP the plugin uses to connect to the sql server? Just to confirm it's using what's written in the config...

For the rest I can confirm it runs very well under Debian 8 on a Pine64 arm64 board, using Mariadb!

**Comment by confuser** [comment]
Normally, MySQL users don't have permission to create databases. That's left to an admin/root user. I can add it to the instructions if it helps, but it does state tables, and not the database itself.

Yes, certainly possible to output the host details.
