### ISSUE TITLE
Overide node?

### ISSUE THREAD

**Issue by Castiella** [BanManagement/BanManager#762]
Hi! I use alt accounts to test staff members on my server, but now obviously as my alts have been banned, i get a notification when joining (and so do my staff) saying i have the same IP as other banned accounts.

Is there any node possible to make myself exempt from the ip notifier, but still see if others have and IP that comes from a banned account?

**Comment by confuser** [comment]
Yes, give yourself the `bm.exempt.alts` permission

**Comment by Castiella** [comment]
Bringing this up again, this worked fine up until now.

i'm getting the notification even though I have the node.

**Comment by confuser** [comment]
Has anything changed on your server recently that could coincide with this? Given staff any new permissions, or using a different permission plugin?

**Comment by Castiella** [comment]
no, not in a long time

**Comment by confuser** [comment]
@Castiella Is this still an issue? Other than potentially a bug/change in Bukkit/Spigot itself, I can't see anything that could cause this all of a sudden.
