### ISSUE TITLE
Cant use any commands

### ISSUE THREAD

**Issue by zarzwour** [BanManagement/BanManager#764]
# Issue report

**Tell us about your environment**

Thermos
1.7.10 1614
1.7.10 latest

Online

(default config)

```

When ever i try to do a command it tells me the usage example
/ban user Griefing
the server would respond
/ban <player< <reason>

even reload does this 

plugins in picture
![tttt](https://user-images.githubusercontent.com/20389570/37565098-ff4f4bd8-2a78-11e8-9670-880b5637bd14.PNG)

**Comment by confuser** [comment]
Check your server logs. BanManager most likely isn't enabled (check config) or could not start due ot an error.

**Comment by zarzwour** [comment]
[latest.log](https://github.com/BanManagement/BanManager/files/1822598/latest.log)

**Comment by confuser** [comment]
```Access denied for user 'mc40288'@'%' to database 'local_bans'```

Check your connection details, BanManager was unable to connect to the database

**Comment by zarzwour** [comment]
renamed data base relaunching now

**Comment by zarzwour** [comment]
Works now thank you so much!!!!

**Comment by zarzwour** [comment]
Whats a good way to export the data to a readable chart?

**Comment by confuser** [comment]
Which data? It's all in MySQL, so it should be fairly trivial to query

**Comment by zarzwour** [comment]
my mysql data charts
