### ISSUE TITLE
Rational multi-server support suggestion for reports (at least)

### ISSUE THREAD

**Issue by Ghostlyr** [BanManagement/BanManager#767]
Hello.
I am extremely disappointed with the current multi-server implementation.
For all mute-kick-ban punishments I have enough "local" structure, but not for reports. Use different tables or change world names for each server is not a good idea. Still want to use only "local" structure, but be able to divide reports and if this is required - specify another server.
Implement a something like the current "global/local" databases for my purpose is not suitable.

I want to propose a popular solution:
- Config value to specify the current default server-name
- Additional column in the database indicating the name of the server (from where report was sent)
- Additional command argument to specify another server (enough simple for the view/modify reports from another server)

Want to believe that in the current plugin architecture this is possible, since reports are not affected by the "global database" system.

**Comment by confuser** [comment]
I'm afraid I'm not quite sure what you're asking for here. Reports can't be issued from other servers, as player locations are logged with each report.

**Comment by Ghostlyr** [comment]
Creation of reports with other destination is not required. Actually, moderation from others too.

I would just like to see a way to split reports between servers without using a many alternative tables.

**Comment by confuser** [comment]
What's the issue you're having using multiple tables?

**Comment by Ghostlyr** [comment]
This requires to use of 4 tables for each server (to split all - reports, commands, comments, locations). Uncomfortable to manage (for moderators activity inspection), bad for performance and very bad for web scripts - especially collect statistics.

**Comment by confuser** [comment]
I'm afraid this doesn't make much sense. To cover your points:

1. All data can be viewed in game, no need to be looking at the tables directly.
2. No, normalising the data is best practice, and the most performant option. What your suggesting is actually less performant in the long run.
3. No, it's quite easy to generate statistics using a query.

**Comment by Ghostlyr** [comment]
Hmm. Normalization is the presence of relations. At me there is only duplication of identical tables which as a fact could not be - 8 servers, 32 tables only for reports 😐
