### ISSUE TITLE
Tab Completion Issue

### ISSUE THREAD

**Issue by GridLockMC** [BanManagement/BanManager#778]
So any time someone tries to punish a player the tab completion will tab complete to players who arent even on the server. I have a player names thundermelon on my server but when I type thunder and press tab a guy name thunderdome comes up in the command and this player isnt on the server. I tried to press tab several times but it doesnt do anything but auto complete to thunderdome.

**Comment by confuser** [comment]
Disable `offlineAutoComplete` within your `config.yml` file

**Comment by GridLockMC** [comment]
I set it to false but it still is auto completing with people who arent on the server...
