### ISSUE TITLE
Unable to compile from maven: Unknown host repo.bukkit.org

### ISSUE THREAD

**Issue by jascotty2** [BanManagement/BanManager#783]
I found an error with /addnote, and so I downloaded the source to try to fix it, but I am unable to compile, even after updating the pom for the new api - one of the dependencies seems to require bukkit 1.6.4, and tries to grab it from a deleted domain.

Failed to execute goal on project BanManager: Could not resolve dependencies for project me.confuser:BanManager:jar:6.0.0-SNAPSHOT: Failed to collect dependencies for [com.google.guava:guava:jar:17.0 (compile), org.spigotmc:spigot-api:jar:1.13.1-R0.1-SNAPSHOT (compile), com.j256.ormlite:ormlite-core:jar:4.48 (compile), com.j256.ormlite:ormlite-jdbc:jar:4.48 (compile), com.zaxxer:HikariCP:jar:2.4.7 (compile), org.slf4j:slf4j-simple:jar:1.6.4 (compile), me.confuser:BukkitPluginUtil:jar:1.7.0 (compile), com.googlecode.concurrent-trees:concurrent-trees:jar:2.4.0 (compile), org.projectlombok:lombok:jar:1.14.2 (provided), net.gravitydevelopment.updater:updater:jar:2.3 (compile), com.google.code.gson:gson:jar:2.3.1 (compile), commons-net:commons-net:jar:3.3 (compile), com.github.spullara.cli-parser:cli-parser:jar:1.1.2 (compile), com.maxmind.geoip2:geoip2:jar:2.2.0 (compile), me.rayzr522:jsonmessage:jar:1.0.0 (compile), junit:junit:jar:4.12 (test), org.powermock:powermock-module-junit4:jar:1.5.5 (test), org.powermock:powermock-api-mockito:jar:1.5.5 (test)]: Failed to read artifact descriptor for org.bukkit:bukkit:jar:1.6.4-R2.0: Could not transfer artifact org.bukkit:bukkit:pom:1.6.4-R2.0 from/to bukkit-repo (http://repo.bukkit.org/content/groups/public): repo.bukkit.org: Unknown host repo.bukkit.org

I was able to fix this to get it to compile by commenting out the repository listing under `~/.m2/repository/net/gravitydevelopment/updater/updater/2.3/updater-2.3.pom`

Opening this issue so that you know that there is an aging problem with one of your dependencies

**Comment by confuser** [comment]
Thanks, will take a look. What's the `/addnote` issue?

**Comment by jascotty2** [comment]
Turned out to be a generally rare circumstance that wouldn't affect a server operating "normally"

If you loaded the plugin while the server is up and you are logged in at the time the plugin is loaded, you are not added to the actors internal database, and any database insertions that require a non-null actor throw an exception. Logging out and back in again fixes the issue.

**Comment by confuser** [comment]
@jascotty2 can you confirm you can now compile? Travis and jenkins seems to be passing now.

**Comment by jascotty2** [comment]
Pulled it up on a different computer just to confirm my edits didn't interfere, and it does work! :)
Looks good!
