### ISSUE TITLE
Error on login "Could not compile this SELECT_LONG"

### ISSUE THREAD

**Issue by JohOply** [BanManagement/BanManager#785]
# Issue report

**Tell us about your environment**

* **Server Software:** IDK
* **Server Version:** This server is running CraftBukkit version git-Spigot-f09662d-a46fdbc (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
* **BanManager Version:** 6.0.0

* **Online/Offline mode**: OFFLINE (because bungee)
* **Bungeecoord online/offline mode (if applicable)**:  BUNGEE ONLINE

**BanManager config.yml**:

https://pastebin.com/KCM3FERs

**Describe your issue:** 
Error on each player login: https://pastebin.com/TBLfZAWr

**How to replicate:** 
Just login to the server
 
Thanks for reading

**Comment by confuser** [comment]
Fix released as `v6.0.1` , awaiting approval on BukkitDev. In the mean time, it can be downloaded from https://ci.frostcast.net/job/BanManager/36/
