### ISSUE TITLE
Flag -i or -ips doesn't work on 6.0.2

### ISSUE THREAD

**Issue by Germanode** [BanManagement/BanManager#789]
* **Server Software:** Paper 1.12.2
* **Server Version:** 1.12.2
* **BanManager Version:** 6.0.2

* **Online/Offline mode**: Offline

**BanManager config.yml**:
[https://pastebin.com/KTSKpe4V](https://pastebin.com/KTSKpe4V)

**Describe your issue:** 

/bminfo Username -ips
and
/bminfo Username -i

returns: **A flag has been incorrectly used**

This is pretty much it

**Comment by confuser** [comment]
Try `/bminfo <player> -ips <pageNumber>` instead, e.g. `/bminfo confuser -ips 2`
