### ISSUE TITLE
Closed reports showing in the /reports list

### ISSUE THREAD

**Issue by KarlPro123** [BanManagement/BanManager#790]
Useful stuff:

Plugin version: the latest we can get from bukkit
Server version: 1.14.2

Closed reports are showing in /reports list. Will not vanish after relog. Maybe a restart would help? 

https://gyazo.com/a1e53ec0f46c98957e01f7b1c8de819c

**Comment by KarlPro123** [comment]
https://gyazo.com/1fe057272f457db8f85a2888f669329c something else

**Comment by Pet0203** [comment]
Also got this issue.

**Comment by confuser** [comment]
Resolved in `v7.1.1`
