### ISSUE TITLE
Offline players can be banned even if they have the exempt permission

### ISSUE THREAD

**Issue by Smartjer123** [BanManagement/BanManager#794]
This is not a bug this is a feature request. It would be nice if offline players with the exempted permission could not be banned/muted/tempbanned.

**Comment by scpketer** [comment]
I could bring such a change in here, kk

**Comment by Smartjer123** [comment]
Thanks. Also do you know how to make it not say kicked whilst connecting to ...

**Comment by confuser** [comment]
Unfortunately it's not possible within Bukkit to check the permission of an offline player. If it's an issue, you can manually exempt the player via `BanManager/exemptions.yml`

To disable the kick whilst connecting message, remove the `bm.notify.denied.player` permission

**Comment by Smartjer123** [comment]
But would it be possible to integrate with a permission plugin like luck perms ?
