### ISSUE TITLE
Request: When someone /msg a muted user, tell them they are muted.

### ISSUE THREAD

**Issue by FrozenBeard** [BanManagement/BanManager#796]
Not entirely sure how this would work, but if a user is muted and someone sends them a message via /msg send them back a message to say they are muted, so they know they will not respond. 
I currently use ChatControl Pro for my /msg if this helps.

**Comment by confuser** [comment]
This is quite specific. I'm afraid there's no way to reliably handle this within BM, it would need to be added in `ChatControl Pro` itself.

**Comment by FrozenBeard** [comment]
Thanks, I messaged both of you to figure out which plugin would need to do it.
