### ISSUE TITLE
Possibility to set /bminfo messages

### ISSUE THREAD

**Issue by Nety01** [BanManagement/BanManager#798]
I think it would be nice if you could edit what to display on /bminfo. I know now you can edit the messages one by one, but I can't remove the website there and this would be much easier.

**Comment by confuser** [comment]
Could you be a bit more specific with what changes you'd like to make?

Each option is behind a permission, so to remove the website section from showing, it's enough to remove or negate the `bm.command.bminfo.website` permission from players.

**Comment by Nety01** [comment]
Oh sorry, didn't know about this feature, thank you.
