### ISSUE TITLE
BanManager::Task: me.confuser.banmanager.commands.KickCommand$1$1 (Single)

### ISSUE THREAD

**Issue by FrozenBeard** [BanManagement/BanManager#799]
is causing lag, it looks like ChatControl::Event: o.m.c.f.n. .A (PlayerQuitEvent) is related, but which plugin is it?

![Screenshot 2019-08-26 22 54 36](https://user-images.githubusercontent.com/144046/63726236-9559a900-c854-11e9-82cf-0f142c99af04.png)

**Comment by confuser** [comment]
It's difficult to say for certain as the kick command in BM creates multiple tasks. Are you able to reproduce this issue consistently? If so, does it occur when the silent flag is used?

**Comment by FrozenBeard** [comment]
I think this has happened for a very long time and i've only bothered to just make a ticket.

Each time I do a timings report its in there, so its consistent to being there at all times, I dont think this is happening when we run a kick, but the console may be running kicks for all sorts of things, like when someone gets kicked for using client mods etc, I use the kick with banmanager with a message so its all recorded in the same place, which is awesome.

how can I test this?

**Comment by confuser** [comment]
It's more likely to be ChatControl. I'm not sure what you've used to obtain these timings, but if you add up the total ms times, it nears the BanManager's combined total. Given the kick command runs in a separate sync task, it makes sense it then causes subsequent quit events etc to show in the same call stack.
