### ISSUE TITLE
 [WARN] java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.

### ISSUE THREAD

**Issue by FrozenBeard** [BanManagement/BanManager#801]
BanManager 6.0.2
Paper-1617 (MC: 1.12.2)

Every time a player logs in, the console gets spammed with:

3 examples all happening one after each other with peoepe logging in:

The plugins up and working as all bans etc are being processed and saved, this is just a bug.

https://gist.github.com/FrozenBeard/b04788ca31331c9c0014bf1d49c9ba77
https://gist.github.com/FrozenBeard/58a10eefbfcfc6ed06107aa51c139a9a
https://gist.github.com/FrozenBeard/989635ff533bff6d4cbd0f08064916f8

**Comment by confuser** [comment]
The issue is with `xpboost`. It doesn't appear to handle reconnecting properly - https://github.com/milkwalk/XPBoost/blob/master/src/cz/dubcat/xpboost/api/MainAPI.java#L104 I'm not sure why BanManager is interfering though

**Comment by FrozenBeard** [comment]
Thanks man! why the hell is it messing with BanManager SQL connection!

My Xpboost is very old, I will update it and hope it solves!
