### ISSUE TITLE
Can't kick from another server

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [BanManagement/BanManager#803]
# Issue report

**Tell us about your environment**
Bungeecord - 10 servers connected all hooked via SQL database with Banmanager

* **Server Software:** Paper 207
* **Server Version:** 1.14.4
* **BanManager Version:** 6.0.2

* **Online/Offline mode**: 
* **Bungeecoord online/offline mode (if applicable)**: 
Bungee online mode

**BanManager config.yml**:

https://pastebin.com/AJcNn7rE

**Describe your issue:** 

**How to replicate:** 
Before I updated to 1.14.4 version 6.0.2 I was able to run /kick [name] from the server I was connected, and the [name] wouldn't have to be on the same server as me, and they would be kicked. For some reason, it just says "Player isn't online" and I have to go to their particular server in order to kick them.

See above.
 
**Further information:**

**Comment by confuser** [comment]
What version were you on before?
