### ISSUE TITLE
[Feature Request] Update Web UI to support UUID

### ISSUE THREAD

**Issue by c0wg0d** [BanManagement/BanManager#805]
It would be nice if we got an update to the Web UI to allow searching for players by UUID, as well as to view a player's UUID when looking at their record, with a "copy to clipboard" option, and also a nice to have would be to see all previous player name changes.  (See namemc.com for example.)

**Comment by confuser** [comment]
Is this for the PHP version of the WebUI or the newer version? Can you open the issue over at https://github.com/BanManagement/BanManager-WebUI/ please as this repo is purely for the minecraft server implementation
