### ISSUE TITLE
Able to ban/kick without permissions on sponge.

### ISSUE THREAD

**Issue by clienthax** [BanManagement/BanManager#811]
Latest sponge version,
able to ban and kick without having any permissions.

**Comment by OopsieWoopsie** [comment]
i dont understand if that's a feature request or a bug report

**Comment by clienthax** [comment]
> i dont understand if that's a feature request or a bug report

Why the heck would it be s feature request

**Comment by OopsieWoopsie** [comment]
> > i dont understand if that's a feature request or a bug report
> 
> Why the heck would it be a feature request

1. I wasn't being serious, it's obvious you wasn't requesting that.
2. You can read the issue in both ways (or at least me, a non-english person).

**Comment by clienthax** [comment]
> > > i dont understand if that's a feature request or a bug report
> > 
> > 
> > Why the heck would it be a feature request
> 
> 1. I wasn't being serious, it's obvious you wasn't requesting that.
> 2. You can read the issue in both ways (or at least me, a non-english person).

Issue trackers are for issues, not for your amusement.

**Comment by confuser** [comment]
@clienthax may need your assistance with digging into where the issue lays as I'm not too familiar with Sponge enough yet. The commands are implementing a [testPermission](https://github.com/BanManagement/BanManager/blob/master/sponge/src/main/java/me/confuser/banmanager/sponge/SpongeCommand.java#L76) method, I'm not sure where else the permission is meant to be set, unless it needs implementing in the command `execute` method itself?

**Comment by clienthax** [comment]
Will take a looky when i can

**Comment by clienthax** [comment]
@confuser 
```
    /**
     * Test whether this command can probably be executed by the given source.
     *
     * <p>If implementations are unsure if the command can be executed by
     * the source, {@code true} should be returned. Return values of this method
     * may be used to determine whether this command is listed in command
     * listings.</p>
     *
     * @param source The caller of the command
     * @return Whether permission is (probably) granted
     */
```

Seems it doesn't get used for any checks.
