### ISSUE TITLE
Thousands of "The last packet successfully received from the server was 667,272 milliseconds ago." 

### ISSUE THREAD

**Issue by FrozenBeard** [BanManagement/BanManager#813]
I have thousands of "The last packet successfully received from the server was 667,272 milliseconds ago." in my logs daily, it suggestions to add autoReconnect=true but im not sure where to do this in banmanager?

Paper: git-Paper-1617 (MC: 1.12.2) 
BanManager 6.0.2

https://gist.github.com/FrozenBeard/4617fdce1613213a261a730e4cdc8c48

**Comment by confuser** [comment]
It's already set. It looks like `xpboost` is perhaps the issue again.

**Comment by confuser** [comment]
Within your `xboost` config, try appending `?autoReconnect=true` to your database name, e.g. `database: 'yourDbName?autoReconnect=true'`

**Comment by FrozenBeard** [comment]
Thanks man, Ill give this a go and see after tomorrows reboot 👍
