### ISSUE TITLE
Download failed: Error downloading plugin BanManager.jar: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by t-vanbeek** [BanManagement/BanManager#823]
i have copied this from my console while trying to download the plugin

26.12 02:20:39 [Plugin Installation] Starting download of BanManager.jar
26.12 02:20:41 [Multicraft] Download failed: Error downloading plugin BanManager.jar: 'NoneType' object has no attribute 'group'
26.12 02:21:12 [Plugin Installation] Starting download of BanManager.jar
26.12 02:21:14 [Multicraft] Download failed: Error downloading plugin BanManager.jar: 'NoneType' object has no attribute 'group'

# Issue report

**Tell us about your environment**

* **Server Software:**
* **Server Version:**
* **BanManager Version:**

* **Online/Offline mode**: 
* **Bungeecoord online/offline mode (if applicable)**: 

**BanManager config.yml**:

```yaml

Ensure you mask/remove any MySQL credentials!

```

**Describe your issue:** 

**How to replicate:** 

 
**Further information:**

**Comment by confuser** [comment]
This isn't a BanManager issue, it seems like an issue with whatever you're using to download the plugin?
