### ISSUE TITLE
/bmactivity 1y error

### ISSUE THREAD

**Issue by Nety01** [BanManagement/BanManager#825]
# Issue report

**Tell us about your environment**

* **Server Software:** Paper
* **Server Version:** 1.13.2
* **BanManager Version:** 7.0.0-SNAPSHOT

* **Online/Offline mode**: Offline

**Describe your issue:** 
This error occurs after typing /bmactivity 1y ingame https://hastebin.com/uqamonifip.md

**Comment by confuser** [comment]
Does this occur with any other time differences? Looks more like a data issue than the plugin

**Comment by Nety01** [comment]
1d, 25d, 1w, 2w, 3w, 4w works but it throws error on 5w, I can't open the hastebin I sent firstly so I'm sending this error https://pastebin.com/uu1AMEL6

Could it be caused by that on server start it types `[BanManager] Missing player for ban 3, ignored` etc. so it doesn't know the name?

**Comment by confuser** [comment]
Yes, that would be the cause. It should be easy to fix with a couple of queries on your database.

```SELECT HEX(player_id) FROM bm_player_bans WHERE id = 3```
```UPDATE bm_players SET name = 'ANameHere' WHERE id = UNHEX('pasteUUIDresultHere')```

**Comment by Nety01** [comment]
Well yeah but how I am supposed to know whose was the old uuid when the creation of uuid's has changed (and I have deleted the old player history in bm database)
