### ISSUE TITLE
Discord notifications still not working

### ISSUE THREAD

**Issue by Nety01** [BanManagement/BanManager#828]
Still not working for me :/ 
https://github.com/BanManagement/BanManager/issues/826

**Comment by confuser** [comment]
So I've setup a BanManager discord server to test this, and it appears to be working fine. Your `discord.yml` config should look something similar to this:

```
# Requires DiscordSRV (Bukkit only)
enabled: true
punishments:
  ban:
    channel: global
    message: '&6[player] has been permanently banned by [actor] for &4[reason]'
  tempban:
    channel: global
    message: '&6[player] has been temporarily banned for [expires] by [actor] for
      &4[reason]'
  mute:
    channel: global
    message: '&6[player] has been permanently muted by [actor] for &4[reason]'
  tempmute:
    channel: global
    message: '&6[player] has been temporarily muted for [expires] by [actor] for &4[reason]'
  warning:
    channel: global
    message: '&6[player] has been warned by [actor] for &4[reason]'
```

**Comment by Nety01** [comment]
Oh!! Now it's working, thank you. I typed the channel ID to discord.yml config.... Maybe would be useful to put there a comment that you firstly have to register the channel id in DiscordSRV config and then in discord.yml you have to type the name you wrote there.

**Comment by confuser** [comment]
I've updated https://banmanagement.com/setup/minecraft-server to hopefully show more information on different configuration options amongst other things.
