### ISSUE TITLE
Permissions conflict with EssentialsX

### ISSUE THREAD

**Issue by Nety01** [BanManagement/BanManager#829]
Hey, from any reason, players on my server can use command /ban, /kick, /tempban, /unban. But not /unmute, /tempbanip,... Is this BanManager issue or not? When only those commands can be executed. Players have bm.command.* set to false. Also I've update the luckperms to v5 if it could be the reason.

**Comment by confuser** [comment]
Can you elaborate on this? Any player can use `/ban` etc? Are they op'd?

**Comment by Nety01** [comment]
They are not opped, and yes any player can use it. Can't there be a conflict with EssentialsX? As I tried to replicate that issue on my test server with EssentialsX, LuckPerms and BanManager and once reproduced the issue but not anymore, I'm trying to know more...

**Comment by Nety01** [comment]
Maybe the order of installing the plugins, as it changes the permission error message, idk I can't reproduce it anymore but reproduced it once :c

**Comment by Nety01** [comment]
I have EssentialsX (latest dev build btw) + BanManager -> players can use /ban

I remove BanManager -> players can't use /ban (Error - &4You do not have access to that command.)

When I add the BanManager back, players can again use /ban

**Comment by confuser** [comment]
Are you restarting the server when adding/removing plugins?

**Comment by Nety01** [comment]
Yes I am. Also I've been trying to solve this problem with EssentialsX devs, but they think it's not their problem. Just btw does BanManager override essentials commands /eban, /ekick etc. ?

**Comment by confuser** [comment]
No, BM doesn't overwrite any commands specifically. It uses Bukkit's inbuilt permission system (registers commands with a permission via [plugin.yml](https://github.com/BanManagement/BanManager/blob/master/common/src/main/resources/plugin.yml#L14)). This didn't appear to be an issue with Essentials in the past.
