### ISSUE TITLE
Add a default reason

### ISSUE THREAD

**Issue by Nety01** [BanManagement/BanManager#831]
Would be very useful if somewhere in config would be something like default_reason: "Violation of rules" and that would be placed as the reason if none is specified in the /ban, /kick etc. command.

**Comment by confuser** [comment]
I'm not sure I'd implement this. The idea is that every ban should have a reason, adding a default value removes any context for it. You can however specify reason shortcuts though set in `reasons.yml`, e.g. `/ban confuser #hacking`

**Comment by Nety01** [comment]
Hmm yeah that's true but sometimes you just need to ban/kick someone as fast as possible to stop him doing anything wrong and thinking about the reason could delay it

**Comment by confuser** [comment]
This goes against BanManagers ethos/purpose, so I won't be adding this, sorry
