### ISSUE TITLE
Embedded message in Discord notifications

### ISSUE THREAD

**Issue by TheNety** [BanManagement/BanManager#832]
With embedded messages it could look something like that

![obrazek](https://user-images.githubusercontent.com/42073765/72096622-dbeb0400-331a-11ea-9859-4914649afb4e.png)

Or it's more a work for DiscordSRV devs?

**Comment by confuser** [comment]
Possibly work for DiscordSRV devs, but first try formatting the message using Discord markdown

**Comment by confuser** [comment]
After investigating this, it looks like it's possible via DiscordSRV, but it'll be difficult for it to be customisable via configuration

**Comment by confuser** [comment]
Webhooks implemented to show actor name/avatar
