### ISSUE TITLE
Discord.yml overwrites the ""

### ISSUE THREAD

**Issue by TheNety** [BanManagement/BanManager#838]
Paper 1.15.2
BanManager latest dev build

Hey, after server restart it automatically overwrites the `"` back to `'` in discord.yml messages.

**Comment by confuser** [comment]
Can you provide an example? I'm presuming this will be due to `snakeyaml`

**Comment by Nety01** [comment]
Example of discord.yml?
https://hastebin.com/pahadilipi.pl
