### ISSUE TITLE
Bans not notifying anyone

### ISSUE THREAD

**Issue by Castiella** [BanManagement/BanManager#846]
BanManager version 7.0.1
This server is running Paper version git-Paper-121 (MC: 1.15.2) 

After updating to the newest version of Ban Manager we no longer get notified in chat when a player is banned. This is just applying to bans and I have double checked everyone including myself (who is opped) still has the permission .

There is no error in console, and the bans are applying as we've checked with /bminfo.

**Comment by confuser** [comment]
Given you haven't followed the issue template, do you have `displayNotifications` set to true in your config.yml?

**Comment by Castiella** [comment]
Oh, half my issue isnt there, I don't know what I did. 

It is set to true, heres the config, though it has not been changed since updating.
https://pastebin.com/m7g00wzR

**Comment by confuser** [comment]
https://ci.frostcast.net/job/BanManager/94/
