### ISSUE TITLE
Console name conflicting with another player

### ISSUE THREAD

**Issue by Nety01** [BanManagement/BanManager#848]
After the latest update to dev version 95 when I type **/ban player reason** it doesn't do anything, no message, no ban. Now only works from console.

**Comment by confuser** [comment]
Does `/bminfo` show the player as banned?

**Comment by Nety01** [comment]
No it doesn't.

**Comment by confuser** [comment]
I'm not able to reproduce this currently. Does /banmanager:ban produce a different outcome?

**Comment by Nety01** [comment]
When I try this command it just returns the command usage:
![obrazek](https://user-images.githubusercontent.com/42073765/76212365-978bbf80-6208-11ea-83e0-1d406e8cef83.png)

**Comment by confuser** [comment]
Sounds like the plugin failed to start up. Any errors in the console?

**Comment by Nety01** [comment]
Only error after the server start up is this https://hastebin.com/aqecafuqup.sql after doing /banip on player who doesn't exist but I don't really think that could be the issue. The plugin seems enabled.

**Comment by confuser** [comment]
Which build were you using previously, and does reverting back to this build solve the issue?

**Comment by Nety01** [comment]
Ohh I found the issue. When you change "Console" to existing player in console.yml weird things start happening, even this issue has been caused by this. I changed Console to my name. Maybe you should treat this by not allowing of using the existing player name or something like that. Then it creates duplicated accounts in BanManager, shows IP 127.0.0.0 for that player, can't ban and maybe more. Thanks for help!

**Comment by confuser** [comment]
I'll keep this open to add in a check to hopefully prevent this from occurring again
