### ISSUE TITLE
Double notification on /banip and /tempbanip

### ISSUE THREAD

**Issue by Nety01** [BanManagement/BanManager#851]
When I /tempbanip or /banip a player with 2 accounts, it sends the ban notification twice.
EDIT: It sends double notification only for the admin who banned the player.

Paper 1.15.2
BanManager 7.1.0-SNAPSHOT

**Comment by confuser** [comment]
What do the messages look like?

**Comment by Nety01** [comment]
![image](https://user-images.githubusercontent.com/42073765/77254977-945eed80-6c64-11ea-80ed-d2895d4561f2.png)
