### ISSUE TITLE
Add baniprecords to /bmclear

### ISSUE THREAD

**Issue by Nety01** [BanManagement/BanManager#853]
As title says, the /bmclear baniprecords for removing history of IP Bans is missing. Would be nice if it's added.

**Comment by confuser** [comment]
Via `/bmclear <ipAddress> baniprecords` or are you expecting this for player names, e.g. `/bmclear <player> baniprecords`?

**Comment by Nety01** [comment]
`/bmclear <player> baniprecords` Would be better
