### ISSUE TITLE
Eror after /bmactivity

### ISSUE THREAD

**Issue by Nety01** [BanManagement/BanManager#854]
After typing for example /bmactivity 1d, in chat it returns "No results found" and throws this error in console (censored name of database)

https://pastebin.com/FgKm2aQz

Paper 1.15.2
BanManager 7.1.0-SNAPSHOT

**Comment by confuser** [comment]
Are you using MySQL or MariaDB? Which version?

**Comment by Nety01** [comment]
MySQL 5.5
