### ISSUE TITLE
Don't split words to another line

### ISSUE THREAD

**Issue by Nety01** [BanManagement/BanManager#855]
The word "adminem" is one word, but it splitted it to "a" and "dminem" to another line.
![image](https://user-images.githubusercontent.com/42073765/77253332-aedf9980-6c59-11ea-9ce0-83c735481cdd.png)

Would it be possible to use another handling (or something like that) of those messages so this doesn't happen?

Paper 1.15.2
BanManager 7.1.0-SNAPSHOT

**Comment by confuser** [comment]
I believe this is a Minecraft client issue, not much I can do on the server side sadly
