### ISSUE TITLE
Command Override Issue

### ISSUE THREAD

**Issue by B4m1237** [BanManagement/BanManager#856]
I have a separate reports plugin that has similar commands for reporting as ban manager does.
https://www.spigotmc.org/resources/ingamereports.76303/

When my server was 1.14.4 I was able to use both plugins by overriding in the commands.yml using 
 report:
  - ingamereports:report $1-
  reports:
  - ingamereports:reports $1-

Once I updated to 1.15.2 and updated ban manager to version 7.0.4 that solution stopped working. I've also tried changing the '$1' to '$$1' but that didn't work either.

I'm unable to even use /ingamereports:report <arg> or /ingamereports:reports <arg> ingame as ban manager completely overrides those as well, which it didn't do in 1.14.

**Comment by confuser** [comment]
I'm not able to reproduce this. BanManager hasn't changed the way it registers commands since its inception. At the moment it appears to be either an issue with the ingamereports plugin or potentially a bug with the aforementioned Spigot version.

**Comment by zenith4183** [comment]
I'm having the same issue only with the /mute command of my chat plugin being overwritten by BanManager 7.0.4.  No other changes were made to the server except for updating BanManager.  I've been using commands.yml to avoid the clashing for years, but even that isn't working now with 7.0.4.

**Comment by confuser** [comment]
@zenith4183 which chat plugin are you using? I've not been able to reproduce this issue yet

**Comment by zenith4183** [comment]
It's a private chat plugin that I write.  I can send you a copy if you like.  I did some more testing myself and found what may help you reproduce the issue.  This problem only occurs if DiscordSRV is a plugin on the server.  If I remove DiscordSRV and restart the server, everything works fine.  Put it back in, and BanManager starts stealing the /mute command again.  @B4m1237 could maybe confirm if he is also using DiscordSRV.

**Comment by B4m1237** [comment]
I am using discordsrv. I talked to the dev of the plugin I was having issues with (know them) and they were able to make different commands that solved the problem, changed them from report and reports to glreport and glreports for me.

**Comment by confuser** [comment]
@zenith4183 that's an interesting find. Prior to v7, v6 didn't soft depend on DiscordSRV, perhaps it wasn't an issue then as BanManager loaded first, where as now it doesn't... Regardless, would suggest raising an issue with DiscordSRV as I imagine it will be affecting other plugins too.

**Comment by confuser** [comment]
Can you try https://ci.frostcast.net/job/BanManager/124/ to see if it resolves the issue?

**Comment by zenith4183** [comment]
Can confirm that it does resolve the issue for me.  Thanks!
