### ISSUE TITLE
Placeholders

### ISSUE THREAD

**Issue by TheNety** [BanManagement/BanManager#876]
Could you add some basic placeholders? To the plugin directly or to PlaceholderAPI. Like `%bm_player_bans%`, `%bm_player_PLAYER-NAME_bans%` would show number of the players bans etc.

**Comment by confuser** [comment]
Placeholders to where? messages.yml?

**Comment by Nety01** [comment]
Placeholders that can be used out of the plugin, like in scoreboard, in custom commands and so

**Comment by TomLewis** [comment]
I too would like this please, placeholderapi placeholders, so that we can show them in chat to staff etc.

**Comment by confuser** [comment]
Note: Placeholders are synchronous which currently limits supported identifiers to data available in-memory only

**Comment by TomLewis** [comment]
@confuser Can we please get placeholders specific to users we specify? That's how I wanted to use placeholders.

**Comment by confuser** [comment]
> @confuser Can we please get placeholders specific to users we specify? That's how I wanted to use placeholders.

They are specific, anything starting with `current` requires a player argument
