### ISSUE TITLE
Issue with bmkick and bmkick <name> -s

### ISSUE THREAD

**Issue by phyzeek** [BanManagement/BanManager#880]
Minecraft Version 1.15.2
7.1.1-SNAPSHOT dev version #128
We're using a bungeecord system. (bungeebanmanager)

We are using the permission "bm.command.kick.silent".

/bmkick <playername> -s The command works but the message is still showing for everyone.
/bmkick <playername> The Command works but the message shows not for everyone. Its shows literally random

**Comment by confuser** [comment]
Do the affected players have the `bm.notify.kick` permission?

**Comment by phyzeek** [comment]
No one have this permission. Neither admin nor normal players.

**Comment by phyzeek** [comment]
Ignore my last post. The lowest rank on our server have this permission and all other inherit the permission.

**Comment by confuser** [comment]
I'm going to need your help on narrowing this down as I'm not able to reproduce the issue.

- Player/console issuing /kick command will be sent the kicked message if they do not have `bm.notify.kick` permission or it's silent
- Other players are only notified if the kick is not silent and have `bm.notify.kick` permission

**Comment by phyzeek** [comment]
Sorry for my late answer.
Everyone owns this permission 'bm.notify.kick', but the kicked message not shows for everyone. That's literally random.
If we use the kick command silent, the kicked message shows for everyone and is for no one hidden.

**Comment by phyzeek** [comment]
Any Idea?

**Comment by confuser** [comment]
@phyzeek Still not able to reproduce this, are you sure you're using banmanager's kick command? Does the same issue occur when using /bmkick?

**Comment by phyzeek** [comment]
Hey, thank you for your answer.

Example 1: We're using the cmd `/bmkick <playername> -s <reason>` and this shown to everyone.
Example 2: We're using the cmd `/bmkick <playername> <reason>` and this is shown only to a few players.

This Problem exists only for /bmkick and not for /bmwarn, /bmban, /bmtempban etc.
