### ISSUE TITLE
IP Address Exception

### ISSUE THREAD

**Issue by RealMCSamuel** [BanManagement/BanManager#881]
Server Software: Bukkit
Server Version: 1.12.2
BanManager Version: 7.0.4
[config.txt](https://github.com/BanManagement/BanManager/files/4569694/config.txt)

When I run the /bminfo command and tab a name, nothing comes up in-games, and this error message appears in the console.
[error.txt](https://github.com/BanManagement/BanManager/files/4569695/config.txt)

**Comment by confuser** [comment]
Please see #863

**Comment by RealMCSamuel** [comment]
This is enabled and I can tab other people's names. However, when I press enter to run the command, nothing shows up and the error appears in the console. I apologize as that might not have been clear at first.

**Comment by confuser** [comment]
The issue is caused by a wrongly formatted ip field. The issue I linked covers how to resolve it https://github.com/BanManagement/BanManager/issues/863#issuecomment-615458195
