### ISSUE TITLE
Granular permissions on bminfo / IP addresses

### ISSUE THREAD

**Issue by zeronerve** [BanManagement/BanManager#883]
Love your software thanks! We'd like to be able to limit access to player IP addresses to only senior moderators, while allowing lower level moderators to continue to use `/bminfo` but without the IP data. Could you please add a perm such as `bm.bminfo.ip` that would give us granular control over who sees what info?

Thanks!

**Comment by confuser** [comment]
The `bm.command.bminfo.connection` permission should cover this, if not could you elaborate?

**Comment by zeronerve** [comment]
Thank you. Let me test a few things and I may elaborate. Sounds helpful though.
