### ISSUE TITLE
[Feature] Configurable time period an IP is associated with a player

### ISSUE THREAD

**Issue by jascotty2** [BanManagement/BanManager#885]
I am using the punishAlts feature and it has been extremely helpful in stopping a number of troll attacks (some with 10+ alts that they tried one after another), however I have also run across some issues with IP collisions with banned players and legitimate players using the same ISP with dynamic IP addresses. 

While looking for a possible solution, I noticed that the duplicate finder logic completely ignores how long ago a player connected from any given IP
https://github.com/BanManagement/BanManager/blob/master/common/src/main/java/me/confuser/banmanager/common/storage/PlayerBanStorage.java#L260

This could be resolved by permitting a configurable delay before an IP is considered 'old' and no longer associated with an account. (Using the 'leave' column for best accuracy) (I have little time anymore for doing coding so I'd probably end up hard-coding a patch with a delay for my server if you don't want to add this feature)

**Comment by confuser** [comment]
Certainly something that can be added. However, note that `leave` is only populated if `logIps` is enabled.  The method you've linked to uses the player table rather than history, so perhaps `lastSeen` would be more suited instead.
