### ISSUE TITLE
Additional Discord Notifications and Current Punishment List

### ISSUE THREAD

**Issue by Vulant** [BanManagement/BanManager#901]
Hello, I'd like to suggest an addition to the discord punishment notifications.

I noticed that discord so far only notifies if there's been a punishment, but does not notify when a player is unmuted or unbanned. I think it's equally important to know if someone has been unbanned or unmuted.

I'd also like to suggest a command that will tell you who is currently muted or has warnings, similar to the /banlist command.

Thank you for your time.

**Comment by confuser** [comment]
Additionally add a report option as well

**Comment by Vulant** [comment]
Is this released in the latest snapshot on spongeforge or have you not uploaded it yet?
