### ISSUE TITLE
Kicks dont save anywhere

### ISSUE THREAD

**Issue by Azim** [BanManagement/BanManager#904]
# Issue report

**Tell us about your environment**

* **Server Software:** Paper
* **Server Version:**  1.16.3
* **BanManager Version:** latest

* **Online/Offline mode**: online
* **Bungeecoord online/offline mode (if applicable)**: 

**BanManager config.yml**: defaults

**Describe your issue:** 
When player is kicked, no records about that is stored. When you later execute bminfo, it will show 0 kicks

**How to replicate:** 
1. kick player
2. look at bminfo

 
**Further information:**

**Comment by confuser** [comment]
Ensure `logKicks` is enabled in your `config.yml` file

**Comment by Azim** [comment]
Oh, you're right. Thanks.
Maybe then dont display it in bminfo at all?
