### ISSUE TITLE
Mute to block SimpleClans Clan/Ally chat when Toggled

### ISSUE THREAD

**Issue by TomLewis** [BanManagement/BanManager#917]
# Issue report

**Tell us about your environment**

* **Server Software:** Paper 
* **Server Version:** 1.12.2
* **BanManager Version:** 6.0.2

* **Online/Offline mode**: 
* **Bungeecoord online/offline mode (if applicable)**: Online Bungee

**BanManager config.yml**:

n/a

**Describe your issue:** 

When a player is muted via BanManger, a player can toggle their SimpleClans Clan/ally chat to talk without needing a command and they will bypass the mute and still be able to talk into their Clan/Ally chats

**How to replicate:** 
1) Get muted via BanManager
2) Toggle SimpleClans Crew chat to not need a command to stay in that channel
3) Talk normally to your crew/ally without being muted
 
**Further information:**
SimpleClans Ticket https://github.com/RoinujNosde/SimpleClans/issues/173

@RoinujNosde Reply was:
> Check with BanManager's devs if they can cancel the AsyncPlayerChatEvent at LOWEST priority as well.

**Comment by confuser** [comment]
Try changing `chatPriority` in your config.yml to `lowest`

**Comment by TomLewis** [comment]
Hey @confuser thanks for the quick response, I set `chatPriority: lowest` and did `/bmreload` but they can still talk in Ally & Clan Chat, does BanManager require a full server restart for this setting to take effect?

**Comment by confuser** [comment]
Yes, a full restart is required. I've raised #918 as it should be possible to change via /bmreload instead
