### ISSUE TITLE
Plugin fails to load with Java 16 (which will be needed for 1.17)

### ISSUE THREAD

**Issue by Momshroom** [BanManagement/BanManager#928]
# Issue report

**Tell us about your environment**

* **Server Software:**
Paper
* **Server Version:**
1.16.5 (build 762)
* **BanManager Version:**
7.4.0

* **Online/Offline mode**: 
Online

* **Bungeecoord online/offline mode (if applicable)**: 
No bungeecord

**BanManager config.yml**:

```yaml

https://paste.gg/p/Momshroom/35e9f3912b244e38b572f3bd9902ef25

Ensure you mask/remove any MySQL credentials!

```

**Describe your issue:** 

The plugin doesn't load once the server is upgraded to use Java 16.  (Doing this in preparation for Minecraft 1.17).

Console Error of BanManager not loading:
https://paste.gg/p/Momshroom/ef9c585e094c46e69bf417f6e50cbbf1

If you really need a full startup log, I can get you one, but those are the only BanManager related errors

**How to replicate:** 

 Update Java version to 16
 
**Further information:**

 
The plugin loaded fine before updating the Java version from Java 11 to 16.  No other changes were made.

**Comment by confuser** [comment]
I've just tested again, and it appears to be okay. The error message here seems to be more of an issue with a corrupted jar file. Please re-download BanManager and try again.

**Comment by Momshroom** [comment]
Re-downloading the jar did fix this.. sorry didn't report back sooner and for the hassle. Thank you
