### ISSUE TITLE
Velocity Proxy 3.1.x (3.0.2 build 82 tested) support

### ISSUE THREAD

**Issue by rautamiekka** [BanManagement/BanManager#939]
The BungeeCord version doesn't support [Velocity](https://github.com/VelocityPowered/Velocity), which is meant to be a superior, modern successor of BungeeCord and Waterfall, with the price of not supporting non-Velocity plugins.

[Velocity 3.0.2 build 82](https://ci.velocitypowered.com/job/velocity-3.0.0/82/) tested.

There are plugins which support Velocity, so you can take a look at their code if necessary. Some of which:
- [LuckPerms](https://github.com/lucko/LuckPerms) has a separate Velocity binary.
- [SkinsRestorerX](https://github.com/SkinsRestorer/SkinsRestorerX) uses a single binary for all supported platforms.
- [Plan](https://github.com/plan-player-analytics/Plan) uses a single binary for all supported platforms.

All of those share a common base code within the plugin, while the platforms have their specific codes separated.

[More plugins on the Forum](https://forums.velocitypowered.com/c/plugins/plugin-releases/6).

**Comment by MAXOUXAX** [comment]
I agree, Velocity support would be really great!

**Comment by rautamiekka** [comment]
Velocity 3.1.0 is in the works. So far not very much has changed.
