### ISSUE TITLE
Expired warns are not included in /bminfo

### ISSUE THREAD

**Issue by piotrskibapl** [BanManagement/BanManager#941]
# Issue report

**Tell us about your environment**

* **Server Software:** Paper
* **Server Version:** Build 780 (MC: 1.16.5)
* **BanManager Version:** 7.5.0

* **Online/Offline mode**: false
* **Bungeecoord online/offline mode (if applicable)**: false

**BanManager config.yml**:

Not relevant; issue present also with non-modified config

**Describe your issue:** 

Warnings that are expired (issued using `/tempwarn` command) are not included in /bminfo output. It looks like they're entirely removed from the database and no record is left after its expiration.

**How to replicate:** 

1. Use `/tempwarn your_name 60s test`
2. Check `/bminfo` - you should see an information about total bans, mutes, kicks and warnings amount; warnings include the recent one
3. Wait at least 60 seconds for the warning to expire
4. Check `/bminfo` again - the recent warning is not included in the total warnings amount now

**Comment by confuser** [comment]
This is a feature, not a bug. What is the use case here in using temp warnings?
