### ISSUE TITLE
[Feature request] Ban waves

### ISSUE THREAD

**Issue by GeekCornerGH** [BanManagement/BanManager#950]
Instead of just banning, adding ban waves every x hours would be a plus

**Comment by GeekCornerGH** [comment]
> A ban wave is a large scale gaming event in which certain accounts get permanently barred from services, for major disruptions. If the violation seems to be severe, such as phishing, scamming accounts can be deleted without any prior notices or commands.
from [hmm here](https://www.quora.com/What-is-the-reason-for-the-Roblox-Ban-Wave-2020)

**Comment by MattW-source** [comment]
Only use-case where Ban Waves are useful in Minecraft servers are with Anti-Cheats. Sometimes you may want to queue up automated bans from anti-cheats and have them all run at once to make it difficult for hackers to figure out what they got detected for. Most anti-cheats have this sort of functionality built in directly and queue up a series of commands to run.

**Comment by confuser** [comment]
I'm not sure this belongs within BanManager; it can handle the banning itself, but the waves function seems server/scenario specific and doesn't feel like it would align with this plugin's ideals
