### ISSUE TITLE
Silent flag doesn't work for kick command

### ISSUE THREAD

**Issue by piotrskibapl** [BanManagement/BanManager#977]
# Issue report

**Tell us about your environment**

* **Server Software:** Paper build 387
* **Server Version:** 1.18.2
* **BanManager Version:** 7.8.0

* **Online/Offline mode**: offline
* **Bungeecoord online/offline mode (if applicable)**: offline

**BanManager config.yml**:
not relevant - reproducible with the default config

**Describe your issue:** 

Silent flag doesn't work for the "kick" command

**How to replicate:** 
1. Run "/kick username test -s"

Expected: Other players shouldn't see that the player was kicked
Observed: Kick message is sent to all users

**Comment by confuser** [comment]
@piotrskibapl can you run `/bmkick username test -s` and confirm they're still visible? Also please confirm that the players who can see it do **not** have the permission `bm.notify.kick` or any other variation e.g. `bm.notify.*`

**Comment by piotrskibapl** [comment]
@confuser just tested, and `/bmkick username test -s` gives me the same results.
Currently on my server all users **do** have the permission `bm.notify.kick`, however, it seems to me that the kick message shouldn't be visible to the users if a silent flag is used (that's the behavior for example of `/bmtempban`). I tried removing the `bm.notify.kick` permission and the users did not see the kick message, however, they didn't see it even if there was no silent flag added.
