### ISSUE TITLE
[FEATURE RQ] DiscordSRV Unlink with bans.

### ISSUE THREAD

**Issue by Castiella** [BanManagement/BanManager#991]
HI,

I was wondering if you'd consider an option to automatically unlink discord accounts with /discordsrv unlink name when a player is banned from the minecraft server?

I'll happily donate to the cause! 
My DC is _.cassi._ if you would like to discuss payment!

Thank you :)

**Comment by confuser** [comment]
You should be able to do this already using a hook https://banmanagement.com/docs/banmanager/configuration/config-yml#hooks
